/*
**
** The C code is generated by [ATS/Postiats-0-2-13]
** The starting compilation time is: 2017-1-6: 21h:22m
**
*/

/*
** include runtime header files
*/
#ifndef _ATS_CCOMP_HEADER_NONE_
#include "pats_ccomp_config.h"
#include "pats_ccomp_basics.h"
#include "pats_ccomp_typedefs.h"
#include "pats_ccomp_instrset.h"
#include "pats_ccomp_memalloc.h"
#ifndef _ATS_CCOMP_EXCEPTION_NONE_
#include "pats_ccomp_memalloca.h"
#include "pats_ccomp_exception.h"
#endif // end of [_ATS_CCOMP_EXCEPTION_NONE_]
#endif /* _ATS_CCOMP_HEADER_NONE_ */


/*
** include prelude cats files
*/
#ifndef _ATS_CCOMP_PRELUDE_NONE_
//
#include "prelude/CATS/basics.cats"
#include "prelude/CATS/integer.cats"
#include "prelude/CATS/pointer.cats"
#include "prelude/CATS/integer_long.cats"
#include "prelude/CATS/integer_size.cats"
#include "prelude/CATS/integer_short.cats"
#include "prelude/CATS/bool.cats"
#include "prelude/CATS/char.cats"
#include "prelude/CATS/float.cats"
#include "prelude/CATS/integer_ptr.cats"
#include "prelude/CATS/integer_fixed.cats"
#include "prelude/CATS/memory.cats"
#include "prelude/CATS/string.cats"
#include "prelude/CATS/strptr.cats"
//
#include "prelude/CATS/fprintf.cats"
//
#include "prelude/CATS/filebas.cats"
//
#include "prelude/CATS/list.cats"
#include "prelude/CATS/option.cats"
#include "prelude/CATS/array.cats"
#include "prelude/CATS/arrayptr.cats"
#include "prelude/CATS/arrayref.cats"
#include "prelude/CATS/matrix.cats"
#include "prelude/CATS/matrixptr.cats"
//
#endif /* _ATS_CCOMP_PRELUDE_NONE_ */
/*
** for user-supplied prelude
*/
#ifdef _ATS_CCOMP_PRELUDE_USER_
//
#include _ATS_CCOMP_PRELUDE_USER_
//
#endif /* _ATS_CCOMP_PRELUDE_USER_ */
/*
** for user2-supplied prelude
*/
#ifdef _ATS_CCOMP_PRELUDE_USER2_
//
#include _ATS_CCOMP_PRELUDE_USER2_
//
#endif /* _ATS_CCOMP_PRELUDE_USER2_ */

/*
staload-prologues(beg)
*/
/*
/home/ubuntu/workspace/ATS2/prelude/DATS/basics.dats: 1534(line=44, offs=1) -- 1573(line=45, offs=32)
*/
/*
/home/ubuntu/workspace/ATS2/prelude/DATS/integer.dats: 1596(line=49, offs=1) -- 1635(line=49, offs=40)
*/
/*
/home/ubuntu/workspace/ATS2/prelude/DATS/pointer.dats: 1533(line=44, offs=1) -- 1572(line=44, offs=40)
*/
/*
/home/ubuntu/workspace/ATS2/prelude/DATS/integer_long.dats: 1602(line=49, offs=1) -- 1641(line=49, offs=40)
*/
/*
/home/ubuntu/workspace/ATS2/prelude/DATS/integer_size.dats: 1597(line=49, offs=1) -- 1636(line=49, offs=40)
*/
/*
/home/ubuntu/workspace/ATS2/prelude/DATS/integer_short.dats: 1603(line=49, offs=1) -- 1642(line=49, offs=40)
*/
/*
/home/ubuntu/workspace/ATS2/prelude/DATS/char.dats: 1610(line=48, offs=1) -- 1649(line=48, offs=40)
*/
/*
/home/ubuntu/workspace/ATS2/prelude/DATS/float.dats: 1636(line=50, offs=1) -- 1675(line=50, offs=40)
*/
/*
/home/ubuntu/workspace/ATS2/prelude/DATS/string.dats: 1609(line=48, offs=1) -- 1648(line=48, offs=40)
*/
/*
/home/ubuntu/workspace/ATS2/prelude/DATS/strptr.dats: 1609(line=48, offs=1) -- 1648(line=48, offs=40)
*/
/*
/home/ubuntu/workspace/ATS2/prelude/DATS/strptr.dats: 1671(line=52, offs=1) -- 1718(line=52, offs=48)
*/
/*
/home/ubuntu/workspace/ATS2/prelude/DATS/integer.dats: 1596(line=49, offs=1) -- 1635(line=49, offs=40)
*/
/*
/home/ubuntu/workspace/ATS2/prelude/DATS/integer_ptr.dats: 1601(line=49, offs=1) -- 1640(line=49, offs=40)
*/
/*
/home/ubuntu/workspace/ATS2/prelude/DATS/integer_fixed.dats: 1603(line=49, offs=1) -- 1642(line=49, offs=40)
*/
/*
/home/ubuntu/workspace/ATS2/prelude/DATS/memory.dats: 1410(line=38, offs=1) -- 1449(line=39, offs=32)
*/
/*
/home/ubuntu/workspace/ATS2/prelude/DATS/filebas.dats: 1613(line=49, offs=1) -- 1652(line=50, offs=32)
*/
/*
/home/ubuntu/workspace/ATS2/prelude/DATS/filebas.dats: 1675(line=54, offs=1) -- 1721(line=55, offs=39)
*/
/*
/home/ubuntu/workspace/ATS2/prelude/DATS/integer.dats: 1596(line=49, offs=1) -- 1635(line=49, offs=40)
*/
/*
/home/ubuntu/workspace/ATS2/prelude/DATS/filebas.dats: 1744(line=59, offs=1) -- 1789(line=60, offs=38)
*/
/*
/home/ubuntu/workspace/ATS2/libats/libc/SATS/stdio.sats: 1390(line=36, offs=1) -- 1437(line=39, offs=3)
*/

#include \
"libats/libc/CATS/stdio.cats"
/*
/home/ubuntu/workspace/ATS2/libats/libc/SATS/stdio.sats: 1950(line=69, offs=1) -- 1999(line=71, offs=34)
*/
/*
/home/ubuntu/workspace/ATS2/libats/libc/SATS/sys/types.sats: 1390(line=36, offs=1) -- 1441(line=39, offs=3)
*/

#include \
"libats/libc/CATS/sys/types.cats"
/*
/home/ubuntu/workspace/ATS2/prelude/DATS/filebas.dats: 1871(line=66, offs=1) -- 1918(line=66, offs=48)
*/
/*
/home/ubuntu/workspace/ATS2/libats/libc/SATS/sys/stat.sats: 1390(line=36, offs=1) -- 1440(line=39, offs=3)
*/

#include \
"libats/libc/CATS/sys/stat.cats"
/*
/home/ubuntu/workspace/ATS2/libats/libc/SATS/sys/stat.sats: 1756(line=58, offs=1) -- 1805(line=60, offs=34)
*/
/*
/home/ubuntu/workspace/ATS2/libats/libc/SATS/sys/types.sats: 1390(line=36, offs=1) -- 1441(line=39, offs=3)
*/

#include \
"libats/libc/CATS/sys/types.cats"
/*
/home/ubuntu/workspace/ATS2/prelude/DATS/filebas.dats: 15413(line=857, offs=1) -- 15450(line=858, offs=30)
*/
/*
/home/ubuntu/workspace/ATS2/libats/libc/SATS/stdio.sats: 1390(line=36, offs=1) -- 1437(line=39, offs=3)
*/

#include \
"libats/libc/CATS/stdio.cats"
/*
/home/ubuntu/workspace/ATS2/libats/libc/SATS/stdio.sats: 1950(line=69, offs=1) -- 1999(line=71, offs=34)
*/
/*
/home/ubuntu/workspace/ATS2/libats/libc/SATS/sys/types.sats: 1390(line=36, offs=1) -- 1441(line=39, offs=3)
*/

#include \
"libats/libc/CATS/sys/types.cats"
/*
/home/ubuntu/workspace/ATS2/prelude/DATS/list.dats: 1529(line=44, offs=1) -- 1568(line=45, offs=32)
*/
/*
/home/ubuntu/workspace/ATS2/prelude/DATS/list.dats: 1569(line=46, offs=1) -- 1615(line=47, offs=39)
*/
/*
/home/ubuntu/workspace/ATS2/prelude/DATS/unsafe.dats: 1532(line=44, offs=1) -- 1566(line=44, offs=35)
*/
/*
/home/ubuntu/workspace/ATS2/prelude/DATS/list_vt.dats: 1538(line=44, offs=1) -- 1577(line=45, offs=32)
*/
/*
/home/ubuntu/workspace/ATS2/prelude/DATS/list_vt.dats: 1578(line=46, offs=1) -- 1624(line=47, offs=39)
*/
/*
/home/ubuntu/workspace/ATS2/prelude/DATS/unsafe.dats: 1532(line=44, offs=1) -- 1566(line=44, offs=35)
*/
/*
/home/ubuntu/workspace/ATS2/prelude/DATS/array.dats: 1534(line=44, offs=1) -- 1573(line=44, offs=40)
*/
/*
/home/ubuntu/workspace/ATS2/prelude/DATS/array.dats: 1574(line=45, offs=1) -- 1616(line=45, offs=43)
*/
/*
/home/ubuntu/workspace/ATS2/prelude/DATS/arrayptr.dats: 1532(line=44, offs=1) -- 1571(line=44, offs=40)
*/
/*
/home/ubuntu/workspace/ATS2/prelude/DATS/arrayref.dats: 1532(line=44, offs=1) -- 1571(line=44, offs=40)
*/
/*
/home/ubuntu/workspace/ATS2/prelude/DATS/matrix.dats: 1535(line=44, offs=1) -- 1574(line=44, offs=40)
*/
/*
/home/ubuntu/workspace/ATS2/prelude/DATS/matrixptr.dats: 1538(line=44, offs=1) -- 1577(line=44, offs=40)
*/
/*
/home/ubuntu/workspace/ATS2/prelude/DATS/matrixref.dats: 1538(line=44, offs=1) -- 1577(line=44, offs=40)
*/
/*
/home/ubuntu/workspace/ATS2/prelude/DATS/stream.dats: 1523(line=44, offs=1) -- 1562(line=44, offs=40)
*/
/*
/home/ubuntu/workspace/ATS2/prelude/DATS/stream_vt.dats: 1523(line=44, offs=1) -- 1562(line=44, offs=40)
*/
/*
/home/ubuntu/workspace/ATS2/prelude/DATS/tostring.dats: 1528(line=44, offs=1) -- 1567(line=45, offs=32)
*/
/*
/home/ubuntu/workspace/ATS2/prelude/DATS/unsafe.dats: 1532(line=44, offs=1) -- 1566(line=44, offs=35)
*/
/*
/home/ubuntu/workspace/ATS2/prelude/DATS/checkast.dats: 1531(line=44, offs=1) -- 1570(line=45, offs=32)
*/
/*
/home/ubuntu/workspace/ATS2/libats/ML/SATS/list0.sats: 1665(line=47, offs=1) -- 1700(line=47, offs=36)
*/
/*
/home/ubuntu/workspace/ATS2/libats/ML/SATS/option0.sats: 1524(line=41, offs=1) -- 1559(line=41, offs=36)
*/
/*
/home/ubuntu/workspace/ATS2/libats/ML/SATS/array0.sats: 1525(line=41, offs=1) -- 1571(line=44, offs=3)
*/

#include \
"libats/ML/CATS/array0.cats"
/*
/home/ubuntu/workspace/ATS2/libats/ML/SATS/array0.sats: 1610(line=48, offs=1) -- 1645(line=48, offs=36)
*/
/*
/home/ubuntu/workspace/ATS2/libats/ML/SATS/matrix0.sats: 1526(line=41, offs=1) -- 1561(line=41, offs=36)
*/
/*
/home/ubuntu/workspace/ATS2/libats/ML/SATS/string.sats: 1525(line=41, offs=1) -- 1560(line=41, offs=36)
*/
/*
/home/ubuntu/workspace/ATS2/libats/ML/SATS/strarr.sats: 1538(line=43, offs=1) -- 1574(line=43, offs=37)
*/
/*
/home/ubuntu/workspace/ATS2/libats/ML/SATS/strarr.sats: 1599(line=47, offs=1) -- 1649(line=51, offs=3)
*/

//
#include "libats/ML/CATS/strarr.cats"
//
/*
/home/ubuntu/workspace/ATS2/libats/ML/SATS/gvalue.sats: 1534(line=42, offs=1) -- 1569(line=42, offs=36)
*/
/*
/home/ubuntu/workspace/ATS2/libats/ML/SATS/stream.sats: 1532(line=43, offs=1) -- 1567(line=43, offs=36)
*/
/*
/home/ubuntu/workspace/ATS2/libats/ML/SATS/stream_vt.sats: 1534(line=43, offs=1) -- 1569(line=44, offs=28)
*/
/*
/home/ubuntu/workspace/ATS2/libats/ML/SATS/filebas.sats: 1525(line=41, offs=1) -- 1560(line=41, offs=36)
*/
/*
/home/ubuntu/workspace/ATS2/libats/ML/SATS/intrange.sats: 1629(line=47, offs=1) -- 1664(line=47, offs=36)
*/
/*
/home/ubuntu/workspace/ATS2/libats/ML/DATS/list0.dats: 1444(line=40, offs=1) -- 1483(line=41, offs=32)
*/
/*
/home/ubuntu/workspace/ATS2/libats/ML/DATS/list0.dats: 1506(line=45, offs=1) -- 1541(line=45, offs=36)
*/
/*
/home/ubuntu/workspace/ATS2/libats/ML/DATS/list0.dats: 1542(line=46, offs=1) -- 1577(line=46, offs=36)
*/
/*
/home/ubuntu/workspace/ATS2/libats/ML/SATS/list0.sats: 1665(line=47, offs=1) -- 1700(line=47, offs=36)
*/
/*
/home/ubuntu/workspace/ATS2/libats/ML/DATS/option0.dats: 1392(line=36, offs=1) -- 1431(line=37, offs=32)
*/
/*
/home/ubuntu/workspace/ATS2/libats/ML/DATS/option0.dats: 1454(line=41, offs=1) -- 1489(line=41, offs=36)
*/
/*
/home/ubuntu/workspace/ATS2/libats/ML/DATS/option0.dats: 1490(line=42, offs=1) -- 1527(line=42, offs=38)
*/
/*
/home/ubuntu/workspace/ATS2/libats/ML/SATS/option0.sats: 1524(line=41, offs=1) -- 1559(line=41, offs=36)
*/
/*
/home/ubuntu/workspace/ATS2/libats/ML/DATS/array0.dats: 1394(line=36, offs=1) -- 1433(line=37, offs=32)
*/
/*
/home/ubuntu/workspace/ATS2/libats/ML/DATS/array0.dats: 1458(line=41, offs=1) -- 1493(line=41, offs=36)
*/
/*
/home/ubuntu/workspace/ATS2/libats/ML/DATS/array0.dats: 1494(line=42, offs=1) -- 1529(line=42, offs=36)
*/
/*
/home/ubuntu/workspace/ATS2/libats/ML/SATS/list0.sats: 1665(line=47, offs=1) -- 1700(line=47, offs=36)
*/
/*
/home/ubuntu/workspace/ATS2/libats/ML/DATS/array0.dats: 1530(line=43, offs=1) -- 1566(line=43, offs=37)
*/
/*
/home/ubuntu/workspace/ATS2/libats/ML/SATS/array0.sats: 1525(line=41, offs=1) -- 1571(line=44, offs=3)
*/

#include \
"libats/ML/CATS/array0.cats"
/*
/home/ubuntu/workspace/ATS2/libats/ML/SATS/array0.sats: 1610(line=48, offs=1) -- 1645(line=48, offs=36)
*/
/*
/home/ubuntu/workspace/ATS2/libats/ML/DATS/matrix0.dats: 1396(line=36, offs=1) -- 1435(line=37, offs=32)
*/
/*
/home/ubuntu/workspace/ATS2/libats/ML/DATS/matrix0.dats: 1458(line=41, offs=1) -- 1493(line=41, offs=36)
*/
/*
/home/ubuntu/workspace/ATS2/libats/ML/DATS/matrix0.dats: 1494(line=42, offs=1) -- 1531(line=42, offs=38)
*/
/*
/home/ubuntu/workspace/ATS2/libats/ML/SATS/matrix0.sats: 1526(line=41, offs=1) -- 1561(line=41, offs=36)
*/
/*
/home/ubuntu/workspace/ATS2/libats/ML/DATS/string.dats: 1609(line=46, offs=1) -- 1648(line=46, offs=40)
*/
/*
/home/ubuntu/workspace/ATS2/libats/ML/DATS/string.dats: 2770(line=107, offs=1) -- 2805(line=107, offs=36)
*/
/*
/home/ubuntu/workspace/ATS2/libats/ML/DATS/string.dats: 2806(line=108, offs=1) -- 2841(line=108, offs=36)
*/
/*
/home/ubuntu/workspace/ATS2/libats/ML/SATS/list0.sats: 1665(line=47, offs=1) -- 1700(line=47, offs=36)
*/
/*
/home/ubuntu/workspace/ATS2/libats/ML/DATS/string.dats: 2842(line=109, offs=1) -- 2878(line=109, offs=37)
*/
/*
/home/ubuntu/workspace/ATS2/libats/ML/SATS/string.sats: 1525(line=41, offs=1) -- 1560(line=41, offs=36)
*/
/*
/home/ubuntu/workspace/ATS2/libats/ML/DATS/strarr.dats: 1613(line=46, offs=1) -- 1652(line=47, offs=32)
*/
/*
/home/ubuntu/workspace/ATS2/libats/ML/DATS/strarr.dats: 1675(line=51, offs=1) -- 1710(line=51, offs=36)
*/
/*
/home/ubuntu/workspace/ATS2/libats/ML/DATS/strarr.dats: 1711(line=52, offs=1) -- 1747(line=52, offs=37)
*/
/*
/home/ubuntu/workspace/ATS2/libats/ML/SATS/array0.sats: 1525(line=41, offs=1) -- 1571(line=44, offs=3)
*/

#include \
"libats/ML/CATS/array0.cats"
/*
/home/ubuntu/workspace/ATS2/libats/ML/SATS/array0.sats: 1610(line=48, offs=1) -- 1645(line=48, offs=36)
*/
/*
/home/ubuntu/workspace/ATS2/libats/ML/DATS/strarr.dats: 1748(line=53, offs=1) -- 1796(line=53, offs=49)
*/
/*
/home/ubuntu/workspace/ATS2/libats/ML/DATS/array0.dats: 1394(line=36, offs=1) -- 1433(line=37, offs=32)
*/
/*
/home/ubuntu/workspace/ATS2/libats/ML/DATS/array0.dats: 1458(line=41, offs=1) -- 1493(line=41, offs=36)
*/
/*
/home/ubuntu/workspace/ATS2/libats/ML/DATS/array0.dats: 1494(line=42, offs=1) -- 1529(line=42, offs=36)
*/
/*
/home/ubuntu/workspace/ATS2/libats/ML/SATS/list0.sats: 1665(line=47, offs=1) -- 1700(line=47, offs=36)
*/
/*
/home/ubuntu/workspace/ATS2/libats/ML/DATS/array0.dats: 1530(line=43, offs=1) -- 1566(line=43, offs=37)
*/
/*
/home/ubuntu/workspace/ATS2/libats/ML/SATS/array0.sats: 1525(line=41, offs=1) -- 1571(line=44, offs=3)
*/

#include \
"libats/ML/CATS/array0.cats"
/*
/home/ubuntu/workspace/ATS2/libats/ML/SATS/array0.sats: 1610(line=48, offs=1) -- 1645(line=48, offs=36)
*/
/*
/home/ubuntu/workspace/ATS2/libats/ML/DATS/strarr.dats: 1819(line=57, offs=1) -- 1855(line=57, offs=37)
*/
/*
/home/ubuntu/workspace/ATS2/libats/ML/SATS/strarr.sats: 1538(line=43, offs=1) -- 1574(line=43, offs=37)
*/
/*
/home/ubuntu/workspace/ATS2/libats/ML/SATS/strarr.sats: 1599(line=47, offs=1) -- 1649(line=51, offs=3)
*/

//
#include "libats/ML/CATS/strarr.cats"
//
/*
/home/ubuntu/workspace/ATS2/libats/ML/DATS/stream.dats: 1447(line=40, offs=1) -- 1486(line=41, offs=32)
*/
/*
/home/ubuntu/workspace/ATS2/libats/ML/DATS/stream.dats: 1509(line=45, offs=1) -- 1544(line=45, offs=36)
*/
/*
/home/ubuntu/workspace/ATS2/libats/ML/DATS/stream.dats: 1545(line=46, offs=1) -- 1581(line=46, offs=37)
*/
/*
/home/ubuntu/workspace/ATS2/libats/ML/SATS/stream.sats: 1532(line=43, offs=1) -- 1567(line=43, offs=36)
*/
/*
/home/ubuntu/workspace/ATS2/libats/ML/DATS/stream_vt.dats: 1447(line=40, offs=1) -- 1486(line=41, offs=32)
*/
/*
/home/ubuntu/workspace/ATS2/libats/ML/DATS/stream_vt.dats: 1509(line=45, offs=1) -- 1544(line=45, offs=36)
*/
/*
/home/ubuntu/workspace/ATS2/libats/ML/DATS/stream_vt.dats: 1545(line=46, offs=1) -- 1584(line=46, offs=40)
*/
/*
/home/ubuntu/workspace/ATS2/libats/ML/SATS/stream_vt.sats: 1534(line=43, offs=1) -- 1569(line=44, offs=28)
*/
/*
/home/ubuntu/workspace/ATS2/libats/ML/DATS/filebas.dats: 1472(line=40, offs=1) -- 1511(line=41, offs=32)
*/
/*
/home/ubuntu/workspace/ATS2/libats/ML/DATS/filebas.dats: 1534(line=45, offs=1) -- 1581(line=46, offs=40)
*/
/*
/home/ubuntu/workspace/ATS2/prelude/DATS/integer.dats: 1596(line=49, offs=1) -- 1635(line=49, offs=40)
*/
/*
/home/ubuntu/workspace/ATS2/libats/ML/DATS/filebas.dats: 1582(line=47, offs=1) -- 1634(line=48, offs=45)
*/
/*
/home/ubuntu/workspace/ATS2/prelude/DATS/integer_size.dats: 1597(line=49, offs=1) -- 1636(line=49, offs=40)
*/
/*
/home/ubuntu/workspace/ATS2/libats/ML/DATS/filebas.dats: 1657(line=52, offs=1) -- 1704(line=52, offs=48)
*/
/*
/home/ubuntu/workspace/ATS2/prelude/DATS/filebas.dats: 1613(line=49, offs=1) -- 1652(line=50, offs=32)
*/
/*
/home/ubuntu/workspace/ATS2/prelude/DATS/filebas.dats: 1675(line=54, offs=1) -- 1721(line=55, offs=39)
*/
/*
/home/ubuntu/workspace/ATS2/prelude/DATS/integer.dats: 1596(line=49, offs=1) -- 1635(line=49, offs=40)
*/
/*
/home/ubuntu/workspace/ATS2/prelude/DATS/filebas.dats: 1744(line=59, offs=1) -- 1789(line=60, offs=38)
*/
/*
/home/ubuntu/workspace/ATS2/libats/libc/SATS/stdio.sats: 1390(line=36, offs=1) -- 1437(line=39, offs=3)
*/

#include \
"libats/libc/CATS/stdio.cats"
/*
/home/ubuntu/workspace/ATS2/libats/libc/SATS/stdio.sats: 1950(line=69, offs=1) -- 1999(line=71, offs=34)
*/
/*
/home/ubuntu/workspace/ATS2/libats/libc/SATS/sys/types.sats: 1390(line=36, offs=1) -- 1441(line=39, offs=3)
*/

#include \
"libats/libc/CATS/sys/types.cats"
/*
/home/ubuntu/workspace/ATS2/prelude/DATS/filebas.dats: 1871(line=66, offs=1) -- 1918(line=66, offs=48)
*/
/*
/home/ubuntu/workspace/ATS2/libats/libc/SATS/sys/stat.sats: 1390(line=36, offs=1) -- 1440(line=39, offs=3)
*/

#include \
"libats/libc/CATS/sys/stat.cats"
/*
/home/ubuntu/workspace/ATS2/libats/libc/SATS/sys/stat.sats: 1756(line=58, offs=1) -- 1805(line=60, offs=34)
*/
/*
/home/ubuntu/workspace/ATS2/libats/libc/SATS/sys/types.sats: 1390(line=36, offs=1) -- 1441(line=39, offs=3)
*/

#include \
"libats/libc/CATS/sys/types.cats"
/*
/home/ubuntu/workspace/ATS2/prelude/DATS/filebas.dats: 15413(line=857, offs=1) -- 15450(line=858, offs=30)
*/
/*
/home/ubuntu/workspace/ATS2/libats/libc/SATS/stdio.sats: 1390(line=36, offs=1) -- 1437(line=39, offs=3)
*/

#include \
"libats/libc/CATS/stdio.cats"
/*
/home/ubuntu/workspace/ATS2/libats/libc/SATS/stdio.sats: 1950(line=69, offs=1) -- 1999(line=71, offs=34)
*/
/*
/home/ubuntu/workspace/ATS2/libats/libc/SATS/sys/types.sats: 1390(line=36, offs=1) -- 1441(line=39, offs=3)
*/

#include \
"libats/libc/CATS/sys/types.cats"
/*
/home/ubuntu/workspace/ATS2/libats/ML/DATS/filebas.dats: 2234(line=78, offs=1) -- 2269(line=78, offs=36)
*/
/*
/home/ubuntu/workspace/ATS2/libats/ML/DATS/filebas.dats: 2270(line=79, offs=1) -- 2305(line=79, offs=36)
*/
/*
/home/ubuntu/workspace/ATS2/libats/ML/SATS/list0.sats: 1665(line=47, offs=1) -- 1700(line=47, offs=36)
*/
/*
/home/ubuntu/workspace/ATS2/libats/ML/DATS/filebas.dats: 2306(line=80, offs=1) -- 2343(line=80, offs=38)
*/
/*
/home/ubuntu/workspace/ATS2/libats/ML/SATS/option0.sats: 1524(line=41, offs=1) -- 1559(line=41, offs=36)
*/
/*
/home/ubuntu/workspace/ATS2/libats/ML/DATS/filebas.dats: 2366(line=84, offs=1) -- 2403(line=84, offs=38)
*/
/*
/home/ubuntu/workspace/ATS2/libats/ML/SATS/filebas.sats: 1525(line=41, offs=1) -- 1560(line=41, offs=36)
*/
/*
/home/ubuntu/workspace/ATS2/libats/ML/DATS/filebas.dats: 2957(line=114, offs=1) -- 3003(line=114, offs=47)
*/
/*
/home/ubuntu/workspace/ATS2/prelude/DATS/strptr.dats: 1609(line=48, offs=1) -- 1648(line=48, offs=40)
*/
/*
/home/ubuntu/workspace/ATS2/prelude/DATS/strptr.dats: 1671(line=52, offs=1) -- 1718(line=52, offs=48)
*/
/*
/home/ubuntu/workspace/ATS2/prelude/DATS/integer.dats: 1596(line=49, offs=1) -- 1635(line=49, offs=40)
*/
/*
/home/ubuntu/workspace/ATS2/libats/ML/DATS/intrange.dats: 1397(line=36, offs=1) -- 1432(line=36, offs=36)
*/
/*
/home/ubuntu/workspace/ATS2/libats/ML/DATS/intrange.dats: 1455(line=40, offs=1) -- 1490(line=40, offs=36)
*/
/*
/home/ubuntu/workspace/ATS2/libats/ML/SATS/list0.sats: 1665(line=47, offs=1) -- 1700(line=47, offs=36)
*/
/*
/home/ubuntu/workspace/ATS2/libats/ML/DATS/intrange.dats: 1491(line=41, offs=1) -- 1527(line=41, offs=37)
*/
/*
/home/ubuntu/workspace/ATS2/libats/ML/SATS/array0.sats: 1525(line=41, offs=1) -- 1571(line=44, offs=3)
*/

#include \
"libats/ML/CATS/array0.cats"
/*
/home/ubuntu/workspace/ATS2/libats/ML/SATS/array0.sats: 1610(line=48, offs=1) -- 1645(line=48, offs=36)
*/
/*
/home/ubuntu/workspace/ATS2/libats/ML/DATS/intrange.dats: 1528(line=42, offs=1) -- 1566(line=42, offs=39)
*/
/*
/home/ubuntu/workspace/ATS2/libats/ML/SATS/intrange.sats: 1629(line=47, offs=1) -- 1664(line=47, offs=36)
*/
/*
/home/ubuntu/workspace/ATS2/libats/ML/SATS/stdlib.sats: 1522(line=41, offs=1) -- 1557(line=41, offs=36)
*/
/*
/home/ubuntu/workspace/ATS2/libats/ML/DATS/stdlib.dats: 1394(line=36, offs=1) -- 1433(line=38, offs=27)
*/
/*
/home/ubuntu/workspace/ATS2/libats/ML/DATS/stdlib.dats: 1437(line=40, offs=1) -- 1484(line=42, offs=31)
*/
/*
/home/ubuntu/workspace/ATS2/libats/libc/SATS/stdlib.sats: 1389(line=36, offs=1) -- 1443(line=41, offs=3)
*/

//
#include \
"libats/libc/CATS/stdlib.cats"
//
/*
/home/ubuntu/workspace/ATS2/libats/libc/SATS/stdlib.sats: 1810(line=62, offs=1) -- 1857(line=64, offs=31)
*/
/*
/home/ubuntu/workspace/ATS2/libats/ML/DATS/stdlib.dats: 1509(line=46, offs=1) -- 1544(line=46, offs=36)
*/
/*
/home/ubuntu/workspace/ATS2/libats/ML/DATS/stdlib.dats: 1567(line=50, offs=1) -- 1603(line=50, offs=37)
*/
/*
/home/ubuntu/workspace/ATS2/libats/ML/SATS/stdlib.sats: 1522(line=41, offs=1) -- 1557(line=41, offs=36)
*/
/*
/home/ubuntu/workspace/ATS2/libats/ML/SATS/funmap.sats: 1524(line=43, offs=1) -- 1559(line=43, offs=36)
*/
/*
/home/ubuntu/workspace/ATS2/libats/ML/SATS/funset.sats: 1524(line=41, offs=1) -- 1559(line=41, offs=36)
*/
/*
/home/ubuntu/workspace/ATS2/libats/ML/DATS/funmap.dats: 1485(line=41, offs=1) -- 1531(line=42, offs=34)
*/
/*
/home/ubuntu/workspace/ATS2/libats/ML/DATS/funmap.dats: 1556(line=46, offs=1) -- 1591(line=46, offs=36)
*/
/*
/home/ubuntu/workspace/ATS2/libats/ML/SATS/list0.sats: 1665(line=47, offs=1) -- 1700(line=47, offs=36)
*/
/*
/home/ubuntu/workspace/ATS2/libats/ML/DATS/funmap.dats: 1614(line=50, offs=1) -- 1650(line=50, offs=37)
*/
/*
/home/ubuntu/workspace/ATS2/libats/ML/SATS/funmap.sats: 1524(line=43, offs=1) -- 1559(line=43, offs=36)
*/
/*
/home/ubuntu/workspace/ATS2/libats/DATS/funmap_avltree.dats: 1534(line=43, offs=1) -- 1573(line=43, offs=40)
*/
/*
/home/ubuntu/workspace/ATS2/libats/DATS/funmap_avltree.dats: 1596(line=47, offs=1) -- 1637(line=47, offs=42)
*/
/*
/home/ubuntu/workspace/ATS2/libats/ML/DATS/funset.dats: 1484(line=40, offs=1) -- 1523(line=41, offs=32)
*/
/*
/home/ubuntu/workspace/ATS2/libats/ML/DATS/funset.dats: 1550(line=45, offs=1) -- 1596(line=47, offs=34)
*/
/*
/home/ubuntu/workspace/ATS2/libats/ML/DATS/funset.dats: 1621(line=51, offs=1) -- 1656(line=51, offs=36)
*/
/*
/home/ubuntu/workspace/ATS2/libats/ML/DATS/funset.dats: 1679(line=55, offs=1) -- 1714(line=55, offs=36)
*/
/*
/home/ubuntu/workspace/ATS2/libats/ML/SATS/list0.sats: 1665(line=47, offs=1) -- 1700(line=47, offs=36)
*/
/*
/home/ubuntu/workspace/ATS2/libats/ML/DATS/funset.dats: 1737(line=59, offs=1) -- 1773(line=59, offs=37)
*/
/*
/home/ubuntu/workspace/ATS2/libats/ML/SATS/funset.sats: 1524(line=41, offs=1) -- 1559(line=41, offs=36)
*/
/*
/home/ubuntu/workspace/ATS2/libats/DATS/funset_avltree.dats: 1417(line=37, offs=1) -- 1456(line=37, offs=40)
*/
/*
/home/ubuntu/workspace/ATS2/libats/DATS/funset_avltree.dats: 1479(line=41, offs=1) -- 1520(line=41, offs=42)
*/
/*
/home/ubuntu/workspace/ATS2/libats/ML/SATS/dynarray.sats: 1529(line=41, offs=1) -- 1564(line=41, offs=36)
*/
/*
/home/ubuntu/workspace/ATS2/libats/DATS/dynarray.dats: 1399(line=36, offs=1) -- 1438(line=37, offs=32)
*/
/*
/home/ubuntu/workspace/ATS2/libats/DATS/dynarray.dats: 1461(line=41, offs=1) -- 1496(line=41, offs=36)
*/
/*
/home/ubuntu/workspace/ATS2/libats/SATS/dynarray.sats: 1467(line=40, offs=1) -- 1510(line=42, offs=3)
*/

#include "libats/CATS/dynarray.cats"
/*
/home/ubuntu/workspace/ATS2/libats/ML/DATS/dynarray.dats: 1396(line=36, offs=1) -- 1435(line=37, offs=32)
*/
/*
/home/ubuntu/workspace/ATS2/libats/ML/DATS/dynarray.dats: 1460(line=41, offs=1) -- 1500(line=42, offs=33)
*/
/*
/home/ubuntu/workspace/ATS2/libats/SATS/dynarray.sats: 1467(line=40, offs=1) -- 1510(line=42, offs=3)
*/

#include "libats/CATS/dynarray.cats"
/*
/home/ubuntu/workspace/ATS2/libats/ML/DATS/dynarray.dats: 1525(line=46, offs=1) -- 1560(line=46, offs=36)
*/
/*
/home/ubuntu/workspace/ATS2/libats/ML/DATS/dynarray.dats: 1561(line=47, offs=1) -- 1596(line=47, offs=36)
*/
/*
/home/ubuntu/workspace/ATS2/libats/ML/SATS/list0.sats: 1665(line=47, offs=1) -- 1700(line=47, offs=36)
*/
/*
/home/ubuntu/workspace/ATS2/libats/ML/DATS/dynarray.dats: 1619(line=51, offs=1) -- 1657(line=51, offs=39)
*/
/*
/home/ubuntu/workspace/ATS2/libats/ML/SATS/dynarray.sats: 1529(line=41, offs=1) -- 1564(line=41, offs=36)
*/
/*
/home/ubuntu/workspace/ATS2/libats/ML/SATS/hashtblref.sats: 1524(line=43, offs=1) -- 1559(line=43, offs=36)
*/
/*
/home/ubuntu/workspace/ATS2/libats/DATS/qlist.dats: 1404(line=36, offs=1) -- 1443(line=37, offs=32)
*/
/*
/home/ubuntu/workspace/ATS2/libats/DATS/qlist.dats: 1466(line=41, offs=1) -- 1498(line=41, offs=33)
*/
/*
/home/ubuntu/workspace/ATS2/libats/SATS/qlist.sats: 1605(line=53, offs=1) -- 1645(line=55, offs=3)
*/

#include "libats/CATS/qlist.cats"
/*
/home/ubuntu/workspace/ATS2/libats/DATS/hashfun.dats: 1354(line=35, offs=1) -- 1393(line=36, offs=32)
*/
/*
/home/ubuntu/workspace/ATS2/libats/DATS/hashfun.dats: 1416(line=40, offs=1) -- 1450(line=40, offs=35)
*/
/*
/home/ubuntu/workspace/ATS2/libats/SATS/hashfun.sats: 1354(line=35, offs=1) -- 1396(line=37, offs=3)
*/

#include "libats/CATS/hashfun.cats"
/*
/home/ubuntu/workspace/ATS2/libats/DATS/linmap_list.dats: 1539(line=41, offs=1) -- 1578(line=42, offs=32)
*/
/*
/home/ubuntu/workspace/ATS2/libats/DATS/linmap_list.dats: 1601(line=46, offs=1) -- 1639(line=46, offs=39)
*/
/*
/home/ubuntu/workspace/ATS2/libats/DATS/hashtbl_chain.dats: 1604(line=42, offs=1) -- 1643(line=43, offs=32)
*/
/*
/home/ubuntu/workspace/ATS2/libats/DATS/hashtbl_chain.dats: 1666(line=47, offs=1) -- 1700(line=47, offs=35)
*/
/*
/home/ubuntu/workspace/ATS2/libats/SATS/hashfun.sats: 1354(line=35, offs=1) -- 1396(line=37, offs=3)
*/

#include "libats/CATS/hashfun.cats"
/*
/home/ubuntu/workspace/ATS2/libats/DATS/hashtbl_chain.dats: 1723(line=51, offs=1) -- 1763(line=51, offs=41)
*/
/*
/home/ubuntu/workspace/ATS2/libats/DATS/hashtbl_chain.dats: 2924(line=127, offs=1) -- 2967(line=128, offs=36)
*/
/*
/home/ubuntu/workspace/ATS2/libats/ML/DATS/qlistref.dats: 1447(line=40, offs=1) -- 1486(line=41, offs=32)
*/
/*
/home/ubuntu/workspace/ATS2/libats/ML/DATS/qlistref.dats: 1511(line=45, offs=1) -- 1543(line=45, offs=33)
*/
/*
/home/ubuntu/workspace/ATS2/libats/SATS/qlist.sats: 1605(line=53, offs=1) -- 1645(line=55, offs=3)
*/

#include "libats/CATS/qlist.cats"
/*
/home/ubuntu/workspace/ATS2/libats/ML/DATS/qlistref.dats: 1547(line=47, offs=1) -- 1582(line=47, offs=36)
*/
/*
/home/ubuntu/workspace/ATS2/libats/ML/DATS/qlistref.dats: 1583(line=48, offs=1) -- 1621(line=48, offs=39)
*/
/*
/home/ubuntu/workspace/ATS2/libats/ML/DATS/slistref.dats: 1452(line=41, offs=1) -- 1491(line=42, offs=32)
*/
/*
/home/ubuntu/workspace/ATS2/libats/ML/DATS/slistref.dats: 1516(line=46, offs=1) -- 1551(line=46, offs=36)
*/
/*
/home/ubuntu/workspace/ATS2/libats/ML/DATS/slistref.dats: 1552(line=47, offs=1) -- 1590(line=47, offs=39)
*/
/*
/home/ubuntu/workspace/ATS2/libats/ML/DATS/hashtblref.dats: 1394(line=36, offs=1) -- 1433(line=37, offs=32)
*/
/*
/home/ubuntu/workspace/ATS2/libats/ML/DATS/hashtblref.dats: 1458(line=41, offs=1) -- 1503(line=42, offs=33)
*/
/*
/home/ubuntu/workspace/ATS2/libats/ML/DATS/hashtblref.dats: 1528(line=46, offs=1) -- 1563(line=46, offs=36)
*/
/*
/home/ubuntu/workspace/ATS2/libats/ML/DATS/hashtblref.dats: 1586(line=50, offs=1) -- 1621(line=50, offs=36)
*/
/*
/home/ubuntu/workspace/ATS2/libats/ML/SATS/list0.sats: 1665(line=47, offs=1) -- 1700(line=47, offs=36)
*/
/*
/home/ubuntu/workspace/ATS2/libats/ML/DATS/hashtblref.dats: 1644(line=54, offs=1) -- 1678(line=54, offs=35)
*/
/*
/home/ubuntu/workspace/ATS2/libats/SATS/hashfun.sats: 1354(line=35, offs=1) -- 1396(line=37, offs=3)
*/

#include "libats/CATS/hashfun.cats"
/*
/home/ubuntu/workspace/ATS2/libats/ML/DATS/hashtblref.dats: 1679(line=55, offs=1) -- 1719(line=55, offs=41)
*/
/*
/home/ubuntu/workspace/ATS2/libats/ML/SATS/hashtblref.sats: 1524(line=43, offs=1) -- 1559(line=43, offs=36)
*/
/*
staload-prologues(end)
*/
/*
typedefs-for-tyrecs-and-tysums(beg)
*/
typedef
ATSstruct {
#if(0)
int contag ;
#endif
atstyvar_type(a) atslab__0 ;
atstype_boxed atslab__1 ;
} postiats_tysum_0 ;
typedef
ATSstruct {
#if(0)
int contag ;
#endif
atstkind_t0ype(atstype_char) atslab__0 ;
atstype_boxed atslab__1 ;
} postiats_tysum_1 ;
typedef
ATSstruct {
#if(0)
int contag ;
#endif
atstkind_t0ype(atstype_char) atslab__0 ;
atstkind_type(atstype_ptrk) atslab__1 ;
} postiats_tysum_2 ;
/*
typedefs-for-tyrecs-and-tysums(end)
*/
/*
dynconlst-declaration(beg)
*/
ATSdynexn_extdec(ATSLIB_056_prelude__ListSubscriptExn) ;
/*
dynconlst-declaration(end)
*/
/*
dyncstlst-declaration(beg)
*/
ATSdyncst_mac(atspre_eq_char0_char0)
ATSdyncst_mac(atspre_g1int2int_int_int)
ATSdyncst_mac(atspre_g1int_gte_int)
ATSdyncst_mac(atspre_g1int_gt_int)
ATSdyncst_mac(atspre_g1int_sub_int)
ATSdyncst_mac(atspre_neq_char1_char1)
ATSdyncst_mac(atspre_add_ptr1_bsz)
ATSdyncst_mac(atspre_print_bool)
ATSdyncst_mac(atspre_print_newline)
/*
dyncstlst-declaration(end)
*/
/*
dynvalist-implementation(beg)
*/
/*
dynvalist-implementation(end)
*/
/*
exnconlst-declaration(beg)
*/
#ifndef _ATS_CCOMP_EXCEPTION_NONE_
ATSextern()
atsvoid_t0ype
the_atsexncon_initize
(
  atstype_exnconptr d2c, atstype_string exnmsg
) ;
#endif // end of [_ATS_CCOMP_EXCEPTION_NONE_]
/*
exnconlst-declaration(end)
*/
/*
assumelst-declaration(beg)
*/
/*
assumelst-declaration(end)
*/
/*
extypelst-declaration(beg)
*/
/*
extypelst-declaration(end)
*/
ATSstatic()
atstkind_t0ype(atstype_bool)
myfun_0(atstkind_type(atstype_ptrk)) ;

#if(0)
#if(0)
ATSextern()
atstyvar_type(a)
ATSLIB_056_libats_056_ML__list0_get_at_exn__1(atstype_boxed, atstkind_t0ype(atstype_int)) ;
#endif // end of [QUALIFIED]
#endif // end of [TEMPLATE]

ATSstatic()
atstkind_t0ype(atstype_char)
ATSLIB_056_libats_056_ML__list0_get_at_exn__1__1(atstype_boxed, atstkind_t0ype(atstype_int)) ;

#if(0)
#if(0)
ATSextern()
atstyvar_type(a)
ATSLIB_056_libats_056_ML__list0_nth_exn__3(atstype_boxed, atstkind_t0ype(atstype_int)) ;
#endif // end of [QUALIFIED]
#endif // end of [TEMPLATE]

ATSstatic()
atstkind_t0ype(atstype_char)
ATSLIB_056_libats_056_ML__list0_nth_exn__3__1(atstype_boxed, atstkind_t0ype(atstype_int)) ;

#if(0)
#if(0)
ATSextern()
atstkind_t0ype(atstype_bool)
ATSLIB_056_prelude__gte_g1int_int__5(atstkind_t0ype(atstyvar_type(tk)), atstkind_t0ype(atstype_int)) ;
#endif // end of [QUALIFIED]
#endif // end of [TEMPLATE]

ATSstatic()
atstkind_t0ype(atstype_bool)
ATSLIB_056_prelude__gte_g1int_int__5__1(atstkind_t0ype(atstype_int), atstkind_t0ype(atstype_int)) ;

#if(0)
ATSstatic()
atstyvar_type(a)
loop_9__9(atstype_boxed, atstkind_t0ype(atstype_int)) ;
#endif // end of [TEMPLATE]

ATSstatic()
atstkind_t0ype(atstype_char)
loop_9__9__1(atstype_boxed, atstkind_t0ype(atstype_int)) ;

#if(0)
#if(0)
ATSextern()
atstkind_t0ype(atstype_bool)
ATSLIB_056_prelude__gt_g1int_int__11(atstkind_t0ype(atstyvar_type(tk)), atstkind_t0ype(atstype_int)) ;
#endif // end of [QUALIFIED]
#endif // end of [TEMPLATE]

ATSstatic()
atstkind_t0ype(atstype_bool)
ATSLIB_056_prelude__gt_g1int_int__11__1(atstkind_t0ype(atstype_int), atstkind_t0ype(atstype_int)) ;

#if(0)
#if(0)
ATSextern()
atstype_boxed
ATSLIB_056_libats_056_ML__string_explode__15(atstkind_type(atstype_ptrk)) ;
#endif // end of [QUALIFIED]
#endif // end of [TEMPLATE]

ATSstatic()
atstype_boxed
ATSLIB_056_libats_056_ML__string_explode__15__1(atstkind_type(atstype_ptrk)) ;

#if(0)
#if(0)
ATSextern()
atstype_boxed
ATSLIB_056_prelude__string_explode__17(atstkind_type(atstype_ptrk)) ;
#endif // end of [QUALIFIED]
#endif // end of [TEMPLATE]

#if(0)
ATSstatic()
atsvoid_t0ype
loop_18__18(atstkind_type(atstype_ptrk), atsrefarg1_type(atstkind_type(atstype_ptrk))) ;
#endif // end of [TEMPLATE]

ATSstatic()
atstype_boxed
ATSLIB_056_prelude__string_explode__17__1(atstkind_type(atstype_ptrk)) ;

ATSstatic()
atsvoid_t0ype
loop_18__18__1(atstkind_type(atstype_ptrk), atsrefarg1_type(atstkind_type(atstype_ptrk))) ;

#if(0)
#if(0)
ATSextern()
atstyvar_type(a)
ATSLIB_056_prelude_056_unsafe__ptr0_get__22(atstkind_type(atstype_ptrk)) ;
#endif // end of [QUALIFIED]
#endif // end of [TEMPLATE]

ATSstatic()
atstkind_t0ype(atstype_char)
ATSLIB_056_prelude_056_unsafe__ptr0_get__22__1(atstkind_type(atstype_ptrk)) ;

#if(0)
#if(0)
ATSextern()
atstkind_type(atstype_ptrk)
ATSLIB_056_prelude__ptr1_succ__24(atstkind_type(atstype_ptrk)) ;
#endif // end of [QUALIFIED]
#endif // end of [TEMPLATE]

ATSstatic()
atstkind_type(atstype_ptrk)
ATSLIB_056_prelude__ptr1_succ__24__1(atstkind_type(atstype_ptrk)) ;

#if(0)
ATSextern()
atsvoid_t0ype
mainats_void_0() ;
#endif // end of [QUALIFIED]

/*
/home/ubuntu/workspace/RosettaATS/test/test.dats: 137(line=8, offs=1) -- 241(line=12, offs=2)
*/
/*
local: 
global: myfun_0$0(level=0)
local: 
global: 
*/
ATSstatic()
atstkind_t0ype(atstype_bool)
myfun_0(atstkind_type(atstype_ptrk) arg0)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret0, atstkind_t0ype(atstype_bool)) ;
ATStmpdec(tmp1, atstkind_t0ype(atstype_bool)) ;
ATStmpdec(tmp2, atstkind_t0ype(atstype_char)) ;
ATStmpdec(tmp31, atstype_boxed) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /home/ubuntu/workspace/RosettaATS/test/test.dats: 137(line=8, offs=1) -- 241(line=12, offs=2)
*/
ATSINSflab(__patsflab_myfun_0):
/*
emit_instr: loc0 = /home/ubuntu/workspace/RosettaATS/test/test.dats: 188(line=10, offs=23) -- 206(line=10, offs=41)
*/
ATSINSmove(tmp31, ATSLIB_056_libats_056_ML__string_explode__15__1(arg0)) ;

/*
emit_instr: loc0 = /home/ubuntu/workspace/RosettaATS/test/test.dats: 171(line=10, offs=6) -- 210(line=10, offs=45)
*/
ATSINSmove(tmp2, ATSLIB_056_libats_056_ML__list0_get_at_exn__1__1(tmp31, ATSPMVi0nt(3))) ;

/*
emit_instr: loc0 = /home/ubuntu/workspace/RosettaATS/test/test.dats: 171(line=10, offs=6) -- 216(line=10, offs=51)
*/
ATSINSmove(tmp1, atspre_eq_char0_char0(tmp2, ATSPMVchar('e'))) ;

/*
emit_instr: loc0 = /home/ubuntu/workspace/RosettaATS/test/test.dats: 168(line=10, offs=3) -- 239(line=11, offs=13)
*/
ATSif(
tmp1
) ATSthen() {
/*
emit_instr: loc0 = /home/ubuntu/workspace/RosettaATS/test/test.dats: 222(line=10, offs=57) -- 226(line=10, offs=61)
*/
ATSINSmove(tmpret0, ATSPMVbool_true()) ;
} ATSelse() {
/*
emit_instr: loc0 = /home/ubuntu/workspace/RosettaATS/test/test.dats: 234(line=11, offs=8) -- 239(line=11, offs=13)
*/
ATSINSmove(tmpret0, ATSPMVbool_false()) ;
} /* ATSendif */
ATSfunbody_end()
ATSreturn(tmpret0) ;
} /* end of [myfun_0] */

#if(0)
/*
/home/ubuntu/workspace/ATS2/libats/ML/DATS/list0.dats: 7101(line=417, offs=3) -- 7132(line=417, offs=34)
*/
/*
local: 
global: list0_get_at_exn$1$0(level=0)
local: 
global: 
*/
ATSextern()
/*
imparg = a(9159)
tmparg = S2Evar(a(9159))
tmpsub = None()
*/
atstyvar_type(a)
ATSLIB_056_libats_056_ML__list0_get_at_exn__1(atstype_boxed arg0, atstkind_t0ype(atstype_int) arg1)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret3, atstyvar_type(a)) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /home/ubuntu/workspace/ATS2/libats/ML/DATS/list0.dats({$PATSLIBATS}/ML/DATS/list0.dats): 7082(line=416, offs=1) -- 7132(line=417, offs=34)
*/
ATSINSflab(__patsflab_list0_get_at_exn):
/*
emit_instr: loc0 = /home/ubuntu/workspace/ATS2/libats/ML/DATS/list0.dats({$PATSLIBATS}/ML/DATS/list0.dats): 7111(line=417, offs=13) -- 7132(line=417, offs=34)
*/
ATSINSmove(tmpret3, PMVtmpltcst(list0_nth_exn<S2Evar(a(9159))>)(arg0, arg1)) ;

ATSfunbody_end()
ATSreturn(tmpret3) ;
} /* end of [ATSLIB_056_libats_056_ML__list0_get_at_exn__1] */
#endif // end of [TEMPLATE]

/*
/home/ubuntu/workspace/ATS2/libats/ML/DATS/list0.dats: 7101(line=417, offs=3) -- 7132(line=417, offs=34)
*/
/*
local: 
global: list0_get_at_exn$1$1(level=1)
local: 
global: 
*/
ATSstatic()
/*
imparg = a(9159)
tmparg = S2Evar(a(9159))
tmpsub = Some(a(9159) -> S2Ecst(char_t0ype))
*/
atstkind_t0ype(atstype_char)
ATSLIB_056_libats_056_ML__list0_get_at_exn__1__1(atstype_boxed arg0, atstkind_t0ype(atstype_int) arg1)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret3__1, atstkind_t0ype(atstype_char)) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /home/ubuntu/workspace/ATS2/libats/ML/DATS/list0.dats({$PATSLIBATS}/ML/DATS/list0.dats): 7082(line=416, offs=1) -- 7132(line=417, offs=34)
*/
ATSINSflab(__patsflab_list0_get_at_exn):
/*
emit_instr: loc0 = /home/ubuntu/workspace/ATS2/libats/ML/DATS/list0.dats({$PATSLIBATS}/ML/DATS/list0.dats): 7111(line=417, offs=13) -- 7132(line=417, offs=34)
*/
ATSINSmove(tmpret3__1, ATSLIB_056_libats_056_ML__list0_nth_exn__3__1(arg0, arg1)) ;

ATSfunbody_end()
ATSreturn(tmpret3__1) ;
} /* end of [ATSLIB_056_libats_056_ML__list0_get_at_exn__1__1] */

#if(0)
/*
/home/ubuntu/workspace/ATS2/libats/ML/DATS/list0.dats: 6607(line=377, offs=3) -- 6723(line=388, offs=4)
*/
/*
local: 
global: list0_nth_exn$3$0(level=0)
local: 
global: 
*/
ATSextern()
/*
imparg = a(9156)
tmparg = S2Evar(a(9156))
tmpsub = None()
*/
atstyvar_type(a)
ATSLIB_056_libats_056_ML__list0_nth_exn__3(atstype_boxed arg0, atstkind_t0ype(atstype_int) arg1)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret5, atstyvar_type(a)) ;
ATStmpdec(tmp6, atstkind_t0ype(atstype_bool)) ;
ATStmpdec(tmp7, atstype_exnconptr) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /home/ubuntu/workspace/ATS2/libats/ML/DATS/list0.dats({$PATSLIBATS}/ML/DATS/list0.dats): 6591(line=376, offs=1) -- 6723(line=388, offs=4)
*/
ATSINSflab(__patsflab_list0_nth_exn):
/*
emit_instr: loc0 = /home/ubuntu/workspace/ATS2/libats/ML/DATS/list0.dats({$PATSLIBATS}/ML/DATS/list0.dats): 6617(line=377, offs=13) -- 6723(line=388, offs=4)
*/
/*
letpush(beg)
*/
/* (*nothing*) */
/*
letpush(end)
*/

/*
emit_instr: loc0 = /home/ubuntu/workspace/ATS2/libats/ML/DATS/list0.dats({$PATSLIBATS}/ML/DATS/list0.dats): 6658(line=384, offs=1) -- 6664(line=384, offs=7)
*/
ATSINSmove(tmp6, PMVtmpltcst(gte_g1int_int<S2Eextkind(atstype_int)>)(ATSPMVcastfn(g1ofg0_int, atstkind_t0ype(atstype_int), arg1), ATSPMVi0nt(0))) ;

/*
emit_instr: loc0 = /home/ubuntu/workspace/ATS2/libats/ML/DATS/list0.dats({$PATSLIBATS}/ML/DATS/list0.dats): 6655(line=383, offs=1) -- 6716(line=386, offs=31)
*/
ATSif(
tmp6
) ATSthen() {
/*
emit_instr: loc0 = /home/ubuntu/workspace/ATS2/libats/ML/DATS/list0.dats({$PATSLIBATS}/ML/DATS/list0.dats): 6670(line=385, offs=6) -- 6685(line=385, offs=21)
*/
ATSINSmove(tmpret5, PMVtmpltvar(loop$4536(0)<S2Evar(a(9156))>)(arg0, ATSPMVcastfn(g1ofg0_int, atstkind_t0ype(atstype_int), arg1))) ;

} ATSelse() {
/*
emit_instr: loc0 = /home/ubuntu/workspace/ATS2/libats/ML/DATS/list0.dats({$PATSLIBATS}/ML/DATS/list0.dats): 6698(line=386, offs=13) -- 6716(line=386, offs=31)
*/

ATSINSmove_exn0(tmp7, ATSLIB_056_prelude__ListSubscriptExn) ;

/*
emit_instr: loc0 = /home/ubuntu/workspace/ATS2/libats/ML/DATS/list0.dats({$PATSLIBATS}/ML/DATS/list0.dats): 6691(line=386, offs=6) -- 6716(line=386, offs=31)
*/
ATSINSraise_exn(tmpret5, tmp7) ;
} /* ATSendif */
/*
emit_instr: loc0 = /home/ubuntu/workspace/ATS2/libats/ML/DATS/list0.dats({$PATSLIBATS}/ML/DATS/list0.dats): 6617(line=377, offs=13) -- 6723(line=388, offs=4)
*/
/*
INSletpop()
*/
ATSfunbody_end()
ATSreturn(tmpret5) ;
} /* end of [ATSLIB_056_libats_056_ML__list0_nth_exn__3] */
#endif // end of [TEMPLATE]

/*
/home/ubuntu/workspace/ATS2/libats/ML/DATS/list0.dats: 6607(line=377, offs=3) -- 6723(line=388, offs=4)
*/
/*
local: 
global: list0_nth_exn$3$1(level=2)
local: 
global: 
*/
ATSstatic()
/*
imparg = a(9156)
tmparg = S2Evar(a(9156))
tmpsub = Some(a(9156) -> S2Ecst(char_t0ype))
*/
atstkind_t0ype(atstype_char)
ATSLIB_056_libats_056_ML__list0_nth_exn__3__1(atstype_boxed arg0, atstkind_t0ype(atstype_int) arg1)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret5__1, atstkind_t0ype(atstype_char)) ;
ATStmpdec(tmp6__1, atstkind_t0ype(atstype_bool)) ;
ATStmpdec(tmp7__1, atstype_exnconptr) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /home/ubuntu/workspace/ATS2/libats/ML/DATS/list0.dats({$PATSLIBATS}/ML/DATS/list0.dats): 6591(line=376, offs=1) -- 6723(line=388, offs=4)
*/
ATSINSflab(__patsflab_list0_nth_exn):
/*
emit_instr: loc0 = /home/ubuntu/workspace/ATS2/libats/ML/DATS/list0.dats({$PATSLIBATS}/ML/DATS/list0.dats): 6617(line=377, offs=13) -- 6723(line=388, offs=4)
*/
/*
letpush(beg)
*/
/* (*nothing*) */
/*
letpush(end)
*/

/*
emit_instr: loc0 = /home/ubuntu/workspace/ATS2/libats/ML/DATS/list0.dats({$PATSLIBATS}/ML/DATS/list0.dats): 6658(line=384, offs=1) -- 6664(line=384, offs=7)
*/
ATSINSmove(tmp6__1, ATSLIB_056_prelude__gte_g1int_int__5__1(ATSPMVcastfn(g1ofg0_int, atstkind_t0ype(atstype_int), arg1), ATSPMVi0nt(0))) ;

/*
emit_instr: loc0 = /home/ubuntu/workspace/ATS2/libats/ML/DATS/list0.dats({$PATSLIBATS}/ML/DATS/list0.dats): 6655(line=383, offs=1) -- 6716(line=386, offs=31)
*/
ATSif(
tmp6__1
) ATSthen() {
/*
emit_instr: loc0 = /home/ubuntu/workspace/ATS2/libats/ML/DATS/list0.dats({$PATSLIBATS}/ML/DATS/list0.dats): 6670(line=385, offs=6) -- 6685(line=385, offs=21)
*/
ATSINSmove(tmpret5__1, loop_9__9__1(arg0, ATSPMVcastfn(g1ofg0_int, atstkind_t0ype(atstype_int), arg1))) ;

} ATSelse() {
/*
emit_instr: loc0 = /home/ubuntu/workspace/ATS2/libats/ML/DATS/list0.dats({$PATSLIBATS}/ML/DATS/list0.dats): 6698(line=386, offs=13) -- 6716(line=386, offs=31)
*/

ATSINSmove_exn0(tmp7__1, ATSLIB_056_prelude__ListSubscriptExn) ;

/*
emit_instr: loc0 = /home/ubuntu/workspace/ATS2/libats/ML/DATS/list0.dats({$PATSLIBATS}/ML/DATS/list0.dats): 6691(line=386, offs=6) -- 6716(line=386, offs=31)
*/
ATSINSraise_exn(tmpret5__1, tmp7__1) ;
} /* ATSendif */
/*
emit_instr: loc0 = /home/ubuntu/workspace/ATS2/libats/ML/DATS/list0.dats({$PATSLIBATS}/ML/DATS/list0.dats): 6617(line=377, offs=13) -- 6723(line=388, offs=4)
*/
/*
INSletpop()
*/
ATSfunbody_end()
ATSreturn(tmpret5__1) ;
} /* end of [ATSLIB_056_libats_056_ML__list0_nth_exn__3__1] */

#if(0)
/*
/home/ubuntu/workspace/ATS2/prelude/DATS/integer.dats: 12329(line=629, offs=3) -- 12369(line=629, offs=43)
*/
/*
local: 
global: gte_g1int_int$5$0(level=0)
local: 
global: 
*/
ATSextern()
/*
imparg = tk(4634)
tmparg = S2Evar(tk(4634))
tmpsub = None()
*/
atstkind_t0ype(atstype_bool)
ATSLIB_056_prelude__gte_g1int_int__5(atstkind_t0ype(atstyvar_type(tk)) arg0, atstkind_t0ype(atstype_int) arg1)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret11, atstkind_t0ype(atstype_bool)) ;
ATStmpdec(tmp12, atstkind_t0ype(atstyvar_type(tk))) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /home/ubuntu/workspace/ATS2/prelude/DATS/integer.dats({$PATSPRE}/DATS/integer.dats): 12313(line=628, offs=1) -- 12369(line=629, offs=43)
*/
ATSINSflab(__patsflab_gte_g1int_int):
/*
emit_instr: loc0 = /home/ubuntu/workspace/ATS2/prelude/DATS/integer.dats({$PATSPRE}/DATS/integer.dats): 12356(line=629, offs=30) -- 12367(line=629, offs=41)
*/
ATSINSmove(tmp12, PMVtmpltcst(g1int2int<S2Eextkind(atstype_int), S2Evar(tk(4634))>)(arg1)) ;

/*
emit_instr: loc0 = /home/ubuntu/workspace/ATS2/prelude/DATS/integer.dats({$PATSPRE}/DATS/integer.dats): 12338(line=629, offs=12) -- 12369(line=629, offs=43)
*/
ATSINSmove(tmpret11, PMVtmpltcst(g1int_gte<S2Evar(tk(4634))>)(arg0, tmp12)) ;

ATSfunbody_end()
ATSreturn(tmpret11) ;
} /* end of [ATSLIB_056_prelude__gte_g1int_int__5] */
#endif // end of [TEMPLATE]

/*
/home/ubuntu/workspace/ATS2/prelude/DATS/integer.dats: 12329(line=629, offs=3) -- 12369(line=629, offs=43)
*/
/*
local: 
global: gte_g1int_int$5$1(level=3)
local: 
global: 
*/
ATSstatic()
/*
imparg = tk(4634)
tmparg = S2Evar(tk(4634))
tmpsub = Some(tk(4634) -> S2Eextkind(atstype_int))
*/
atstkind_t0ype(atstype_bool)
ATSLIB_056_prelude__gte_g1int_int__5__1(atstkind_t0ype(atstype_int) arg0, atstkind_t0ype(atstype_int) arg1)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret11__1, atstkind_t0ype(atstype_bool)) ;
ATStmpdec(tmp12__1, atstkind_t0ype(atstype_int)) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /home/ubuntu/workspace/ATS2/prelude/DATS/integer.dats({$PATSPRE}/DATS/integer.dats): 12313(line=628, offs=1) -- 12369(line=629, offs=43)
*/
ATSINSflab(__patsflab_gte_g1int_int):
/*
emit_instr: loc0 = /home/ubuntu/workspace/ATS2/prelude/DATS/integer.dats({$PATSPRE}/DATS/integer.dats): 12356(line=629, offs=30) -- 12367(line=629, offs=41)
*/
ATSINSmove(tmp12__1, atspre_g1int2int_int_int(arg1)) ;

/*
emit_instr: loc0 = /home/ubuntu/workspace/ATS2/prelude/DATS/integer.dats({$PATSPRE}/DATS/integer.dats): 12338(line=629, offs=12) -- 12369(line=629, offs=43)
*/
ATSINSmove(tmpret11__1, atspre_g1int_gte_int(arg0, tmp12__1)) ;

ATSfunbody_end()
ATSreturn(tmpret11__1) ;
} /* end of [ATSLIB_056_prelude__gte_g1int_int__5__1] */

#if(0)
/*
/home/ubuntu/workspace/ATS2/libats/ML/DATS/list0.dats: 6293(line=356, offs=1) -- 6527(line=370, offs=4)
*/
/*
local: 
global: loop_9$0(level=3)
local: 
global: 
*/
ATSstatic()
atstyvar_type(a)
loop_9__9(atstype_boxed arg0, atstkind_t0ype(atstype_int) arg1)
{
/* tmpvardeclst(beg) */
ATStmpdec(apy0, atstype_boxed) ;
ATStmpdec(apy1, atstkind_t0ype(atstype_int)) ;
ATStmpdec(tmpret15, atstyvar_type(a)) ;
ATStmpdec(tmp16, atstyvar_type(a)) ;
ATStmpdec(tmp17, atstype_boxed) ;
ATStmpdec(tmp18, atstkind_t0ype(atstype_bool)) ;
ATStmpdec(tmp19, atstkind_t0ype(atstype_int)) ;
ATStmpdec(tmp20, atstype_exnconptr) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /home/ubuntu/workspace/ATS2/libats/ML/DATS/list0.dats({$PATSLIBATS}/ML/DATS/list0.dats): 6293(line=356, offs=1) -- 6527(line=370, offs=4)
*/
ATSINSflab(__patsflab_loop_9):
/*
emit_instr: loc0 = /home/ubuntu/workspace/ATS2/libats/ML/DATS/list0.dats({$PATSLIBATS}/ML/DATS/list0.dats): 6363(line=362, offs=1) -- 6520(line=368, offs=44)
*/
ATScaseof_beg()
/*
** ibranchlst-beg
*/
ATSbranch_beg()
/*
emit_instr: loc0 = /home/ubuntu/workspace/ATS2/libats/ML/DATS/list0.dats({$PATSLIBATS}/ML/DATS/list0.dats): 6377(line=363, offs=3) -- 6399(line=364, offs=12)
*/
ATSINSlab(__atstmplab0):
/*
emit_instr: loc0 = /home/ubuntu/workspace/ATS2/libats/ML/DATS/list0.dats({$PATSLIBATS}/ML/DATS/list0.dats): 6315(line=358, offs=3) -- 6317(line=358, offs=5)
*/
ATSifthen(ATSCKptrisnull(arg0)) { ATSINSgoto(__atstmplab3) ; } ;
/*
emit_instr: loc0 = /home/ubuntu/workspace/ATS2/libats/ML/DATS/list0.dats({$PATSLIBATS}/ML/DATS/list0.dats): 6399(line=364, offs=12) -- 6399(line=364, offs=12)
*/
ATSINSlab(__atstmplab1):
/*
emit_instr: loc0 = /home/ubuntu/workspace/ATS2/libats/ML/DATS/list0.dats({$PATSLIBATS}/ML/DATS/list0.dats): 6393(line=364, offs=6) -- 6394(line=364, offs=7)
*/
ATSINSmove(tmp16, ATSSELcon(arg0, postiats_tysum_0, atslab__0)) ;
/*
emit_instr: loc0 = /home/ubuntu/workspace/ATS2/libats/ML/DATS/list0.dats({$PATSLIBATS}/ML/DATS/list0.dats): 6396(line=364, offs=9) -- 6398(line=364, offs=11)
*/
ATSINSmove(tmp17, ATSSELcon(arg0, postiats_tysum_0, atslab__1)) ;
/*
emit_instr: loc0 = : 0(line=0, offs=0) -- 0(line=0, offs=0)
*/
/*
ibranch-mbody:
*/
/*
emit_instr: loc0 = /home/ubuntu/workspace/ATS2/libats/ML/DATS/list0.dats({$PATSLIBATS}/ML/DATS/list0.dats): 6414(line=366, offs=8) -- 6419(line=366, offs=13)
*/
ATSINSmove(tmp18, PMVtmpltcst(gt_g1int_int<S2Eextkind(atstype_int)>)(arg1, ATSPMVi0nt(0))) ;

/*
emit_instr: loc0 = /home/ubuntu/workspace/ATS2/libats/ML/DATS/list0.dats({$PATSLIBATS}/ML/DATS/list0.dats): 6411(line=366, offs=5) -- 6449(line=366, offs=43)
*/
ATSif(
tmp18
) ATSthen() {
/*
emit_instr: loc0 = /home/ubuntu/workspace/ATS2/libats/ML/DATS/list0.dats({$PATSLIBATS}/ML/DATS/list0.dats): 6438(line=366, offs=32) -- 6441(line=366, offs=35)
*/
ATSINSmove(tmp19, PMVtmpltcst(g1int_sub<S2Eextkind(atstype_int)>)(arg1, ATSPMVi0nt(1))) ;

/*
emit_instr: loc0 = /home/ubuntu/workspace/ATS2/libats/ML/DATS/list0.dats({$PATSLIBATS}/ML/DATS/list0.dats): 6425(line=366, offs=19) -- 6442(line=366, offs=36)
*/
ATStailcal_beg()
ATSINSmove_tlcal(apy0, tmp17) ;
ATSINSmove_tlcal(apy1, tmp19) ;
ATSINSargmove_tlcal(arg0, apy0) ;
ATSINSargmove_tlcal(arg1, apy1) ;
ATSINSfgoto(__patsflab_loop_9) ;
ATStailcal_end()

} ATSelse() {
/*
emit_instr: loc0 = /home/ubuntu/workspace/ATS2/libats/ML/DATS/list0.dats({$PATSLIBATS}/ML/DATS/list0.dats): 6448(line=366, offs=42) -- 6449(line=366, offs=43)
*/
ATSINSmove(tmpret15, tmp16) ;
} /* ATSendif */
ATSbranch_end()

ATSbranch_beg()
/*
emit_instr: loc0 = /home/ubuntu/workspace/ATS2/libats/ML/DATS/list0.dats({$PATSLIBATS}/ML/DATS/list0.dats): 6479(line=368, offs=3) -- 6491(line=368, offs=15)
*/
ATSINSlab(__atstmplab2):
/*
emit_instr: loc0 = /home/ubuntu/workspace/ATS2/libats/ML/DATS/list0.dats({$PATSLIBATS}/ML/DATS/list0.dats): 6315(line=358, offs=3) -- 6317(line=358, offs=5)
*/
#if(0)
ATSifthen(ATSCKptriscons(arg0)) { ATSINSdeadcode_fail() ; } ;
#endif
/*
emit_instr: loc0 = /home/ubuntu/workspace/ATS2/libats/ML/DATS/list0.dats({$PATSLIBATS}/ML/DATS/list0.dats): 6491(line=368, offs=15) -- 6491(line=368, offs=15)
*/
ATSINSlab(__atstmplab3):
/*
emit_instr: loc0 = : 0(line=0, offs=0) -- 0(line=0, offs=0)
*/
/*
ibranch-mbody:
*/
/*
emit_instr: loc0 = /home/ubuntu/workspace/ATS2/libats/ML/DATS/list0.dats({$PATSLIBATS}/ML/DATS/list0.dats): 6502(line=368, offs=26) -- 6520(line=368, offs=44)
*/

ATSINSmove_exn0(tmp20, ATSLIB_056_prelude__ListSubscriptExn) ;

/*
emit_instr: loc0 = /home/ubuntu/workspace/ATS2/libats/ML/DATS/list0.dats({$PATSLIBATS}/ML/DATS/list0.dats): 6495(line=368, offs=19) -- 6520(line=368, offs=44)
*/
ATSINSraise_exn(tmpret15, tmp20) ;
ATSbranch_end()

/*
** ibranchlst-end
*/
ATScaseof_end()

ATSfunbody_end()
ATSreturn(tmpret15) ;
} /* end of [loop_9__9] */
#endif // end of [TEMPLATE]

/*
/home/ubuntu/workspace/ATS2/libats/ML/DATS/list0.dats: 6293(line=356, offs=1) -- 6527(line=370, offs=4)
*/
/*
local: 
global: loop_9$1(level=3)
local: 
global: 
*/
ATSstatic()
atstkind_t0ype(atstype_char)
loop_9__9__1(atstype_boxed arg0, atstkind_t0ype(atstype_int) arg1)
{
/* tmpvardeclst(beg) */
ATStmpdec(apy0, atstype_boxed) ;
ATStmpdec(apy1, atstkind_t0ype(atstype_int)) ;
ATStmpdec(tmpret15__1, atstkind_t0ype(atstype_char)) ;
ATStmpdec(tmp16__1, atstkind_t0ype(atstype_char)) ;
ATStmpdec(tmp17__1, atstype_boxed) ;
ATStmpdec(tmp18__1, atstkind_t0ype(atstype_bool)) ;
ATStmpdec(tmp19__1, atstkind_t0ype(atstype_int)) ;
ATStmpdec(tmp20__1, atstype_exnconptr) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /home/ubuntu/workspace/ATS2/libats/ML/DATS/list0.dats({$PATSLIBATS}/ML/DATS/list0.dats): 6293(line=356, offs=1) -- 6527(line=370, offs=4)
*/
ATSINSflab(__patsflab_loop_9):
/*
emit_instr: loc0 = /home/ubuntu/workspace/ATS2/libats/ML/DATS/list0.dats({$PATSLIBATS}/ML/DATS/list0.dats): 6363(line=362, offs=1) -- 6520(line=368, offs=44)
*/
ATScaseof_beg()
/*
** ibranchlst-beg
*/
ATSbranch_beg()
/*
emit_instr: loc0 = /home/ubuntu/workspace/ATS2/libats/ML/DATS/list0.dats({$PATSLIBATS}/ML/DATS/list0.dats): 6377(line=363, offs=3) -- 6399(line=364, offs=12)
*/
ATSINSlab(__atstmplab0):
/*
emit_instr: loc0 = /home/ubuntu/workspace/ATS2/libats/ML/DATS/list0.dats({$PATSLIBATS}/ML/DATS/list0.dats): 6315(line=358, offs=3) -- 6317(line=358, offs=5)
*/
ATSifthen(ATSCKptrisnull(arg0)) { ATSINSgoto(__atstmplab3) ; } ;
/*
emit_instr: loc0 = /home/ubuntu/workspace/ATS2/libats/ML/DATS/list0.dats({$PATSLIBATS}/ML/DATS/list0.dats): 6399(line=364, offs=12) -- 6399(line=364, offs=12)
*/
ATSINSlab(__atstmplab1):
/*
emit_instr: loc0 = /home/ubuntu/workspace/ATS2/libats/ML/DATS/list0.dats({$PATSLIBATS}/ML/DATS/list0.dats): 6393(line=364, offs=6) -- 6394(line=364, offs=7)
*/
ATSINSmove(tmp16__1, ATSSELcon(arg0, postiats_tysum_1, atslab__0)) ;
/*
emit_instr: loc0 = /home/ubuntu/workspace/ATS2/libats/ML/DATS/list0.dats({$PATSLIBATS}/ML/DATS/list0.dats): 6396(line=364, offs=9) -- 6398(line=364, offs=11)
*/
ATSINSmove(tmp17__1, ATSSELcon(arg0, postiats_tysum_1, atslab__1)) ;
/*
emit_instr: loc0 = : 0(line=0, offs=0) -- 0(line=0, offs=0)
*/
/*
ibranch-mbody:
*/
/*
emit_instr: loc0 = /home/ubuntu/workspace/ATS2/libats/ML/DATS/list0.dats({$PATSLIBATS}/ML/DATS/list0.dats): 6414(line=366, offs=8) -- 6419(line=366, offs=13)
*/
ATSINSmove(tmp18__1, ATSLIB_056_prelude__gt_g1int_int__11__1(arg1, ATSPMVi0nt(0))) ;

/*
emit_instr: loc0 = /home/ubuntu/workspace/ATS2/libats/ML/DATS/list0.dats({$PATSLIBATS}/ML/DATS/list0.dats): 6411(line=366, offs=5) -- 6449(line=366, offs=43)
*/
ATSif(
tmp18__1
) ATSthen() {
/*
emit_instr: loc0 = /home/ubuntu/workspace/ATS2/libats/ML/DATS/list0.dats({$PATSLIBATS}/ML/DATS/list0.dats): 6438(line=366, offs=32) -- 6441(line=366, offs=35)
*/
ATSINSmove(tmp19__1, atspre_g1int_sub_int(arg1, ATSPMVi0nt(1))) ;

/*
emit_instr: loc0 = /home/ubuntu/workspace/ATS2/libats/ML/DATS/list0.dats({$PATSLIBATS}/ML/DATS/list0.dats): 6425(line=366, offs=19) -- 6442(line=366, offs=36)
*/
ATStailcal_beg()
ATSINSmove_tlcal(apy0, tmp17__1) ;
ATSINSmove_tlcal(apy1, tmp19__1) ;
ATSINSargmove_tlcal(arg0, apy0) ;
ATSINSargmove_tlcal(arg1, apy1) ;
ATSINSfgoto(__patsflab_loop_9) ;
ATStailcal_end()

} ATSelse() {
/*
emit_instr: loc0 = /home/ubuntu/workspace/ATS2/libats/ML/DATS/list0.dats({$PATSLIBATS}/ML/DATS/list0.dats): 6448(line=366, offs=42) -- 6449(line=366, offs=43)
*/
ATSINSmove(tmpret15__1, tmp16__1) ;
} /* ATSendif */
ATSbranch_end()

ATSbranch_beg()
/*
emit_instr: loc0 = /home/ubuntu/workspace/ATS2/libats/ML/DATS/list0.dats({$PATSLIBATS}/ML/DATS/list0.dats): 6479(line=368, offs=3) -- 6491(line=368, offs=15)
*/
ATSINSlab(__atstmplab2):
/*
emit_instr: loc0 = /home/ubuntu/workspace/ATS2/libats/ML/DATS/list0.dats({$PATSLIBATS}/ML/DATS/list0.dats): 6315(line=358, offs=3) -- 6317(line=358, offs=5)
*/
#if(0)
ATSifthen(ATSCKptriscons(arg0)) { ATSINSdeadcode_fail() ; } ;
#endif
/*
emit_instr: loc0 = /home/ubuntu/workspace/ATS2/libats/ML/DATS/list0.dats({$PATSLIBATS}/ML/DATS/list0.dats): 6491(line=368, offs=15) -- 6491(line=368, offs=15)
*/
ATSINSlab(__atstmplab3):
/*
emit_instr: loc0 = : 0(line=0, offs=0) -- 0(line=0, offs=0)
*/
/*
ibranch-mbody:
*/
/*
emit_instr: loc0 = /home/ubuntu/workspace/ATS2/libats/ML/DATS/list0.dats({$PATSLIBATS}/ML/DATS/list0.dats): 6502(line=368, offs=26) -- 6520(line=368, offs=44)
*/

ATSINSmove_exn0(tmp20__1, ATSLIB_056_prelude__ListSubscriptExn) ;

/*
emit_instr: loc0 = /home/ubuntu/workspace/ATS2/libats/ML/DATS/list0.dats({$PATSLIBATS}/ML/DATS/list0.dats): 6495(line=368, offs=19) -- 6520(line=368, offs=44)
*/
ATSINSraise_exn(tmpret15__1, tmp20__1) ;
ATSbranch_end()

/*
** ibranchlst-end
*/
ATScaseof_end()

ATSfunbody_end()
ATSreturn(tmpret15__1) ;
} /* end of [loop_9__9__1] */

#if(0)
/*
/home/ubuntu/workspace/ATS2/prelude/DATS/integer.dats: 12251(line=625, offs=3) -- 12290(line=625, offs=42)
*/
/*
local: 
global: gt_g1int_int$11$0(level=0)
local: 
global: 
*/
ATSextern()
/*
imparg = tk(4631)
tmparg = S2Evar(tk(4631))
tmpsub = None()
*/
atstkind_t0ype(atstype_bool)
ATSLIB_056_prelude__gt_g1int_int__11(atstkind_t0ype(atstyvar_type(tk)) arg0, atstkind_t0ype(atstype_int) arg1)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret27, atstkind_t0ype(atstype_bool)) ;
ATStmpdec(tmp28, atstkind_t0ype(atstyvar_type(tk))) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /home/ubuntu/workspace/ATS2/prelude/DATS/integer.dats({$PATSPRE}/DATS/integer.dats): 12236(line=624, offs=1) -- 12290(line=625, offs=42)
*/
ATSINSflab(__patsflab_gt_g1int_int):
/*
emit_instr: loc0 = /home/ubuntu/workspace/ATS2/prelude/DATS/integer.dats({$PATSPRE}/DATS/integer.dats): 12277(line=625, offs=29) -- 12288(line=625, offs=40)
*/
ATSINSmove(tmp28, PMVtmpltcst(g1int2int<S2Eextkind(atstype_int), S2Evar(tk(4631))>)(arg1)) ;

/*
emit_instr: loc0 = /home/ubuntu/workspace/ATS2/prelude/DATS/integer.dats({$PATSPRE}/DATS/integer.dats): 12260(line=625, offs=12) -- 12290(line=625, offs=42)
*/
ATSINSmove(tmpret27, PMVtmpltcst(g1int_gt<S2Evar(tk(4631))>)(arg0, tmp28)) ;

ATSfunbody_end()
ATSreturn(tmpret27) ;
} /* end of [ATSLIB_056_prelude__gt_g1int_int__11] */
#endif // end of [TEMPLATE]

/*
/home/ubuntu/workspace/ATS2/prelude/DATS/integer.dats: 12251(line=625, offs=3) -- 12290(line=625, offs=42)
*/
/*
local: 
global: gt_g1int_int$11$1(level=4)
local: 
global: 
*/
ATSstatic()
/*
imparg = tk(4631)
tmparg = S2Evar(tk(4631))
tmpsub = Some(tk(4631) -> S2Eextkind(atstype_int))
*/
atstkind_t0ype(atstype_bool)
ATSLIB_056_prelude__gt_g1int_int__11__1(atstkind_t0ype(atstype_int) arg0, atstkind_t0ype(atstype_int) arg1)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret27__1, atstkind_t0ype(atstype_bool)) ;
ATStmpdec(tmp28__1, atstkind_t0ype(atstype_int)) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /home/ubuntu/workspace/ATS2/prelude/DATS/integer.dats({$PATSPRE}/DATS/integer.dats): 12236(line=624, offs=1) -- 12290(line=625, offs=42)
*/
ATSINSflab(__patsflab_gt_g1int_int):
/*
emit_instr: loc0 = /home/ubuntu/workspace/ATS2/prelude/DATS/integer.dats({$PATSPRE}/DATS/integer.dats): 12277(line=625, offs=29) -- 12288(line=625, offs=40)
*/
ATSINSmove(tmp28__1, atspre_g1int2int_int_int(arg1)) ;

/*
emit_instr: loc0 = /home/ubuntu/workspace/ATS2/prelude/DATS/integer.dats({$PATSPRE}/DATS/integer.dats): 12260(line=625, offs=12) -- 12290(line=625, offs=42)
*/
ATSINSmove(tmpret27__1, atspre_g1int_gt_int(arg0, tmp28__1)) ;

ATSfunbody_end()
ATSreturn(tmpret27__1) ;
} /* end of [ATSLIB_056_prelude__gt_g1int_int__11__1] */

#if(0)
/*
/home/ubuntu/workspace/ATS2/libats/ML/DATS/string.dats: 6755(line=395, offs=3) -- 6890(line=408, offs=4)
*/
/*
local: 
global: string_explode$15$0(level=0)
local: 
global: 
*/
ATSextern()
/*
imparg = 
tmparg = 
tmpsub = None()
*/
atstype_boxed
ATSLIB_056_libats_056_ML__string_explode__15(atstkind_type(atstype_ptrk) arg0)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret32, atstype_boxed) ;
ATStmpdec(tmp33, atstype_boxed) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /home/ubuntu/workspace/ATS2/libats/ML/DATS/string.dats({$PATSLIBATS}/ML/DATS/string.dats): 6738(line=394, offs=1) -- 6890(line=408, offs=4)
*/
ATSINSflab(__patsflab_string_explode):
/*
emit_instr: loc0 = /home/ubuntu/workspace/ATS2/libats/ML/DATS/string.dats({$PATSLIBATS}/ML/DATS/string.dats): 6763(line=395, offs=11) -- 6890(line=408, offs=4)
*/
/*
letpush(beg)
*/
/* (*nothing*) */
/*
emit_instr: loc0 = /home/ubuntu/workspace/ATS2/libats/ML/DATS/string.dats({$PATSLIBATS}/ML/DATS/string.dats): 6828(line=404, offs=4) -- 6854(line=404, offs=30)
*/
ATSINSmove(tmp33, PMVtmpltcst(string_explode<>)(ATSPMVcastfn(g1ofg0_string, atstkind_type(atstype_ptrk), arg0))) ;

/*
letpush(end)
*/

/*
emit_instr: loc0 = /home/ubuntu/workspace/ATS2/libats/ML/DATS/string.dats({$PATSLIBATS}/ML/DATS/string.dats): 6865(line=407, offs=3) -- 6885(line=407, offs=23)
*/
ATSINSmove(tmpret32, ATSPMVcastfn(list0_of_list_vt, atstype_boxed, tmp33)) ;
/*
emit_instr: loc0 = /home/ubuntu/workspace/ATS2/libats/ML/DATS/string.dats({$PATSLIBATS}/ML/DATS/string.dats): 6763(line=395, offs=11) -- 6890(line=408, offs=4)
*/
/*
INSletpop()
*/
ATSfunbody_end()
ATSreturn(tmpret32) ;
} /* end of [ATSLIB_056_libats_056_ML__string_explode__15] */
#endif // end of [TEMPLATE]

/*
/home/ubuntu/workspace/ATS2/libats/ML/DATS/string.dats: 6755(line=395, offs=3) -- 6890(line=408, offs=4)
*/
/*
local: 
global: string_explode$15$1(level=1)
local: 
global: 
*/
ATSstatic()
/*
imparg = 
tmparg = 
tmpsub = Some()
*/
atstype_boxed
ATSLIB_056_libats_056_ML__string_explode__15__1(atstkind_type(atstype_ptrk) arg0)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret32__1, atstype_boxed) ;
ATStmpdec(tmp33__1, atstype_boxed) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /home/ubuntu/workspace/ATS2/libats/ML/DATS/string.dats({$PATSLIBATS}/ML/DATS/string.dats): 6738(line=394, offs=1) -- 6890(line=408, offs=4)
*/
ATSINSflab(__patsflab_string_explode):
/*
emit_instr: loc0 = /home/ubuntu/workspace/ATS2/libats/ML/DATS/string.dats({$PATSLIBATS}/ML/DATS/string.dats): 6763(line=395, offs=11) -- 6890(line=408, offs=4)
*/
/*
letpush(beg)
*/
/* (*nothing*) */
/*
emit_instr: loc0 = /home/ubuntu/workspace/ATS2/libats/ML/DATS/string.dats({$PATSLIBATS}/ML/DATS/string.dats): 6828(line=404, offs=4) -- 6854(line=404, offs=30)
*/
ATSINSmove(tmp33__1, ATSLIB_056_prelude__string_explode__17__1(ATSPMVcastfn(g1ofg0_string, atstkind_type(atstype_ptrk), arg0))) ;

/*
letpush(end)
*/

/*
emit_instr: loc0 = /home/ubuntu/workspace/ATS2/libats/ML/DATS/string.dats({$PATSLIBATS}/ML/DATS/string.dats): 6865(line=407, offs=3) -- 6885(line=407, offs=23)
*/
ATSINSmove(tmpret32__1, ATSPMVcastfn(list0_of_list_vt, atstype_boxed, tmp33__1)) ;
/*
emit_instr: loc0 = /home/ubuntu/workspace/ATS2/libats/ML/DATS/string.dats({$PATSLIBATS}/ML/DATS/string.dats): 6763(line=395, offs=11) -- 6890(line=408, offs=4)
*/
/*
INSletpop()
*/
ATSfunbody_end()
ATSreturn(tmpret32__1) ;
} /* end of [ATSLIB_056_libats_056_ML__string_explode__15__1] */

#if(0)
/*
/home/ubuntu/workspace/ATS2/prelude/DATS/string.dats: 17793(line=980, offs=6) -- 18586(line=1025, offs=4)
*/
/*
local: 
global: string_explode$17$0(level=0)
local: 
global: 
*/
ATSextern()
/*
imparg = 
tmparg = 
tmpsub = None()
*/
atstype_boxed
ATSLIB_056_prelude__string_explode__17(atstkind_type(atstype_ptrk) arg0)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret36, atstype_boxed) ;
ATStmpdec(tmpref44, atstkind_type(atstype_ptrk)) ;
// ATStmpdec_void(tmp45) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /home/ubuntu/workspace/ATS2/prelude/DATS/string.dats({$PATSPRE}/DATS/string.dats): 17773(line=979, offs=1) -- 18586(line=1025, offs=4)
*/
ATSINSflab(__patsflab_string_explode):
/*
emit_instr: loc0 = /home/ubuntu/workspace/ATS2/prelude/DATS/string.dats({$PATSPRE}/DATS/string.dats): 17799(line=980, offs=12) -- 18586(line=1025, offs=4)
*/
/*
letpush(beg)
*/
/*
emit_instr: loc0 = /home/ubuntu/workspace/ATS2/prelude/DATS/string.dats({$PATSPRE}/DATS/string.dats): 18524(line=1020, offs=5) -- 18527(line=1020, offs=8)
*/
/*
ATSINStmpdec(tmpref44) ;
*/
/*
emit_instr: loc0 = /home/ubuntu/workspace/ATS2/prelude/DATS/string.dats({$PATSPRE}/DATS/string.dats): 18556(line=1021, offs=24) -- 18569(line=1021, offs=37)
*/
ATSINSmove_void(tmp45, ATSfunclo_fun(PMVd2vfunlab(d2v=loop$582(1), flab=loop_18$0(level=1)), (atstkind_type(atstype_ptrk), atsrefarg1_type(atstkind_type(atstype_ptrk))), atsvoid_t0ype)(arg0, ATSPMVrefarg1(ATSPMVptrof(tmpref44)))) ;

/*
letpush(end)
*/

/*
emit_instr: loc0 = /home/ubuntu/workspace/ATS2/prelude/DATS/string.dats({$PATSPRE}/DATS/string.dats): 18579(line=1024, offs=3) -- 18582(line=1024, offs=6)
*/
ATSINSmove(tmpret36, tmpref44) ;
/*
emit_instr: loc0 = /home/ubuntu/workspace/ATS2/prelude/DATS/string.dats({$PATSPRE}/DATS/string.dats): 17799(line=980, offs=12) -- 18586(line=1025, offs=4)
*/
/*
INSletpop()
*/
ATSfunbody_end()
ATSreturn(tmpret36) ;
} /* end of [ATSLIB_056_prelude__string_explode__17] */
#endif // end of [TEMPLATE]

#if(0)
/*
/home/ubuntu/workspace/ATS2/prelude/DATS/string.dats: 17891(line=986, offs=5) -- 18499(line=1018, offs=4)
*/
/*
local: loop_18$0(level=1)
global: loop_18$0(level=1)
local: 
global: 
*/
ATSstatic()
atsvoid_t0ype
loop_18__18(atstkind_type(atstype_ptrk) arg0, atsrefarg1_type(atstkind_type(atstype_ptrk)) arg1)
{
/* tmpvardeclst(beg) */
ATStmpdec(apy0, atstkind_type(atstype_ptrk)) ;
ATStmpdec(apy1, atsrefarg1_type(atstkind_type(atstype_ptrk))) ;
// ATStmpdec_void(tmpret37) ;
ATStmpdec(tmp38, atstkind_t0ype(atstype_char)) ;
ATStmpdec(tmp39, atstkind_t0ype(atstype_bool)) ;
ATStmpdec(tmp40, atstype_datcontyp) ;
ATStmpdec(tmp41, atstype_datcontyp) ;
ATStmpdec(tmp42, atstkind_type(atstype_ptrk)) ;
ATStmpdec(tmp43, atstype_boxed) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /home/ubuntu/workspace/ATS2/prelude/DATS/string.dats({$PATSPRE}/DATS/string.dats): 17891(line=986, offs=5) -- 18499(line=1018, offs=4)
*/
ATSINSflab(__patsflab_loop_18):
/*
emit_instr: loc0 = /home/ubuntu/workspace/ATS2/prelude/DATS/string.dats({$PATSPRE}/DATS/string.dats): 17967(line=990, offs=18) -- 18499(line=1018, offs=4)
*/
/*
letpush(beg)
*/
/* (*nothing*) */
/*
emit_instr: loc0 = /home/ubuntu/workspace/ATS2/prelude/DATS/string.dats({$PATSPRE}/DATS/string.dats): 18006(line=992, offs=11) -- 18027(line=992, offs=32)
*/
ATSINSmove(tmp38, PMVtmpltcst(ptr1_get<S2Eexi(c(88); S2Eapp(S2Ecst(<=); S2Eapp(S2Ecst(~); S2Eintinf(128)), S2Evar(c(88))), S2Eapp(S2Ecst(<); S2Evar(c(88)), S2Eintinf(128)); S2Eapp(S2Ecst(char_int_t0ype); S2Evar(c(88))))>)(ATSPMVcastfn(string2ptr, atstkind_type(atstype_ptrk), arg0))) ;

/*
letpush(end)
*/

/*
emit_instr: loc0 = /home/ubuntu/workspace/ATS2/prelude/DATS/string.dats({$PATSPRE}/DATS/string.dats): 18038(line=995, offs=4) -- 18047(line=995, offs=13)
*/
ATSINSmove(tmp39, atspre_neq_char1_char1(tmp38, ATSPMVchar('\000'))) ;

/*
emit_instr: loc0 = /home/ubuntu/workspace/ATS2/prelude/DATS/string.dats({$PATSPRE}/DATS/string.dats): 18035(line=995, offs=1) -- 18477(line=1016, offs=4)
*/
ATSif(
tmp39
) ATSthen() {
/*
emit_instr: loc0 = /home/ubuntu/workspace/ATS2/prelude/DATS/string.dats({$PATSPRE}/DATS/string.dats): 18053(line=995, offs=19) -- 18338(line=1008, offs=4)
*/
/*
letpush(beg)
*/
/*
emit_instr: loc0 = /home/ubuntu/workspace/ATS2/prelude/DATS/string.dats({$PATSPRE}/DATS/string.dats): 18175(line=1002, offs=5) -- 18204(line=1002, offs=34)
*/

/*
#LINCONSTATUS==0
*/
ATSINSmove_con1_beg()
ATSINSmove_con1_new(tmp40, postiats_tysum_1) ;
#if(0)
ATSINSstore_con1_tag(tmp40, 1) ;
#endif
ATSINSstore_con1_ofs(tmp40, postiats_tysum_1, atslab__0, tmp38) ;
#if(0)
ATSINSstore_con1_ofs(tmp40, postiats_tysum_1, atslab__1, ATSPMVtop()) ;
#endif
ATSINSmove_con1_end()
/*
emit_instr: loc0 = /home/ubuntu/workspace/ATS2/prelude/DATS/string.dats({$PATSPRE}/DATS/string.dats): 18164(line=1001, offs=12) -- 18204(line=1002, offs=34)
*/
ATSINSstore(ATSderef(arg1, atstkind_type(atstype_ptrk)), tmp40) ;
/*
emit_instr: loc0 = /home/ubuntu/workspace/ATS2/prelude/DATS/string.dats({$PATSPRE}/DATS/string.dats): 18236(line=1003, offs=32) -- 18239(line=1003, offs=35)
*/
ATSINSmove(tmp41, ATSderef(arg1, atstype_datcontyp)) ;
/*
emit_instr: loc0 = /home/ubuntu/workspace/ATS2/prelude/DATS/string.dats({$PATSPRE}/DATS/string.dats): 18211(line=1003, offs=7) -- 18233(line=1003, offs=29)
*/
#if(0)
ATSifthen(ATSCKptrisnull(tmp41)) { ATSINSdeadcode_fail() ; } ;
#endif
/*
emit_instr: loc0 = /home/ubuntu/workspace/ATS2/prelude/DATS/string.dats({$PATSPRE}/DATS/string.dats): 18272(line=1004, offs=33) -- 18289(line=1004, offs=50)
*/
ATSINSmove(tmp42, PMVtmpltcst(ptr1_succ<S2Ecst(char_t0ype)>)(ATSPMVcastfn(string2ptr, atstkind_type(atstype_ptrk), arg0))) ;

/*
letpush(end)
*/

/*
emit_instr: loc0 = /home/ubuntu/workspace/ATS2/prelude/DATS/string.dats({$PATSPRE}/DATS/string.dats): 18303(line=1005, offs=12) -- 18317(line=1005, offs=26)
*/
ATStailcal_beg()
ATSINSmove_tlcal(apy0, ATSPMVcastfn(cast, atstkind_type(atstype_ptrk), tmp42)) ;
ATSINSmove_tlcal(apy1, ATSPMVrefarg1(ATSPMVptrof(ATSSELcon(tmp41, postiats_tysum_2, atslab__1)))) ;
ATSINSargmove_tlcal(arg0, apy0) ;
ATSINSargmove_tlcal(arg1, apy1) ;
ATSINSfgoto(__patsflab_loop_18) ;
ATStailcal_end()

/*
emit_instr: loc0 = /home/ubuntu/workspace/ATS2/prelude/DATS/string.dats({$PATSPRE}/DATS/string.dats): 18053(line=995, offs=19) -- 18338(line=1008, offs=4)
*/
/*
INSletpop()
*/
} ATSelse() {
/*
emit_instr: loc0 = /home/ubuntu/workspace/ATS2/prelude/DATS/string.dats({$PATSPRE}/DATS/string.dats): 18459(line=1015, offs=10) -- 18473(line=1015, offs=24)
*/

ATSINSmove_nil(tmp43) ;

/*
emit_instr: loc0 = /home/ubuntu/workspace/ATS2/prelude/DATS/string.dats({$PATSPRE}/DATS/string.dats): 18452(line=1015, offs=3) -- 18473(line=1015, offs=24)
*/
ATSINSstore(ATSderef(arg1, atstkind_type(atstype_ptrk)), tmp43) ;
/*
emit_instr: loc0 = /home/ubuntu/workspace/ATS2/prelude/DATS/string.dats({$PATSPRE}/DATS/string.dats): 18452(line=1015, offs=3) -- 18473(line=1015, offs=24)
*/
ATSINSmove_void(tmpret37, ATSPMVempty()) ;
} /* ATSendif */
/*
emit_instr: loc0 = /home/ubuntu/workspace/ATS2/prelude/DATS/string.dats({$PATSPRE}/DATS/string.dats): 17967(line=990, offs=18) -- 18499(line=1018, offs=4)
*/
/*
INSletpop()
*/
ATSfunbody_end()
ATSreturn_void(tmpret37) ;
} /* end of [loop_18__18] */
#endif // end of [TEMPLATE]

/*
/home/ubuntu/workspace/ATS2/prelude/DATS/string.dats: 17793(line=980, offs=6) -- 18586(line=1025, offs=4)
*/
/*
local: 
global: string_explode$17$1(level=2)
local: 
global: 
*/
ATSstatic()
/*
imparg = 
tmparg = 
tmpsub = Some()
*/
atstype_boxed
ATSLIB_056_prelude__string_explode__17__1(atstkind_type(atstype_ptrk) arg0)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret36__1, atstype_boxed) ;
ATStmpdec(tmpref44__1, atstkind_type(atstype_ptrk)) ;
// ATStmpdec_void(tmp45__1) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /home/ubuntu/workspace/ATS2/prelude/DATS/string.dats({$PATSPRE}/DATS/string.dats): 17773(line=979, offs=1) -- 18586(line=1025, offs=4)
*/
ATSINSflab(__patsflab_string_explode):
/*
emit_instr: loc0 = /home/ubuntu/workspace/ATS2/prelude/DATS/string.dats({$PATSPRE}/DATS/string.dats): 17799(line=980, offs=12) -- 18586(line=1025, offs=4)
*/
/*
letpush(beg)
*/
/*
emit_instr: loc0 = /home/ubuntu/workspace/ATS2/prelude/DATS/string.dats({$PATSPRE}/DATS/string.dats): 18524(line=1020, offs=5) -- 18527(line=1020, offs=8)
*/
/*
ATSINStmpdec(tmpref44) ;
*/
/*
emit_instr: loc0 = /home/ubuntu/workspace/ATS2/prelude/DATS/string.dats({$PATSPRE}/DATS/string.dats): 18556(line=1021, offs=24) -- 18569(line=1021, offs=37)
*/
ATSINSmove_void(tmp45__1, loop_18__18__1(arg0, ATSPMVrefarg1(ATSPMVptrof(tmpref44__1)))) ;

/*
letpush(end)
*/

/*
emit_instr: loc0 = /home/ubuntu/workspace/ATS2/prelude/DATS/string.dats({$PATSPRE}/DATS/string.dats): 18579(line=1024, offs=3) -- 18582(line=1024, offs=6)
*/
ATSINSmove(tmpret36__1, tmpref44__1) ;
/*
emit_instr: loc0 = /home/ubuntu/workspace/ATS2/prelude/DATS/string.dats({$PATSPRE}/DATS/string.dats): 17799(line=980, offs=12) -- 18586(line=1025, offs=4)
*/
/*
INSletpop()
*/
ATSfunbody_end()
ATSreturn(tmpret36__1) ;
} /* end of [ATSLIB_056_prelude__string_explode__17__1] */

/*
/home/ubuntu/workspace/ATS2/prelude/DATS/string.dats: 17891(line=986, offs=5) -- 18499(line=1018, offs=4)
*/
/*
local: loop_18$1(level=3)
global: loop_18$1(level=3)
local: 
global: 
*/
ATSstatic()
atsvoid_t0ype
loop_18__18__1(atstkind_type(atstype_ptrk) arg0, atsrefarg1_type(atstkind_type(atstype_ptrk)) arg1)
{
/* tmpvardeclst(beg) */
ATStmpdec(apy0, atstkind_type(atstype_ptrk)) ;
ATStmpdec(apy1, atsrefarg1_type(atstkind_type(atstype_ptrk))) ;
// ATStmpdec_void(tmpret37__1) ;
ATStmpdec(tmp38__1, atstkind_t0ype(atstype_char)) ;
ATStmpdec(tmp39__1, atstkind_t0ype(atstype_bool)) ;
ATStmpdec(tmp40__1, atstype_datcontyp) ;
ATStmpdec(tmp41__1, atstype_datcontyp) ;
ATStmpdec(tmp42__1, atstkind_type(atstype_ptrk)) ;
ATStmpdec(tmp43__1, atstype_boxed) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /home/ubuntu/workspace/ATS2/prelude/DATS/string.dats({$PATSPRE}/DATS/string.dats): 17891(line=986, offs=5) -- 18499(line=1018, offs=4)
*/
ATSINSflab(__patsflab_loop_18):
/*
emit_instr: loc0 = /home/ubuntu/workspace/ATS2/prelude/DATS/string.dats({$PATSPRE}/DATS/string.dats): 17967(line=990, offs=18) -- 18499(line=1018, offs=4)
*/
/*
letpush(beg)
*/
/* (*nothing*) */
/*
emit_instr: loc0 = /home/ubuntu/workspace/ATS2/prelude/DATS/string.dats({$PATSPRE}/DATS/string.dats): 18006(line=992, offs=11) -- 18027(line=992, offs=32)
*/
ATSINSmove(tmp38__1, ATSLIB_056_prelude_056_unsafe__ptr0_get__22__1(ATSPMVcastfn(string2ptr, atstkind_type(atstype_ptrk), arg0))) ;

/*
letpush(end)
*/

/*
emit_instr: loc0 = /home/ubuntu/workspace/ATS2/prelude/DATS/string.dats({$PATSPRE}/DATS/string.dats): 18038(line=995, offs=4) -- 18047(line=995, offs=13)
*/
ATSINSmove(tmp39__1, atspre_neq_char1_char1(tmp38__1, ATSPMVchar('\000'))) ;

/*
emit_instr: loc0 = /home/ubuntu/workspace/ATS2/prelude/DATS/string.dats({$PATSPRE}/DATS/string.dats): 18035(line=995, offs=1) -- 18477(line=1016, offs=4)
*/
ATSif(
tmp39__1
) ATSthen() {
/*
emit_instr: loc0 = /home/ubuntu/workspace/ATS2/prelude/DATS/string.dats({$PATSPRE}/DATS/string.dats): 18053(line=995, offs=19) -- 18338(line=1008, offs=4)
*/
/*
letpush(beg)
*/
/*
emit_instr: loc0 = /home/ubuntu/workspace/ATS2/prelude/DATS/string.dats({$PATSPRE}/DATS/string.dats): 18175(line=1002, offs=5) -- 18204(line=1002, offs=34)
*/

/*
#LINCONSTATUS==0
*/
ATSINSmove_con1_beg()
ATSINSmove_con1_new(tmp40__1, postiats_tysum_1) ;
#if(0)
ATSINSstore_con1_tag(tmp40__1, 1) ;
#endif
ATSINSstore_con1_ofs(tmp40__1, postiats_tysum_1, atslab__0, tmp38__1) ;
#if(0)
ATSINSstore_con1_ofs(tmp40__1, postiats_tysum_1, atslab__1, ATSPMVtop()) ;
#endif
ATSINSmove_con1_end()
/*
emit_instr: loc0 = /home/ubuntu/workspace/ATS2/prelude/DATS/string.dats({$PATSPRE}/DATS/string.dats): 18164(line=1001, offs=12) -- 18204(line=1002, offs=34)
*/
ATSINSstore(ATSderef(arg1, atstkind_type(atstype_ptrk)), tmp40__1) ;
/*
emit_instr: loc0 = /home/ubuntu/workspace/ATS2/prelude/DATS/string.dats({$PATSPRE}/DATS/string.dats): 18236(line=1003, offs=32) -- 18239(line=1003, offs=35)
*/
ATSINSmove(tmp41__1, ATSderef(arg1, atstype_datcontyp)) ;
/*
emit_instr: loc0 = /home/ubuntu/workspace/ATS2/prelude/DATS/string.dats({$PATSPRE}/DATS/string.dats): 18211(line=1003, offs=7) -- 18233(line=1003, offs=29)
*/
#if(0)
ATSifthen(ATSCKptrisnull(tmp41__1)) { ATSINSdeadcode_fail() ; } ;
#endif
/*
emit_instr: loc0 = /home/ubuntu/workspace/ATS2/prelude/DATS/string.dats({$PATSPRE}/DATS/string.dats): 18272(line=1004, offs=33) -- 18289(line=1004, offs=50)
*/
ATSINSmove(tmp42__1, ATSLIB_056_prelude__ptr1_succ__24__1(ATSPMVcastfn(string2ptr, atstkind_type(atstype_ptrk), arg0))) ;

/*
letpush(end)
*/

/*
emit_instr: loc0 = /home/ubuntu/workspace/ATS2/prelude/DATS/string.dats({$PATSPRE}/DATS/string.dats): 18303(line=1005, offs=12) -- 18317(line=1005, offs=26)
*/
ATStailcal_beg()
ATSINSmove_tlcal(apy0, ATSPMVcastfn(cast, atstkind_type(atstype_ptrk), tmp42__1)) ;
ATSINSmove_tlcal(apy1, ATSPMVrefarg1(ATSPMVptrof(ATSSELcon(tmp41__1, postiats_tysum_2, atslab__1)))) ;
ATSINSargmove_tlcal(arg0, apy0) ;
ATSINSargmove_tlcal(arg1, apy1) ;
ATSINSfgoto(__patsflab_loop_18) ;
ATStailcal_end()

/*
emit_instr: loc0 = /home/ubuntu/workspace/ATS2/prelude/DATS/string.dats({$PATSPRE}/DATS/string.dats): 18053(line=995, offs=19) -- 18338(line=1008, offs=4)
*/
/*
INSletpop()
*/
} ATSelse() {
/*
emit_instr: loc0 = /home/ubuntu/workspace/ATS2/prelude/DATS/string.dats({$PATSPRE}/DATS/string.dats): 18459(line=1015, offs=10) -- 18473(line=1015, offs=24)
*/

ATSINSmove_nil(tmp43__1) ;

/*
emit_instr: loc0 = /home/ubuntu/workspace/ATS2/prelude/DATS/string.dats({$PATSPRE}/DATS/string.dats): 18452(line=1015, offs=3) -- 18473(line=1015, offs=24)
*/
ATSINSstore(ATSderef(arg1, atstkind_type(atstype_ptrk)), tmp43__1) ;
/*
emit_instr: loc0 = /home/ubuntu/workspace/ATS2/prelude/DATS/string.dats({$PATSPRE}/DATS/string.dats): 18452(line=1015, offs=3) -- 18473(line=1015, offs=24)
*/
ATSINSmove_void(tmpret37__1, ATSPMVempty()) ;
} /* ATSendif */
/*
emit_instr: loc0 = /home/ubuntu/workspace/ATS2/prelude/DATS/string.dats({$PATSPRE}/DATS/string.dats): 17967(line=990, offs=18) -- 18499(line=1018, offs=4)
*/
/*
INSletpop()
*/
ATSfunbody_end()
ATSreturn_void(tmpret37__1) ;
} /* end of [loop_18__18__1] */

#if(0)
/*
/home/ubuntu/workspace/ATS2/prelude/DATS/unsafe.dats: 1763(line=60, offs=3) -- 1976(line=68, offs=2)
*/
/*
local: 
global: ptr0_get$22$0(level=0)
local: 
global: 
*/
ATSextern()
/*
imparg = a(5706)
tmparg = S2Evar(a(5706))
tmpsub = None()
*/
atstyvar_type(a)
ATSLIB_056_prelude_056_unsafe__ptr0_get__22(atstkind_type(atstype_ptrk) arg0)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret56, atstyvar_type(a)) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /home/ubuntu/workspace/ATS2/prelude/DATS/unsafe.dats: 1752(line=59, offs=1) -- 1976(line=68, offs=2)
*/
ATSINSflab(__patsflab_ptr0_get):
/*
emit_instr: loc0 = /home/ubuntu/workspace/ATS2/prelude/DATS/unsafe.dats: 1769(line=60, offs=9) -- 1976(line=68, offs=2)
*/
/*
letpush(beg)
*/
/* (*nothing*) */
/*
letpush(end)
*/

/*
emit_instr: loc0 = /home/ubuntu/workspace/ATS2/prelude/DATS/unsafe.dats: 1950(line=66, offs=11) -- 1952(line=66, offs=13)
*/
ATSINSmove(tmpret56, ATSderef(ATSPMVcastfn(g1ofg0_ptr, atstkind_type(atstype_ptrk), arg0), atstyvar_type(a))) ;
/*
emit_instr: loc0 = /home/ubuntu/workspace/ATS2/prelude/DATS/unsafe.dats: 1769(line=60, offs=9) -- 1976(line=68, offs=2)
*/
/*
INSletpop()
*/
ATSfunbody_end()
ATSreturn(tmpret56) ;
} /* end of [ATSLIB_056_prelude_056_unsafe__ptr0_get__22] */
#endif // end of [TEMPLATE]

/*
/home/ubuntu/workspace/ATS2/prelude/DATS/unsafe.dats: 1763(line=60, offs=3) -- 1976(line=68, offs=2)
*/
/*
local: 
global: ptr0_get$22$1(level=4)
local: 
global: 
*/
ATSstatic()
/*
imparg = a(5706)
tmparg = S2Evar(a(5706))
tmpsub = Some(a(5706) -> S2Eexi(c$16337(24633); S2Eapp(S2Ecst(<=); S2Eapp(S2Ecst(~); S2Eintinf(128)), S2Evar(c$16337(24633))), S2Eapp(S2Ecst(<); S2Evar(c$16337(24633)), S2Eintinf(128)); S2Eapp(S2Ecst(char_int_t0ype); S2Evar(c$16337(24633)))))
*/
atstkind_t0ype(atstype_char)
ATSLIB_056_prelude_056_unsafe__ptr0_get__22__1(atstkind_type(atstype_ptrk) arg0)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret56__1, atstkind_t0ype(atstype_char)) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /home/ubuntu/workspace/ATS2/prelude/DATS/unsafe.dats: 1752(line=59, offs=1) -- 1976(line=68, offs=2)
*/
ATSINSflab(__patsflab_ptr0_get):
/*
emit_instr: loc0 = /home/ubuntu/workspace/ATS2/prelude/DATS/unsafe.dats: 1769(line=60, offs=9) -- 1976(line=68, offs=2)
*/
/*
letpush(beg)
*/
/* (*nothing*) */
/*
letpush(end)
*/

/*
emit_instr: loc0 = /home/ubuntu/workspace/ATS2/prelude/DATS/unsafe.dats: 1950(line=66, offs=11) -- 1952(line=66, offs=13)
*/
ATSINSmove(tmpret56__1, ATSderef(ATSPMVcastfn(g1ofg0_ptr, atstkind_type(atstype_ptrk), arg0), atstkind_t0ype(atstype_char))) ;
/*
emit_instr: loc0 = /home/ubuntu/workspace/ATS2/prelude/DATS/unsafe.dats: 1769(line=60, offs=9) -- 1976(line=68, offs=2)
*/
/*
INSletpop()
*/
ATSfunbody_end()
ATSreturn(tmpret56__1) ;
} /* end of [ATSLIB_056_prelude_056_unsafe__ptr0_get__22__1] */

#if(0)
/*
/home/ubuntu/workspace/ATS2/prelude/DATS/pointer.dats: 2331(line=91, offs=13) -- 2390(line=92, offs=54)
*/
/*
local: 
global: ptr1_succ$24$0(level=0)
local: 
global: 
*/
ATSextern()
/*
imparg = a(4686)
tmparg = S2Evar(a(4686))
tmpsub = None()
*/
atstkind_type(atstype_ptrk)
ATSLIB_056_prelude__ptr1_succ__24(atstkind_type(atstype_ptrk) arg0)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret58, atstkind_type(atstype_ptrk)) ;
ATStmpdec(tmp59, atstkind_type(atstype_ptrk)) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /home/ubuntu/workspace/ATS2/prelude/DATS/pointer.dats({$PATSPRE}/DATS/pointer.dats): 2319(line=91, offs=1) -- 2390(line=92, offs=54)
*/
ATSINSflab(__patsflab_ptr1_succ):
/*
emit_instr: loc0 = /home/ubuntu/workspace/ATS2/prelude/DATS/pointer.dats({$PATSPRE}/DATS/pointer.dats): 2364(line=92, offs=28) -- 2389(line=92, offs=53)
*/
ATSINSmove(tmp59, atspre_add_ptr1_bsz(arg0, ATSPMVsizeof(atstyvar_type(a)))) ;

/*
emit_instr: loc0 = /home/ubuntu/workspace/ATS2/prelude/DATS/pointer.dats({$PATSPRE}/DATS/pointer.dats): 2337(line=92, offs=1) -- 2390(line=92, offs=54)
*/
ATSINSmove(tmpret58, ATSPMVcastfn(cast, atstkind_type(atstype_ptrk), tmp59)) ;
ATSfunbody_end()
ATSreturn(tmpret58) ;
} /* end of [ATSLIB_056_prelude__ptr1_succ__24] */
#endif // end of [TEMPLATE]

/*
/home/ubuntu/workspace/ATS2/prelude/DATS/pointer.dats: 2331(line=91, offs=13) -- 2390(line=92, offs=54)
*/
/*
local: 
global: ptr1_succ$24$1(level=4)
local: 
global: 
*/
ATSstatic()
/*
imparg = a(4686)
tmparg = S2Evar(a(4686))
tmpsub = Some(a(4686) -> S2Ecst(char_t0ype))
*/
atstkind_type(atstype_ptrk)
ATSLIB_056_prelude__ptr1_succ__24__1(atstkind_type(atstype_ptrk) arg0)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret58__1, atstkind_type(atstype_ptrk)) ;
ATStmpdec(tmp59__1, atstkind_type(atstype_ptrk)) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /home/ubuntu/workspace/ATS2/prelude/DATS/pointer.dats({$PATSPRE}/DATS/pointer.dats): 2319(line=91, offs=1) -- 2390(line=92, offs=54)
*/
ATSINSflab(__patsflab_ptr1_succ):
/*
emit_instr: loc0 = /home/ubuntu/workspace/ATS2/prelude/DATS/pointer.dats({$PATSPRE}/DATS/pointer.dats): 2364(line=92, offs=28) -- 2389(line=92, offs=53)
*/
ATSINSmove(tmp59__1, atspre_add_ptr1_bsz(arg0, ATSPMVsizeof(atstkind_t0ype(atstype_char)))) ;

/*
emit_instr: loc0 = /home/ubuntu/workspace/ATS2/prelude/DATS/pointer.dats({$PATSPRE}/DATS/pointer.dats): 2337(line=92, offs=1) -- 2390(line=92, offs=54)
*/
ATSINSmove(tmpret58__1, ATSPMVcastfn(cast, atstkind_type(atstype_ptrk), tmp59__1)) ;
ATSfunbody_end()
ATSreturn(tmpret58__1) ;
} /* end of [ATSLIB_056_prelude__ptr1_succ__24__1] */

/*
/home/ubuntu/workspace/RosettaATS/test/test.dats: 259(line=14, offs=17) -- 334(line=18, offs=2)
*/
/*
local: myfun_0$0(level=0)
global: myfun_0$0(level=0), mainats_void_0$26$0(level=0)
local: 
global: 
*/
ATSextern()
atsvoid_t0ype
mainats_void_0()
{
/* tmpvardeclst(beg) */
// ATStmpdec_void(tmpret62) ;
// ATStmpdec_void(tmp63) ;
ATStmpdec(tmp64, atstkind_t0ype(atstype_bool)) ;
// ATStmpdec_void(tmp65) ;
// ATStmpdec_void(tmp66) ;
ATStmpdec(tmp67, atstkind_t0ype(atstype_bool)) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /home/ubuntu/workspace/RosettaATS/test/test.dats: 253(line=14, offs=11) -- 334(line=18, offs=2)
*/
ATSINSflab(__patsflab_main_void_0):
/*
emit_instr: loc0 = /home/ubuntu/workspace/RosettaATS/test/test.dats: 278(line=16, offs=12) -- 297(line=16, offs=31)
*/
ATSINSmove(tmp64, myfun_0(ATSPMVstring("hsdgsadfsg"))) ;

/*
emit_instr: loc0 = /home/ubuntu/workspace/RosettaATS/test/test.dats: 269(line=16, offs=3) -- 298(line=16, offs=32)
*/
ATSINSmove_void(tmp63, atspre_print_bool(tmp64)) ;

/*
emit_instr: loc0 = /home/ubuntu/workspace/RosettaATS/test/test.dats: 269(line=16, offs=3) -- 298(line=16, offs=32)
*/
ATSINSmove_void(tmp65, atspre_print_newline()) ;

/*
emit_instr: loc0 = /home/ubuntu/workspace/RosettaATS/test/test.dats: 311(line=17, offs=12) -- 330(line=17, offs=31)
*/
ATSINSmove(tmp67, myfun_0(ATSPMVstring("aaaeaaaaaa"))) ;

/*
emit_instr: loc0 = /home/ubuntu/workspace/RosettaATS/test/test.dats: 302(line=17, offs=3) -- 331(line=17, offs=32)
*/
ATSINSmove_void(tmp66, atspre_print_bool(tmp67)) ;

/*
emit_instr: loc0 = /home/ubuntu/workspace/RosettaATS/test/test.dats: 302(line=17, offs=3) -- 331(line=17, offs=32)
*/
ATSINSmove_void(tmpret62, atspre_print_newline()) ;

ATSfunbody_end()
ATSreturn_void(tmpret62) ;
} /* end of [mainats_void_0] */

/*
** for initialization(dynloading)
*/
ATSdynloadflag_minit(_057_home_057_ubuntu_057_workspace_057_RosettaATS_057_test_057_test_056_dats__dynloadflag) ;
ATSextern()
atsvoid_t0ype
_057_home_057_ubuntu_057_workspace_057_RosettaATS_057_test_057_test_056_dats__dynload()
{
ATSfunbody_beg()
ATSdynload(/*void*/)
ATSdynloadflag_sta(
_057_home_057_ubuntu_057_workspace_057_RosettaATS_057_test_057_test_056_dats__dynloadflag
) ;
ATSif(
ATSCKiseqz(
_057_home_057_ubuntu_057_workspace_057_RosettaATS_057_test_057_test_056_dats__dynloadflag
)
) ATSthen() {
ATSdynloadset(_057_home_057_ubuntu_057_workspace_057_RosettaATS_057_test_057_test_056_dats__dynloadflag) ;
/*
dynexnlst-initize(beg)
*/
ATSdynexn_initize(ATSLIB_056_prelude__ListSubscriptExn, "/home/ubuntu/workspace/ATS2/prelude/SATS/list.sats:ListSubscriptExn") ;
/*
dynexnlst-initize(end)
*/
} /* ATSendif */
ATSfunbody_end()
ATSreturn_void(tmpret_void) ;
} /* end of [*_dynload] */

/*
** the ATS runtime
*/
#ifndef _ATS_CCOMP_RUNTIME_NONE_
#include "pats_ccomp_runtime.c"
#include "pats_ccomp_runtime_memalloc.c"
#ifndef _ATS_CCOMP_EXCEPTION_NONE_
#include "pats_ccomp_runtime2_dats.c"
#ifndef _ATS_CCOMP_RUNTIME_TRYWITH_NONE_
#include "pats_ccomp_runtime_trywith.c"
#endif /* _ATS_CCOMP_RUNTIME_TRYWITH_NONE_ */
#endif // end of [_ATS_CCOMP_EXCEPTION_NONE_]
#endif /* _ATS_CCOMP_RUNTIME_NONE_ */

/*
** the [main] implementation
*/
int
main
(
int argc, char **argv, char **envp
) {
int err = 0 ;
_057_home_057_ubuntu_057_workspace_057_RosettaATS_057_test_057_test_056_dats__dynload() ;
ATSmainats_void_0(err) ;
return (err) ;
} /* end of [main] */

/* ****** ****** */

/* end-of-compilation-unit */
