/*
**
** The C code is generated by [ATS/Postiats-0-2-13]
** The starting compilation time is: 2017-1-6:  5h:23m
**
*/

/*
** include runtime header files
*/
#ifndef _ATS_CCOMP_HEADER_NONE_
#include "pats_ccomp_config.h"
#include "pats_ccomp_basics.h"
#include "pats_ccomp_typedefs.h"
#include "pats_ccomp_instrset.h"
#include "pats_ccomp_memalloc.h"
#ifndef _ATS_CCOMP_EXCEPTION_NONE_
#include "pats_ccomp_memalloca.h"
#include "pats_ccomp_exception.h"
#endif // end of [_ATS_CCOMP_EXCEPTION_NONE_]
#endif /* _ATS_CCOMP_HEADER_NONE_ */


/*
** include prelude cats files
*/
#ifndef _ATS_CCOMP_PRELUDE_NONE_
//
#include "prelude/CATS/basics.cats"
#include "prelude/CATS/integer.cats"
#include "prelude/CATS/pointer.cats"
#include "prelude/CATS/integer_long.cats"
#include "prelude/CATS/integer_size.cats"
#include "prelude/CATS/integer_short.cats"
#include "prelude/CATS/bool.cats"
#include "prelude/CATS/char.cats"
#include "prelude/CATS/float.cats"
#include "prelude/CATS/integer_ptr.cats"
#include "prelude/CATS/integer_fixed.cats"
#include "prelude/CATS/memory.cats"
#include "prelude/CATS/string.cats"
#include "prelude/CATS/strptr.cats"
//
#include "prelude/CATS/fprintf.cats"
//
#include "prelude/CATS/filebas.cats"
//
#include "prelude/CATS/list.cats"
#include "prelude/CATS/option.cats"
#include "prelude/CATS/array.cats"
#include "prelude/CATS/arrayptr.cats"
#include "prelude/CATS/arrayref.cats"
#include "prelude/CATS/matrix.cats"
#include "prelude/CATS/matrixptr.cats"
//
#endif /* _ATS_CCOMP_PRELUDE_NONE_ */
/*
** for user-supplied prelude
*/
#ifdef _ATS_CCOMP_PRELUDE_USER_
//
#include _ATS_CCOMP_PRELUDE_USER_
//
#endif /* _ATS_CCOMP_PRELUDE_USER_ */
/*
** for user2-supplied prelude
*/
#ifdef _ATS_CCOMP_PRELUDE_USER2_
//
#include _ATS_CCOMP_PRELUDE_USER2_
//
#endif /* _ATS_CCOMP_PRELUDE_USER2_ */

/*
staload-prologues(beg)
*/
/*
/home/ubuntu/workspace/ATS2/prelude/DATS/basics.dats: 1534(line=44, offs=1) -- 1573(line=45, offs=32)
*/
/*
/home/ubuntu/workspace/ATS2/prelude/DATS/integer.dats: 1596(line=49, offs=1) -- 1635(line=49, offs=40)
*/
/*
/home/ubuntu/workspace/ATS2/prelude/DATS/pointer.dats: 1533(line=44, offs=1) -- 1572(line=44, offs=40)
*/
/*
/home/ubuntu/workspace/ATS2/prelude/DATS/integer_long.dats: 1602(line=49, offs=1) -- 1641(line=49, offs=40)
*/
/*
/home/ubuntu/workspace/ATS2/prelude/DATS/integer_size.dats: 1597(line=49, offs=1) -- 1636(line=49, offs=40)
*/
/*
/home/ubuntu/workspace/ATS2/prelude/DATS/integer_short.dats: 1603(line=49, offs=1) -- 1642(line=49, offs=40)
*/
/*
/home/ubuntu/workspace/ATS2/prelude/DATS/char.dats: 1610(line=48, offs=1) -- 1649(line=48, offs=40)
*/
/*
/home/ubuntu/workspace/ATS2/prelude/DATS/float.dats: 1636(line=50, offs=1) -- 1675(line=50, offs=40)
*/
/*
/home/ubuntu/workspace/ATS2/prelude/DATS/string.dats: 1609(line=48, offs=1) -- 1648(line=48, offs=40)
*/
/*
/home/ubuntu/workspace/ATS2/prelude/DATS/strptr.dats: 1609(line=48, offs=1) -- 1648(line=48, offs=40)
*/
/*
/home/ubuntu/workspace/ATS2/prelude/DATS/strptr.dats: 1671(line=52, offs=1) -- 1718(line=52, offs=48)
*/
/*
/home/ubuntu/workspace/ATS2/prelude/DATS/integer.dats: 1596(line=49, offs=1) -- 1635(line=49, offs=40)
*/
/*
/home/ubuntu/workspace/ATS2/prelude/DATS/integer_ptr.dats: 1601(line=49, offs=1) -- 1640(line=49, offs=40)
*/
/*
/home/ubuntu/workspace/ATS2/prelude/DATS/integer_fixed.dats: 1603(line=49, offs=1) -- 1642(line=49, offs=40)
*/
/*
/home/ubuntu/workspace/ATS2/prelude/DATS/memory.dats: 1410(line=38, offs=1) -- 1449(line=39, offs=32)
*/
/*
/home/ubuntu/workspace/ATS2/prelude/DATS/filebas.dats: 1613(line=49, offs=1) -- 1652(line=50, offs=32)
*/
/*
/home/ubuntu/workspace/ATS2/prelude/DATS/filebas.dats: 1675(line=54, offs=1) -- 1721(line=55, offs=39)
*/
/*
/home/ubuntu/workspace/ATS2/prelude/DATS/integer.dats: 1596(line=49, offs=1) -- 1635(line=49, offs=40)
*/
/*
/home/ubuntu/workspace/ATS2/prelude/DATS/filebas.dats: 1744(line=59, offs=1) -- 1789(line=60, offs=38)
*/
/*
/home/ubuntu/workspace/ATS2/libats/libc/SATS/stdio.sats: 1390(line=36, offs=1) -- 1437(line=39, offs=3)
*/

#include \
"libats/libc/CATS/stdio.cats"
/*
/home/ubuntu/workspace/ATS2/libats/libc/SATS/stdio.sats: 1950(line=69, offs=1) -- 1999(line=71, offs=34)
*/
/*
/home/ubuntu/workspace/ATS2/libats/libc/SATS/sys/types.sats: 1390(line=36, offs=1) -- 1441(line=39, offs=3)
*/

#include \
"libats/libc/CATS/sys/types.cats"
/*
/home/ubuntu/workspace/ATS2/prelude/DATS/filebas.dats: 1871(line=66, offs=1) -- 1918(line=66, offs=48)
*/
/*
/home/ubuntu/workspace/ATS2/libats/libc/SATS/sys/stat.sats: 1390(line=36, offs=1) -- 1440(line=39, offs=3)
*/

#include \
"libats/libc/CATS/sys/stat.cats"
/*
/home/ubuntu/workspace/ATS2/libats/libc/SATS/sys/stat.sats: 1756(line=58, offs=1) -- 1805(line=60, offs=34)
*/
/*
/home/ubuntu/workspace/ATS2/libats/libc/SATS/sys/types.sats: 1390(line=36, offs=1) -- 1441(line=39, offs=3)
*/

#include \
"libats/libc/CATS/sys/types.cats"
/*
/home/ubuntu/workspace/ATS2/prelude/DATS/filebas.dats: 15413(line=857, offs=1) -- 15450(line=858, offs=30)
*/
/*
/home/ubuntu/workspace/ATS2/libats/libc/SATS/stdio.sats: 1390(line=36, offs=1) -- 1437(line=39, offs=3)
*/

#include \
"libats/libc/CATS/stdio.cats"
/*
/home/ubuntu/workspace/ATS2/libats/libc/SATS/stdio.sats: 1950(line=69, offs=1) -- 1999(line=71, offs=34)
*/
/*
/home/ubuntu/workspace/ATS2/libats/libc/SATS/sys/types.sats: 1390(line=36, offs=1) -- 1441(line=39, offs=3)
*/

#include \
"libats/libc/CATS/sys/types.cats"
/*
/home/ubuntu/workspace/ATS2/prelude/DATS/list.dats: 1529(line=44, offs=1) -- 1568(line=45, offs=32)
*/
/*
/home/ubuntu/workspace/ATS2/prelude/DATS/list.dats: 1569(line=46, offs=1) -- 1615(line=47, offs=39)
*/
/*
/home/ubuntu/workspace/ATS2/prelude/DATS/unsafe.dats: 1532(line=44, offs=1) -- 1566(line=44, offs=35)
*/
/*
/home/ubuntu/workspace/ATS2/prelude/DATS/list_vt.dats: 1538(line=44, offs=1) -- 1577(line=45, offs=32)
*/
/*
/home/ubuntu/workspace/ATS2/prelude/DATS/list_vt.dats: 1578(line=46, offs=1) -- 1624(line=47, offs=39)
*/
/*
/home/ubuntu/workspace/ATS2/prelude/DATS/unsafe.dats: 1532(line=44, offs=1) -- 1566(line=44, offs=35)
*/
/*
/home/ubuntu/workspace/ATS2/prelude/DATS/array.dats: 1534(line=44, offs=1) -- 1573(line=44, offs=40)
*/
/*
/home/ubuntu/workspace/ATS2/prelude/DATS/array.dats: 1574(line=45, offs=1) -- 1616(line=45, offs=43)
*/
/*
/home/ubuntu/workspace/ATS2/prelude/DATS/arrayptr.dats: 1532(line=44, offs=1) -- 1571(line=44, offs=40)
*/
/*
/home/ubuntu/workspace/ATS2/prelude/DATS/arrayref.dats: 1532(line=44, offs=1) -- 1571(line=44, offs=40)
*/
/*
/home/ubuntu/workspace/ATS2/prelude/DATS/matrix.dats: 1535(line=44, offs=1) -- 1574(line=44, offs=40)
*/
/*
/home/ubuntu/workspace/ATS2/prelude/DATS/matrixptr.dats: 1538(line=44, offs=1) -- 1577(line=44, offs=40)
*/
/*
/home/ubuntu/workspace/ATS2/prelude/DATS/matrixref.dats: 1538(line=44, offs=1) -- 1577(line=44, offs=40)
*/
/*
/home/ubuntu/workspace/ATS2/prelude/DATS/stream.dats: 1523(line=44, offs=1) -- 1562(line=44, offs=40)
*/
/*
/home/ubuntu/workspace/ATS2/prelude/DATS/stream_vt.dats: 1523(line=44, offs=1) -- 1562(line=44, offs=40)
*/
/*
/home/ubuntu/workspace/ATS2/prelude/DATS/tostring.dats: 1528(line=44, offs=1) -- 1567(line=45, offs=32)
*/
/*
/home/ubuntu/workspace/ATS2/prelude/DATS/unsafe.dats: 1532(line=44, offs=1) -- 1566(line=44, offs=35)
*/
/*
/home/ubuntu/workspace/ATS2/prelude/DATS/checkast.dats: 1531(line=44, offs=1) -- 1570(line=45, offs=32)
*/
/*
/home/ubuntu/workspace/ATS2/libats/ML/SATS/list0.sats: 1665(line=47, offs=1) -- 1700(line=47, offs=36)
*/
/*
/home/ubuntu/workspace/ATS2/libats/ML/SATS/option0.sats: 1524(line=41, offs=1) -- 1559(line=41, offs=36)
*/
/*
/home/ubuntu/workspace/ATS2/libats/ML/SATS/array0.sats: 1525(line=41, offs=1) -- 1571(line=44, offs=3)
*/

#include \
"libats/ML/CATS/array0.cats"
/*
/home/ubuntu/workspace/ATS2/libats/ML/SATS/array0.sats: 1610(line=48, offs=1) -- 1645(line=48, offs=36)
*/
/*
/home/ubuntu/workspace/ATS2/libats/ML/SATS/matrix0.sats: 1526(line=41, offs=1) -- 1561(line=41, offs=36)
*/
/*
/home/ubuntu/workspace/ATS2/libats/ML/SATS/string.sats: 1525(line=41, offs=1) -- 1560(line=41, offs=36)
*/
/*
/home/ubuntu/workspace/ATS2/libats/ML/SATS/strarr.sats: 1538(line=43, offs=1) -- 1574(line=43, offs=37)
*/
/*
/home/ubuntu/workspace/ATS2/libats/ML/SATS/strarr.sats: 1599(line=47, offs=1) -- 1649(line=51, offs=3)
*/

//
#include "libats/ML/CATS/strarr.cats"
//
/*
/home/ubuntu/workspace/ATS2/libats/ML/SATS/gvalue.sats: 1534(line=42, offs=1) -- 1569(line=42, offs=36)
*/
/*
/home/ubuntu/workspace/ATS2/libats/ML/SATS/stream.sats: 1532(line=43, offs=1) -- 1567(line=43, offs=36)
*/
/*
/home/ubuntu/workspace/ATS2/libats/ML/SATS/stream_vt.sats: 1534(line=43, offs=1) -- 1569(line=44, offs=28)
*/
/*
/home/ubuntu/workspace/ATS2/libats/ML/SATS/filebas.sats: 1525(line=41, offs=1) -- 1560(line=41, offs=36)
*/
/*
/home/ubuntu/workspace/ATS2/libats/ML/SATS/intrange.sats: 1629(line=47, offs=1) -- 1664(line=47, offs=36)
*/
/*
/home/ubuntu/workspace/ATS2/libats/ML/DATS/list0.dats: 1444(line=40, offs=1) -- 1483(line=41, offs=32)
*/
/*
/home/ubuntu/workspace/ATS2/libats/ML/DATS/list0.dats: 1506(line=45, offs=1) -- 1541(line=45, offs=36)
*/
/*
/home/ubuntu/workspace/ATS2/libats/ML/DATS/list0.dats: 1542(line=46, offs=1) -- 1577(line=46, offs=36)
*/
/*
/home/ubuntu/workspace/ATS2/libats/ML/SATS/list0.sats: 1665(line=47, offs=1) -- 1700(line=47, offs=36)
*/
/*
/home/ubuntu/workspace/ATS2/libats/ML/DATS/option0.dats: 1392(line=36, offs=1) -- 1431(line=37, offs=32)
*/
/*
/home/ubuntu/workspace/ATS2/libats/ML/DATS/option0.dats: 1454(line=41, offs=1) -- 1489(line=41, offs=36)
*/
/*
/home/ubuntu/workspace/ATS2/libats/ML/DATS/option0.dats: 1490(line=42, offs=1) -- 1527(line=42, offs=38)
*/
/*
/home/ubuntu/workspace/ATS2/libats/ML/SATS/option0.sats: 1524(line=41, offs=1) -- 1559(line=41, offs=36)
*/
/*
/home/ubuntu/workspace/ATS2/libats/ML/DATS/array0.dats: 1394(line=36, offs=1) -- 1433(line=37, offs=32)
*/
/*
/home/ubuntu/workspace/ATS2/libats/ML/DATS/array0.dats: 1458(line=41, offs=1) -- 1493(line=41, offs=36)
*/
/*
/home/ubuntu/workspace/ATS2/libats/ML/DATS/array0.dats: 1494(line=42, offs=1) -- 1529(line=42, offs=36)
*/
/*
/home/ubuntu/workspace/ATS2/libats/ML/SATS/list0.sats: 1665(line=47, offs=1) -- 1700(line=47, offs=36)
*/
/*
/home/ubuntu/workspace/ATS2/libats/ML/DATS/array0.dats: 1530(line=43, offs=1) -- 1566(line=43, offs=37)
*/
/*
/home/ubuntu/workspace/ATS2/libats/ML/SATS/array0.sats: 1525(line=41, offs=1) -- 1571(line=44, offs=3)
*/

#include \
"libats/ML/CATS/array0.cats"
/*
/home/ubuntu/workspace/ATS2/libats/ML/SATS/array0.sats: 1610(line=48, offs=1) -- 1645(line=48, offs=36)
*/
/*
/home/ubuntu/workspace/ATS2/libats/ML/DATS/matrix0.dats: 1396(line=36, offs=1) -- 1435(line=37, offs=32)
*/
/*
/home/ubuntu/workspace/ATS2/libats/ML/DATS/matrix0.dats: 1458(line=41, offs=1) -- 1493(line=41, offs=36)
*/
/*
/home/ubuntu/workspace/ATS2/libats/ML/DATS/matrix0.dats: 1494(line=42, offs=1) -- 1531(line=42, offs=38)
*/
/*
/home/ubuntu/workspace/ATS2/libats/ML/SATS/matrix0.sats: 1526(line=41, offs=1) -- 1561(line=41, offs=36)
*/
/*
/home/ubuntu/workspace/ATS2/libats/ML/DATS/string.dats: 1609(line=46, offs=1) -- 1648(line=46, offs=40)
*/
/*
/home/ubuntu/workspace/ATS2/libats/ML/DATS/string.dats: 2770(line=107, offs=1) -- 2805(line=107, offs=36)
*/
/*
/home/ubuntu/workspace/ATS2/libats/ML/DATS/string.dats: 2806(line=108, offs=1) -- 2841(line=108, offs=36)
*/
/*
/home/ubuntu/workspace/ATS2/libats/ML/SATS/list0.sats: 1665(line=47, offs=1) -- 1700(line=47, offs=36)
*/
/*
/home/ubuntu/workspace/ATS2/libats/ML/DATS/string.dats: 2842(line=109, offs=1) -- 2878(line=109, offs=37)
*/
/*
/home/ubuntu/workspace/ATS2/libats/ML/SATS/string.sats: 1525(line=41, offs=1) -- 1560(line=41, offs=36)
*/
/*
/home/ubuntu/workspace/ATS2/libats/ML/DATS/strarr.dats: 1613(line=46, offs=1) -- 1652(line=47, offs=32)
*/
/*
/home/ubuntu/workspace/ATS2/libats/ML/DATS/strarr.dats: 1675(line=51, offs=1) -- 1710(line=51, offs=36)
*/
/*
/home/ubuntu/workspace/ATS2/libats/ML/DATS/strarr.dats: 1711(line=52, offs=1) -- 1747(line=52, offs=37)
*/
/*
/home/ubuntu/workspace/ATS2/libats/ML/SATS/array0.sats: 1525(line=41, offs=1) -- 1571(line=44, offs=3)
*/

#include \
"libats/ML/CATS/array0.cats"
/*
/home/ubuntu/workspace/ATS2/libats/ML/SATS/array0.sats: 1610(line=48, offs=1) -- 1645(line=48, offs=36)
*/
/*
/home/ubuntu/workspace/ATS2/libats/ML/DATS/strarr.dats: 1748(line=53, offs=1) -- 1796(line=53, offs=49)
*/
/*
/home/ubuntu/workspace/ATS2/libats/ML/DATS/array0.dats: 1394(line=36, offs=1) -- 1433(line=37, offs=32)
*/
/*
/home/ubuntu/workspace/ATS2/libats/ML/DATS/array0.dats: 1458(line=41, offs=1) -- 1493(line=41, offs=36)
*/
/*
/home/ubuntu/workspace/ATS2/libats/ML/DATS/array0.dats: 1494(line=42, offs=1) -- 1529(line=42, offs=36)
*/
/*
/home/ubuntu/workspace/ATS2/libats/ML/SATS/list0.sats: 1665(line=47, offs=1) -- 1700(line=47, offs=36)
*/
/*
/home/ubuntu/workspace/ATS2/libats/ML/DATS/array0.dats: 1530(line=43, offs=1) -- 1566(line=43, offs=37)
*/
/*
/home/ubuntu/workspace/ATS2/libats/ML/SATS/array0.sats: 1525(line=41, offs=1) -- 1571(line=44, offs=3)
*/

#include \
"libats/ML/CATS/array0.cats"
/*
/home/ubuntu/workspace/ATS2/libats/ML/SATS/array0.sats: 1610(line=48, offs=1) -- 1645(line=48, offs=36)
*/
/*
/home/ubuntu/workspace/ATS2/libats/ML/DATS/strarr.dats: 1819(line=57, offs=1) -- 1855(line=57, offs=37)
*/
/*
/home/ubuntu/workspace/ATS2/libats/ML/SATS/strarr.sats: 1538(line=43, offs=1) -- 1574(line=43, offs=37)
*/
/*
/home/ubuntu/workspace/ATS2/libats/ML/SATS/strarr.sats: 1599(line=47, offs=1) -- 1649(line=51, offs=3)
*/

//
#include "libats/ML/CATS/strarr.cats"
//
/*
/home/ubuntu/workspace/ATS2/libats/ML/DATS/stream.dats: 1447(line=40, offs=1) -- 1486(line=41, offs=32)
*/
/*
/home/ubuntu/workspace/ATS2/libats/ML/DATS/stream.dats: 1509(line=45, offs=1) -- 1544(line=45, offs=36)
*/
/*
/home/ubuntu/workspace/ATS2/libats/ML/DATS/stream.dats: 1545(line=46, offs=1) -- 1581(line=46, offs=37)
*/
/*
/home/ubuntu/workspace/ATS2/libats/ML/SATS/stream.sats: 1532(line=43, offs=1) -- 1567(line=43, offs=36)
*/
/*
/home/ubuntu/workspace/ATS2/libats/ML/DATS/stream_vt.dats: 1447(line=40, offs=1) -- 1486(line=41, offs=32)
*/
/*
/home/ubuntu/workspace/ATS2/libats/ML/DATS/stream_vt.dats: 1509(line=45, offs=1) -- 1544(line=45, offs=36)
*/
/*
/home/ubuntu/workspace/ATS2/libats/ML/DATS/stream_vt.dats: 1545(line=46, offs=1) -- 1584(line=46, offs=40)
*/
/*
/home/ubuntu/workspace/ATS2/libats/ML/SATS/stream_vt.sats: 1534(line=43, offs=1) -- 1569(line=44, offs=28)
*/
/*
/home/ubuntu/workspace/ATS2/libats/ML/DATS/filebas.dats: 1472(line=40, offs=1) -- 1511(line=41, offs=32)
*/
/*
/home/ubuntu/workspace/ATS2/libats/ML/DATS/filebas.dats: 1534(line=45, offs=1) -- 1581(line=46, offs=40)
*/
/*
/home/ubuntu/workspace/ATS2/prelude/DATS/integer.dats: 1596(line=49, offs=1) -- 1635(line=49, offs=40)
*/
/*
/home/ubuntu/workspace/ATS2/libats/ML/DATS/filebas.dats: 1582(line=47, offs=1) -- 1634(line=48, offs=45)
*/
/*
/home/ubuntu/workspace/ATS2/prelude/DATS/integer_size.dats: 1597(line=49, offs=1) -- 1636(line=49, offs=40)
*/
/*
/home/ubuntu/workspace/ATS2/libats/ML/DATS/filebas.dats: 1657(line=52, offs=1) -- 1704(line=52, offs=48)
*/
/*
/home/ubuntu/workspace/ATS2/prelude/DATS/filebas.dats: 1613(line=49, offs=1) -- 1652(line=50, offs=32)
*/
/*
/home/ubuntu/workspace/ATS2/prelude/DATS/filebas.dats: 1675(line=54, offs=1) -- 1721(line=55, offs=39)
*/
/*
/home/ubuntu/workspace/ATS2/prelude/DATS/integer.dats: 1596(line=49, offs=1) -- 1635(line=49, offs=40)
*/
/*
/home/ubuntu/workspace/ATS2/prelude/DATS/filebas.dats: 1744(line=59, offs=1) -- 1789(line=60, offs=38)
*/
/*
/home/ubuntu/workspace/ATS2/libats/libc/SATS/stdio.sats: 1390(line=36, offs=1) -- 1437(line=39, offs=3)
*/

#include \
"libats/libc/CATS/stdio.cats"
/*
/home/ubuntu/workspace/ATS2/libats/libc/SATS/stdio.sats: 1950(line=69, offs=1) -- 1999(line=71, offs=34)
*/
/*
/home/ubuntu/workspace/ATS2/libats/libc/SATS/sys/types.sats: 1390(line=36, offs=1) -- 1441(line=39, offs=3)
*/

#include \
"libats/libc/CATS/sys/types.cats"
/*
/home/ubuntu/workspace/ATS2/prelude/DATS/filebas.dats: 1871(line=66, offs=1) -- 1918(line=66, offs=48)
*/
/*
/home/ubuntu/workspace/ATS2/libats/libc/SATS/sys/stat.sats: 1390(line=36, offs=1) -- 1440(line=39, offs=3)
*/

#include \
"libats/libc/CATS/sys/stat.cats"
/*
/home/ubuntu/workspace/ATS2/libats/libc/SATS/sys/stat.sats: 1756(line=58, offs=1) -- 1805(line=60, offs=34)
*/
/*
/home/ubuntu/workspace/ATS2/libats/libc/SATS/sys/types.sats: 1390(line=36, offs=1) -- 1441(line=39, offs=3)
*/

#include \
"libats/libc/CATS/sys/types.cats"
/*
/home/ubuntu/workspace/ATS2/prelude/DATS/filebas.dats: 15413(line=857, offs=1) -- 15450(line=858, offs=30)
*/
/*
/home/ubuntu/workspace/ATS2/libats/libc/SATS/stdio.sats: 1390(line=36, offs=1) -- 1437(line=39, offs=3)
*/

#include \
"libats/libc/CATS/stdio.cats"
/*
/home/ubuntu/workspace/ATS2/libats/libc/SATS/stdio.sats: 1950(line=69, offs=1) -- 1999(line=71, offs=34)
*/
/*
/home/ubuntu/workspace/ATS2/libats/libc/SATS/sys/types.sats: 1390(line=36, offs=1) -- 1441(line=39, offs=3)
*/

#include \
"libats/libc/CATS/sys/types.cats"
/*
/home/ubuntu/workspace/ATS2/libats/ML/DATS/filebas.dats: 2234(line=78, offs=1) -- 2269(line=78, offs=36)
*/
/*
/home/ubuntu/workspace/ATS2/libats/ML/DATS/filebas.dats: 2270(line=79, offs=1) -- 2305(line=79, offs=36)
*/
/*
/home/ubuntu/workspace/ATS2/libats/ML/SATS/list0.sats: 1665(line=47, offs=1) -- 1700(line=47, offs=36)
*/
/*
/home/ubuntu/workspace/ATS2/libats/ML/DATS/filebas.dats: 2306(line=80, offs=1) -- 2343(line=80, offs=38)
*/
/*
/home/ubuntu/workspace/ATS2/libats/ML/SATS/option0.sats: 1524(line=41, offs=1) -- 1559(line=41, offs=36)
*/
/*
/home/ubuntu/workspace/ATS2/libats/ML/DATS/filebas.dats: 2366(line=84, offs=1) -- 2403(line=84, offs=38)
*/
/*
/home/ubuntu/workspace/ATS2/libats/ML/SATS/filebas.sats: 1525(line=41, offs=1) -- 1560(line=41, offs=36)
*/
/*
/home/ubuntu/workspace/ATS2/libats/ML/DATS/filebas.dats: 2957(line=114, offs=1) -- 3003(line=114, offs=47)
*/
/*
/home/ubuntu/workspace/ATS2/prelude/DATS/strptr.dats: 1609(line=48, offs=1) -- 1648(line=48, offs=40)
*/
/*
/home/ubuntu/workspace/ATS2/prelude/DATS/strptr.dats: 1671(line=52, offs=1) -- 1718(line=52, offs=48)
*/
/*
/home/ubuntu/workspace/ATS2/prelude/DATS/integer.dats: 1596(line=49, offs=1) -- 1635(line=49, offs=40)
*/
/*
/home/ubuntu/workspace/ATS2/libats/ML/DATS/intrange.dats: 1397(line=36, offs=1) -- 1432(line=36, offs=36)
*/
/*
/home/ubuntu/workspace/ATS2/libats/ML/DATS/intrange.dats: 1455(line=40, offs=1) -- 1490(line=40, offs=36)
*/
/*
/home/ubuntu/workspace/ATS2/libats/ML/SATS/list0.sats: 1665(line=47, offs=1) -- 1700(line=47, offs=36)
*/
/*
/home/ubuntu/workspace/ATS2/libats/ML/DATS/intrange.dats: 1491(line=41, offs=1) -- 1527(line=41, offs=37)
*/
/*
/home/ubuntu/workspace/ATS2/libats/ML/SATS/array0.sats: 1525(line=41, offs=1) -- 1571(line=44, offs=3)
*/

#include \
"libats/ML/CATS/array0.cats"
/*
/home/ubuntu/workspace/ATS2/libats/ML/SATS/array0.sats: 1610(line=48, offs=1) -- 1645(line=48, offs=36)
*/
/*
/home/ubuntu/workspace/ATS2/libats/ML/DATS/intrange.dats: 1528(line=42, offs=1) -- 1566(line=42, offs=39)
*/
/*
/home/ubuntu/workspace/ATS2/libats/ML/SATS/intrange.sats: 1629(line=47, offs=1) -- 1664(line=47, offs=36)
*/
/*
/home/ubuntu/workspace/ATS2/libats/ML/SATS/stdlib.sats: 1522(line=41, offs=1) -- 1557(line=41, offs=36)
*/
/*
/home/ubuntu/workspace/ATS2/libats/ML/DATS/stdlib.dats: 1394(line=36, offs=1) -- 1433(line=38, offs=27)
*/
/*
/home/ubuntu/workspace/ATS2/libats/ML/DATS/stdlib.dats: 1437(line=40, offs=1) -- 1484(line=42, offs=31)
*/
/*
/home/ubuntu/workspace/ATS2/libats/libc/SATS/stdlib.sats: 1389(line=36, offs=1) -- 1443(line=41, offs=3)
*/

//
#include \
"libats/libc/CATS/stdlib.cats"
//
/*
/home/ubuntu/workspace/ATS2/libats/libc/SATS/stdlib.sats: 1810(line=62, offs=1) -- 1857(line=64, offs=31)
*/
/*
/home/ubuntu/workspace/ATS2/libats/ML/DATS/stdlib.dats: 1509(line=46, offs=1) -- 1544(line=46, offs=36)
*/
/*
/home/ubuntu/workspace/ATS2/libats/ML/DATS/stdlib.dats: 1567(line=50, offs=1) -- 1603(line=50, offs=37)
*/
/*
/home/ubuntu/workspace/ATS2/libats/ML/SATS/stdlib.sats: 1522(line=41, offs=1) -- 1557(line=41, offs=36)
*/
/*
/home/ubuntu/workspace/ATS2/libats/ML/SATS/funmap.sats: 1524(line=43, offs=1) -- 1559(line=43, offs=36)
*/
/*
/home/ubuntu/workspace/ATS2/libats/ML/SATS/funset.sats: 1524(line=41, offs=1) -- 1559(line=41, offs=36)
*/
/*
/home/ubuntu/workspace/ATS2/libats/ML/DATS/funmap.dats: 1485(line=41, offs=1) -- 1531(line=42, offs=34)
*/
/*
/home/ubuntu/workspace/ATS2/libats/ML/DATS/funmap.dats: 1556(line=46, offs=1) -- 1591(line=46, offs=36)
*/
/*
/home/ubuntu/workspace/ATS2/libats/ML/SATS/list0.sats: 1665(line=47, offs=1) -- 1700(line=47, offs=36)
*/
/*
/home/ubuntu/workspace/ATS2/libats/ML/DATS/funmap.dats: 1614(line=50, offs=1) -- 1650(line=50, offs=37)
*/
/*
/home/ubuntu/workspace/ATS2/libats/ML/SATS/funmap.sats: 1524(line=43, offs=1) -- 1559(line=43, offs=36)
*/
/*
/home/ubuntu/workspace/ATS2/libats/DATS/funmap_avltree.dats: 1534(line=43, offs=1) -- 1573(line=43, offs=40)
*/
/*
/home/ubuntu/workspace/ATS2/libats/DATS/funmap_avltree.dats: 1596(line=47, offs=1) -- 1637(line=47, offs=42)
*/
/*
/home/ubuntu/workspace/ATS2/libats/ML/DATS/funset.dats: 1484(line=40, offs=1) -- 1523(line=41, offs=32)
*/
/*
/home/ubuntu/workspace/ATS2/libats/ML/DATS/funset.dats: 1550(line=45, offs=1) -- 1596(line=47, offs=34)
*/
/*
/home/ubuntu/workspace/ATS2/libats/ML/DATS/funset.dats: 1621(line=51, offs=1) -- 1656(line=51, offs=36)
*/
/*
/home/ubuntu/workspace/ATS2/libats/ML/DATS/funset.dats: 1679(line=55, offs=1) -- 1714(line=55, offs=36)
*/
/*
/home/ubuntu/workspace/ATS2/libats/ML/SATS/list0.sats: 1665(line=47, offs=1) -- 1700(line=47, offs=36)
*/
/*
/home/ubuntu/workspace/ATS2/libats/ML/DATS/funset.dats: 1737(line=59, offs=1) -- 1773(line=59, offs=37)
*/
/*
/home/ubuntu/workspace/ATS2/libats/ML/SATS/funset.sats: 1524(line=41, offs=1) -- 1559(line=41, offs=36)
*/
/*
/home/ubuntu/workspace/ATS2/libats/DATS/funset_avltree.dats: 1417(line=37, offs=1) -- 1456(line=37, offs=40)
*/
/*
/home/ubuntu/workspace/ATS2/libats/DATS/funset_avltree.dats: 1479(line=41, offs=1) -- 1520(line=41, offs=42)
*/
/*
/home/ubuntu/workspace/ATS2/libats/ML/SATS/dynarray.sats: 1529(line=41, offs=1) -- 1564(line=41, offs=36)
*/
/*
/home/ubuntu/workspace/ATS2/libats/DATS/dynarray.dats: 1399(line=36, offs=1) -- 1438(line=37, offs=32)
*/
/*
/home/ubuntu/workspace/ATS2/libats/DATS/dynarray.dats: 1461(line=41, offs=1) -- 1496(line=41, offs=36)
*/
/*
/home/ubuntu/workspace/ATS2/libats/SATS/dynarray.sats: 1467(line=40, offs=1) -- 1510(line=42, offs=3)
*/

#include "libats/CATS/dynarray.cats"
/*
/home/ubuntu/workspace/ATS2/libats/ML/DATS/dynarray.dats: 1396(line=36, offs=1) -- 1435(line=37, offs=32)
*/
/*
/home/ubuntu/workspace/ATS2/libats/ML/DATS/dynarray.dats: 1460(line=41, offs=1) -- 1500(line=42, offs=33)
*/
/*
/home/ubuntu/workspace/ATS2/libats/SATS/dynarray.sats: 1467(line=40, offs=1) -- 1510(line=42, offs=3)
*/

#include "libats/CATS/dynarray.cats"
/*
/home/ubuntu/workspace/ATS2/libats/ML/DATS/dynarray.dats: 1525(line=46, offs=1) -- 1560(line=46, offs=36)
*/
/*
/home/ubuntu/workspace/ATS2/libats/ML/DATS/dynarray.dats: 1561(line=47, offs=1) -- 1596(line=47, offs=36)
*/
/*
/home/ubuntu/workspace/ATS2/libats/ML/SATS/list0.sats: 1665(line=47, offs=1) -- 1700(line=47, offs=36)
*/
/*
/home/ubuntu/workspace/ATS2/libats/ML/DATS/dynarray.dats: 1619(line=51, offs=1) -- 1657(line=51, offs=39)
*/
/*
/home/ubuntu/workspace/ATS2/libats/ML/SATS/dynarray.sats: 1529(line=41, offs=1) -- 1564(line=41, offs=36)
*/
/*
/home/ubuntu/workspace/ATS2/libats/ML/SATS/hashtblref.sats: 1524(line=43, offs=1) -- 1559(line=43, offs=36)
*/
/*
/home/ubuntu/workspace/ATS2/libats/DATS/qlist.dats: 1404(line=36, offs=1) -- 1443(line=37, offs=32)
*/
/*
/home/ubuntu/workspace/ATS2/libats/DATS/qlist.dats: 1466(line=41, offs=1) -- 1498(line=41, offs=33)
*/
/*
/home/ubuntu/workspace/ATS2/libats/SATS/qlist.sats: 1605(line=53, offs=1) -- 1645(line=55, offs=3)
*/

#include "libats/CATS/qlist.cats"
/*
/home/ubuntu/workspace/ATS2/libats/DATS/hashfun.dats: 1354(line=35, offs=1) -- 1393(line=36, offs=32)
*/
/*
/home/ubuntu/workspace/ATS2/libats/DATS/hashfun.dats: 1416(line=40, offs=1) -- 1450(line=40, offs=35)
*/
/*
/home/ubuntu/workspace/ATS2/libats/SATS/hashfun.sats: 1354(line=35, offs=1) -- 1396(line=37, offs=3)
*/

#include "libats/CATS/hashfun.cats"
/*
/home/ubuntu/workspace/ATS2/libats/DATS/linmap_list.dats: 1539(line=41, offs=1) -- 1578(line=42, offs=32)
*/
/*
/home/ubuntu/workspace/ATS2/libats/DATS/linmap_list.dats: 1601(line=46, offs=1) -- 1639(line=46, offs=39)
*/
/*
/home/ubuntu/workspace/ATS2/libats/DATS/hashtbl_chain.dats: 1604(line=42, offs=1) -- 1643(line=43, offs=32)
*/
/*
/home/ubuntu/workspace/ATS2/libats/DATS/hashtbl_chain.dats: 1666(line=47, offs=1) -- 1700(line=47, offs=35)
*/
/*
/home/ubuntu/workspace/ATS2/libats/SATS/hashfun.sats: 1354(line=35, offs=1) -- 1396(line=37, offs=3)
*/

#include "libats/CATS/hashfun.cats"
/*
/home/ubuntu/workspace/ATS2/libats/DATS/hashtbl_chain.dats: 1723(line=51, offs=1) -- 1763(line=51, offs=41)
*/
/*
/home/ubuntu/workspace/ATS2/libats/DATS/hashtbl_chain.dats: 2924(line=127, offs=1) -- 2967(line=128, offs=36)
*/
/*
/home/ubuntu/workspace/ATS2/libats/ML/DATS/qlistref.dats: 1447(line=40, offs=1) -- 1486(line=41, offs=32)
*/
/*
/home/ubuntu/workspace/ATS2/libats/ML/DATS/qlistref.dats: 1511(line=45, offs=1) -- 1543(line=45, offs=33)
*/
/*
/home/ubuntu/workspace/ATS2/libats/SATS/qlist.sats: 1605(line=53, offs=1) -- 1645(line=55, offs=3)
*/

#include "libats/CATS/qlist.cats"
/*
/home/ubuntu/workspace/ATS2/libats/ML/DATS/qlistref.dats: 1547(line=47, offs=1) -- 1582(line=47, offs=36)
*/
/*
/home/ubuntu/workspace/ATS2/libats/ML/DATS/qlistref.dats: 1583(line=48, offs=1) -- 1621(line=48, offs=39)
*/
/*
/home/ubuntu/workspace/ATS2/libats/ML/DATS/slistref.dats: 1452(line=41, offs=1) -- 1491(line=42, offs=32)
*/
/*
/home/ubuntu/workspace/ATS2/libats/ML/DATS/slistref.dats: 1516(line=46, offs=1) -- 1551(line=46, offs=36)
*/
/*
/home/ubuntu/workspace/ATS2/libats/ML/DATS/slistref.dats: 1552(line=47, offs=1) -- 1590(line=47, offs=39)
*/
/*
/home/ubuntu/workspace/ATS2/libats/ML/DATS/hashtblref.dats: 1394(line=36, offs=1) -- 1433(line=37, offs=32)
*/
/*
/home/ubuntu/workspace/ATS2/libats/ML/DATS/hashtblref.dats: 1458(line=41, offs=1) -- 1503(line=42, offs=33)
*/
/*
/home/ubuntu/workspace/ATS2/libats/ML/DATS/hashtblref.dats: 1528(line=46, offs=1) -- 1563(line=46, offs=36)
*/
/*
/home/ubuntu/workspace/ATS2/libats/ML/DATS/hashtblref.dats: 1586(line=50, offs=1) -- 1621(line=50, offs=36)
*/
/*
/home/ubuntu/workspace/ATS2/libats/ML/SATS/list0.sats: 1665(line=47, offs=1) -- 1700(line=47, offs=36)
*/
/*
/home/ubuntu/workspace/ATS2/libats/ML/DATS/hashtblref.dats: 1644(line=54, offs=1) -- 1678(line=54, offs=35)
*/
/*
/home/ubuntu/workspace/ATS2/libats/SATS/hashfun.sats: 1354(line=35, offs=1) -- 1396(line=37, offs=3)
*/

#include "libats/CATS/hashfun.cats"
/*
/home/ubuntu/workspace/ATS2/libats/ML/DATS/hashtblref.dats: 1679(line=55, offs=1) -- 1719(line=55, offs=41)
*/
/*
/home/ubuntu/workspace/ATS2/libats/ML/SATS/hashtblref.sats: 1524(line=43, offs=1) -- 1559(line=43, offs=36)
*/
/*
staload-prologues(end)
*/
/*
typedefs-for-tyrecs-and-tysums(beg)
*/
/*
typedefs-for-tyrecs-and-tysums(end)
*/
/*
dynconlst-declaration(beg)
*/
/*
dynconlst-declaration(end)
*/
/*
dyncstlst-declaration(beg)
*/
ATSdyncst_mac(atspre_g1int2int_int_int)
ATSdyncst_mac(atspre_g1int_gt_int)
ATSdyncst_mac(atspre_print_string)
ATSdyncst_mac(atspre_print_newline)
/*
dyncstlst-declaration(end)
*/
/*
dynvalist-implementation(beg)
*/
/*
dynvalist-implementation(end)
*/
/*
exnconlst-declaration(beg)
*/
#ifndef _ATS_CCOMP_EXCEPTION_NONE_
ATSextern()
atsvoid_t0ype
the_atsexncon_initize
(
  atstype_exnconptr d2c, atstype_string exnmsg
) ;
#endif // end of [_ATS_CCOMP_EXCEPTION_NONE_]
/*
exnconlst-declaration(end)
*/
/*
assumelst-declaration(beg)
*/
/*
assumelst-declaration(end)
*/
/*
extypelst-declaration(beg)
*/
/*
extypelst-declaration(end)
*/
ATSstatic()
atsvoid_t0ype
myfun_0() ;

#if(0)
#if(0)
ATSextern()
atstkind_t0ype(atstype_bool)
ATSLIB_056_prelude__gt_g1int_int__1(atstkind_t0ype(atstyvar_type(tk)), atstkind_t0ype(atstype_int)) ;
#endif // end of [QUALIFIED]
#endif // end of [TEMPLATE]

ATSstatic()
atstkind_t0ype(atstype_bool)
ATSLIB_056_prelude__gt_g1int_int__1__1(atstkind_t0ype(atstype_int), atstkind_t0ype(atstype_int)) ;

#if(0)
ATSextern()
atsvoid_t0ype
mainats_void_0() ;
#endif // end of [QUALIFIED]

/*
/home/ubuntu/workspace/RosettaATS/test/test.dats: 137(line=8, offs=1) -- 245(line=13, offs=4)
*/
/*
local: 
global: myfun_0$0(level=0)
local: 
global: 
*/
ATSstatic()
atsvoid_t0ype
myfun_0()
{
/* tmpvardeclst(beg) */
// ATStmpdec_void(tmpret0) ;
ATStmpdec(tmp1, atstkind_t0ype(atstype_bool)) ;
ATStmpdec(tmp2, atstkind_t0ype(atstype_bool)) ;
// ATStmpdec_void(tmp7) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /home/ubuntu/workspace/RosettaATS/test/test.dats: 137(line=8, offs=1) -- 245(line=13, offs=4)
*/
ATSINSflab(__patsflab_myfun_0):
/*
emit_instr: loc0 = /home/ubuntu/workspace/RosettaATS/test/test.dats: 153(line=9, offs=1) -- 245(line=13, offs=4)
*/
/*
letpush(beg)
*/
/*
emit_instr: loc0 = /home/ubuntu/workspace/RosettaATS/test/test.dats: 173(line=10, offs=17) -- 176(line=10, offs=20)
*/
ATSINSmove(tmp2, ATSLIB_056_prelude__gt_g1int_int__1__1(ATSPMVi0nt(2), ATSPMVi0nt(3))) ;

/*
emit_instr: loc0 = /home/ubuntu/workspace/RosettaATS/test/test.dats: 170(line=10, offs=14) -- 197(line=10, offs=41)
*/
ATSif(
tmp2
) ATSthen() {
/*
emit_instr: loc0 = /home/ubuntu/workspace/RosettaATS/test/test.dats: 182(line=10, offs=26) -- 186(line=10, offs=30)
*/
ATSINSmove(tmp1, ATSPMVbool_true()) ;
} ATSelse() {
/*
emit_instr: loc0 = /home/ubuntu/workspace/RosettaATS/test/test.dats: 192(line=10, offs=36) -- 197(line=10, offs=41)
*/
ATSINSmove(tmp1, ATSPMVbool_false()) ;
} /* ATSendif */
/*
letpush(end)
*/

/*
emit_instr: loc0 = /home/ubuntu/workspace/RosettaATS/test/test.dats: 203(line=12, offs=3) -- 241(line=12, offs=41)
*/
ATSif(
tmp1
) ATSthen() {
/*
emit_instr: loc0 = /home/ubuntu/workspace/RosettaATS/test/test.dats: 216(line=12, offs=16) -- 233(line=12, offs=33)
*/
ATSINSmove_void(tmp7, atspre_print_string(ATSPMVstring("TRUE!"))) ;

/*
emit_instr: loc0 = /home/ubuntu/workspace/RosettaATS/test/test.dats: 216(line=12, offs=16) -- 233(line=12, offs=33)
*/
ATSINSmove_void(tmpret0, atspre_print_newline()) ;

} ATSelse() {
/*
emit_instr: loc0 = /home/ubuntu/workspace/RosettaATS/test/test.dats: 239(line=12, offs=39) -- 241(line=12, offs=41)
*/
ATSINSmove_void(tmpret0, ATSPMVempty()) ;
} /* ATSendif */
/*
emit_instr: loc0 = /home/ubuntu/workspace/RosettaATS/test/test.dats: 153(line=9, offs=1) -- 245(line=13, offs=4)
*/
/*
INSletpop()
*/
ATSfunbody_end()
ATSreturn_void(tmpret0) ;
} /* end of [myfun_0] */

#if(0)
/*
/home/ubuntu/workspace/ATS2/prelude/DATS/integer.dats: 12251(line=625, offs=3) -- 12290(line=625, offs=42)
*/
/*
local: 
global: gt_g1int_int$1$0(level=0)
local: 
global: 
*/
ATSextern()
/*
imparg = tk(4631)
tmparg = S2Evar(tk(4631))
tmpsub = None()
*/
atstkind_t0ype(atstype_bool)
ATSLIB_056_prelude__gt_g1int_int__1(atstkind_t0ype(atstyvar_type(tk)) arg0, atstkind_t0ype(atstype_int) arg1)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret3, atstkind_t0ype(atstype_bool)) ;
ATStmpdec(tmp4, atstkind_t0ype(atstyvar_type(tk))) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /home/ubuntu/workspace/ATS2/prelude/DATS/integer.dats({$PATSPRE}/DATS/integer.dats): 12236(line=624, offs=1) -- 12290(line=625, offs=42)
*/
ATSINSflab(__patsflab_gt_g1int_int):
/*
emit_instr: loc0 = /home/ubuntu/workspace/ATS2/prelude/DATS/integer.dats({$PATSPRE}/DATS/integer.dats): 12277(line=625, offs=29) -- 12288(line=625, offs=40)
*/
ATSINSmove(tmp4, PMVtmpltcst(g1int2int<S2Eextkind(atstype_int), S2Evar(tk(4631))>)(arg1)) ;

/*
emit_instr: loc0 = /home/ubuntu/workspace/ATS2/prelude/DATS/integer.dats({$PATSPRE}/DATS/integer.dats): 12260(line=625, offs=12) -- 12290(line=625, offs=42)
*/
ATSINSmove(tmpret3, PMVtmpltcst(g1int_gt<S2Evar(tk(4631))>)(arg0, tmp4)) ;

ATSfunbody_end()
ATSreturn(tmpret3) ;
} /* end of [ATSLIB_056_prelude__gt_g1int_int__1] */
#endif // end of [TEMPLATE]

/*
/home/ubuntu/workspace/ATS2/prelude/DATS/integer.dats: 12251(line=625, offs=3) -- 12290(line=625, offs=42)
*/
/*
local: 
global: gt_g1int_int$1$1(level=1)
local: 
global: 
*/
ATSstatic()
/*
imparg = tk(4631)
tmparg = S2Evar(tk(4631))
tmpsub = Some(tk(4631) -> S2Eextkind(atstype_int))
*/
atstkind_t0ype(atstype_bool)
ATSLIB_056_prelude__gt_g1int_int__1__1(atstkind_t0ype(atstype_int) arg0, atstkind_t0ype(atstype_int) arg1)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret3__1, atstkind_t0ype(atstype_bool)) ;
ATStmpdec(tmp4__1, atstkind_t0ype(atstype_int)) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /home/ubuntu/workspace/ATS2/prelude/DATS/integer.dats({$PATSPRE}/DATS/integer.dats): 12236(line=624, offs=1) -- 12290(line=625, offs=42)
*/
ATSINSflab(__patsflab_gt_g1int_int):
/*
emit_instr: loc0 = /home/ubuntu/workspace/ATS2/prelude/DATS/integer.dats({$PATSPRE}/DATS/integer.dats): 12277(line=625, offs=29) -- 12288(line=625, offs=40)
*/
ATSINSmove(tmp4__1, atspre_g1int2int_int_int(arg1)) ;

/*
emit_instr: loc0 = /home/ubuntu/workspace/ATS2/prelude/DATS/integer.dats({$PATSPRE}/DATS/integer.dats): 12260(line=625, offs=12) -- 12290(line=625, offs=42)
*/
ATSINSmove(tmpret3__1, atspre_g1int_gt_int(arg0, tmp4__1)) ;

ATSfunbody_end()
ATSreturn(tmpret3__1) ;
} /* end of [ATSLIB_056_prelude__gt_g1int_int__1__1] */

/*
/home/ubuntu/workspace/RosettaATS/test/test.dats: 263(line=15, offs=17) -- 282(line=18, offs=2)
*/
/*
local: myfun_0$0(level=0)
global: myfun_0$0(level=0), mainats_void_0$5$0(level=0)
local: 
global: 
*/
ATSextern()
atsvoid_t0ype
mainats_void_0()
{
/* tmpvardeclst(beg) */
// ATStmpdec_void(tmpret8) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /home/ubuntu/workspace/RosettaATS/test/test.dats: 257(line=15, offs=11) -- 282(line=18, offs=2)
*/
ATSINSflab(__patsflab_main_void_0):
/*
emit_instr: loc0 = /home/ubuntu/workspace/RosettaATS/test/test.dats: 273(line=17, offs=3) -- 280(line=17, offs=10)
*/
ATSINSmove_void(tmpret8, myfun_0()) ;

ATSfunbody_end()
ATSreturn_void(tmpret8) ;
} /* end of [mainats_void_0] */

/*
** for initialization(dynloading)
*/
ATSdynloadflag_minit(_057_home_057_ubuntu_057_workspace_057_RosettaATS_057_test_057_test_056_dats__dynloadflag) ;
ATSextern()
atsvoid_t0ype
_057_home_057_ubuntu_057_workspace_057_RosettaATS_057_test_057_test_056_dats__dynload()
{
ATSfunbody_beg()
ATSdynload(/*void*/)
ATSdynloadflag_sta(
_057_home_057_ubuntu_057_workspace_057_RosettaATS_057_test_057_test_056_dats__dynloadflag
) ;
ATSif(
ATSCKiseqz(
_057_home_057_ubuntu_057_workspace_057_RosettaATS_057_test_057_test_056_dats__dynloadflag
)
) ATSthen() {
ATSdynloadset(_057_home_057_ubuntu_057_workspace_057_RosettaATS_057_test_057_test_056_dats__dynloadflag) ;
/*
dynexnlst-initize(beg)
*/
/*
dynexnlst-initize(end)
*/
} /* ATSendif */
ATSfunbody_end()
ATSreturn_void(tmpret_void) ;
} /* end of [*_dynload] */

/*
** the ATS runtime
*/
#ifndef _ATS_CCOMP_RUNTIME_NONE_
#include "pats_ccomp_runtime.c"
#include "pats_ccomp_runtime_memalloc.c"
#ifndef _ATS_CCOMP_EXCEPTION_NONE_
#include "pats_ccomp_runtime2_dats.c"
#ifndef _ATS_CCOMP_RUNTIME_TRYWITH_NONE_
#include "pats_ccomp_runtime_trywith.c"
#endif /* _ATS_CCOMP_RUNTIME_TRYWITH_NONE_ */
#endif // end of [_ATS_CCOMP_EXCEPTION_NONE_]
#endif /* _ATS_CCOMP_RUNTIME_NONE_ */

/*
** the [main] implementation
*/
int
main
(
int argc, char **argv, char **envp
) {
int err = 0 ;
_057_home_057_ubuntu_057_workspace_057_RosettaATS_057_test_057_test_056_dats__dynload() ;
ATSmainats_void_0(err) ;
return (err) ;
} /* end of [main] */

/* ****** ****** */

/* end-of-compilation-unit */
