/*
**
** The C code is generated by [ATS/Postiats-0-2-13]
** The starting compilation time is: 2017-1-4:  0h:40m
**
*/

/*
** include runtime header files
*/
#ifndef _ATS_CCOMP_HEADER_NONE_
#include "pats_ccomp_config.h"
#include "pats_ccomp_basics.h"
#include "pats_ccomp_typedefs.h"
#include "pats_ccomp_instrset.h"
#include "pats_ccomp_memalloc.h"
#ifndef _ATS_CCOMP_EXCEPTION_NONE_
#include "pats_ccomp_memalloca.h"
#include "pats_ccomp_exception.h"
#endif // end of [_ATS_CCOMP_EXCEPTION_NONE_]
#endif /* _ATS_CCOMP_HEADER_NONE_ */


/*
** include prelude cats files
*/
#ifndef _ATS_CCOMP_PRELUDE_NONE_
//
#include "prelude/CATS/basics.cats"
#include "prelude/CATS/integer.cats"
#include "prelude/CATS/pointer.cats"
#include "prelude/CATS/integer_long.cats"
#include "prelude/CATS/integer_size.cats"
#include "prelude/CATS/integer_short.cats"
#include "prelude/CATS/bool.cats"
#include "prelude/CATS/char.cats"
#include "prelude/CATS/float.cats"
#include "prelude/CATS/integer_ptr.cats"
#include "prelude/CATS/integer_fixed.cats"
#include "prelude/CATS/memory.cats"
#include "prelude/CATS/string.cats"
#include "prelude/CATS/strptr.cats"
//
#include "prelude/CATS/fprintf.cats"
//
#include "prelude/CATS/filebas.cats"
//
#include "prelude/CATS/list.cats"
#include "prelude/CATS/option.cats"
#include "prelude/CATS/array.cats"
#include "prelude/CATS/arrayptr.cats"
#include "prelude/CATS/arrayref.cats"
#include "prelude/CATS/matrix.cats"
#include "prelude/CATS/matrixptr.cats"
//
#endif /* _ATS_CCOMP_PRELUDE_NONE_ */
/*
** for user-supplied prelude
*/
#ifdef _ATS_CCOMP_PRELUDE_USER_
//
#include _ATS_CCOMP_PRELUDE_USER_
//
#endif /* _ATS_CCOMP_PRELUDE_USER_ */
/*
** for user2-supplied prelude
*/
#ifdef _ATS_CCOMP_PRELUDE_USER2_
//
#include _ATS_CCOMP_PRELUDE_USER2_
//
#endif /* _ATS_CCOMP_PRELUDE_USER2_ */

/*
staload-prologues(beg)
*/
/*
/home/ubuntu/workspace/ATS2/prelude/DATS/basics.dats: 1534(line=44, offs=1) -- 1573(line=45, offs=32)
*/
/*
/home/ubuntu/workspace/ATS2/prelude/DATS/integer.dats: 1596(line=49, offs=1) -- 1635(line=49, offs=40)
*/
/*
/home/ubuntu/workspace/ATS2/prelude/DATS/pointer.dats: 1533(line=44, offs=1) -- 1572(line=44, offs=40)
*/
/*
/home/ubuntu/workspace/ATS2/prelude/DATS/integer_long.dats: 1602(line=49, offs=1) -- 1641(line=49, offs=40)
*/
/*
/home/ubuntu/workspace/ATS2/prelude/DATS/integer_size.dats: 1597(line=49, offs=1) -- 1636(line=49, offs=40)
*/
/*
/home/ubuntu/workspace/ATS2/prelude/DATS/integer_short.dats: 1603(line=49, offs=1) -- 1642(line=49, offs=40)
*/
/*
/home/ubuntu/workspace/ATS2/prelude/DATS/char.dats: 1610(line=48, offs=1) -- 1649(line=48, offs=40)
*/
/*
/home/ubuntu/workspace/ATS2/prelude/DATS/float.dats: 1636(line=50, offs=1) -- 1675(line=50, offs=40)
*/
/*
/home/ubuntu/workspace/ATS2/prelude/DATS/string.dats: 1609(line=48, offs=1) -- 1648(line=48, offs=40)
*/
/*
/home/ubuntu/workspace/ATS2/prelude/DATS/strptr.dats: 1609(line=48, offs=1) -- 1648(line=48, offs=40)
*/
/*
/home/ubuntu/workspace/ATS2/prelude/DATS/strptr.dats: 1671(line=52, offs=1) -- 1718(line=52, offs=48)
*/
/*
/home/ubuntu/workspace/ATS2/prelude/DATS/integer.dats: 1596(line=49, offs=1) -- 1635(line=49, offs=40)
*/
/*
/home/ubuntu/workspace/ATS2/prelude/DATS/integer_ptr.dats: 1601(line=49, offs=1) -- 1640(line=49, offs=40)
*/
/*
/home/ubuntu/workspace/ATS2/prelude/DATS/integer_fixed.dats: 1603(line=49, offs=1) -- 1642(line=49, offs=40)
*/
/*
/home/ubuntu/workspace/ATS2/prelude/DATS/memory.dats: 1410(line=38, offs=1) -- 1449(line=39, offs=32)
*/
/*
/home/ubuntu/workspace/ATS2/prelude/DATS/filebas.dats: 1613(line=49, offs=1) -- 1652(line=50, offs=32)
*/
/*
/home/ubuntu/workspace/ATS2/prelude/DATS/filebas.dats: 1675(line=54, offs=1) -- 1721(line=55, offs=39)
*/
/*
/home/ubuntu/workspace/ATS2/prelude/DATS/integer.dats: 1596(line=49, offs=1) -- 1635(line=49, offs=40)
*/
/*
/home/ubuntu/workspace/ATS2/prelude/DATS/filebas.dats: 1744(line=59, offs=1) -- 1789(line=60, offs=38)
*/
/*
/home/ubuntu/workspace/ATS2/libats/libc/SATS/stdio.sats: 1390(line=36, offs=1) -- 1437(line=39, offs=3)
*/

#include \
"libats/libc/CATS/stdio.cats"
/*
/home/ubuntu/workspace/ATS2/libats/libc/SATS/stdio.sats: 1950(line=69, offs=1) -- 1999(line=71, offs=34)
*/
/*
/home/ubuntu/workspace/ATS2/libats/libc/SATS/sys/types.sats: 1390(line=36, offs=1) -- 1441(line=39, offs=3)
*/

#include \
"libats/libc/CATS/sys/types.cats"
/*
/home/ubuntu/workspace/ATS2/prelude/DATS/filebas.dats: 1871(line=66, offs=1) -- 1918(line=66, offs=48)
*/
/*
/home/ubuntu/workspace/ATS2/libats/libc/SATS/sys/stat.sats: 1390(line=36, offs=1) -- 1440(line=39, offs=3)
*/

#include \
"libats/libc/CATS/sys/stat.cats"
/*
/home/ubuntu/workspace/ATS2/libats/libc/SATS/sys/stat.sats: 1756(line=58, offs=1) -- 1805(line=60, offs=34)
*/
/*
/home/ubuntu/workspace/ATS2/libats/libc/SATS/sys/types.sats: 1390(line=36, offs=1) -- 1441(line=39, offs=3)
*/

#include \
"libats/libc/CATS/sys/types.cats"
/*
/home/ubuntu/workspace/ATS2/prelude/DATS/filebas.dats: 15413(line=857, offs=1) -- 15450(line=858, offs=30)
*/
/*
/home/ubuntu/workspace/ATS2/libats/libc/SATS/stdio.sats: 1390(line=36, offs=1) -- 1437(line=39, offs=3)
*/

#include \
"libats/libc/CATS/stdio.cats"
/*
/home/ubuntu/workspace/ATS2/libats/libc/SATS/stdio.sats: 1950(line=69, offs=1) -- 1999(line=71, offs=34)
*/
/*
/home/ubuntu/workspace/ATS2/libats/libc/SATS/sys/types.sats: 1390(line=36, offs=1) -- 1441(line=39, offs=3)
*/

#include \
"libats/libc/CATS/sys/types.cats"
/*
/home/ubuntu/workspace/ATS2/prelude/DATS/list.dats: 1529(line=44, offs=1) -- 1568(line=45, offs=32)
*/
/*
/home/ubuntu/workspace/ATS2/prelude/DATS/list.dats: 1569(line=46, offs=1) -- 1615(line=47, offs=39)
*/
/*
/home/ubuntu/workspace/ATS2/prelude/DATS/unsafe.dats: 1532(line=44, offs=1) -- 1566(line=44, offs=35)
*/
/*
/home/ubuntu/workspace/ATS2/prelude/DATS/list_vt.dats: 1538(line=44, offs=1) -- 1577(line=45, offs=32)
*/
/*
/home/ubuntu/workspace/ATS2/prelude/DATS/list_vt.dats: 1578(line=46, offs=1) -- 1624(line=47, offs=39)
*/
/*
/home/ubuntu/workspace/ATS2/prelude/DATS/unsafe.dats: 1532(line=44, offs=1) -- 1566(line=44, offs=35)
*/
/*
/home/ubuntu/workspace/ATS2/prelude/DATS/array.dats: 1534(line=44, offs=1) -- 1573(line=44, offs=40)
*/
/*
/home/ubuntu/workspace/ATS2/prelude/DATS/array.dats: 1574(line=45, offs=1) -- 1616(line=45, offs=43)
*/
/*
/home/ubuntu/workspace/ATS2/prelude/DATS/arrayptr.dats: 1532(line=44, offs=1) -- 1571(line=44, offs=40)
*/
/*
/home/ubuntu/workspace/ATS2/prelude/DATS/arrayref.dats: 1532(line=44, offs=1) -- 1571(line=44, offs=40)
*/
/*
/home/ubuntu/workspace/ATS2/prelude/DATS/matrix.dats: 1535(line=44, offs=1) -- 1574(line=44, offs=40)
*/
/*
/home/ubuntu/workspace/ATS2/prelude/DATS/matrixptr.dats: 1538(line=44, offs=1) -- 1577(line=44, offs=40)
*/
/*
/home/ubuntu/workspace/ATS2/prelude/DATS/matrixref.dats: 1538(line=44, offs=1) -- 1577(line=44, offs=40)
*/
/*
/home/ubuntu/workspace/ATS2/prelude/DATS/stream.dats: 1523(line=44, offs=1) -- 1562(line=44, offs=40)
*/
/*
/home/ubuntu/workspace/ATS2/prelude/DATS/stream_vt.dats: 1523(line=44, offs=1) -- 1562(line=44, offs=40)
*/
/*
/home/ubuntu/workspace/ATS2/prelude/DATS/tostring.dats: 1528(line=44, offs=1) -- 1567(line=45, offs=32)
*/
/*
/home/ubuntu/workspace/ATS2/prelude/DATS/unsafe.dats: 1532(line=44, offs=1) -- 1566(line=44, offs=35)
*/
/*
/home/ubuntu/workspace/ATS2/prelude/DATS/checkast.dats: 1531(line=44, offs=1) -- 1570(line=45, offs=32)
*/
/*
staload-prologues(end)
*/
/*
typedefs-for-tyrecs-and-tysums(beg)
*/
/*
typedefs-for-tyrecs-and-tysums(end)
*/
/*
dynconlst-declaration(beg)
*/
/*
dynconlst-declaration(end)
*/
/*
dyncstlst-declaration(beg)
*/
ATSdyncst_mac(atspre_g0int2int_int_int)
ATSdyncst_mac(atspre_g0int_gt_int)
ATSdyncst_mac(atspre_g0int_eq_int)
ATSdyncst_mac(atspre_g0int_mod_int)
ATSdyncst_mac(atspre_g0int_add_int)
ATSdyncst_mac(atspre_print_string)
ATSdyncst_mac(atspre_print_int)
ATSdyncst_extfun(_057_home_057_ubuntu_057_workspace_057_RosettaATS_057_greatest_common_divisor_057_gcd_056_dats__gcd, (atstkind_t0ype(atstype_int), atstkind_t0ype(atstype_int)), atstkind_t0ype(atstype_int)) ;
ATSdyncst_mac(atspre_print_newline)
/*
dyncstlst-declaration(end)
*/
/*
dynvalist-implementation(beg)
*/
/*
dynvalist-implementation(end)
*/
/*
exnconlst-declaration(beg)
*/
#ifndef _ATS_CCOMP_EXCEPTION_NONE_
ATSextern()
atsvoid_t0ype
the_atsexncon_initize
(
  atstype_exnconptr d2c, atstype_string exnmsg
) ;
#endif // end of [_ATS_CCOMP_EXCEPTION_NONE_]
/*
exnconlst-declaration(end)
*/
/*
assumelst-declaration(beg)
*/
/*
assumelst-declaration(end)
*/
/*
extypelst-declaration(beg)
*/
/*
extypelst-declaration(end)
*/
#if(0)
ATSextern()
atstkind_t0ype(atstype_int)
_057_home_057_ubuntu_057_workspace_057_RosettaATS_057_greatest_common_divisor_057_gcd_056_dats__gcd(atstkind_t0ype(atstype_int), atstkind_t0ype(atstype_int)) ;
#endif // end of [QUALIFIED]

ATSstatic()
atstkind_t0ype(atstype_int)
loop_1(atstkind_t0ype(atstype_int), atstkind_t0ype(atstype_int), atstkind_t0ype(atstype_int), atstkind_t0ype(atstype_int)) ;

#if(0)
#if(0)
ATSextern()
atstkind_t0ype(atstype_bool)
ATSLIB_056_prelude__gt_g0int_int__2(atstkind_t0ype(atstyvar_type(tk)), atstkind_t0ype(atstype_int)) ;
#endif // end of [QUALIFIED]
#endif // end of [TEMPLATE]

ATSstatic()
atstkind_t0ype(atstype_bool)
ATSLIB_056_prelude__gt_g0int_int__2__1(atstkind_t0ype(atstype_int), atstkind_t0ype(atstype_int)) ;

ATSstatic()
atstkind_t0ype(atstype_bool)
ATSLIB_056_prelude__gt_g0int_int__2__2(atstkind_t0ype(atstype_int), atstkind_t0ype(atstype_int)) ;

#if(0)
#if(0)
ATSextern()
atstkind_t0ype(atstype_bool)
ATSLIB_056_prelude__eq_g0int_int__7(atstkind_t0ype(atstyvar_type(tk)), atstkind_t0ype(atstype_int)) ;
#endif // end of [QUALIFIED]
#endif // end of [TEMPLATE]

ATSstatic()
atstkind_t0ype(atstype_bool)
ATSLIB_056_prelude__eq_g0int_int__7__1(atstkind_t0ype(atstype_int), atstkind_t0ype(atstype_int)) ;

ATSstatic()
atstkind_t0ype(atstype_bool)
ATSLIB_056_prelude__eq_g0int_int__7__2(atstkind_t0ype(atstype_int), atstkind_t0ype(atstype_int)) ;

#if(0)
ATSextern()
atsvoid_t0ype
mainats_void_0() ;
#endif // end of [QUALIFIED]

ATSstatic()
atsvoid_t0ype
main_func_14() ;

/*
/home/ubuntu/workspace/RosettaATS/greatest_common_divisor/gcd.dats: 152(line=13, offs=4) -- 462(line=28, offs=2)
*/
/*
local: 
global: gcd$0$0(level=0)
local: 
global: 
*/
ATSextern()
atstkind_t0ype(atstype_int)
_057_home_057_ubuntu_057_workspace_057_RosettaATS_057_greatest_common_divisor_057_gcd_056_dats__gcd(atstkind_t0ype(atstype_int) arg0, atstkind_t0ype(atstype_int) arg1)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret0, atstkind_t0ype(atstype_int)) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /home/ubuntu/workspace/RosettaATS/greatest_common_divisor/gcd.dats: 149(line=13, offs=1) -- 462(line=28, offs=2)
*/
ATSINSflab(__patsflab_gcd):
/*
emit_instr: loc0 = /home/ubuntu/workspace/RosettaATS/greatest_common_divisor/gcd.dats: 175(line=15, offs=3) -- 460(line=27, offs=6)
*/
/*
letpush(beg)
*/
/*
letpush(end)
*/

/*
emit_instr: loc0 = /home/ubuntu/workspace/RosettaATS/greatest_common_divisor/gcd.dats: 438(line=26, offs=5) -- 454(line=26, offs=21)
*/
ATSINSmove(tmpret0, loop_1(arg0, arg1, ATSPMVi0nt(1), ATSPMVi0nt(1))) ;

/*
emit_instr: loc0 = /home/ubuntu/workspace/RosettaATS/greatest_common_divisor/gcd.dats: 175(line=15, offs=3) -- 460(line=27, offs=6)
*/
/*
INSletpop()
*/
ATSfunbody_end()
ATSreturn(tmpret0) ;
} /* end of [_057_home_057_ubuntu_057_workspace_057_RosettaATS_057_greatest_common_divisor_057_gcd_056_dats__gcd] */

/*
/home/ubuntu/workspace/RosettaATS/greatest_common_divisor/gcd.dats: 183(line=15, offs=11) -- 427(line=24, offs=4)
*/
/*
local: loop_1$0(level=1)
global: loop_1$0(level=1)
local: 
global: 
*/
ATSstatic()
atstkind_t0ype(atstype_int)
loop_1(atstkind_t0ype(atstype_int) arg0, atstkind_t0ype(atstype_int) arg1, atstkind_t0ype(atstype_int) arg2, atstkind_t0ype(atstype_int) arg3)
{
/* tmpvardeclst(beg) */
ATStmpdec(apy0, atstkind_t0ype(atstype_int)) ;
ATStmpdec(apy1, atstkind_t0ype(atstype_int)) ;
ATStmpdec(apy2, atstkind_t0ype(atstype_int)) ;
ATStmpdec(apy3, atstkind_t0ype(atstype_int)) ;
ATStmpdec(tmpret1, atstkind_t0ype(atstype_int)) ;
ATStmpdec(tmp2, atstkind_t0ype(atstype_bool)) ;
ATStmpdec(tmp3, atstkind_t0ype(atstype_bool)) ;
ATStmpdec(tmp10, atstkind_t0ype(atstype_bool)) ;
ATStmpdec(tmp11, atstkind_t0ype(atstype_bool)) ;
ATStmpdec(tmp16, atstkind_t0ype(atstype_int)) ;
ATStmpdec(tmp19, atstkind_t0ype(atstype_int)) ;
ATStmpdec(tmp20, atstkind_t0ype(atstype_int)) ;
ATStmpdec(tmp21, atstkind_t0ype(atstype_int)) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /home/ubuntu/workspace/RosettaATS/greatest_common_divisor/gcd.dats: 183(line=15, offs=11) -- 427(line=24, offs=4)
*/
ATSINSflab(__patsflab_loop_1):
/*
emit_instr: loc0 = /home/ubuntu/workspace/RosettaATS/greatest_common_divisor/gcd.dats: 249(line=17, offs=8) -- 269(line=17, offs=28)
*/
ATSINSmove(tmp3, ATSLIB_056_prelude__gt_g0int_int__2__1(arg3, arg0)) ;

/*
emit_instr: loc0 = /home/ubuntu/workspace/RosettaATS/greatest_common_divisor/gcd.dats: 249(line=17, offs=8) -- 269(line=17, offs=28)
*/
ATSif(
tmp3
) ATSthen() {
/*
emit_instr: loc0 = /home/ubuntu/workspace/RosettaATS/greatest_common_divisor/gcd.dats: 249(line=17, offs=8) -- 269(line=17, offs=28)
*/
ATSINSmove(tmp2, ATSPMVbool_true()) ;
} ATSelse() {
/*
emit_instr: loc0 = /home/ubuntu/workspace/RosettaATS/greatest_common_divisor/gcd.dats: 249(line=17, offs=8) -- 269(line=17, offs=28)
*/
ATSINSmove(tmp2, ATSLIB_056_prelude__gt_g0int_int__2__2(arg3, arg1)) ;

} /* ATSendif */
/*
emit_instr: loc0 = /home/ubuntu/workspace/RosettaATS/greatest_common_divisor/gcd.dats: 246(line=17, offs=5) -- 423(line=23, offs=6)
*/
ATSif(
tmp2
) ATSthen() {
/*
emit_instr: loc0 = /home/ubuntu/workspace/RosettaATS/greatest_common_divisor/gcd.dats: 275(line=17, offs=34) -- 284(line=17, offs=43)
*/
ATSINSmove(tmpret1, arg2) ;
} ATSelse() {
/*
emit_instr: loc0 = /home/ubuntu/workspace/RosettaATS/greatest_common_divisor/gcd.dats: 309(line=20, offs=10) -- 337(line=20, offs=38)
*/
ATSINSmove(tmp16, atspre_g0int_mod_int(arg0, arg3)) ;

/*
emit_instr: loc0 = /home/ubuntu/workspace/RosettaATS/greatest_common_divisor/gcd.dats: 309(line=20, offs=10) -- 337(line=20, offs=38)
*/
ATSINSmove(tmp11, ATSLIB_056_prelude__eq_g0int_int__7__1(tmp16, ATSPMVi0nt(0))) ;

/*
emit_instr: loc0 = /home/ubuntu/workspace/RosettaATS/greatest_common_divisor/gcd.dats: 309(line=20, offs=10) -- 337(line=20, offs=38)
*/
ATSif(
tmp11
) ATSthen() {
/*
emit_instr: loc0 = /home/ubuntu/workspace/RosettaATS/greatest_common_divisor/gcd.dats: 309(line=20, offs=10) -- 337(line=20, offs=38)
*/
ATSINSmove(tmp19, atspre_g0int_mod_int(arg1, arg3)) ;

/*
emit_instr: loc0 = /home/ubuntu/workspace/RosettaATS/greatest_common_divisor/gcd.dats: 309(line=20, offs=10) -- 337(line=20, offs=38)
*/
ATSINSmove(tmp10, ATSLIB_056_prelude__eq_g0int_int__7__2(tmp19, ATSPMVi0nt(0))) ;

} ATSelse() {
/*
emit_instr: loc0 = /home/ubuntu/workspace/RosettaATS/greatest_common_divisor/gcd.dats: 309(line=20, offs=10) -- 337(line=20, offs=38)
*/
ATSINSmove(tmp10, ATSPMVbool_false()) ;
} /* ATSendif */
/*
emit_instr: loc0 = /home/ubuntu/workspace/RosettaATS/greatest_common_divisor/gcd.dats: 306(line=20, offs=7) -- 417(line=22, offs=41)
*/
ATSif(
tmp10
) ATSthen() {
/*
emit_instr: loc0 = /home/ubuntu/workspace/RosettaATS/greatest_common_divisor/gcd.dats: 369(line=21, offs=26) -- 375(line=21, offs=32)
*/
ATSINSmove(tmp20, atspre_g0int_add_int(arg3, ATSPMVi0nt(1))) ;

/*
emit_instr: loc0 = /home/ubuntu/workspace/RosettaATS/greatest_common_divisor/gcd.dats: 352(line=21, offs=9) -- 376(line=21, offs=33)
*/
ATStailcal_beg()
ATSINSmove_tlcal(apy0, arg0) ;
ATSINSmove_tlcal(apy1, arg1) ;
ATSINSmove_tlcal(apy2, arg3) ;
ATSINSmove_tlcal(apy3, tmp20) ;
ATSINSargmove_tlcal(arg0, apy0) ;
ATSINSargmove_tlcal(arg1, apy1) ;
ATSINSargmove_tlcal(arg2, apy2) ;
ATSINSargmove_tlcal(arg3, apy3) ;
ATSINSfgoto(__patsflab_loop_1) ;
ATStailcal_end()

} ATSelse() {
/*
emit_instr: loc0 = /home/ubuntu/workspace/RosettaATS/greatest_common_divisor/gcd.dats: 410(line=22, offs=34) -- 416(line=22, offs=40)
*/
ATSINSmove(tmp21, atspre_g0int_add_int(arg3, ATSPMVi0nt(1))) ;

/*
emit_instr: loc0 = /home/ubuntu/workspace/RosettaATS/greatest_common_divisor/gcd.dats: 388(line=22, offs=12) -- 417(line=22, offs=41)
*/
ATStailcal_beg()
ATSINSmove_tlcal(apy0, arg0) ;
ATSINSmove_tlcal(apy1, arg1) ;
ATSINSmove_tlcal(apy2, arg2) ;
ATSINSmove_tlcal(apy3, tmp21) ;
ATSINSargmove_tlcal(arg0, apy0) ;
ATSINSargmove_tlcal(arg1, apy1) ;
ATSINSargmove_tlcal(arg2, apy2) ;
ATSINSargmove_tlcal(arg3, apy3) ;
ATSINSfgoto(__patsflab_loop_1) ;
ATStailcal_end()

} /* ATSendif */
} /* ATSendif */
ATSfunbody_end()
ATSreturn(tmpret1) ;
} /* end of [loop_1] */

#if(0)
/*
/home/ubuntu/workspace/ATS2/prelude/DATS/integer.dats: 11672(line=592, offs=3) -- 11711(line=592, offs=42)
*/
/*
local: 
global: gt_g0int_int$2$0(level=0)
local: 
global: 
*/
ATSextern()
/*
imparg = tk(4620)
tmparg = S2Evar(tk(4620))
tmpsub = None()
*/
atstkind_t0ype(atstype_bool)
ATSLIB_056_prelude__gt_g0int_int__2(atstkind_t0ype(atstyvar_type(tk)) arg0, atstkind_t0ype(atstype_int) arg1)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret4, atstkind_t0ype(atstype_bool)) ;
ATStmpdec(tmp5, atstkind_t0ype(atstyvar_type(tk))) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /home/ubuntu/workspace/ATS2/prelude/DATS/integer.dats({$PATSPRE}/DATS/integer.dats): 11657(line=591, offs=1) -- 11711(line=592, offs=42)
*/
ATSINSflab(__patsflab_gt_g0int_int):
/*
emit_instr: loc0 = /home/ubuntu/workspace/ATS2/prelude/DATS/integer.dats({$PATSPRE}/DATS/integer.dats): 11698(line=592, offs=29) -- 11709(line=592, offs=40)
*/
ATSINSmove(tmp5, PMVtmpltcst(g0int2int<S2Eextkind(atstype_int), S2Evar(tk(4620))>)(arg1)) ;

/*
emit_instr: loc0 = /home/ubuntu/workspace/ATS2/prelude/DATS/integer.dats({$PATSPRE}/DATS/integer.dats): 11681(line=592, offs=12) -- 11711(line=592, offs=42)
*/
ATSINSmove(tmpret4, PMVtmpltcst(g0int_gt<S2Evar(tk(4620))>)(arg0, tmp5)) ;

ATSfunbody_end()
ATSreturn(tmpret4) ;
} /* end of [ATSLIB_056_prelude__gt_g0int_int__2] */
#endif // end of [TEMPLATE]

/*
/home/ubuntu/workspace/ATS2/prelude/DATS/integer.dats: 11672(line=592, offs=3) -- 11711(line=592, offs=42)
*/
/*
local: 
global: gt_g0int_int$2$1(level=2)
local: 
global: 
*/
ATSstatic()
/*
imparg = tk(4620)
tmparg = S2Evar(tk(4620))
tmpsub = Some(tk(4620) -> S2Eextkind(atstype_int))
*/
atstkind_t0ype(atstype_bool)
ATSLIB_056_prelude__gt_g0int_int__2__1(atstkind_t0ype(atstype_int) arg0, atstkind_t0ype(atstype_int) arg1)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret4__1, atstkind_t0ype(atstype_bool)) ;
ATStmpdec(tmp5__1, atstkind_t0ype(atstype_int)) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /home/ubuntu/workspace/ATS2/prelude/DATS/integer.dats({$PATSPRE}/DATS/integer.dats): 11657(line=591, offs=1) -- 11711(line=592, offs=42)
*/
ATSINSflab(__patsflab_gt_g0int_int):
/*
emit_instr: loc0 = /home/ubuntu/workspace/ATS2/prelude/DATS/integer.dats({$PATSPRE}/DATS/integer.dats): 11698(line=592, offs=29) -- 11709(line=592, offs=40)
*/
ATSINSmove(tmp5__1, atspre_g0int2int_int_int(arg1)) ;

/*
emit_instr: loc0 = /home/ubuntu/workspace/ATS2/prelude/DATS/integer.dats({$PATSPRE}/DATS/integer.dats): 11681(line=592, offs=12) -- 11711(line=592, offs=42)
*/
ATSINSmove(tmpret4__1, atspre_g0int_gt_int(arg0, tmp5__1)) ;

ATSfunbody_end()
ATSreturn(tmpret4__1) ;
} /* end of [ATSLIB_056_prelude__gt_g0int_int__2__1] */

/*
/home/ubuntu/workspace/ATS2/prelude/DATS/integer.dats: 11672(line=592, offs=3) -- 11711(line=592, offs=42)
*/
/*
local: 
global: gt_g0int_int$2$2(level=2)
local: 
global: 
*/
ATSstatic()
/*
imparg = tk(4620)
tmparg = S2Evar(tk(4620))
tmpsub = Some(tk(4620) -> S2Eextkind(atstype_int))
*/
atstkind_t0ype(atstype_bool)
ATSLIB_056_prelude__gt_g0int_int__2__2(atstkind_t0ype(atstype_int) arg0, atstkind_t0ype(atstype_int) arg1)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret4__2, atstkind_t0ype(atstype_bool)) ;
ATStmpdec(tmp5__2, atstkind_t0ype(atstype_int)) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /home/ubuntu/workspace/ATS2/prelude/DATS/integer.dats({$PATSPRE}/DATS/integer.dats): 11657(line=591, offs=1) -- 11711(line=592, offs=42)
*/
ATSINSflab(__patsflab_gt_g0int_int):
/*
emit_instr: loc0 = /home/ubuntu/workspace/ATS2/prelude/DATS/integer.dats({$PATSPRE}/DATS/integer.dats): 11698(line=592, offs=29) -- 11709(line=592, offs=40)
*/
ATSINSmove(tmp5__2, atspre_g0int2int_int_int(arg1)) ;

/*
emit_instr: loc0 = /home/ubuntu/workspace/ATS2/prelude/DATS/integer.dats({$PATSPRE}/DATS/integer.dats): 11681(line=592, offs=12) -- 11711(line=592, offs=42)
*/
ATSINSmove(tmpret4__2, atspre_g0int_gt_int(arg0, tmp5__2)) ;

ATSfunbody_end()
ATSreturn(tmpret4__2) ;
} /* end of [ATSLIB_056_prelude__gt_g0int_int__2__2] */

#if(0)
/*
/home/ubuntu/workspace/ATS2/prelude/DATS/integer.dats: 11831(line=601, offs=3) -- 11870(line=601, offs=42)
*/
/*
local: 
global: eq_g0int_int$7$0(level=0)
local: 
global: 
*/
ATSextern()
/*
imparg = tk(4622)
tmparg = S2Evar(tk(4622))
tmpsub = None()
*/
atstkind_t0ype(atstype_bool)
ATSLIB_056_prelude__eq_g0int_int__7(atstkind_t0ype(atstyvar_type(tk)) arg0, atstkind_t0ype(atstype_int) arg1)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret12, atstkind_t0ype(atstype_bool)) ;
ATStmpdec(tmp13, atstkind_t0ype(atstyvar_type(tk))) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /home/ubuntu/workspace/ATS2/prelude/DATS/integer.dats({$PATSPRE}/DATS/integer.dats): 11816(line=600, offs=1) -- 11870(line=601, offs=42)
*/
ATSINSflab(__patsflab_eq_g0int_int):
/*
emit_instr: loc0 = /home/ubuntu/workspace/ATS2/prelude/DATS/integer.dats({$PATSPRE}/DATS/integer.dats): 11857(line=601, offs=29) -- 11868(line=601, offs=40)
*/
ATSINSmove(tmp13, PMVtmpltcst(g0int2int<S2Eextkind(atstype_int), S2Evar(tk(4622))>)(arg1)) ;

/*
emit_instr: loc0 = /home/ubuntu/workspace/ATS2/prelude/DATS/integer.dats({$PATSPRE}/DATS/integer.dats): 11840(line=601, offs=12) -- 11870(line=601, offs=42)
*/
ATSINSmove(tmpret12, PMVtmpltcst(g0int_eq<S2Evar(tk(4622))>)(arg0, tmp13)) ;

ATSfunbody_end()
ATSreturn(tmpret12) ;
} /* end of [ATSLIB_056_prelude__eq_g0int_int__7] */
#endif // end of [TEMPLATE]

/*
/home/ubuntu/workspace/ATS2/prelude/DATS/integer.dats: 11831(line=601, offs=3) -- 11870(line=601, offs=42)
*/
/*
local: 
global: eq_g0int_int$7$1(level=2)
local: 
global: 
*/
ATSstatic()
/*
imparg = tk(4622)
tmparg = S2Evar(tk(4622))
tmpsub = Some(tk(4622) -> S2Eextkind(atstype_int))
*/
atstkind_t0ype(atstype_bool)
ATSLIB_056_prelude__eq_g0int_int__7__1(atstkind_t0ype(atstype_int) arg0, atstkind_t0ype(atstype_int) arg1)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret12__1, atstkind_t0ype(atstype_bool)) ;
ATStmpdec(tmp13__1, atstkind_t0ype(atstype_int)) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /home/ubuntu/workspace/ATS2/prelude/DATS/integer.dats({$PATSPRE}/DATS/integer.dats): 11816(line=600, offs=1) -- 11870(line=601, offs=42)
*/
ATSINSflab(__patsflab_eq_g0int_int):
/*
emit_instr: loc0 = /home/ubuntu/workspace/ATS2/prelude/DATS/integer.dats({$PATSPRE}/DATS/integer.dats): 11857(line=601, offs=29) -- 11868(line=601, offs=40)
*/
ATSINSmove(tmp13__1, atspre_g0int2int_int_int(arg1)) ;

/*
emit_instr: loc0 = /home/ubuntu/workspace/ATS2/prelude/DATS/integer.dats({$PATSPRE}/DATS/integer.dats): 11840(line=601, offs=12) -- 11870(line=601, offs=42)
*/
ATSINSmove(tmpret12__1, atspre_g0int_eq_int(arg0, tmp13__1)) ;

ATSfunbody_end()
ATSreturn(tmpret12__1) ;
} /* end of [ATSLIB_056_prelude__eq_g0int_int__7__1] */

/*
/home/ubuntu/workspace/ATS2/prelude/DATS/integer.dats: 11831(line=601, offs=3) -- 11870(line=601, offs=42)
*/
/*
local: 
global: eq_g0int_int$7$2(level=2)
local: 
global: 
*/
ATSstatic()
/*
imparg = tk(4622)
tmparg = S2Evar(tk(4622))
tmpsub = Some(tk(4622) -> S2Eextkind(atstype_int))
*/
atstkind_t0ype(atstype_bool)
ATSLIB_056_prelude__eq_g0int_int__7__2(atstkind_t0ype(atstype_int) arg0, atstkind_t0ype(atstype_int) arg1)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret12__2, atstkind_t0ype(atstype_bool)) ;
ATStmpdec(tmp13__2, atstkind_t0ype(atstype_int)) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /home/ubuntu/workspace/ATS2/prelude/DATS/integer.dats({$PATSPRE}/DATS/integer.dats): 11816(line=600, offs=1) -- 11870(line=601, offs=42)
*/
ATSINSflab(__patsflab_eq_g0int_int):
/*
emit_instr: loc0 = /home/ubuntu/workspace/ATS2/prelude/DATS/integer.dats({$PATSPRE}/DATS/integer.dats): 11857(line=601, offs=29) -- 11868(line=601, offs=40)
*/
ATSINSmove(tmp13__2, atspre_g0int2int_int_int(arg1)) ;

/*
emit_instr: loc0 = /home/ubuntu/workspace/ATS2/prelude/DATS/integer.dats({$PATSPRE}/DATS/integer.dats): 11840(line=601, offs=12) -- 11870(line=601, offs=42)
*/
ATSINSmove(tmpret12__2, atspre_g0int_eq_int(arg0, tmp13__2)) ;

ATSfunbody_end()
ATSreturn(tmpret12__2) ;
} /* end of [ATSLIB_056_prelude__eq_g0int_int__7__2] */

/*
/home/ubuntu/workspace/RosettaATS/greatest_common_divisor/gcd.dats: 501(line=32, offs=17) -- 740(line=44, offs=2)
*/
/*
local: 
global: mainats_void_0$13$0(level=0)
local: 
global: 
*/
ATSextern()
atsvoid_t0ype
mainats_void_0()
{
/* tmpvardeclst(beg) */
// ATStmpdec_void(tmpret22) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /home/ubuntu/workspace/RosettaATS/greatest_common_divisor/gcd.dats: 495(line=32, offs=11) -- 740(line=44, offs=2)
*/
ATSINSflab(__patsflab_main_void_0):
/*
emit_instr: loc0 = /home/ubuntu/workspace/RosettaATS/greatest_common_divisor/gcd.dats: 510(line=34, offs=3) -- 738(line=43, offs=6)
*/
/*
letpush(beg)
*/
/*
letpush(end)
*/

/*
emit_instr: loc0 = /home/ubuntu/workspace/RosettaATS/greatest_common_divisor/gcd.dats: 721(line=42, offs=5) -- 732(line=42, offs=16)
*/
ATSINSmove_void(tmpret22, main_func_14()) ;

/*
emit_instr: loc0 = /home/ubuntu/workspace/RosettaATS/greatest_common_divisor/gcd.dats: 510(line=34, offs=3) -- 738(line=43, offs=6)
*/
/*
INSletpop()
*/
ATSfunbody_end()
ATSreturn_void(tmpret22) ;
} /* end of [mainats_void_0] */

/*
/home/ubuntu/workspace/RosettaATS/greatest_common_divisor/gcd.dats: 518(line=34, offs=11) -- 711(line=40, offs=4)
*/
/*
local: 
global: main_func_14$0(level=1)
local: 
global: 
*/
ATSstatic()
atsvoid_t0ype
main_func_14()
{
/* tmpvardeclst(beg) */
// ATStmpdec_void(tmpret23) ;
// ATStmpdec_void(tmp24) ;
// ATStmpdec_void(tmp25) ;
ATStmpdec(tmp26, atstkind_t0ype(atstype_int)) ;
// ATStmpdec_void(tmp27) ;
// ATStmpdec_void(tmp28) ;
// ATStmpdec_void(tmp29) ;
ATStmpdec(tmp30, atstkind_t0ype(atstype_int)) ;
// ATStmpdec_void(tmp31) ;
// ATStmpdec_void(tmp32) ;
// ATStmpdec_void(tmp33) ;
ATStmpdec(tmp34, atstkind_t0ype(atstype_int)) ;
// ATStmpdec_void(tmp35) ;
// ATStmpdec_void(tmp36) ;
// ATStmpdec_void(tmp37) ;
ATStmpdec(tmp38, atstkind_t0ype(atstype_int)) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /home/ubuntu/workspace/RosettaATS/greatest_common_divisor/gcd.dats: 518(line=34, offs=11) -- 711(line=40, offs=4)
*/
ATSINSflab(__patsflab_main_func_14):
/*
emit_instr: loc0 = /home/ubuntu/workspace/RosettaATS/greatest_common_divisor/gcd.dats: 546(line=36, offs=5) -- 579(line=36, offs=38)
*/
ATSINSmove_void(tmp24, atspre_print_string(ATSPMVstring("15, 25: "))) ;

/*
emit_instr: loc0 = /home/ubuntu/workspace/RosettaATS/greatest_common_divisor/gcd.dats: 567(line=36, offs=26) -- 578(line=36, offs=37)
*/
ATSINSmove(tmp26, _057_home_057_ubuntu_057_workspace_057_RosettaATS_057_greatest_common_divisor_057_gcd_056_dats__gcd(ATSPMVi0nt(15), ATSPMVi0nt(25))) ;

/*
emit_instr: loc0 = /home/ubuntu/workspace/RosettaATS/greatest_common_divisor/gcd.dats: 546(line=36, offs=5) -- 579(line=36, offs=38)
*/
ATSINSmove_void(tmp25, atspre_print_int(tmp26)) ;

/*
emit_instr: loc0 = /home/ubuntu/workspace/RosettaATS/greatest_common_divisor/gcd.dats: 546(line=36, offs=5) -- 579(line=36, offs=38)
*/
ATSINSmove_void(tmp27, atspre_print_newline()) ;

/*
emit_instr: loc0 = /home/ubuntu/workspace/RosettaATS/greatest_common_divisor/gcd.dats: 585(line=37, offs=5) -- 618(line=37, offs=38)
*/
ATSINSmove_void(tmp28, atspre_print_string(ATSPMVstring("77, 88: "))) ;

/*
emit_instr: loc0 = /home/ubuntu/workspace/RosettaATS/greatest_common_divisor/gcd.dats: 606(line=37, offs=26) -- 617(line=37, offs=37)
*/
ATSINSmove(tmp30, _057_home_057_ubuntu_057_workspace_057_RosettaATS_057_greatest_common_divisor_057_gcd_056_dats__gcd(ATSPMVi0nt(77), ATSPMVi0nt(88))) ;

/*
emit_instr: loc0 = /home/ubuntu/workspace/RosettaATS/greatest_common_divisor/gcd.dats: 585(line=37, offs=5) -- 618(line=37, offs=38)
*/
ATSINSmove_void(tmp29, atspre_print_int(tmp30)) ;

/*
emit_instr: loc0 = /home/ubuntu/workspace/RosettaATS/greatest_common_divisor/gcd.dats: 585(line=37, offs=5) -- 618(line=37, offs=38)
*/
ATSINSmove_void(tmp31, atspre_print_newline()) ;

/*
emit_instr: loc0 = /home/ubuntu/workspace/RosettaATS/greatest_common_divisor/gcd.dats: 624(line=38, offs=5) -- 661(line=38, offs=42)
*/
ATSINSmove_void(tmp32, atspre_print_string(ATSPMVstring("256, 365: "))) ;

/*
emit_instr: loc0 = /home/ubuntu/workspace/RosettaATS/greatest_common_divisor/gcd.dats: 647(line=38, offs=28) -- 660(line=38, offs=41)
*/
ATSINSmove(tmp34, _057_home_057_ubuntu_057_workspace_057_RosettaATS_057_greatest_common_divisor_057_gcd_056_dats__gcd(ATSPMVi0nt(256), ATSPMVi0nt(365))) ;

/*
emit_instr: loc0 = /home/ubuntu/workspace/RosettaATS/greatest_common_divisor/gcd.dats: 624(line=38, offs=5) -- 661(line=38, offs=42)
*/
ATSINSmove_void(tmp33, atspre_print_int(tmp34)) ;

/*
emit_instr: loc0 = /home/ubuntu/workspace/RosettaATS/greatest_common_divisor/gcd.dats: 624(line=38, offs=5) -- 661(line=38, offs=42)
*/
ATSINSmove_void(tmp35, atspre_print_newline()) ;

/*
emit_instr: loc0 = /home/ubuntu/workspace/RosettaATS/greatest_common_divisor/gcd.dats: 667(line=39, offs=5) -- 706(line=39, offs=44)
*/
ATSINSmove_void(tmp36, atspre_print_string(ATSPMVstring("256, 2560: "))) ;

/*
emit_instr: loc0 = /home/ubuntu/workspace/RosettaATS/greatest_common_divisor/gcd.dats: 691(line=39, offs=29) -- 705(line=39, offs=43)
*/
ATSINSmove(tmp38, _057_home_057_ubuntu_057_workspace_057_RosettaATS_057_greatest_common_divisor_057_gcd_056_dats__gcd(ATSPMVi0nt(256), ATSPMVi0nt(2560))) ;

/*
emit_instr: loc0 = /home/ubuntu/workspace/RosettaATS/greatest_common_divisor/gcd.dats: 667(line=39, offs=5) -- 706(line=39, offs=44)
*/
ATSINSmove_void(tmp37, atspre_print_int(tmp38)) ;

/*
emit_instr: loc0 = /home/ubuntu/workspace/RosettaATS/greatest_common_divisor/gcd.dats: 667(line=39, offs=5) -- 706(line=39, offs=44)
*/
ATSINSmove_void(tmpret23, atspre_print_newline()) ;

ATSfunbody_end()
ATSreturn_void(tmpret23) ;
} /* end of [main_func_14] */

/*
** for initialization(dynloading)
*/
ATSdynloadflag_minit(_057_home_057_ubuntu_057_workspace_057_RosettaATS_057_greatest_common_divisor_057_gcd_056_dats__dynloadflag) ;
ATSextern()
atsvoid_t0ype
_057_home_057_ubuntu_057_workspace_057_RosettaATS_057_greatest_common_divisor_057_gcd_056_dats__dynload()
{
ATSfunbody_beg()
ATSdynload(/*void*/)
ATSdynloadflag_sta(
_057_home_057_ubuntu_057_workspace_057_RosettaATS_057_greatest_common_divisor_057_gcd_056_dats__dynloadflag
) ;
ATSif(
ATSCKiseqz(
_057_home_057_ubuntu_057_workspace_057_RosettaATS_057_greatest_common_divisor_057_gcd_056_dats__dynloadflag
)
) ATSthen() {
ATSdynloadset(_057_home_057_ubuntu_057_workspace_057_RosettaATS_057_greatest_common_divisor_057_gcd_056_dats__dynloadflag) ;
/*
dynexnlst-initize(beg)
*/
/*
dynexnlst-initize(end)
*/
} /* ATSendif */
ATSfunbody_end()
ATSreturn_void(tmpret_void) ;
} /* end of [*_dynload] */

/*
** the ATS runtime
*/
#ifndef _ATS_CCOMP_RUNTIME_NONE_
#include "pats_ccomp_runtime.c"
#include "pats_ccomp_runtime_memalloc.c"
#ifndef _ATS_CCOMP_EXCEPTION_NONE_
#include "pats_ccomp_runtime2_dats.c"
#ifndef _ATS_CCOMP_RUNTIME_TRYWITH_NONE_
#include "pats_ccomp_runtime_trywith.c"
#endif /* _ATS_CCOMP_RUNTIME_TRYWITH_NONE_ */
#endif // end of [_ATS_CCOMP_EXCEPTION_NONE_]
#endif /* _ATS_CCOMP_RUNTIME_NONE_ */

/*
** the [main] implementation
*/
int
main
(
int argc, char **argv, char **envp
) {
int err = 0 ;
_057_home_057_ubuntu_057_workspace_057_RosettaATS_057_greatest_common_divisor_057_gcd_056_dats__dynload() ;
ATSmainats_void_0(err) ;
return (err) ;
} /* end of [main] */

/* ****** ****** */

/* end-of-compilation-unit */
