/*
**
** The C code is generated by [ATS/Postiats-0-2-13]
** The starting compilation time is: 2017-1-7: 23h:26m
**
*/

/*
** include runtime header files
*/
#ifndef _ATS_CCOMP_HEADER_NONE_
#include "pats_ccomp_config.h"
#include "pats_ccomp_basics.h"
#include "pats_ccomp_typedefs.h"
#include "pats_ccomp_instrset.h"
#include "pats_ccomp_memalloc.h"
#ifndef _ATS_CCOMP_EXCEPTION_NONE_
#include "pats_ccomp_memalloca.h"
#include "pats_ccomp_exception.h"
#endif // end of [_ATS_CCOMP_EXCEPTION_NONE_]
#endif /* _ATS_CCOMP_HEADER_NONE_ */


/*
** include prelude cats files
*/
#ifndef _ATS_CCOMP_PRELUDE_NONE_
//
#include "prelude/CATS/basics.cats"
#include "prelude/CATS/integer.cats"
#include "prelude/CATS/pointer.cats"
#include "prelude/CATS/integer_long.cats"
#include "prelude/CATS/integer_size.cats"
#include "prelude/CATS/integer_short.cats"
#include "prelude/CATS/bool.cats"
#include "prelude/CATS/char.cats"
#include "prelude/CATS/float.cats"
#include "prelude/CATS/integer_ptr.cats"
#include "prelude/CATS/integer_fixed.cats"
#include "prelude/CATS/memory.cats"
#include "prelude/CATS/string.cats"
#include "prelude/CATS/strptr.cats"
//
#include "prelude/CATS/fprintf.cats"
//
#include "prelude/CATS/filebas.cats"
//
#include "prelude/CATS/list.cats"
#include "prelude/CATS/option.cats"
#include "prelude/CATS/array.cats"
#include "prelude/CATS/arrayptr.cats"
#include "prelude/CATS/arrayref.cats"
#include "prelude/CATS/matrix.cats"
#include "prelude/CATS/matrixptr.cats"
//
#endif /* _ATS_CCOMP_PRELUDE_NONE_ */
/*
** for user-supplied prelude
*/
#ifdef _ATS_CCOMP_PRELUDE_USER_
//
#include _ATS_CCOMP_PRELUDE_USER_
//
#endif /* _ATS_CCOMP_PRELUDE_USER_ */
/*
** for user2-supplied prelude
*/
#ifdef _ATS_CCOMP_PRELUDE_USER2_
//
#include _ATS_CCOMP_PRELUDE_USER2_
//
#endif /* _ATS_CCOMP_PRELUDE_USER2_ */

/*
staload-prologues(beg)
*/
/*
/home/ubuntu/workspace/ATS2/prelude/DATS/basics.dats: 1534(line=44, offs=1) -- 1573(line=45, offs=32)
*/
/*
/home/ubuntu/workspace/ATS2/prelude/DATS/integer.dats: 1596(line=49, offs=1) -- 1635(line=49, offs=40)
*/
/*
/home/ubuntu/workspace/ATS2/prelude/DATS/pointer.dats: 1533(line=44, offs=1) -- 1572(line=44, offs=40)
*/
/*
/home/ubuntu/workspace/ATS2/prelude/DATS/integer_long.dats: 1602(line=49, offs=1) -- 1641(line=49, offs=40)
*/
/*
/home/ubuntu/workspace/ATS2/prelude/DATS/integer_size.dats: 1597(line=49, offs=1) -- 1636(line=49, offs=40)
*/
/*
/home/ubuntu/workspace/ATS2/prelude/DATS/integer_short.dats: 1603(line=49, offs=1) -- 1642(line=49, offs=40)
*/
/*
/home/ubuntu/workspace/ATS2/prelude/DATS/char.dats: 1610(line=48, offs=1) -- 1649(line=48, offs=40)
*/
/*
/home/ubuntu/workspace/ATS2/prelude/DATS/float.dats: 1636(line=50, offs=1) -- 1675(line=50, offs=40)
*/
/*
/home/ubuntu/workspace/ATS2/prelude/DATS/string.dats: 1609(line=48, offs=1) -- 1648(line=48, offs=40)
*/
/*
/home/ubuntu/workspace/ATS2/prelude/DATS/strptr.dats: 1609(line=48, offs=1) -- 1648(line=48, offs=40)
*/
/*
/home/ubuntu/workspace/ATS2/prelude/DATS/strptr.dats: 1671(line=52, offs=1) -- 1718(line=52, offs=48)
*/
/*
/home/ubuntu/workspace/ATS2/prelude/DATS/integer.dats: 1596(line=49, offs=1) -- 1635(line=49, offs=40)
*/
/*
/home/ubuntu/workspace/ATS2/prelude/DATS/integer_ptr.dats: 1601(line=49, offs=1) -- 1640(line=49, offs=40)
*/
/*
/home/ubuntu/workspace/ATS2/prelude/DATS/integer_fixed.dats: 1603(line=49, offs=1) -- 1642(line=49, offs=40)
*/
/*
/home/ubuntu/workspace/ATS2/prelude/DATS/memory.dats: 1410(line=38, offs=1) -- 1449(line=39, offs=32)
*/
/*
/home/ubuntu/workspace/ATS2/prelude/DATS/filebas.dats: 1613(line=49, offs=1) -- 1652(line=50, offs=32)
*/
/*
/home/ubuntu/workspace/ATS2/prelude/DATS/filebas.dats: 1675(line=54, offs=1) -- 1721(line=55, offs=39)
*/
/*
/home/ubuntu/workspace/ATS2/prelude/DATS/integer.dats: 1596(line=49, offs=1) -- 1635(line=49, offs=40)
*/
/*
/home/ubuntu/workspace/ATS2/prelude/DATS/filebas.dats: 1744(line=59, offs=1) -- 1789(line=60, offs=38)
*/
/*
/home/ubuntu/workspace/ATS2/libats/libc/SATS/stdio.sats: 1390(line=36, offs=1) -- 1437(line=39, offs=3)
*/

#include \
"libats/libc/CATS/stdio.cats"
/*
/home/ubuntu/workspace/ATS2/libats/libc/SATS/stdio.sats: 1950(line=69, offs=1) -- 1999(line=71, offs=34)
*/
/*
/home/ubuntu/workspace/ATS2/libats/libc/SATS/sys/types.sats: 1390(line=36, offs=1) -- 1441(line=39, offs=3)
*/

#include \
"libats/libc/CATS/sys/types.cats"
/*
/home/ubuntu/workspace/ATS2/prelude/DATS/filebas.dats: 1871(line=66, offs=1) -- 1918(line=66, offs=48)
*/
/*
/home/ubuntu/workspace/ATS2/libats/libc/SATS/sys/stat.sats: 1390(line=36, offs=1) -- 1440(line=39, offs=3)
*/

#include \
"libats/libc/CATS/sys/stat.cats"
/*
/home/ubuntu/workspace/ATS2/libats/libc/SATS/sys/stat.sats: 1756(line=58, offs=1) -- 1805(line=60, offs=34)
*/
/*
/home/ubuntu/workspace/ATS2/libats/libc/SATS/sys/types.sats: 1390(line=36, offs=1) -- 1441(line=39, offs=3)
*/

#include \
"libats/libc/CATS/sys/types.cats"
/*
/home/ubuntu/workspace/ATS2/prelude/DATS/filebas.dats: 15413(line=857, offs=1) -- 15450(line=858, offs=30)
*/
/*
/home/ubuntu/workspace/ATS2/libats/libc/SATS/stdio.sats: 1390(line=36, offs=1) -- 1437(line=39, offs=3)
*/

#include \
"libats/libc/CATS/stdio.cats"
/*
/home/ubuntu/workspace/ATS2/libats/libc/SATS/stdio.sats: 1950(line=69, offs=1) -- 1999(line=71, offs=34)
*/
/*
/home/ubuntu/workspace/ATS2/libats/libc/SATS/sys/types.sats: 1390(line=36, offs=1) -- 1441(line=39, offs=3)
*/

#include \
"libats/libc/CATS/sys/types.cats"
/*
/home/ubuntu/workspace/ATS2/prelude/DATS/list.dats: 1529(line=44, offs=1) -- 1568(line=45, offs=32)
*/
/*
/home/ubuntu/workspace/ATS2/prelude/DATS/list.dats: 1569(line=46, offs=1) -- 1615(line=47, offs=39)
*/
/*
/home/ubuntu/workspace/ATS2/prelude/DATS/unsafe.dats: 1532(line=44, offs=1) -- 1566(line=44, offs=35)
*/
/*
/home/ubuntu/workspace/ATS2/prelude/DATS/list_vt.dats: 1538(line=44, offs=1) -- 1577(line=45, offs=32)
*/
/*
/home/ubuntu/workspace/ATS2/prelude/DATS/list_vt.dats: 1578(line=46, offs=1) -- 1624(line=47, offs=39)
*/
/*
/home/ubuntu/workspace/ATS2/prelude/DATS/unsafe.dats: 1532(line=44, offs=1) -- 1566(line=44, offs=35)
*/
/*
/home/ubuntu/workspace/ATS2/prelude/DATS/array.dats: 1534(line=44, offs=1) -- 1573(line=44, offs=40)
*/
/*
/home/ubuntu/workspace/ATS2/prelude/DATS/array.dats: 1574(line=45, offs=1) -- 1616(line=45, offs=43)
*/
/*
/home/ubuntu/workspace/ATS2/prelude/DATS/arrayptr.dats: 1532(line=44, offs=1) -- 1571(line=44, offs=40)
*/
/*
/home/ubuntu/workspace/ATS2/prelude/DATS/arrayref.dats: 1532(line=44, offs=1) -- 1571(line=44, offs=40)
*/
/*
/home/ubuntu/workspace/ATS2/prelude/DATS/matrix.dats: 1535(line=44, offs=1) -- 1574(line=44, offs=40)
*/
/*
/home/ubuntu/workspace/ATS2/prelude/DATS/matrixptr.dats: 1538(line=44, offs=1) -- 1577(line=44, offs=40)
*/
/*
/home/ubuntu/workspace/ATS2/prelude/DATS/matrixref.dats: 1538(line=44, offs=1) -- 1577(line=44, offs=40)
*/
/*
/home/ubuntu/workspace/ATS2/prelude/DATS/stream.dats: 1523(line=44, offs=1) -- 1562(line=44, offs=40)
*/
/*
/home/ubuntu/workspace/ATS2/prelude/DATS/stream_vt.dats: 1523(line=44, offs=1) -- 1562(line=44, offs=40)
*/
/*
/home/ubuntu/workspace/ATS2/prelude/DATS/tostring.dats: 1528(line=44, offs=1) -- 1567(line=45, offs=32)
*/
/*
/home/ubuntu/workspace/ATS2/prelude/DATS/unsafe.dats: 1532(line=44, offs=1) -- 1566(line=44, offs=35)
*/
/*
/home/ubuntu/workspace/ATS2/prelude/DATS/checkast.dats: 1531(line=44, offs=1) -- 1570(line=45, offs=32)
*/
/*
/home/ubuntu/workspace/ATS2/libats/ML/SATS/list0.sats: 1665(line=47, offs=1) -- 1700(line=47, offs=36)
*/
/*
/home/ubuntu/workspace/ATS2/libats/ML/SATS/option0.sats: 1524(line=41, offs=1) -- 1559(line=41, offs=36)
*/
/*
/home/ubuntu/workspace/ATS2/libats/ML/SATS/array0.sats: 1525(line=41, offs=1) -- 1571(line=44, offs=3)
*/

#include \
"libats/ML/CATS/array0.cats"
/*
/home/ubuntu/workspace/ATS2/libats/ML/SATS/array0.sats: 1610(line=48, offs=1) -- 1645(line=48, offs=36)
*/
/*
/home/ubuntu/workspace/ATS2/libats/ML/SATS/matrix0.sats: 1526(line=41, offs=1) -- 1561(line=41, offs=36)
*/
/*
/home/ubuntu/workspace/ATS2/libats/ML/SATS/string.sats: 1525(line=41, offs=1) -- 1560(line=41, offs=36)
*/
/*
/home/ubuntu/workspace/ATS2/libats/ML/SATS/strarr.sats: 1538(line=43, offs=1) -- 1574(line=43, offs=37)
*/
/*
/home/ubuntu/workspace/ATS2/libats/ML/SATS/strarr.sats: 1599(line=47, offs=1) -- 1649(line=51, offs=3)
*/

//
#include "libats/ML/CATS/strarr.cats"
//
/*
/home/ubuntu/workspace/ATS2/libats/ML/SATS/gvalue.sats: 1534(line=42, offs=1) -- 1569(line=42, offs=36)
*/
/*
/home/ubuntu/workspace/ATS2/libats/ML/SATS/stream.sats: 1532(line=43, offs=1) -- 1567(line=43, offs=36)
*/
/*
/home/ubuntu/workspace/ATS2/libats/ML/SATS/stream_vt.sats: 1534(line=43, offs=1) -- 1569(line=44, offs=28)
*/
/*
/home/ubuntu/workspace/ATS2/libats/ML/SATS/filebas.sats: 1525(line=41, offs=1) -- 1560(line=41, offs=36)
*/
/*
/home/ubuntu/workspace/ATS2/libats/ML/SATS/intrange.sats: 1629(line=47, offs=1) -- 1664(line=47, offs=36)
*/
/*
/home/ubuntu/workspace/ATS2/libats/ML/DATS/list0.dats: 1444(line=40, offs=1) -- 1483(line=41, offs=32)
*/
/*
/home/ubuntu/workspace/ATS2/libats/ML/DATS/list0.dats: 1506(line=45, offs=1) -- 1541(line=45, offs=36)
*/
/*
/home/ubuntu/workspace/ATS2/libats/ML/DATS/list0.dats: 1542(line=46, offs=1) -- 1577(line=46, offs=36)
*/
/*
/home/ubuntu/workspace/ATS2/libats/ML/SATS/list0.sats: 1665(line=47, offs=1) -- 1700(line=47, offs=36)
*/
/*
/home/ubuntu/workspace/ATS2/libats/ML/DATS/option0.dats: 1392(line=36, offs=1) -- 1431(line=37, offs=32)
*/
/*
/home/ubuntu/workspace/ATS2/libats/ML/DATS/option0.dats: 1454(line=41, offs=1) -- 1489(line=41, offs=36)
*/
/*
/home/ubuntu/workspace/ATS2/libats/ML/DATS/option0.dats: 1490(line=42, offs=1) -- 1527(line=42, offs=38)
*/
/*
/home/ubuntu/workspace/ATS2/libats/ML/SATS/option0.sats: 1524(line=41, offs=1) -- 1559(line=41, offs=36)
*/
/*
/home/ubuntu/workspace/ATS2/libats/ML/DATS/array0.dats: 1394(line=36, offs=1) -- 1433(line=37, offs=32)
*/
/*
/home/ubuntu/workspace/ATS2/libats/ML/DATS/array0.dats: 1458(line=41, offs=1) -- 1493(line=41, offs=36)
*/
/*
/home/ubuntu/workspace/ATS2/libats/ML/DATS/array0.dats: 1494(line=42, offs=1) -- 1529(line=42, offs=36)
*/
/*
/home/ubuntu/workspace/ATS2/libats/ML/SATS/list0.sats: 1665(line=47, offs=1) -- 1700(line=47, offs=36)
*/
/*
/home/ubuntu/workspace/ATS2/libats/ML/DATS/array0.dats: 1530(line=43, offs=1) -- 1566(line=43, offs=37)
*/
/*
/home/ubuntu/workspace/ATS2/libats/ML/SATS/array0.sats: 1525(line=41, offs=1) -- 1571(line=44, offs=3)
*/

#include \
"libats/ML/CATS/array0.cats"
/*
/home/ubuntu/workspace/ATS2/libats/ML/SATS/array0.sats: 1610(line=48, offs=1) -- 1645(line=48, offs=36)
*/
/*
/home/ubuntu/workspace/ATS2/libats/ML/DATS/matrix0.dats: 1396(line=36, offs=1) -- 1435(line=37, offs=32)
*/
/*
/home/ubuntu/workspace/ATS2/libats/ML/DATS/matrix0.dats: 1458(line=41, offs=1) -- 1493(line=41, offs=36)
*/
/*
/home/ubuntu/workspace/ATS2/libats/ML/DATS/matrix0.dats: 1494(line=42, offs=1) -- 1531(line=42, offs=38)
*/
/*
/home/ubuntu/workspace/ATS2/libats/ML/SATS/matrix0.sats: 1526(line=41, offs=1) -- 1561(line=41, offs=36)
*/
/*
/home/ubuntu/workspace/ATS2/libats/ML/DATS/string.dats: 1609(line=46, offs=1) -- 1648(line=46, offs=40)
*/
/*
/home/ubuntu/workspace/ATS2/libats/ML/DATS/string.dats: 2770(line=107, offs=1) -- 2805(line=107, offs=36)
*/
/*
/home/ubuntu/workspace/ATS2/libats/ML/DATS/string.dats: 2806(line=108, offs=1) -- 2841(line=108, offs=36)
*/
/*
/home/ubuntu/workspace/ATS2/libats/ML/SATS/list0.sats: 1665(line=47, offs=1) -- 1700(line=47, offs=36)
*/
/*
/home/ubuntu/workspace/ATS2/libats/ML/DATS/string.dats: 2842(line=109, offs=1) -- 2878(line=109, offs=37)
*/
/*
/home/ubuntu/workspace/ATS2/libats/ML/SATS/string.sats: 1525(line=41, offs=1) -- 1560(line=41, offs=36)
*/
/*
/home/ubuntu/workspace/ATS2/libats/ML/DATS/strarr.dats: 1613(line=46, offs=1) -- 1652(line=47, offs=32)
*/
/*
/home/ubuntu/workspace/ATS2/libats/ML/DATS/strarr.dats: 1675(line=51, offs=1) -- 1710(line=51, offs=36)
*/
/*
/home/ubuntu/workspace/ATS2/libats/ML/DATS/strarr.dats: 1711(line=52, offs=1) -- 1747(line=52, offs=37)
*/
/*
/home/ubuntu/workspace/ATS2/libats/ML/SATS/array0.sats: 1525(line=41, offs=1) -- 1571(line=44, offs=3)
*/

#include \
"libats/ML/CATS/array0.cats"
/*
/home/ubuntu/workspace/ATS2/libats/ML/SATS/array0.sats: 1610(line=48, offs=1) -- 1645(line=48, offs=36)
*/
/*
/home/ubuntu/workspace/ATS2/libats/ML/DATS/strarr.dats: 1748(line=53, offs=1) -- 1796(line=53, offs=49)
*/
/*
/home/ubuntu/workspace/ATS2/libats/ML/DATS/array0.dats: 1394(line=36, offs=1) -- 1433(line=37, offs=32)
*/
/*
/home/ubuntu/workspace/ATS2/libats/ML/DATS/array0.dats: 1458(line=41, offs=1) -- 1493(line=41, offs=36)
*/
/*
/home/ubuntu/workspace/ATS2/libats/ML/DATS/array0.dats: 1494(line=42, offs=1) -- 1529(line=42, offs=36)
*/
/*
/home/ubuntu/workspace/ATS2/libats/ML/SATS/list0.sats: 1665(line=47, offs=1) -- 1700(line=47, offs=36)
*/
/*
/home/ubuntu/workspace/ATS2/libats/ML/DATS/array0.dats: 1530(line=43, offs=1) -- 1566(line=43, offs=37)
*/
/*
/home/ubuntu/workspace/ATS2/libats/ML/SATS/array0.sats: 1525(line=41, offs=1) -- 1571(line=44, offs=3)
*/

#include \
"libats/ML/CATS/array0.cats"
/*
/home/ubuntu/workspace/ATS2/libats/ML/SATS/array0.sats: 1610(line=48, offs=1) -- 1645(line=48, offs=36)
*/
/*
/home/ubuntu/workspace/ATS2/libats/ML/DATS/strarr.dats: 1819(line=57, offs=1) -- 1855(line=57, offs=37)
*/
/*
/home/ubuntu/workspace/ATS2/libats/ML/SATS/strarr.sats: 1538(line=43, offs=1) -- 1574(line=43, offs=37)
*/
/*
/home/ubuntu/workspace/ATS2/libats/ML/SATS/strarr.sats: 1599(line=47, offs=1) -- 1649(line=51, offs=3)
*/

//
#include "libats/ML/CATS/strarr.cats"
//
/*
/home/ubuntu/workspace/ATS2/libats/ML/DATS/stream.dats: 1447(line=40, offs=1) -- 1486(line=41, offs=32)
*/
/*
/home/ubuntu/workspace/ATS2/libats/ML/DATS/stream.dats: 1509(line=45, offs=1) -- 1544(line=45, offs=36)
*/
/*
/home/ubuntu/workspace/ATS2/libats/ML/DATS/stream.dats: 1545(line=46, offs=1) -- 1581(line=46, offs=37)
*/
/*
/home/ubuntu/workspace/ATS2/libats/ML/SATS/stream.sats: 1532(line=43, offs=1) -- 1567(line=43, offs=36)
*/
/*
/home/ubuntu/workspace/ATS2/libats/ML/DATS/stream_vt.dats: 1447(line=40, offs=1) -- 1486(line=41, offs=32)
*/
/*
/home/ubuntu/workspace/ATS2/libats/ML/DATS/stream_vt.dats: 1509(line=45, offs=1) -- 1544(line=45, offs=36)
*/
/*
/home/ubuntu/workspace/ATS2/libats/ML/DATS/stream_vt.dats: 1545(line=46, offs=1) -- 1584(line=46, offs=40)
*/
/*
/home/ubuntu/workspace/ATS2/libats/ML/SATS/stream_vt.sats: 1534(line=43, offs=1) -- 1569(line=44, offs=28)
*/
/*
/home/ubuntu/workspace/ATS2/libats/ML/DATS/filebas.dats: 1472(line=40, offs=1) -- 1511(line=41, offs=32)
*/
/*
/home/ubuntu/workspace/ATS2/libats/ML/DATS/filebas.dats: 1534(line=45, offs=1) -- 1581(line=46, offs=40)
*/
/*
/home/ubuntu/workspace/ATS2/prelude/DATS/integer.dats: 1596(line=49, offs=1) -- 1635(line=49, offs=40)
*/
/*
/home/ubuntu/workspace/ATS2/libats/ML/DATS/filebas.dats: 1582(line=47, offs=1) -- 1634(line=48, offs=45)
*/
/*
/home/ubuntu/workspace/ATS2/prelude/DATS/integer_size.dats: 1597(line=49, offs=1) -- 1636(line=49, offs=40)
*/
/*
/home/ubuntu/workspace/ATS2/libats/ML/DATS/filebas.dats: 1657(line=52, offs=1) -- 1704(line=52, offs=48)
*/
/*
/home/ubuntu/workspace/ATS2/prelude/DATS/filebas.dats: 1613(line=49, offs=1) -- 1652(line=50, offs=32)
*/
/*
/home/ubuntu/workspace/ATS2/prelude/DATS/filebas.dats: 1675(line=54, offs=1) -- 1721(line=55, offs=39)
*/
/*
/home/ubuntu/workspace/ATS2/prelude/DATS/integer.dats: 1596(line=49, offs=1) -- 1635(line=49, offs=40)
*/
/*
/home/ubuntu/workspace/ATS2/prelude/DATS/filebas.dats: 1744(line=59, offs=1) -- 1789(line=60, offs=38)
*/
/*
/home/ubuntu/workspace/ATS2/libats/libc/SATS/stdio.sats: 1390(line=36, offs=1) -- 1437(line=39, offs=3)
*/

#include \
"libats/libc/CATS/stdio.cats"
/*
/home/ubuntu/workspace/ATS2/libats/libc/SATS/stdio.sats: 1950(line=69, offs=1) -- 1999(line=71, offs=34)
*/
/*
/home/ubuntu/workspace/ATS2/libats/libc/SATS/sys/types.sats: 1390(line=36, offs=1) -- 1441(line=39, offs=3)
*/

#include \
"libats/libc/CATS/sys/types.cats"
/*
/home/ubuntu/workspace/ATS2/prelude/DATS/filebas.dats: 1871(line=66, offs=1) -- 1918(line=66, offs=48)
*/
/*
/home/ubuntu/workspace/ATS2/libats/libc/SATS/sys/stat.sats: 1390(line=36, offs=1) -- 1440(line=39, offs=3)
*/

#include \
"libats/libc/CATS/sys/stat.cats"
/*
/home/ubuntu/workspace/ATS2/libats/libc/SATS/sys/stat.sats: 1756(line=58, offs=1) -- 1805(line=60, offs=34)
*/
/*
/home/ubuntu/workspace/ATS2/libats/libc/SATS/sys/types.sats: 1390(line=36, offs=1) -- 1441(line=39, offs=3)
*/

#include \
"libats/libc/CATS/sys/types.cats"
/*
/home/ubuntu/workspace/ATS2/prelude/DATS/filebas.dats: 15413(line=857, offs=1) -- 15450(line=858, offs=30)
*/
/*
/home/ubuntu/workspace/ATS2/libats/libc/SATS/stdio.sats: 1390(line=36, offs=1) -- 1437(line=39, offs=3)
*/

#include \
"libats/libc/CATS/stdio.cats"
/*
/home/ubuntu/workspace/ATS2/libats/libc/SATS/stdio.sats: 1950(line=69, offs=1) -- 1999(line=71, offs=34)
*/
/*
/home/ubuntu/workspace/ATS2/libats/libc/SATS/sys/types.sats: 1390(line=36, offs=1) -- 1441(line=39, offs=3)
*/

#include \
"libats/libc/CATS/sys/types.cats"
/*
/home/ubuntu/workspace/ATS2/libats/ML/DATS/filebas.dats: 2234(line=78, offs=1) -- 2269(line=78, offs=36)
*/
/*
/home/ubuntu/workspace/ATS2/libats/ML/DATS/filebas.dats: 2270(line=79, offs=1) -- 2305(line=79, offs=36)
*/
/*
/home/ubuntu/workspace/ATS2/libats/ML/SATS/list0.sats: 1665(line=47, offs=1) -- 1700(line=47, offs=36)
*/
/*
/home/ubuntu/workspace/ATS2/libats/ML/DATS/filebas.dats: 2306(line=80, offs=1) -- 2343(line=80, offs=38)
*/
/*
/home/ubuntu/workspace/ATS2/libats/ML/SATS/option0.sats: 1524(line=41, offs=1) -- 1559(line=41, offs=36)
*/
/*
/home/ubuntu/workspace/ATS2/libats/ML/DATS/filebas.dats: 2366(line=84, offs=1) -- 2403(line=84, offs=38)
*/
/*
/home/ubuntu/workspace/ATS2/libats/ML/SATS/filebas.sats: 1525(line=41, offs=1) -- 1560(line=41, offs=36)
*/
/*
/home/ubuntu/workspace/ATS2/libats/ML/DATS/filebas.dats: 2957(line=114, offs=1) -- 3003(line=114, offs=47)
*/
/*
/home/ubuntu/workspace/ATS2/prelude/DATS/strptr.dats: 1609(line=48, offs=1) -- 1648(line=48, offs=40)
*/
/*
/home/ubuntu/workspace/ATS2/prelude/DATS/strptr.dats: 1671(line=52, offs=1) -- 1718(line=52, offs=48)
*/
/*
/home/ubuntu/workspace/ATS2/prelude/DATS/integer.dats: 1596(line=49, offs=1) -- 1635(line=49, offs=40)
*/
/*
/home/ubuntu/workspace/ATS2/libats/ML/DATS/intrange.dats: 1397(line=36, offs=1) -- 1432(line=36, offs=36)
*/
/*
/home/ubuntu/workspace/ATS2/libats/ML/DATS/intrange.dats: 1455(line=40, offs=1) -- 1490(line=40, offs=36)
*/
/*
/home/ubuntu/workspace/ATS2/libats/ML/SATS/list0.sats: 1665(line=47, offs=1) -- 1700(line=47, offs=36)
*/
/*
/home/ubuntu/workspace/ATS2/libats/ML/DATS/intrange.dats: 1491(line=41, offs=1) -- 1527(line=41, offs=37)
*/
/*
/home/ubuntu/workspace/ATS2/libats/ML/SATS/array0.sats: 1525(line=41, offs=1) -- 1571(line=44, offs=3)
*/

#include \
"libats/ML/CATS/array0.cats"
/*
/home/ubuntu/workspace/ATS2/libats/ML/SATS/array0.sats: 1610(line=48, offs=1) -- 1645(line=48, offs=36)
*/
/*
/home/ubuntu/workspace/ATS2/libats/ML/DATS/intrange.dats: 1528(line=42, offs=1) -- 1566(line=42, offs=39)
*/
/*
/home/ubuntu/workspace/ATS2/libats/ML/SATS/intrange.sats: 1629(line=47, offs=1) -- 1664(line=47, offs=36)
*/
/*
/home/ubuntu/workspace/ATS2/libats/ML/SATS/stdlib.sats: 1522(line=41, offs=1) -- 1557(line=41, offs=36)
*/
/*
/home/ubuntu/workspace/ATS2/libats/ML/DATS/stdlib.dats: 1394(line=36, offs=1) -- 1433(line=38, offs=27)
*/
/*
/home/ubuntu/workspace/ATS2/libats/ML/DATS/stdlib.dats: 1437(line=40, offs=1) -- 1484(line=42, offs=31)
*/
/*
/home/ubuntu/workspace/ATS2/libats/libc/SATS/stdlib.sats: 1389(line=36, offs=1) -- 1443(line=41, offs=3)
*/

//
#include \
"libats/libc/CATS/stdlib.cats"
//
/*
/home/ubuntu/workspace/ATS2/libats/libc/SATS/stdlib.sats: 1810(line=62, offs=1) -- 1857(line=64, offs=31)
*/
/*
/home/ubuntu/workspace/ATS2/libats/ML/DATS/stdlib.dats: 1509(line=46, offs=1) -- 1544(line=46, offs=36)
*/
/*
/home/ubuntu/workspace/ATS2/libats/ML/DATS/stdlib.dats: 1567(line=50, offs=1) -- 1603(line=50, offs=37)
*/
/*
/home/ubuntu/workspace/ATS2/libats/ML/SATS/stdlib.sats: 1522(line=41, offs=1) -- 1557(line=41, offs=36)
*/
/*
/home/ubuntu/workspace/ATS2/libats/ML/SATS/funmap.sats: 1524(line=43, offs=1) -- 1559(line=43, offs=36)
*/
/*
/home/ubuntu/workspace/ATS2/libats/ML/SATS/funset.sats: 1524(line=41, offs=1) -- 1559(line=41, offs=36)
*/
/*
/home/ubuntu/workspace/ATS2/libats/ML/DATS/funmap.dats: 1485(line=41, offs=1) -- 1531(line=42, offs=34)
*/
/*
/home/ubuntu/workspace/ATS2/libats/ML/DATS/funmap.dats: 1556(line=46, offs=1) -- 1591(line=46, offs=36)
*/
/*
/home/ubuntu/workspace/ATS2/libats/ML/SATS/list0.sats: 1665(line=47, offs=1) -- 1700(line=47, offs=36)
*/
/*
/home/ubuntu/workspace/ATS2/libats/ML/DATS/funmap.dats: 1614(line=50, offs=1) -- 1650(line=50, offs=37)
*/
/*
/home/ubuntu/workspace/ATS2/libats/ML/SATS/funmap.sats: 1524(line=43, offs=1) -- 1559(line=43, offs=36)
*/
/*
/home/ubuntu/workspace/ATS2/libats/DATS/funmap_avltree.dats: 1534(line=43, offs=1) -- 1573(line=43, offs=40)
*/
/*
/home/ubuntu/workspace/ATS2/libats/DATS/funmap_avltree.dats: 1596(line=47, offs=1) -- 1637(line=47, offs=42)
*/
/*
/home/ubuntu/workspace/ATS2/libats/ML/DATS/funset.dats: 1484(line=40, offs=1) -- 1523(line=41, offs=32)
*/
/*
/home/ubuntu/workspace/ATS2/libats/ML/DATS/funset.dats: 1550(line=45, offs=1) -- 1596(line=47, offs=34)
*/
/*
/home/ubuntu/workspace/ATS2/libats/ML/DATS/funset.dats: 1621(line=51, offs=1) -- 1656(line=51, offs=36)
*/
/*
/home/ubuntu/workspace/ATS2/libats/ML/DATS/funset.dats: 1679(line=55, offs=1) -- 1714(line=55, offs=36)
*/
/*
/home/ubuntu/workspace/ATS2/libats/ML/SATS/list0.sats: 1665(line=47, offs=1) -- 1700(line=47, offs=36)
*/
/*
/home/ubuntu/workspace/ATS2/libats/ML/DATS/funset.dats: 1737(line=59, offs=1) -- 1773(line=59, offs=37)
*/
/*
/home/ubuntu/workspace/ATS2/libats/ML/SATS/funset.sats: 1524(line=41, offs=1) -- 1559(line=41, offs=36)
*/
/*
/home/ubuntu/workspace/ATS2/libats/DATS/funset_avltree.dats: 1417(line=37, offs=1) -- 1456(line=37, offs=40)
*/
/*
/home/ubuntu/workspace/ATS2/libats/DATS/funset_avltree.dats: 1479(line=41, offs=1) -- 1520(line=41, offs=42)
*/
/*
/home/ubuntu/workspace/ATS2/libats/ML/SATS/dynarray.sats: 1529(line=41, offs=1) -- 1564(line=41, offs=36)
*/
/*
/home/ubuntu/workspace/ATS2/libats/DATS/dynarray.dats: 1399(line=36, offs=1) -- 1438(line=37, offs=32)
*/
/*
/home/ubuntu/workspace/ATS2/libats/DATS/dynarray.dats: 1461(line=41, offs=1) -- 1496(line=41, offs=36)
*/
/*
/home/ubuntu/workspace/ATS2/libats/SATS/dynarray.sats: 1467(line=40, offs=1) -- 1510(line=42, offs=3)
*/

#include "libats/CATS/dynarray.cats"
/*
/home/ubuntu/workspace/ATS2/libats/ML/DATS/dynarray.dats: 1396(line=36, offs=1) -- 1435(line=37, offs=32)
*/
/*
/home/ubuntu/workspace/ATS2/libats/ML/DATS/dynarray.dats: 1460(line=41, offs=1) -- 1500(line=42, offs=33)
*/
/*
/home/ubuntu/workspace/ATS2/libats/SATS/dynarray.sats: 1467(line=40, offs=1) -- 1510(line=42, offs=3)
*/

#include "libats/CATS/dynarray.cats"
/*
/home/ubuntu/workspace/ATS2/libats/ML/DATS/dynarray.dats: 1525(line=46, offs=1) -- 1560(line=46, offs=36)
*/
/*
/home/ubuntu/workspace/ATS2/libats/ML/DATS/dynarray.dats: 1561(line=47, offs=1) -- 1596(line=47, offs=36)
*/
/*
/home/ubuntu/workspace/ATS2/libats/ML/SATS/list0.sats: 1665(line=47, offs=1) -- 1700(line=47, offs=36)
*/
/*
/home/ubuntu/workspace/ATS2/libats/ML/DATS/dynarray.dats: 1619(line=51, offs=1) -- 1657(line=51, offs=39)
*/
/*
/home/ubuntu/workspace/ATS2/libats/ML/SATS/dynarray.sats: 1529(line=41, offs=1) -- 1564(line=41, offs=36)
*/
/*
/home/ubuntu/workspace/ATS2/libats/ML/SATS/hashtblref.sats: 1524(line=43, offs=1) -- 1559(line=43, offs=36)
*/
/*
/home/ubuntu/workspace/ATS2/libats/DATS/qlist.dats: 1404(line=36, offs=1) -- 1443(line=37, offs=32)
*/
/*
/home/ubuntu/workspace/ATS2/libats/DATS/qlist.dats: 1466(line=41, offs=1) -- 1498(line=41, offs=33)
*/
/*
/home/ubuntu/workspace/ATS2/libats/SATS/qlist.sats: 1605(line=53, offs=1) -- 1645(line=55, offs=3)
*/

#include "libats/CATS/qlist.cats"
/*
/home/ubuntu/workspace/ATS2/libats/DATS/hashfun.dats: 1354(line=35, offs=1) -- 1393(line=36, offs=32)
*/
/*
/home/ubuntu/workspace/ATS2/libats/DATS/hashfun.dats: 1416(line=40, offs=1) -- 1450(line=40, offs=35)
*/
/*
/home/ubuntu/workspace/ATS2/libats/SATS/hashfun.sats: 1354(line=35, offs=1) -- 1396(line=37, offs=3)
*/

#include "libats/CATS/hashfun.cats"
/*
/home/ubuntu/workspace/ATS2/libats/DATS/linmap_list.dats: 1539(line=41, offs=1) -- 1578(line=42, offs=32)
*/
/*
/home/ubuntu/workspace/ATS2/libats/DATS/linmap_list.dats: 1601(line=46, offs=1) -- 1639(line=46, offs=39)
*/
/*
/home/ubuntu/workspace/ATS2/libats/DATS/hashtbl_chain.dats: 1604(line=42, offs=1) -- 1643(line=43, offs=32)
*/
/*
/home/ubuntu/workspace/ATS2/libats/DATS/hashtbl_chain.dats: 1666(line=47, offs=1) -- 1700(line=47, offs=35)
*/
/*
/home/ubuntu/workspace/ATS2/libats/SATS/hashfun.sats: 1354(line=35, offs=1) -- 1396(line=37, offs=3)
*/

#include "libats/CATS/hashfun.cats"
/*
/home/ubuntu/workspace/ATS2/libats/DATS/hashtbl_chain.dats: 1723(line=51, offs=1) -- 1763(line=51, offs=41)
*/
/*
/home/ubuntu/workspace/ATS2/libats/DATS/hashtbl_chain.dats: 2924(line=127, offs=1) -- 2967(line=128, offs=36)
*/
/*
/home/ubuntu/workspace/ATS2/libats/ML/DATS/qlistref.dats: 1447(line=40, offs=1) -- 1486(line=41, offs=32)
*/
/*
/home/ubuntu/workspace/ATS2/libats/ML/DATS/qlistref.dats: 1511(line=45, offs=1) -- 1543(line=45, offs=33)
*/
/*
/home/ubuntu/workspace/ATS2/libats/SATS/qlist.sats: 1605(line=53, offs=1) -- 1645(line=55, offs=3)
*/

#include "libats/CATS/qlist.cats"
/*
/home/ubuntu/workspace/ATS2/libats/ML/DATS/qlistref.dats: 1547(line=47, offs=1) -- 1582(line=47, offs=36)
*/
/*
/home/ubuntu/workspace/ATS2/libats/ML/DATS/qlistref.dats: 1583(line=48, offs=1) -- 1621(line=48, offs=39)
*/
/*
/home/ubuntu/workspace/ATS2/libats/ML/DATS/slistref.dats: 1452(line=41, offs=1) -- 1491(line=42, offs=32)
*/
/*
/home/ubuntu/workspace/ATS2/libats/ML/DATS/slistref.dats: 1516(line=46, offs=1) -- 1551(line=46, offs=36)
*/
/*
/home/ubuntu/workspace/ATS2/libats/ML/DATS/slistref.dats: 1552(line=47, offs=1) -- 1590(line=47, offs=39)
*/
/*
/home/ubuntu/workspace/ATS2/libats/ML/DATS/hashtblref.dats: 1394(line=36, offs=1) -- 1433(line=37, offs=32)
*/
/*
/home/ubuntu/workspace/ATS2/libats/ML/DATS/hashtblref.dats: 1458(line=41, offs=1) -- 1503(line=42, offs=33)
*/
/*
/home/ubuntu/workspace/ATS2/libats/ML/DATS/hashtblref.dats: 1528(line=46, offs=1) -- 1563(line=46, offs=36)
*/
/*
/home/ubuntu/workspace/ATS2/libats/ML/DATS/hashtblref.dats: 1586(line=50, offs=1) -- 1621(line=50, offs=36)
*/
/*
/home/ubuntu/workspace/ATS2/libats/ML/SATS/list0.sats: 1665(line=47, offs=1) -- 1700(line=47, offs=36)
*/
/*
/home/ubuntu/workspace/ATS2/libats/ML/DATS/hashtblref.dats: 1644(line=54, offs=1) -- 1678(line=54, offs=35)
*/
/*
/home/ubuntu/workspace/ATS2/libats/SATS/hashfun.sats: 1354(line=35, offs=1) -- 1396(line=37, offs=3)
*/

#include "libats/CATS/hashfun.cats"
/*
/home/ubuntu/workspace/ATS2/libats/ML/DATS/hashtblref.dats: 1679(line=55, offs=1) -- 1719(line=55, offs=41)
*/
/*
/home/ubuntu/workspace/ATS2/libats/ML/SATS/hashtblref.sats: 1524(line=43, offs=1) -- 1559(line=43, offs=36)
*/
/*
/home/ubuntu/workspace/ATS2/libats/libc/SATS/math.sats: 1380(line=35, offs=1) -- 1426(line=38, offs=3)
*/

#include \
"libats/libc/CATS/math.cats"
/*
staload-prologues(end)
*/
/*
typedefs-for-tyrecs-and-tysums(beg)
*/
typedef
ATSstruct {
atstkind_t0ype(atstype_int) atslab__0 ;
atstkind_t0ype(atstype_int) atslab__1 ;
} postiats_tyrec_0 ;
/*
typedefs-for-tyrecs-and-tysums(end)
*/
/*
dynconlst-declaration(beg)
*/
/*
dynconlst-declaration(end)
*/
/*
dyncstlst-declaration(beg)
*/
ATSdyncst_mac(atspre_g0int2int_int_int)
ATSdyncst_mac(atspre_g0int_gt_int)
ATSdyncst_mac(atspre_g0int_mul_int)
ATSdyncst_mac(atspre_g0int_sub_int)
ATSdyncst_mac(atslib_libats_libc_sqrt_double)
ATSdyncst_mac(atspre_g0int2float_int_double)
ATSdyncst_mac(atspre_g1int2int_int_int)
ATSdyncst_mac(atspre_g1int_eq_int)
ATSdyncst_mac(atspre_g0int_eq_int)
ATSdyncst_mac(atspre_g0int_mod_int)
ATSdyncst_mac(atspre_g0int_lt_int)
ATSdyncst_mac(atspre_g0int_add_int)
ATSdyncst_mac(atspre_g1int_div_int)
ATSdyncst_mac(atspre_g1int_add_int)
ATSdyncst_mac(atspre_g0int_neq_int)
ATSdyncst_mac(atspre_g0int_lte_int)
ATSdyncst_extfun(_057_home_057_ubuntu_057_workspace_057_RosettaATS_057_lucas_lehmer_test_057_lucas_056_dats__fun_s, (atstkind_t0ype(atstype_int)), atstkind_t0ype(atstype_int)) ;
ATSdyncst_mac(atspre_g0int_gte_int)
ATSdyncst_mac(atspre_assert_errmsg_bool1)
ATSdyncst_mac(atspre_g1int_gte_int)
ATSdyncst_mac(atspre_print_string)
ATSdyncst_mac(atspre_print_int)
ATSdyncst_mac(atspre_print_newline)
ATSdyncst_extfun(_057_home_057_ubuntu_057_workspace_057_RosettaATS_057_lucas_lehmer_test_057_lucas_056_dats__test, (atstkind_t0ype(atstype_int), atstkind_t0ype(atstype_int)), atsvoid_t0ype) ;
/*
dyncstlst-declaration(end)
*/
/*
dynvalist-implementation(beg)
*/
/*
dynvalist-implementation(end)
*/
/*
exnconlst-declaration(beg)
*/
#ifndef _ATS_CCOMP_EXCEPTION_NONE_
ATSextern()
atsvoid_t0ype
the_atsexncon_initize
(
  atstype_exnconptr d2c, atstype_string exnmsg
) ;
#endif // end of [_ATS_CCOMP_EXCEPTION_NONE_]
/*
exnconlst-declaration(end)
*/
/*
assumelst-declaration(beg)
*/
/*
assumelst-declaration(end)
*/
/*
extypelst-declaration(beg)
*/
/*
extypelst-declaration(end)
*/
ATSstatic()
atstkind_t0ype(atstype_int)
mypower_0(atstkind_t0ype(atstype_int), atstkind_t0ype(atstype_int)) ;

#if(0)
#if(0)
ATSextern()
atstkind_t0ype(atstype_bool)
ATSLIB_056_prelude__gt_g0int_int__1(atstkind_t0ype(atstyvar_type(tk)), atstkind_t0ype(atstype_int)) ;
#endif // end of [QUALIFIED]
#endif // end of [TEMPLATE]

ATSstatic()
atstkind_t0ype(atstype_bool)
ATSLIB_056_prelude__gt_g0int_int__1__1(atstkind_t0ype(atstype_int), atstkind_t0ype(atstype_int)) ;

ATSstatic()
atstkind_t0ype(atstype_int)
isqrt_7(atstkind_t0ype(atstype_int)) ;

ATSstatic()
atstkind_t0ype(atstype_bool)
is_prime_9(atstkind_t0ype(atstype_int)) ;

#if(0)
#if(0)
ATSextern()
atstkind_t0ype(atstype_bool)
ATSLIB_056_prelude__eq_g1int_int__10(atstkind_t0ype(atstyvar_type(tk)), atstkind_t0ype(atstype_int)) ;
#endif // end of [QUALIFIED]
#endif // end of [TEMPLATE]

ATSstatic()
atstkind_t0ype(atstype_bool)
ATSLIB_056_prelude__eq_g1int_int__10__1(atstkind_t0ype(atstype_int), atstkind_t0ype(atstype_int)) ;

#if(0)
#if(0)
ATSextern()
atstkind_t0ype(atstype_bool)
ATSLIB_056_prelude__eq_g0int_int__14(atstkind_t0ype(atstyvar_type(tk)), atstkind_t0ype(atstype_int)) ;
#endif // end of [QUALIFIED]
#endif // end of [TEMPLATE]

ATSstatic()
atstkind_t0ype(atstype_bool)
ATSLIB_056_prelude__eq_g0int_int__14__1(atstkind_t0ype(atstype_int), atstkind_t0ype(atstype_int)) ;

#if(0)
#if(0)
ATSextern()
atstype_cloptr
ATSLIB_056_libats_056_ML__intrange_forall_method__18(postiats_tyrec_0) ;
#endif // end of [QUALIFIED]
#endif // end of [TEMPLATE]

#if(0)
ATSstatic()
atstkind_t0ype(atstype_bool)
__patsfun_19__19(atstkind_t0ype(atstype_int), atstkind_t0ype(atstype_int), atstype_cloptr) ;
#endif // end of [TEMPLATE]

ATSstatic()
atstype_cloptr
ATSLIB_056_libats_056_ML__intrange_forall_method__18__1(postiats_tyrec_0) ;

ATSstatic()
atstkind_t0ype(atstype_bool)
__patsfun_19__19__1(atstkind_t0ype(atstype_int), atstkind_t0ype(atstype_int), atstype_cloptr) ;

#if(0)
#if(0)
ATSextern()
atstkind_t0ype(atstype_bool)
ATSLIB_056_libats_056_ML__intrange_forall_cloref__22(atstkind_t0ype(atstype_int), atstkind_t0ype(atstype_int), atstype_cloptr) ;
#endif // end of [QUALIFIED]
#endif // end of [TEMPLATE]

#if(0)
ATSstatic()
atstkind_t0ype(atstype_bool)
loop_23__23(atstkind_t0ype(atstype_int), atstkind_t0ype(atstype_int), atstype_cloptr) ;
#endif // end of [TEMPLATE]

ATSstatic()
atstkind_t0ype(atstype_bool)
ATSLIB_056_libats_056_ML__intrange_forall_cloref__22__1(atstkind_t0ype(atstype_int), atstkind_t0ype(atstype_int), atstype_cloptr) ;

ATSstatic()
atstkind_t0ype(atstype_bool)
loop_23__23__1(atstkind_t0ype(atstype_int), atstkind_t0ype(atstype_int), atstype_cloptr) ;

#if(0)
#if(0)
ATSextern()
atstkind_t0ype(atstype_bool)
ATSLIB_056_prelude__lt_g0int_int__26(atstkind_t0ype(atstyvar_type(tk)), atstkind_t0ype(atstype_int)) ;
#endif // end of [QUALIFIED]
#endif // end of [TEMPLATE]

ATSstatic()
atstkind_t0ype(atstype_bool)
ATSLIB_056_prelude__lt_g0int_int__26__1(atstkind_t0ype(atstype_int), atstkind_t0ype(atstype_int)) ;

ATSstatic()
atstkind_t0ype(atstype_bool)
__patsfun_32(atstkind_t0ype(atstype_int), atstkind_t0ype(atstype_int)) ;

#if(0)
#if(0)
ATSextern()
atstkind_t0ype(atstype_bool)
ATSLIB_056_prelude__neq_g0int_int__33(atstkind_t0ype(atstyvar_type(tk)), atstkind_t0ype(atstype_int)) ;
#endif // end of [QUALIFIED]
#endif // end of [TEMPLATE]

ATSstatic()
atstkind_t0ype(atstype_bool)
ATSLIB_056_prelude__neq_g0int_int__33__1(atstkind_t0ype(atstype_int), atstkind_t0ype(atstype_int)) ;

#if(0)
ATSextern()
atstkind_t0ype(atstype_int)
_057_home_057_ubuntu_057_workspace_057_RosettaATS_057_lucas_lehmer_test_057_lucas_056_dats__fun_s(atstkind_t0ype(atstype_int)) ;
#endif // end of [QUALIFIED]

#if(0)
#if(0)
ATSextern()
atstkind_t0ype(atstype_bool)
ATSLIB_056_prelude__lte_g0int_int__37(atstkind_t0ype(atstyvar_type(tk)), atstkind_t0ype(atstype_int)) ;
#endif // end of [QUALIFIED]
#endif // end of [TEMPLATE]

ATSstatic()
atstkind_t0ype(atstype_bool)
ATSLIB_056_prelude__lte_g0int_int__37__1(atstkind_t0ype(atstype_int), atstkind_t0ype(atstype_int)) ;

#if(0)
ATSextern()
atsvoid_t0ype
_057_home_057_ubuntu_057_workspace_057_RosettaATS_057_lucas_lehmer_test_057_lucas_056_dats__test(atstkind_t0ype(atstype_int), atstkind_t0ype(atstype_int)) ;
#endif // end of [QUALIFIED]

#if(0)
#if(0)
ATSextern()
atstkind_t0ype(atstype_bool)
ATSLIB_056_prelude__gte_g0int_int__41(atstkind_t0ype(atstyvar_type(tk)), atstkind_t0ype(atstype_int)) ;
#endif // end of [QUALIFIED]
#endif // end of [TEMPLATE]

ATSstatic()
atstkind_t0ype(atstype_bool)
ATSLIB_056_prelude__gte_g0int_int__41__1(atstkind_t0ype(atstype_int), atstkind_t0ype(atstype_int)) ;

#if(0)
#if(0)
ATSextern()
atstkind_t0ype(atstype_bool)
ATSLIB_056_prelude__gte_g1int_int__44(atstkind_t0ype(atstyvar_type(tk)), atstkind_t0ype(atstype_int)) ;
#endif // end of [QUALIFIED]
#endif // end of [TEMPLATE]

ATSstatic()
atstkind_t0ype(atstype_bool)
ATSLIB_056_prelude__gte_g1int_int__44__1(atstkind_t0ype(atstype_int), atstkind_t0ype(atstype_int)) ;

ATSstatic()
atstkind_t0ype(atstype_bool)
ATSLIB_056_prelude__eq_g0int_int__14__2(atstkind_t0ype(atstype_int), atstkind_t0ype(atstype_int)) ;

#if(0)
ATSextern()
atsvoid_t0ype
mainats_void_0() ;
#endif // end of [QUALIFIED]

ATSclosurerize_beg(__patsfun_19__19__1, (atstkind_t0ype(atstype_int), atstkind_t0ype(atstype_int)), (atstype_cloptr), atstkind_t0ype(atstype_bool))
typedef
ATSstruct {
atstype_funptr cfun ;
atstkind_t0ype(atstype_int) env0 ;
atstkind_t0ype(atstype_int) env1 ;
} __patsfun_19__19__1__closure_t0ype ;
ATSstatic()
atstkind_t0ype(atstype_bool)
__patsfun_19__19__1__cfun
(
__patsfun_19__19__1__closure_t0ype *p_cenv, atstype_cloptr arg0
)
{
ATSFCreturn(__patsfun_19__19__1(p_cenv->env0, p_cenv->env1, arg0)) ;
} /* end of [cfun] */
ATSstatic()
atstype_cloptr
__patsfun_19__19__1__closureinit
(
__patsfun_19__19__1__closure_t0ype *p_cenv, atstkind_t0ype(atstype_int) env0, atstkind_t0ype(atstype_int) env1
)
{
p_cenv->env0 = env0 ;
p_cenv->env1 = env1 ;
p_cenv->cfun = __patsfun_19__19__1__cfun ;
return p_cenv ;
} /* end of [closureinit] */
ATSstatic()
atstype_cloptr
__patsfun_19__19__1__closurerize
(
atstkind_t0ype(atstype_int) env0, atstkind_t0ype(atstype_int) env1
)
{
return __patsfun_19__19__1__closureinit(ATS_MALLOC(sizeof(__patsfun_19__19__1__closure_t0ype)), env0, env1) ;
} /* end of [closurerize] */
ATSclosurerize_end()
ATSclosurerize_beg(__patsfun_32, (atstkind_t0ype(atstype_int)), (atstkind_t0ype(atstype_int)), atstkind_t0ype(atstype_bool))
typedef
ATSstruct {
atstype_funptr cfun ;
atstkind_t0ype(atstype_int) env0 ;
} __patsfun_32__closure_t0ype ;
ATSstatic()
atstkind_t0ype(atstype_bool)
__patsfun_32__cfun
(
__patsfun_32__closure_t0ype *p_cenv, atstkind_t0ype(atstype_int) arg0
)
{
ATSFCreturn(__patsfun_32(p_cenv->env0, arg0)) ;
} /* end of [cfun] */
ATSstatic()
atstype_cloptr
__patsfun_32__closureinit
(
__patsfun_32__closure_t0ype *p_cenv, atstkind_t0ype(atstype_int) env0
)
{
p_cenv->env0 = env0 ;
p_cenv->cfun = __patsfun_32__cfun ;
return p_cenv ;
} /* end of [closureinit] */
ATSstatic()
atstype_cloptr
__patsfun_32__closurerize
(
atstkind_t0ype(atstype_int) env0
)
{
return __patsfun_32__closureinit(ATS_MALLOC(sizeof(__patsfun_32__closure_t0ype)), env0) ;
} /* end of [closurerize] */
ATSclosurerize_end()
/*
/home/ubuntu/workspace/RosettaATS/lucas_lehmer_test/lucas.dats: 324(line=26, offs=1) -- 401(line=29, offs=2)
*/
/*
local: mypower_0$0(level=0)
global: mypower_0$0(level=0)
local: 
global: 
*/
ATSstatic()
atstkind_t0ype(atstype_int)
mypower_0(atstkind_t0ype(atstype_int) arg0, atstkind_t0ype(atstype_int) arg1)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret0, atstkind_t0ype(atstype_int)) ;
ATStmpdec(tmp1, atstkind_t0ype(atstype_bool)) ;
ATStmpdec(tmp6, atstkind_t0ype(atstype_int)) ;
ATStmpdec(tmp7, atstkind_t0ype(atstype_int)) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /home/ubuntu/workspace/RosettaATS/lucas_lehmer_test/lucas.dats: 324(line=26, offs=1) -- 401(line=29, offs=2)
*/
ATSINSflab(__patsflab_mypower_0):
/*
emit_instr: loc0 = /home/ubuntu/workspace/RosettaATS/lucas_lehmer_test/lucas.dats: 362(line=28, offs=6) -- 367(line=28, offs=11)
*/
ATSINSmove(tmp1, ATSLIB_056_prelude__gt_g0int_int__1__1(arg1, ATSPMVi0nt(0))) ;

/*
emit_instr: loc0 = /home/ubuntu/workspace/RosettaATS/lucas_lehmer_test/lucas.dats: 359(line=28, offs=3) -- 399(line=28, offs=43)
*/
ATSif(
tmp1
) ATSthen() {
/*
emit_instr: loc0 = /home/ubuntu/workspace/RosettaATS/lucas_lehmer_test/lucas.dats: 388(line=28, offs=32) -- 391(line=28, offs=35)
*/
ATSINSmove(tmp7, atspre_g0int_sub_int(arg1, ATSPMVi0nt(1))) ;

/*
emit_instr: loc0 = /home/ubuntu/workspace/RosettaATS/lucas_lehmer_test/lucas.dats: 377(line=28, offs=21) -- 392(line=28, offs=36)
*/
ATSINSmove(tmp6, mypower_0(arg0, tmp7)) ;

/*
emit_instr: loc0 = /home/ubuntu/workspace/RosettaATS/lucas_lehmer_test/lucas.dats: 373(line=28, offs=17) -- 392(line=28, offs=36)
*/
ATSINSmove(tmpret0, atspre_g0int_mul_int(arg0, tmp6)) ;

} ATSelse() {
/*
emit_instr: loc0 = /home/ubuntu/workspace/RosettaATS/lucas_lehmer_test/lucas.dats: 398(line=28, offs=42) -- 399(line=28, offs=43)
*/
ATSINSmove(tmpret0, ATSPMVi0nt(1)) ;
} /* ATSendif */
ATSfunbody_end()
ATSreturn(tmpret0) ;
} /* end of [mypower_0] */

#if(0)
/*
/home/ubuntu/workspace/ATS2/prelude/DATS/integer.dats: 11672(line=592, offs=3) -- 11711(line=592, offs=42)
*/
/*
local: 
global: gt_g0int_int$1$0(level=0)
local: 
global: 
*/
ATSextern()
/*
imparg = tk(4620)
tmparg = S2Evar(tk(4620))
tmpsub = None()
*/
atstkind_t0ype(atstype_bool)
ATSLIB_056_prelude__gt_g0int_int__1(atstkind_t0ype(atstyvar_type(tk)) arg0, atstkind_t0ype(atstype_int) arg1)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret2, atstkind_t0ype(atstype_bool)) ;
ATStmpdec(tmp3, atstkind_t0ype(atstyvar_type(tk))) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /home/ubuntu/workspace/ATS2/prelude/DATS/integer.dats({$PATSPRE}/DATS/integer.dats): 11657(line=591, offs=1) -- 11711(line=592, offs=42)
*/
ATSINSflab(__patsflab_gt_g0int_int):
/*
emit_instr: loc0 = /home/ubuntu/workspace/ATS2/prelude/DATS/integer.dats({$PATSPRE}/DATS/integer.dats): 11698(line=592, offs=29) -- 11709(line=592, offs=40)
*/
ATSINSmove(tmp3, PMVtmpltcst(g0int2int<S2Eextkind(atstype_int), S2Evar(tk(4620))>)(arg1)) ;

/*
emit_instr: loc0 = /home/ubuntu/workspace/ATS2/prelude/DATS/integer.dats({$PATSPRE}/DATS/integer.dats): 11681(line=592, offs=12) -- 11711(line=592, offs=42)
*/
ATSINSmove(tmpret2, PMVtmpltcst(g0int_gt<S2Evar(tk(4620))>)(arg0, tmp3)) ;

ATSfunbody_end()
ATSreturn(tmpret2) ;
} /* end of [ATSLIB_056_prelude__gt_g0int_int__1] */
#endif // end of [TEMPLATE]

/*
/home/ubuntu/workspace/ATS2/prelude/DATS/integer.dats: 11672(line=592, offs=3) -- 11711(line=592, offs=42)
*/
/*
local: 
global: gt_g0int_int$1$1(level=1)
local: 
global: 
*/
ATSstatic()
/*
imparg = tk(4620)
tmparg = S2Evar(tk(4620))
tmpsub = Some(tk(4620) -> S2Eextkind(atstype_int))
*/
atstkind_t0ype(atstype_bool)
ATSLIB_056_prelude__gt_g0int_int__1__1(atstkind_t0ype(atstype_int) arg0, atstkind_t0ype(atstype_int) arg1)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret2__1, atstkind_t0ype(atstype_bool)) ;
ATStmpdec(tmp3__1, atstkind_t0ype(atstype_int)) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /home/ubuntu/workspace/ATS2/prelude/DATS/integer.dats({$PATSPRE}/DATS/integer.dats): 11657(line=591, offs=1) -- 11711(line=592, offs=42)
*/
ATSINSflab(__patsflab_gt_g0int_int):
/*
emit_instr: loc0 = /home/ubuntu/workspace/ATS2/prelude/DATS/integer.dats({$PATSPRE}/DATS/integer.dats): 11698(line=592, offs=29) -- 11709(line=592, offs=40)
*/
ATSINSmove(tmp3__1, atspre_g0int2int_int_int(arg1)) ;

/*
emit_instr: loc0 = /home/ubuntu/workspace/ATS2/prelude/DATS/integer.dats({$PATSPRE}/DATS/integer.dats): 11681(line=592, offs=12) -- 11711(line=592, offs=42)
*/
ATSINSmove(tmpret2__1, atspre_g0int_gt_int(arg0, tmp3__1)) ;

ATSfunbody_end()
ATSreturn(tmpret2__1) ;
} /* end of [ATSLIB_056_prelude__gt_g0int_int__1__1] */

/*
/home/ubuntu/workspace/RosettaATS/lucas_lehmer_test/lucas.dats: 429(line=35, offs=1) -- 505(line=36, offs=44)
*/
/*
local: 
global: isqrt_7$0(level=0)
local: 
global: 
*/
ATSstatic()
atstkind_t0ype(atstype_int)
isqrt_7(atstkind_t0ype(atstype_int) arg0)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret8, atstkind_t0ype(atstype_int)) ;
ATStmpdec(tmp9, atstkind_t0ype(atstype_double)) ;
ATStmpdec(tmp10, atstkind_t0ype(atstype_double)) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /home/ubuntu/workspace/RosettaATS/lucas_lehmer_test/lucas.dats: 429(line=35, offs=1) -- 505(line=36, offs=44)
*/
ATSINSflab(__patsflab_isqrt_7):
/*
emit_instr: loc0 = /home/ubuntu/workspace/RosettaATS/lucas_lehmer_test/lucas.dats: 495(line=36, offs=34) -- 502(line=36, offs=41)
*/
ATSINSmove(tmp10, atspre_g0int2float_int_double(arg0)) ;

/*
emit_instr: loc0 = /home/ubuntu/workspace/RosettaATS/lucas_lehmer_test/lucas.dats: 477(line=36, offs=16) -- 504(line=36, offs=43)
*/
ATSINSmove(tmp9, atslib_libats_libc_sqrt_double(tmp10)) ;

/*
emit_instr: loc0 = /home/ubuntu/workspace/RosettaATS/lucas_lehmer_test/lucas.dats: 464(line=36, offs=3) -- 505(line=36, offs=44)
*/
ATSINSmove(tmpret8, ATSPMVcastfn(cast, atstkind_t0ype(atstype_int), tmp9)) ;
ATSfunbody_end()
ATSreturn(tmpret8) ;
} /* end of [isqrt_7] */

/*
/home/ubuntu/workspace/RosettaATS/lucas_lehmer_test/lucas.dats: 513(line=39, offs=1) -- 688(line=52, offs=2)
*/
/*
local: isqrt_7$0(level=0)
global: isqrt_7$0(level=0), is_prime_9$0(level=0)
local: 
global: 
*/
ATSstatic()
atstkind_t0ype(atstype_bool)
is_prime_9(atstkind_t0ype(atstype_int) arg0)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret11, atstkind_t0ype(atstype_bool)) ;
ATStmpdec(tmp12, atstkind_t0ype(atstype_bool)) ;
ATStmpdec(tmp17, atstkind_t0ype(atstype_bool)) ;
ATStmpdec(tmp22, atstkind_t0ype(atstype_int)) ;
ATStmpdec(tmp23, atstype_cloptr) ;
ATStmpdec(tmp46, postiats_tyrec_0) ;
ATStmpdec(tmp47, atstkind_t0ype(atstype_int)) ;
ATStmpdec(tmp48, atstkind_t0ype(atstype_int)) ;
ATStmpdec(tmp49, atstkind_t0ype(atstype_int)) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /home/ubuntu/workspace/RosettaATS/lucas_lehmer_test/lucas.dats: 513(line=39, offs=1) -- 688(line=52, offs=2)
*/
ATSINSflab(__patsflab_is_prime_9):
/*
emit_instr: loc0 = /home/ubuntu/workspace/RosettaATS/lucas_lehmer_test/lucas.dats: 555(line=45, offs=2) -- 560(line=45, offs=7)
*/
ATSINSmove(tmp12, ATSLIB_056_prelude__eq_g1int_int__10__1(arg0, ATSPMVi0nt(2))) ;

/*
emit_instr: loc0 = /home/ubuntu/workspace/RosettaATS/lucas_lehmer_test/lucas.dats: 551(line=44, offs=1) -- 675(line=51, offs=2)
*/
ATSif(
tmp12
) ATSthen() {
/*
emit_instr: loc0 = /home/ubuntu/workspace/RosettaATS/lucas_lehmer_test/lucas.dats: 567(line=46, offs=6) -- 571(line=46, offs=10)
*/
ATSINSmove(tmpret11, ATSPMVbool_true()) ;
} ATSelse() {
/*
emit_instr: loc0 = /home/ubuntu/workspace/RosettaATS/lucas_lehmer_test/lucas.dats: 584(line=48, offs=6) -- 589(line=48, offs=11)
*/
ATSINSmove(tmp22, atspre_g0int_mod_int(arg0, ATSPMVi0nt(2))) ;

/*
emit_instr: loc0 = /home/ubuntu/workspace/RosettaATS/lucas_lehmer_test/lucas.dats: 584(line=48, offs=6) -- 593(line=48, offs=15)
*/
ATSINSmove(tmp17, ATSLIB_056_prelude__eq_g0int_int__14__1(tmp22, ATSPMVi0nt(0))) ;

/*
emit_instr: loc0 = /home/ubuntu/workspace/RosettaATS/lucas_lehmer_test/lucas.dats: 581(line=48, offs=3) -- 673(line=50, offs=65)
*/
ATSif(
tmp17
) ATSthen() {
/*
emit_instr: loc0 = /home/ubuntu/workspace/RosettaATS/lucas_lehmer_test/lucas.dats: 603(line=49, offs=10) -- 608(line=49, offs=15)
*/
ATSINSmove(tmpret11, ATSPMVbool_false()) ;
} ATSelse() {
/*
emit_instr: loc0 = /home/ubuntu/workspace/RosettaATS/lucas_lehmer_test/lucas.dats: 623(line=50, offs=15) -- 630(line=50, offs=22)
*/
ATSINSmove(tmp49, isqrt_7(arg0)) ;

/*
emit_instr: loc0 = /home/ubuntu/workspace/RosettaATS/lucas_lehmer_test/lucas.dats: 623(line=50, offs=15) -- 633(line=50, offs=25)
*/
ATSINSmove(tmp48, atspre_g1int_add_int(tmp49, ATSPMVi0nt(1))) ;

/*
emit_instr: loc0 = /home/ubuntu/workspace/RosettaATS/lucas_lehmer_test/lucas.dats: 622(line=50, offs=14) -- 636(line=50, offs=28)
*/
ATSINSmove(tmp47, atspre_g1int_div_int(tmp48, ATSPMVi0nt(2))) ;

/*
emit_instr: loc0 = /home/ubuntu/workspace/RosettaATS/lucas_lehmer_test/lucas.dats: 618(line=50, offs=10) -- 637(line=50, offs=29)
*/
ATSINSmove_fltrec_beg()
ATSINSstore_fltrec_ofs (tmp46, postiats_tyrec_0, atslab__0, ATSPMVi0nt(1)) ;
ATSINSstore_fltrec_ofs (tmp46, postiats_tyrec_0, atslab__1, tmp47) ;
ATSINSmove_fltrec_end()
/*
emit_instr: loc0 = /home/ubuntu/workspace/RosettaATS/lucas_lehmer_test/lucas.dats: 618(line=50, offs=10) -- 673(line=50, offs=65)
*/
ATSINSmove(tmp23, ATSLIB_056_libats_056_ML__intrange_forall_method__18__1(tmp46)) ;

/*
emit_instr: loc0 = /home/ubuntu/workspace/RosettaATS/lucas_lehmer_test/lucas.dats: 618(line=50, offs=10) -- 673(line=50, offs=65)
*/
ATSINSmove(tmpret11, ATSfunclo_clo(tmp23, (atstype_cloptr, atstype_cloptr), atstkind_t0ype(atstype_bool))(tmp23, ATSPMVcfunlab(-1, __patsfun_32, (arg0)))) ;

} /* ATSendif */
} /* ATSendif */
ATSfunbody_end()
ATSreturn(tmpret11) ;
} /* end of [is_prime_9] */

#if(0)
/*
/home/ubuntu/workspace/ATS2/prelude/DATS/integer.dats: 12410(line=634, offs=3) -- 12449(line=634, offs=42)
*/
/*
local: 
global: eq_g1int_int$10$0(level=0)
local: 
global: 
*/
ATSextern()
/*
imparg = tk(4637)
tmparg = S2Evar(tk(4637))
tmpsub = None()
*/
atstkind_t0ype(atstype_bool)
ATSLIB_056_prelude__eq_g1int_int__10(atstkind_t0ype(atstyvar_type(tk)) arg0, atstkind_t0ype(atstype_int) arg1)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret13, atstkind_t0ype(atstype_bool)) ;
ATStmpdec(tmp14, atstkind_t0ype(atstyvar_type(tk))) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /home/ubuntu/workspace/ATS2/prelude/DATS/integer.dats({$PATSPRE}/DATS/integer.dats): 12395(line=633, offs=1) -- 12449(line=634, offs=42)
*/
ATSINSflab(__patsflab_eq_g1int_int):
/*
emit_instr: loc0 = /home/ubuntu/workspace/ATS2/prelude/DATS/integer.dats({$PATSPRE}/DATS/integer.dats): 12436(line=634, offs=29) -- 12447(line=634, offs=40)
*/
ATSINSmove(tmp14, PMVtmpltcst(g1int2int<S2Eextkind(atstype_int), S2Evar(tk(4637))>)(arg1)) ;

/*
emit_instr: loc0 = /home/ubuntu/workspace/ATS2/prelude/DATS/integer.dats({$PATSPRE}/DATS/integer.dats): 12419(line=634, offs=12) -- 12449(line=634, offs=42)
*/
ATSINSmove(tmpret13, PMVtmpltcst(g1int_eq<S2Evar(tk(4637))>)(arg0, tmp14)) ;

ATSfunbody_end()
ATSreturn(tmpret13) ;
} /* end of [ATSLIB_056_prelude__eq_g1int_int__10] */
#endif // end of [TEMPLATE]

/*
/home/ubuntu/workspace/ATS2/prelude/DATS/integer.dats: 12410(line=634, offs=3) -- 12449(line=634, offs=42)
*/
/*
local: 
global: eq_g1int_int$10$1(level=1)
local: 
global: 
*/
ATSstatic()
/*
imparg = tk(4637)
tmparg = S2Evar(tk(4637))
tmpsub = Some(tk(4637) -> S2Eextkind(atstype_int))
*/
atstkind_t0ype(atstype_bool)
ATSLIB_056_prelude__eq_g1int_int__10__1(atstkind_t0ype(atstype_int) arg0, atstkind_t0ype(atstype_int) arg1)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret13__1, atstkind_t0ype(atstype_bool)) ;
ATStmpdec(tmp14__1, atstkind_t0ype(atstype_int)) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /home/ubuntu/workspace/ATS2/prelude/DATS/integer.dats({$PATSPRE}/DATS/integer.dats): 12395(line=633, offs=1) -- 12449(line=634, offs=42)
*/
ATSINSflab(__patsflab_eq_g1int_int):
/*
emit_instr: loc0 = /home/ubuntu/workspace/ATS2/prelude/DATS/integer.dats({$PATSPRE}/DATS/integer.dats): 12436(line=634, offs=29) -- 12447(line=634, offs=40)
*/
ATSINSmove(tmp14__1, atspre_g1int2int_int_int(arg1)) ;

/*
emit_instr: loc0 = /home/ubuntu/workspace/ATS2/prelude/DATS/integer.dats({$PATSPRE}/DATS/integer.dats): 12419(line=634, offs=12) -- 12449(line=634, offs=42)
*/
ATSINSmove(tmpret13__1, atspre_g1int_eq_int(arg0, tmp14__1)) ;

ATSfunbody_end()
ATSreturn(tmpret13__1) ;
} /* end of [ATSLIB_056_prelude__eq_g1int_int__10__1] */

#if(0)
/*
/home/ubuntu/workspace/ATS2/prelude/DATS/integer.dats: 11831(line=601, offs=3) -- 11870(line=601, offs=42)
*/
/*
local: 
global: eq_g0int_int$14$0(level=0)
local: 
global: 
*/
ATSextern()
/*
imparg = tk(4622)
tmparg = S2Evar(tk(4622))
tmpsub = None()
*/
atstkind_t0ype(atstype_bool)
ATSLIB_056_prelude__eq_g0int_int__14(atstkind_t0ype(atstyvar_type(tk)) arg0, atstkind_t0ype(atstype_int) arg1)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret18, atstkind_t0ype(atstype_bool)) ;
ATStmpdec(tmp19, atstkind_t0ype(atstyvar_type(tk))) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /home/ubuntu/workspace/ATS2/prelude/DATS/integer.dats({$PATSPRE}/DATS/integer.dats): 11816(line=600, offs=1) -- 11870(line=601, offs=42)
*/
ATSINSflab(__patsflab_eq_g0int_int):
/*
emit_instr: loc0 = /home/ubuntu/workspace/ATS2/prelude/DATS/integer.dats({$PATSPRE}/DATS/integer.dats): 11857(line=601, offs=29) -- 11868(line=601, offs=40)
*/
ATSINSmove(tmp19, PMVtmpltcst(g0int2int<S2Eextkind(atstype_int), S2Evar(tk(4622))>)(arg1)) ;

/*
emit_instr: loc0 = /home/ubuntu/workspace/ATS2/prelude/DATS/integer.dats({$PATSPRE}/DATS/integer.dats): 11840(line=601, offs=12) -- 11870(line=601, offs=42)
*/
ATSINSmove(tmpret18, PMVtmpltcst(g0int_eq<S2Evar(tk(4622))>)(arg0, tmp19)) ;

ATSfunbody_end()
ATSreturn(tmpret18) ;
} /* end of [ATSLIB_056_prelude__eq_g0int_int__14] */
#endif // end of [TEMPLATE]

/*
/home/ubuntu/workspace/ATS2/prelude/DATS/integer.dats: 11831(line=601, offs=3) -- 11870(line=601, offs=42)
*/
/*
local: 
global: eq_g0int_int$14$1(level=1)
local: 
global: 
*/
ATSstatic()
/*
imparg = tk(4622)
tmparg = S2Evar(tk(4622))
tmpsub = Some(tk(4622) -> S2Eextkind(atstype_int))
*/
atstkind_t0ype(atstype_bool)
ATSLIB_056_prelude__eq_g0int_int__14__1(atstkind_t0ype(atstype_int) arg0, atstkind_t0ype(atstype_int) arg1)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret18__1, atstkind_t0ype(atstype_bool)) ;
ATStmpdec(tmp19__1, atstkind_t0ype(atstype_int)) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /home/ubuntu/workspace/ATS2/prelude/DATS/integer.dats({$PATSPRE}/DATS/integer.dats): 11816(line=600, offs=1) -- 11870(line=601, offs=42)
*/
ATSINSflab(__patsflab_eq_g0int_int):
/*
emit_instr: loc0 = /home/ubuntu/workspace/ATS2/prelude/DATS/integer.dats({$PATSPRE}/DATS/integer.dats): 11857(line=601, offs=29) -- 11868(line=601, offs=40)
*/
ATSINSmove(tmp19__1, atspre_g0int2int_int_int(arg1)) ;

/*
emit_instr: loc0 = /home/ubuntu/workspace/ATS2/prelude/DATS/integer.dats({$PATSPRE}/DATS/integer.dats): 11840(line=601, offs=12) -- 11870(line=601, offs=42)
*/
ATSINSmove(tmpret18__1, atspre_g0int_eq_int(arg0, tmp19__1)) ;

ATSfunbody_end()
ATSreturn(tmpret18__1) ;
} /* end of [ATSLIB_056_prelude__eq_g0int_int__14__1] */

#if(0)
/*
/home/ubuntu/workspace/ATS2/libats/ML/DATS/intrange.dats: 2956(line=143, offs=3) -- 3012(line=143, offs=59)
*/
/*
local: 
global: intrange_forall_method$18$0(level=0)
local: 
global: 
*/
ATSextern()
/*
imparg = 
tmparg = 
tmpsub = None()
*/
atstype_cloptr
ATSLIB_056_libats_056_ML__intrange_forall_method__18(postiats_tyrec_0 arg0)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmp24, atstkind_t0ype(atstype_int)) ;
ATStmpdec(tmp25, atstkind_t0ype(atstype_int)) ;
ATStmpdec(tmpret26, atstype_cloptr) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /home/ubuntu/workspace/ATS2/libats/ML/DATS/intrange.dats({$PATSLIBATS}/ML/DATS/intrange.dats): 2931(line=142, offs=1) -- 3012(line=143, offs=59)
*/
ATSINSflab(__patsflab_intrange_forall_method):
/*
emit_instr: loc0 = /home/ubuntu/workspace/ATS2/libats/ML/DATS/intrange.dats({$PATSLIBATS}/ML/DATS/intrange.dats): 2960(line=143, offs=7) -- 2961(line=143, offs=8)
*/
ATSINSmove(tmp24, ATSSELfltrec(arg0, postiats_tyrec_0, atslab__0)) ;
/*
emit_instr: loc0 = /home/ubuntu/workspace/ATS2/libats/ML/DATS/intrange.dats({$PATSLIBATS}/ML/DATS/intrange.dats): 2963(line=143, offs=10) -- 2964(line=143, offs=11)
*/
ATSINSmove(tmp25, ATSSELfltrec(arg0, postiats_tyrec_0, atslab__1)) ;
/*
emit_instr: loc0 = /home/ubuntu/workspace/ATS2/libats/ML/DATS/intrange.dats({$PATSLIBATS}/ML/DATS/intrange.dats): 2970(line=143, offs=17) -- 3012(line=143, offs=59)
*/
ATSINSmove(tmpret26, ATSPMVcfunlab(-1, __patsfun_19__19, (tmp24, tmp25))) ;
ATSfunbody_end()
ATSreturn(tmpret26) ;
} /* end of [ATSLIB_056_libats_056_ML__intrange_forall_method__18] */
#endif // end of [TEMPLATE]

#if(0)
/*
/home/ubuntu/workspace/ATS2/libats/ML/DATS/intrange.dats: 2970(line=143, offs=17) -- 3012(line=143, offs=59)
*/
/*
local: 
global: __patsfun_19$0(level=1)
local: l$5659(1)(HSEapp(HSEcst(atstkind_t0ype); HSEs2exp(S2Eextkind(atstype_int)))), r$5660(1)(HSEapp(HSEcst(atstkind_t0ype); HSEs2exp(S2Eextkind(atstype_int))))
global: l$5659(1)(HSEapp(HSEcst(atstkind_t0ype); HSEs2exp(S2Eextkind(atstype_int)))), r$5660(1)(HSEapp(HSEcst(atstkind_t0ype); HSEs2exp(S2Eextkind(atstype_int))))
*/
ATSstatic()
atstkind_t0ype(atstype_bool)
__patsfun_19__19(atstkind_t0ype(atstype_int) env0, atstkind_t0ype(atstype_int) env1, atstype_cloptr arg0)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret27, atstkind_t0ype(atstype_bool)) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /home/ubuntu/workspace/ATS2/libats/ML/DATS/intrange.dats({$PATSLIBATS}/ML/DATS/intrange.dats): 2970(line=143, offs=17) -- 3012(line=143, offs=59)
*/
ATSINSflab(__patsflab___patsfun_19):
/*
emit_instr: loc0 = /home/ubuntu/workspace/ATS2/libats/ML/DATS/intrange.dats({$PATSLIBATS}/ML/DATS/intrange.dats): 2980(line=143, offs=27) -- 3012(line=143, offs=59)
*/
ATSINSmove(tmpret27, PMVtmpltcst(intrange_forall_cloref<>)(env0, env1, arg0)) ;

ATSfunbody_end()
ATSreturn(tmpret27) ;
} /* end of [__patsfun_19__19] */
#endif // end of [TEMPLATE]

/*
/home/ubuntu/workspace/ATS2/libats/ML/DATS/intrange.dats: 2956(line=143, offs=3) -- 3012(line=143, offs=59)
*/
/*
local: 
global: intrange_forall_method$18$1(level=1)
local: 
global: 
*/
ATSstatic()
/*
imparg = 
tmparg = 
tmpsub = Some()
*/
atstype_cloptr
ATSLIB_056_libats_056_ML__intrange_forall_method__18__1(postiats_tyrec_0 arg0)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmp24__1, atstkind_t0ype(atstype_int)) ;
ATStmpdec(tmp25__1, atstkind_t0ype(atstype_int)) ;
ATStmpdec(tmpret26__1, atstype_cloptr) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /home/ubuntu/workspace/ATS2/libats/ML/DATS/intrange.dats({$PATSLIBATS}/ML/DATS/intrange.dats): 2931(line=142, offs=1) -- 3012(line=143, offs=59)
*/
ATSINSflab(__patsflab_intrange_forall_method):
/*
emit_instr: loc0 = /home/ubuntu/workspace/ATS2/libats/ML/DATS/intrange.dats({$PATSLIBATS}/ML/DATS/intrange.dats): 2960(line=143, offs=7) -- 2961(line=143, offs=8)
*/
ATSINSmove(tmp24__1, ATSSELfltrec(arg0, postiats_tyrec_0, atslab__0)) ;
/*
emit_instr: loc0 = /home/ubuntu/workspace/ATS2/libats/ML/DATS/intrange.dats({$PATSLIBATS}/ML/DATS/intrange.dats): 2963(line=143, offs=10) -- 2964(line=143, offs=11)
*/
ATSINSmove(tmp25__1, ATSSELfltrec(arg0, postiats_tyrec_0, atslab__1)) ;
/*
emit_instr: loc0 = /home/ubuntu/workspace/ATS2/libats/ML/DATS/intrange.dats({$PATSLIBATS}/ML/DATS/intrange.dats): 2970(line=143, offs=17) -- 3012(line=143, offs=59)
*/
ATSINSmove(tmpret26__1, ATSPMVcfunlab(-1, __patsfun_19__19__1, (tmp24__1, tmp25__1))) ;
ATSfunbody_end()
ATSreturn(tmpret26__1) ;
} /* end of [ATSLIB_056_libats_056_ML__intrange_forall_method__18__1] */

/*
/home/ubuntu/workspace/ATS2/libats/ML/DATS/intrange.dats: 2970(line=143, offs=17) -- 3012(line=143, offs=59)
*/
/*
local: 
global: __patsfun_19$1(level=2)
local: l$5659(1)(HSEapp(HSEcst(atstkind_t0ype); HSEs2exp(S2Eextkind(atstype_int)))), r$5660(1)(HSEapp(HSEcst(atstkind_t0ype); HSEs2exp(S2Eextkind(atstype_int))))
global: l$5659(1)(HSEapp(HSEcst(atstkind_t0ype); HSEs2exp(S2Eextkind(atstype_int)))), r$5660(1)(HSEapp(HSEcst(atstkind_t0ype); HSEs2exp(S2Eextkind(atstype_int))))
*/
ATSstatic()
atstkind_t0ype(atstype_bool)
__patsfun_19__19__1(atstkind_t0ype(atstype_int) env0, atstkind_t0ype(atstype_int) env1, atstype_cloptr arg0)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret27__1, atstkind_t0ype(atstype_bool)) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /home/ubuntu/workspace/ATS2/libats/ML/DATS/intrange.dats({$PATSLIBATS}/ML/DATS/intrange.dats): 2970(line=143, offs=17) -- 3012(line=143, offs=59)
*/
ATSINSflab(__patsflab___patsfun_19):
/*
emit_instr: loc0 = /home/ubuntu/workspace/ATS2/libats/ML/DATS/intrange.dats({$PATSLIBATS}/ML/DATS/intrange.dats): 2980(line=143, offs=27) -- 3012(line=143, offs=59)
*/
ATSINSmove(tmpret27__1, ATSLIB_056_libats_056_ML__intrange_forall_cloref__22__1(env0, env1, arg0)) ;

ATSfunbody_end()
ATSreturn(tmpret27__1) ;
} /* end of [__patsfun_19__19__1] */

#if(0)
/*
/home/ubuntu/workspace/ATS2/libats/ML/DATS/intrange.dats: 2660(line=120, offs=3) -- 2872(line=138, offs=4)
*/
/*
local: 
global: intrange_forall_cloref$22$0(level=0)
local: 
global: 
*/
ATSextern()
/*
imparg = 
tmparg = 
tmpsub = None()
*/
atstkind_t0ype(atstype_bool)
ATSLIB_056_libats_056_ML__intrange_forall_cloref__22(atstkind_t0ype(atstype_int) arg0, atstkind_t0ype(atstype_int) arg1, atstype_cloptr arg2)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret32, atstkind_t0ype(atstype_bool)) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /home/ubuntu/workspace/ATS2/libats/ML/DATS/intrange.dats({$PATSLIBATS}/ML/DATS/intrange.dats): 2635(line=119, offs=1) -- 2872(line=138, offs=4)
*/
ATSINSflab(__patsflab_intrange_forall_cloref):
/*
emit_instr: loc0 = /home/ubuntu/workspace/ATS2/libats/ML/DATS/intrange.dats({$PATSLIBATS}/ML/DATS/intrange.dats): 2672(line=120, offs=15) -- 2872(line=138, offs=4)
*/
/*
letpush(beg)
*/
/*
letpush(end)
*/

/*
emit_instr: loc0 = /home/ubuntu/workspace/ATS2/libats/ML/DATS/intrange.dats({$PATSLIBATS}/ML/DATS/intrange.dats): 2854(line=137, offs=3) -- 2868(line=137, offs=17)
*/
ATSINSmove(tmpret32, ATSfunclo_fun(PMVd2vfunlab(d2v=loop$5655(1), flab=loop_23$0(level=1)), (atstkind_t0ype(atstype_int), atstkind_t0ype(atstype_int), atstype_cloptr), atstkind_t0ype(atstype_bool))(arg0, arg1, arg2)) ;

/*
emit_instr: loc0 = /home/ubuntu/workspace/ATS2/libats/ML/DATS/intrange.dats({$PATSLIBATS}/ML/DATS/intrange.dats): 2672(line=120, offs=15) -- 2872(line=138, offs=4)
*/
/*
INSletpop()
*/
ATSfunbody_end()
ATSreturn(tmpret32) ;
} /* end of [ATSLIB_056_libats_056_ML__intrange_forall_cloref__22] */
#endif // end of [TEMPLATE]

#if(0)
/*
/home/ubuntu/workspace/ATS2/libats/ML/DATS/intrange.dats: 2683(line=123, offs=1) -- 2825(line=134, offs=2)
*/
/*
local: loop_23$0(level=1)
global: loop_23$0(level=1)
local: 
global: 
*/
ATSstatic()
atstkind_t0ype(atstype_bool)
loop_23__23(atstkind_t0ype(atstype_int) arg0, atstkind_t0ype(atstype_int) arg1, atstype_cloptr arg2)
{
/* tmpvardeclst(beg) */
ATStmpdec(apy0, atstkind_t0ype(atstype_int)) ;
ATStmpdec(apy1, atstkind_t0ype(atstype_int)) ;
ATStmpdec(apy2, atstype_cloptr) ;
ATStmpdec(tmpret33, atstkind_t0ype(atstype_bool)) ;
ATStmpdec(tmp34, atstkind_t0ype(atstype_bool)) ;
ATStmpdec(tmp35, atstkind_t0ype(atstype_bool)) ;
ATStmpdec(tmp36, atstkind_t0ype(atstype_int)) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /home/ubuntu/workspace/ATS2/libats/ML/DATS/intrange.dats({$PATSLIBATS}/ML/DATS/intrange.dats): 2683(line=123, offs=1) -- 2825(line=134, offs=2)
*/
ATSINSflab(__patsflab_loop_23):
/*
emit_instr: loc0 = /home/ubuntu/workspace/ATS2/libats/ML/DATS/intrange.dats({$PATSLIBATS}/ML/DATS/intrange.dats): 2748(line=129, offs=4) -- 2753(line=129, offs=9)
*/
ATSINSmove(tmp34, PMVtmpltcst(lt_g0int_int<S2Eextkind(atstype_int)>)(arg0, arg1)) ;

/*
emit_instr: loc0 = /home/ubuntu/workspace/ATS2/libats/ML/DATS/intrange.dats({$PATSLIBATS}/ML/DATS/intrange.dats): 2745(line=129, offs=1) -- 2820(line=132, offs=14)
*/
ATSif(
tmp34
) ATSthen() {
/*
emit_instr: loc0 = /home/ubuntu/workspace/ATS2/libats/ML/DATS/intrange.dats({$PATSLIBATS}/ML/DATS/intrange.dats): 2770(line=131, offs=8) -- 2773(line=131, offs=11)
*/
ATSINSmove(tmp35, ATSfunclo_clo(arg2, (atstype_cloptr, atstkind_t0ype(atstype_int)), atstkind_t0ype(atstype_bool))(arg2, arg0)) ;

/*
emit_instr: loc0 = /home/ubuntu/workspace/ATS2/libats/ML/DATS/intrange.dats({$PATSLIBATS}/ML/DATS/intrange.dats): 2767(line=131, offs=5) -- 2806(line=131, offs=44)
*/
ATSif(
tmp35
) ATSthen() {
/*
emit_instr: loc0 = /home/ubuntu/workspace/ATS2/libats/ML/DATS/intrange.dats({$PATSLIBATS}/ML/DATS/intrange.dats): 2785(line=131, offs=23) -- 2788(line=131, offs=26)
*/
ATSINSmove(tmp36, PMVtmpltcst(g0int_add<S2Eextkind(atstype_int)>)(arg0, ATSPMVi0nt(1))) ;

/*
emit_instr: loc0 = /home/ubuntu/workspace/ATS2/libats/ML/DATS/intrange.dats({$PATSLIBATS}/ML/DATS/intrange.dats): 2780(line=131, offs=18) -- 2795(line=131, offs=33)
*/
ATStailcal_beg()
ATSINSmove_tlcal(apy0, tmp36) ;
ATSINSmove_tlcal(apy1, arg1) ;
ATSINSmove_tlcal(apy2, arg2) ;
ATSINSargmove_tlcal(arg0, apy0) ;
ATSINSargmove_tlcal(arg1, apy1) ;
ATSINSargmove_tlcal(arg2, apy2) ;
ATSINSfgoto(__patsflab_loop_23) ;
ATStailcal_end()

} ATSelse() {
/*
emit_instr: loc0 = /home/ubuntu/workspace/ATS2/libats/ML/DATS/intrange.dats({$PATSLIBATS}/ML/DATS/intrange.dats): 2801(line=131, offs=39) -- 2806(line=131, offs=44)
*/
ATSINSmove(tmpret33, ATSPMVbool_false()) ;
} /* ATSendif */
} ATSelse() {
/*
emit_instr: loc0 = /home/ubuntu/workspace/ATS2/libats/ML/DATS/intrange.dats({$PATSLIBATS}/ML/DATS/intrange.dats): 2816(line=132, offs=10) -- 2820(line=132, offs=14)
*/
ATSINSmove(tmpret33, ATSPMVbool_true()) ;
} /* ATSendif */
ATSfunbody_end()
ATSreturn(tmpret33) ;
} /* end of [loop_23__23] */
#endif // end of [TEMPLATE]

/*
/home/ubuntu/workspace/ATS2/libats/ML/DATS/intrange.dats: 2660(line=120, offs=3) -- 2872(line=138, offs=4)
*/
/*
local: 
global: intrange_forall_cloref$22$1(level=3)
local: 
global: 
*/
ATSstatic()
/*
imparg = 
tmparg = 
tmpsub = Some()
*/
atstkind_t0ype(atstype_bool)
ATSLIB_056_libats_056_ML__intrange_forall_cloref__22__1(atstkind_t0ype(atstype_int) arg0, atstkind_t0ype(atstype_int) arg1, atstype_cloptr arg2)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret32__1, atstkind_t0ype(atstype_bool)) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /home/ubuntu/workspace/ATS2/libats/ML/DATS/intrange.dats({$PATSLIBATS}/ML/DATS/intrange.dats): 2635(line=119, offs=1) -- 2872(line=138, offs=4)
*/
ATSINSflab(__patsflab_intrange_forall_cloref):
/*
emit_instr: loc0 = /home/ubuntu/workspace/ATS2/libats/ML/DATS/intrange.dats({$PATSLIBATS}/ML/DATS/intrange.dats): 2672(line=120, offs=15) -- 2872(line=138, offs=4)
*/
/*
letpush(beg)
*/
/*
letpush(end)
*/

/*
emit_instr: loc0 = /home/ubuntu/workspace/ATS2/libats/ML/DATS/intrange.dats({$PATSLIBATS}/ML/DATS/intrange.dats): 2854(line=137, offs=3) -- 2868(line=137, offs=17)
*/
ATSINSmove(tmpret32__1, loop_23__23__1(arg0, arg1, arg2)) ;

/*
emit_instr: loc0 = /home/ubuntu/workspace/ATS2/libats/ML/DATS/intrange.dats({$PATSLIBATS}/ML/DATS/intrange.dats): 2672(line=120, offs=15) -- 2872(line=138, offs=4)
*/
/*
INSletpop()
*/
ATSfunbody_end()
ATSreturn(tmpret32__1) ;
} /* end of [ATSLIB_056_libats_056_ML__intrange_forall_cloref__22__1] */

/*
/home/ubuntu/workspace/ATS2/libats/ML/DATS/intrange.dats: 2683(line=123, offs=1) -- 2825(line=134, offs=2)
*/
/*
local: loop_23$1(level=4)
global: loop_23$1(level=4)
local: 
global: 
*/
ATSstatic()
atstkind_t0ype(atstype_bool)
loop_23__23__1(atstkind_t0ype(atstype_int) arg0, atstkind_t0ype(atstype_int) arg1, atstype_cloptr arg2)
{
/* tmpvardeclst(beg) */
ATStmpdec(apy0, atstkind_t0ype(atstype_int)) ;
ATStmpdec(apy1, atstkind_t0ype(atstype_int)) ;
ATStmpdec(apy2, atstype_cloptr) ;
ATStmpdec(tmpret33__1, atstkind_t0ype(atstype_bool)) ;
ATStmpdec(tmp34__1, atstkind_t0ype(atstype_bool)) ;
ATStmpdec(tmp35__1, atstkind_t0ype(atstype_bool)) ;
ATStmpdec(tmp36__1, atstkind_t0ype(atstype_int)) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /home/ubuntu/workspace/ATS2/libats/ML/DATS/intrange.dats({$PATSLIBATS}/ML/DATS/intrange.dats): 2683(line=123, offs=1) -- 2825(line=134, offs=2)
*/
ATSINSflab(__patsflab_loop_23):
/*
emit_instr: loc0 = /home/ubuntu/workspace/ATS2/libats/ML/DATS/intrange.dats({$PATSLIBATS}/ML/DATS/intrange.dats): 2748(line=129, offs=4) -- 2753(line=129, offs=9)
*/
ATSINSmove(tmp34__1, ATSLIB_056_prelude__lt_g0int_int__26__1(arg0, arg1)) ;

/*
emit_instr: loc0 = /home/ubuntu/workspace/ATS2/libats/ML/DATS/intrange.dats({$PATSLIBATS}/ML/DATS/intrange.dats): 2745(line=129, offs=1) -- 2820(line=132, offs=14)
*/
ATSif(
tmp34__1
) ATSthen() {
/*
emit_instr: loc0 = /home/ubuntu/workspace/ATS2/libats/ML/DATS/intrange.dats({$PATSLIBATS}/ML/DATS/intrange.dats): 2770(line=131, offs=8) -- 2773(line=131, offs=11)
*/
ATSINSmove(tmp35__1, ATSfunclo_clo(arg2, (atstype_cloptr, atstkind_t0ype(atstype_int)), atstkind_t0ype(atstype_bool))(arg2, arg0)) ;

/*
emit_instr: loc0 = /home/ubuntu/workspace/ATS2/libats/ML/DATS/intrange.dats({$PATSLIBATS}/ML/DATS/intrange.dats): 2767(line=131, offs=5) -- 2806(line=131, offs=44)
*/
ATSif(
tmp35__1
) ATSthen() {
/*
emit_instr: loc0 = /home/ubuntu/workspace/ATS2/libats/ML/DATS/intrange.dats({$PATSLIBATS}/ML/DATS/intrange.dats): 2785(line=131, offs=23) -- 2788(line=131, offs=26)
*/
ATSINSmove(tmp36__1, atspre_g0int_add_int(arg0, ATSPMVi0nt(1))) ;

/*
emit_instr: loc0 = /home/ubuntu/workspace/ATS2/libats/ML/DATS/intrange.dats({$PATSLIBATS}/ML/DATS/intrange.dats): 2780(line=131, offs=18) -- 2795(line=131, offs=33)
*/
ATStailcal_beg()
ATSINSmove_tlcal(apy0, tmp36__1) ;
ATSINSmove_tlcal(apy1, arg1) ;
ATSINSmove_tlcal(apy2, arg2) ;
ATSINSargmove_tlcal(arg0, apy0) ;
ATSINSargmove_tlcal(arg1, apy1) ;
ATSINSargmove_tlcal(arg2, apy2) ;
ATSINSfgoto(__patsflab_loop_23) ;
ATStailcal_end()

} ATSelse() {
/*
emit_instr: loc0 = /home/ubuntu/workspace/ATS2/libats/ML/DATS/intrange.dats({$PATSLIBATS}/ML/DATS/intrange.dats): 2801(line=131, offs=39) -- 2806(line=131, offs=44)
*/
ATSINSmove(tmpret33__1, ATSPMVbool_false()) ;
} /* ATSendif */
} ATSelse() {
/*
emit_instr: loc0 = /home/ubuntu/workspace/ATS2/libats/ML/DATS/intrange.dats({$PATSLIBATS}/ML/DATS/intrange.dats): 2816(line=132, offs=10) -- 2820(line=132, offs=14)
*/
ATSINSmove(tmpret33__1, ATSPMVbool_true()) ;
} /* ATSendif */
ATSfunbody_end()
ATSreturn(tmpret33__1) ;
} /* end of [loop_23__23__1] */

#if(0)
/*
/home/ubuntu/workspace/ATS2/prelude/DATS/integer.dats: 11513(line=583, offs=3) -- 11552(line=583, offs=42)
*/
/*
local: 
global: lt_g0int_int$26$0(level=0)
local: 
global: 
*/
ATSextern()
/*
imparg = tk(4618)
tmparg = S2Evar(tk(4618))
tmpsub = None()
*/
atstkind_t0ype(atstype_bool)
ATSLIB_056_prelude__lt_g0int_int__26(atstkind_t0ype(atstyvar_type(tk)) arg0, atstkind_t0ype(atstype_int) arg1)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret42, atstkind_t0ype(atstype_bool)) ;
ATStmpdec(tmp43, atstkind_t0ype(atstyvar_type(tk))) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /home/ubuntu/workspace/ATS2/prelude/DATS/integer.dats({$PATSPRE}/DATS/integer.dats): 11498(line=582, offs=1) -- 11552(line=583, offs=42)
*/
ATSINSflab(__patsflab_lt_g0int_int):
/*
emit_instr: loc0 = /home/ubuntu/workspace/ATS2/prelude/DATS/integer.dats({$PATSPRE}/DATS/integer.dats): 11539(line=583, offs=29) -- 11550(line=583, offs=40)
*/
ATSINSmove(tmp43, PMVtmpltcst(g0int2int<S2Eextkind(atstype_int), S2Evar(tk(4618))>)(arg1)) ;

/*
emit_instr: loc0 = /home/ubuntu/workspace/ATS2/prelude/DATS/integer.dats({$PATSPRE}/DATS/integer.dats): 11522(line=583, offs=12) -- 11552(line=583, offs=42)
*/
ATSINSmove(tmpret42, PMVtmpltcst(g0int_lt<S2Evar(tk(4618))>)(arg0, tmp43)) ;

ATSfunbody_end()
ATSreturn(tmpret42) ;
} /* end of [ATSLIB_056_prelude__lt_g0int_int__26] */
#endif // end of [TEMPLATE]

/*
/home/ubuntu/workspace/ATS2/prelude/DATS/integer.dats: 11513(line=583, offs=3) -- 11552(line=583, offs=42)
*/
/*
local: 
global: lt_g0int_int$26$1(level=5)
local: 
global: 
*/
ATSstatic()
/*
imparg = tk(4618)
tmparg = S2Evar(tk(4618))
tmpsub = Some(tk(4618) -> S2Eextkind(atstype_int))
*/
atstkind_t0ype(atstype_bool)
ATSLIB_056_prelude__lt_g0int_int__26__1(atstkind_t0ype(atstype_int) arg0, atstkind_t0ype(atstype_int) arg1)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret42__1, atstkind_t0ype(atstype_bool)) ;
ATStmpdec(tmp43__1, atstkind_t0ype(atstype_int)) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /home/ubuntu/workspace/ATS2/prelude/DATS/integer.dats({$PATSPRE}/DATS/integer.dats): 11498(line=582, offs=1) -- 11552(line=583, offs=42)
*/
ATSINSflab(__patsflab_lt_g0int_int):
/*
emit_instr: loc0 = /home/ubuntu/workspace/ATS2/prelude/DATS/integer.dats({$PATSPRE}/DATS/integer.dats): 11539(line=583, offs=29) -- 11550(line=583, offs=40)
*/
ATSINSmove(tmp43__1, atspre_g0int2int_int_int(arg1)) ;

/*
emit_instr: loc0 = /home/ubuntu/workspace/ATS2/prelude/DATS/integer.dats({$PATSPRE}/DATS/integer.dats): 11522(line=583, offs=12) -- 11552(line=583, offs=42)
*/
ATSINSmove(tmpret42__1, atspre_g0int_lt_int(arg0, tmp43__1)) ;

ATSfunbody_end()
ATSreturn(tmpret42__1) ;
} /* end of [ATSLIB_056_prelude__lt_g0int_int__26__1] */

/*
/home/ubuntu/workspace/RosettaATS/lucas_lehmer_test/lucas.dats: 647(line=50, offs=39) -- 672(line=50, offs=64)
*/
/*
local: 
global: __patsfun_32$0(level=1)
local: n$7240(1)(HSEapp(HSEcst(atstkind_t0ype); HSEs2exp(S2Eextkind(atstype_int))))
global: n$7240(1)(HSEapp(HSEcst(atstkind_t0ype); HSEs2exp(S2Eextkind(atstype_int))))
*/
ATSstatic()
atstkind_t0ype(atstype_bool)
__patsfun_32(atstkind_t0ype(atstype_int) env0, atstkind_t0ype(atstype_int) arg0)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret50, atstkind_t0ype(atstype_bool)) ;
ATStmpdec(tmp55, atstkind_t0ype(atstype_int)) ;
ATStmpdec(tmp56, atstkind_t0ype(atstype_int)) ;
ATStmpdec(tmp57, atstkind_t0ype(atstype_int)) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /home/ubuntu/workspace/RosettaATS/lucas_lehmer_test/lucas.dats: 647(line=50, offs=39) -- 672(line=50, offs=64)
*/
ATSINSflab(__patsflab___patsfun_32):
/*
emit_instr: loc0 = /home/ubuntu/workspace/RosettaATS/lucas_lehmer_test/lucas.dats: 661(line=50, offs=53) -- 664(line=50, offs=56)
*/
ATSINSmove(tmp57, atspre_g0int_mul_int(ATSPMVi0nt(2), arg0)) ;

/*
emit_instr: loc0 = /home/ubuntu/workspace/RosettaATS/lucas_lehmer_test/lucas.dats: 661(line=50, offs=53) -- 666(line=50, offs=58)
*/
ATSINSmove(tmp56, atspre_g0int_add_int(tmp57, ATSPMVi0nt(1))) ;

/*
emit_instr: loc0 = /home/ubuntu/workspace/RosettaATS/lucas_lehmer_test/lucas.dats: 656(line=50, offs=48) -- 667(line=50, offs=59)
*/
ATSINSmove(tmp55, atspre_g0int_mod_int(env0, tmp56)) ;

/*
emit_instr: loc0 = /home/ubuntu/workspace/RosettaATS/lucas_lehmer_test/lucas.dats: 656(line=50, offs=48) -- 672(line=50, offs=64)
*/
ATSINSmove(tmpret50, ATSLIB_056_prelude__neq_g0int_int__33__1(tmp55, ATSPMVi0nt(0))) ;

ATSfunbody_end()
ATSreturn(tmpret50) ;
} /* end of [__patsfun_32] */

#if(0)
/*
/home/ubuntu/workspace/ATS2/prelude/DATS/integer.dats: 11909(line=605, offs=3) -- 11949(line=605, offs=43)
*/
/*
local: 
global: neq_g0int_int$33$0(level=0)
local: 
global: 
*/
ATSextern()
/*
imparg = tk(4623)
tmparg = S2Evar(tk(4623))
tmpsub = None()
*/
atstkind_t0ype(atstype_bool)
ATSLIB_056_prelude__neq_g0int_int__33(atstkind_t0ype(atstyvar_type(tk)) arg0, atstkind_t0ype(atstype_int) arg1)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret51, atstkind_t0ype(atstype_bool)) ;
ATStmpdec(tmp52, atstkind_t0ype(atstyvar_type(tk))) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /home/ubuntu/workspace/ATS2/prelude/DATS/integer.dats({$PATSPRE}/DATS/integer.dats): 11893(line=604, offs=1) -- 11949(line=605, offs=43)
*/
ATSINSflab(__patsflab_neq_g0int_int):
/*
emit_instr: loc0 = /home/ubuntu/workspace/ATS2/prelude/DATS/integer.dats({$PATSPRE}/DATS/integer.dats): 11936(line=605, offs=30) -- 11947(line=605, offs=41)
*/
ATSINSmove(tmp52, PMVtmpltcst(g0int2int<S2Eextkind(atstype_int), S2Evar(tk(4623))>)(arg1)) ;

/*
emit_instr: loc0 = /home/ubuntu/workspace/ATS2/prelude/DATS/integer.dats({$PATSPRE}/DATS/integer.dats): 11918(line=605, offs=12) -- 11949(line=605, offs=43)
*/
ATSINSmove(tmpret51, PMVtmpltcst(g0int_neq<S2Evar(tk(4623))>)(arg0, tmp52)) ;

ATSfunbody_end()
ATSreturn(tmpret51) ;
} /* end of [ATSLIB_056_prelude__neq_g0int_int__33] */
#endif // end of [TEMPLATE]

/*
/home/ubuntu/workspace/ATS2/prelude/DATS/integer.dats: 11909(line=605, offs=3) -- 11949(line=605, offs=43)
*/
/*
local: 
global: neq_g0int_int$33$1(level=2)
local: 
global: 
*/
ATSstatic()
/*
imparg = tk(4623)
tmparg = S2Evar(tk(4623))
tmpsub = Some(tk(4623) -> S2Eextkind(atstype_int))
*/
atstkind_t0ype(atstype_bool)
ATSLIB_056_prelude__neq_g0int_int__33__1(atstkind_t0ype(atstype_int) arg0, atstkind_t0ype(atstype_int) arg1)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret51__1, atstkind_t0ype(atstype_bool)) ;
ATStmpdec(tmp52__1, atstkind_t0ype(atstype_int)) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /home/ubuntu/workspace/ATS2/prelude/DATS/integer.dats({$PATSPRE}/DATS/integer.dats): 11893(line=604, offs=1) -- 11949(line=605, offs=43)
*/
ATSINSflab(__patsflab_neq_g0int_int):
/*
emit_instr: loc0 = /home/ubuntu/workspace/ATS2/prelude/DATS/integer.dats({$PATSPRE}/DATS/integer.dats): 11936(line=605, offs=30) -- 11947(line=605, offs=41)
*/
ATSINSmove(tmp52__1, atspre_g0int2int_int_int(arg1)) ;

/*
emit_instr: loc0 = /home/ubuntu/workspace/ATS2/prelude/DATS/integer.dats({$PATSPRE}/DATS/integer.dats): 11918(line=605, offs=12) -- 11949(line=605, offs=43)
*/
ATSINSmove(tmpret51__1, atspre_g0int_neq_int(arg0, tmp52__1)) ;

ATSfunbody_end()
ATSreturn(tmpret51__1) ;
} /* end of [ATSLIB_056_prelude__neq_g0int_int__33__1] */

/*
/home/ubuntu/workspace/RosettaATS/lucas_lehmer_test/lucas.dats: 751(line=57, offs=7) -- 812(line=61, offs=2)
*/
/*
local: 
global: fun_s$36$0(level=0)
local: 
global: 
*/
ATSextern()
atstkind_t0ype(atstype_int)
_057_home_057_ubuntu_057_workspace_057_RosettaATS_057_lucas_lehmer_test_057_lucas_056_dats__fun_s(atstkind_t0ype(atstype_int) arg0)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret58, atstkind_t0ype(atstype_int)) ;
ATStmpdec(tmp59, atstkind_t0ype(atstype_bool)) ;
ATStmpdec(tmp64, atstkind_t0ype(atstype_int)) ;
ATStmpdec(tmp65, atstkind_t0ype(atstype_int)) ;
ATStmpdec(tmp66, atstkind_t0ype(atstype_int)) ;
ATStmpdec(tmp67, atstkind_t0ype(atstype_int)) ;
ATStmpdec(tmp68, atstkind_t0ype(atstype_int)) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /home/ubuntu/workspace/RosettaATS/lucas_lehmer_test/lucas.dats: 745(line=57, offs=1) -- 812(line=61, offs=2)
*/
ATSINSflab(__patsflab_fun_s):
/*
emit_instr: loc0 = /home/ubuntu/workspace/RosettaATS/lucas_lehmer_test/lucas.dats: 765(line=59, offs=6) -- 771(line=59, offs=12)
*/
ATSINSmove(tmp59, ATSLIB_056_prelude__lte_g0int_int__37__1(arg0, ATSPMVi0nt(1))) ;

/*
emit_instr: loc0 = /home/ubuntu/workspace/RosettaATS/lucas_lehmer_test/lucas.dats: 762(line=59, offs=3) -- 809(line=60, offs=31)
*/
ATSif(
tmp59
) ATSthen() {
/*
emit_instr: loc0 = /home/ubuntu/workspace/RosettaATS/lucas_lehmer_test/lucas.dats: 777(line=59, offs=18) -- 778(line=59, offs=19)
*/
ATSINSmove(tmpret58, ATSPMVi0nt(4)) ;
} ATSelse() {
/*
emit_instr: loc0 = /home/ubuntu/workspace/RosettaATS/lucas_lehmer_test/lucas.dats: 792(line=60, offs=14) -- 795(line=60, offs=17)
*/
ATSINSmove(tmp66, atspre_g0int_sub_int(arg0, ATSPMVi0nt(1))) ;

/*
emit_instr: loc0 = /home/ubuntu/workspace/RosettaATS/lucas_lehmer_test/lucas.dats: 786(line=60, offs=8) -- 796(line=60, offs=18)
*/
ATSINSmove(tmp65, _057_home_057_ubuntu_057_workspace_057_RosettaATS_057_lucas_lehmer_test_057_lucas_056_dats__fun_s(tmp66)) ;

/*
emit_instr: loc0 = /home/ubuntu/workspace/RosettaATS/lucas_lehmer_test/lucas.dats: 803(line=60, offs=25) -- 806(line=60, offs=28)
*/
ATSINSmove(tmp68, atspre_g0int_sub_int(arg0, ATSPMVi0nt(1))) ;

/*
emit_instr: loc0 = /home/ubuntu/workspace/RosettaATS/lucas_lehmer_test/lucas.dats: 797(line=60, offs=19) -- 807(line=60, offs=29)
*/
ATSINSmove(tmp67, _057_home_057_ubuntu_057_workspace_057_RosettaATS_057_lucas_lehmer_test_057_lucas_056_dats__fun_s(tmp68)) ;

/*
emit_instr: loc0 = /home/ubuntu/workspace/RosettaATS/lucas_lehmer_test/lucas.dats: 786(line=60, offs=8) -- 807(line=60, offs=29)
*/
ATSINSmove(tmp64, atspre_g0int_mul_int(tmp65, tmp67)) ;

/*
emit_instr: loc0 = /home/ubuntu/workspace/RosettaATS/lucas_lehmer_test/lucas.dats: 786(line=60, offs=8) -- 809(line=60, offs=31)
*/
ATSINSmove(tmpret58, atspre_g0int_sub_int(tmp64, ATSPMVi0nt(2))) ;

} /* ATSendif */
ATSfunbody_end()
ATSreturn(tmpret58) ;
} /* end of [_057_home_057_ubuntu_057_workspace_057_RosettaATS_057_lucas_lehmer_test_057_lucas_056_dats__fun_s] */

#if(0)
/*
/home/ubuntu/workspace/ATS2/prelude/DATS/integer.dats: 11591(line=587, offs=3) -- 11631(line=587, offs=43)
*/
/*
local: 
global: lte_g0int_int$37$0(level=0)
local: 
global: 
*/
ATSextern()
/*
imparg = tk(4619)
tmparg = S2Evar(tk(4619))
tmpsub = None()
*/
atstkind_t0ype(atstype_bool)
ATSLIB_056_prelude__lte_g0int_int__37(atstkind_t0ype(atstyvar_type(tk)) arg0, atstkind_t0ype(atstype_int) arg1)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret60, atstkind_t0ype(atstype_bool)) ;
ATStmpdec(tmp61, atstkind_t0ype(atstyvar_type(tk))) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /home/ubuntu/workspace/ATS2/prelude/DATS/integer.dats({$PATSPRE}/DATS/integer.dats): 11575(line=586, offs=1) -- 11631(line=587, offs=43)
*/
ATSINSflab(__patsflab_lte_g0int_int):
/*
emit_instr: loc0 = /home/ubuntu/workspace/ATS2/prelude/DATS/integer.dats({$PATSPRE}/DATS/integer.dats): 11618(line=587, offs=30) -- 11629(line=587, offs=41)
*/
ATSINSmove(tmp61, PMVtmpltcst(g0int2int<S2Eextkind(atstype_int), S2Evar(tk(4619))>)(arg1)) ;

/*
emit_instr: loc0 = /home/ubuntu/workspace/ATS2/prelude/DATS/integer.dats({$PATSPRE}/DATS/integer.dats): 11600(line=587, offs=12) -- 11631(line=587, offs=43)
*/
ATSINSmove(tmpret60, PMVtmpltcst(g0int_lte<S2Evar(tk(4619))>)(arg0, tmp61)) ;

ATSfunbody_end()
ATSreturn(tmpret60) ;
} /* end of [ATSLIB_056_prelude__lte_g0int_int__37] */
#endif // end of [TEMPLATE]

/*
/home/ubuntu/workspace/ATS2/prelude/DATS/integer.dats: 11591(line=587, offs=3) -- 11631(line=587, offs=43)
*/
/*
local: 
global: lte_g0int_int$37$1(level=1)
local: 
global: 
*/
ATSstatic()
/*
imparg = tk(4619)
tmparg = S2Evar(tk(4619))
tmpsub = Some(tk(4619) -> S2Eextkind(atstype_int))
*/
atstkind_t0ype(atstype_bool)
ATSLIB_056_prelude__lte_g0int_int__37__1(atstkind_t0ype(atstype_int) arg0, atstkind_t0ype(atstype_int) arg1)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret60__1, atstkind_t0ype(atstype_bool)) ;
ATStmpdec(tmp61__1, atstkind_t0ype(atstype_int)) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /home/ubuntu/workspace/ATS2/prelude/DATS/integer.dats({$PATSPRE}/DATS/integer.dats): 11575(line=586, offs=1) -- 11631(line=587, offs=43)
*/
ATSINSflab(__patsflab_lte_g0int_int):
/*
emit_instr: loc0 = /home/ubuntu/workspace/ATS2/prelude/DATS/integer.dats({$PATSPRE}/DATS/integer.dats): 11618(line=587, offs=30) -- 11629(line=587, offs=41)
*/
ATSINSmove(tmp61__1, atspre_g0int2int_int_int(arg1)) ;

/*
emit_instr: loc0 = /home/ubuntu/workspace/ATS2/prelude/DATS/integer.dats({$PATSPRE}/DATS/integer.dats): 11600(line=587, offs=12) -- 11631(line=587, offs=43)
*/
ATSINSmove(tmpret60__1, atspre_g0int_lte_int(arg0, tmp61__1)) ;

ATSfunbody_end()
ATSreturn(tmpret60__1) ;
} /* end of [ATSLIB_056_prelude__lte_g0int_int__37__1] */

/*
/home/ubuntu/workspace/RosettaATS/lucas_lehmer_test/lucas.dats: 849(line=66, offs=5) -- 1417(line=92, offs=2)
*/
/*
local: mypower_0$0(level=0), is_prime_9$0(level=0)
global: mypower_0$0(level=0), isqrt_7$0(level=0), is_prime_9$0(level=0), test$40$0(level=0)
local: 
global: 
*/
ATSextern()
atsvoid_t0ype
_057_home_057_ubuntu_057_workspace_057_RosettaATS_057_lucas_lehmer_test_057_lucas_056_dats__test(atstkind_t0ype(atstype_int) arg0, atstkind_t0ype(atstype_int) arg1)
{
/* tmpvardeclst(beg) */
ATStmpdec(apy0, atstkind_t0ype(atstype_int)) ;
ATStmpdec(apy1, atstkind_t0ype(atstype_int)) ;
// ATStmpdec_void(tmpret69) ;
ATStmpdec(tmp70, atstkind_t0ype(atstype_bool)) ;
ATStmpdec(tmp75, atstkind_t0ype(atstype_int)) ;
ATStmpdec(tmp76, atstkind_t0ype(atstype_int)) ;
// ATStmpdec_void(tmp77) ;
ATStmpdec(tmp78, atstkind_t0ype(atstype_bool)) ;
ATStmpdec(tmp83, atstkind_t0ype(atstype_bool)) ;
ATStmpdec(tmp84, atstkind_t0ype(atstype_bool)) ;
ATStmpdec(tmp85, atstkind_t0ype(atstype_bool)) ;
ATStmpdec(tmp88, atstkind_t0ype(atstype_int)) ;
ATStmpdec(tmp89, atstkind_t0ype(atstype_int)) ;
ATStmpdec(tmp90, atstkind_t0ype(atstype_int)) ;
ATStmpdec(tmp91, atstkind_t0ype(atstype_bool)) ;
ATStmpdec(tmp92, atstkind_t0ype(atstype_bool)) ;
// ATStmpdec_void(tmp93) ;
// ATStmpdec_void(tmp94) ;
// ATStmpdec_void(tmp95) ;
ATStmpdec(tmp96, atstkind_t0ype(atstype_int)) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /home/ubuntu/workspace/RosettaATS/lucas_lehmer_test/lucas.dats: 845(line=66, offs=1) -- 1417(line=92, offs=2)
*/
ATSINSflab(__patsflab_test):
/*
emit_instr: loc0 = /home/ubuntu/workspace/RosettaATS/lucas_lehmer_test/lucas.dats: 885(line=68, offs=6) -- 900(line=68, offs=21)
*/
ATSINSmove(tmp70, ATSLIB_056_prelude__gte_g0int_int__41__1(arg0, arg1)) ;

/*
emit_instr: loc0 = /home/ubuntu/workspace/RosettaATS/lucas_lehmer_test/lucas.dats: 882(line=68, offs=3) -- 1415(line=91, offs=4)
*/
ATSif(
tmp70
) ATSthen() {
/*
emit_instr: loc0 = /home/ubuntu/workspace/RosettaATS/lucas_lehmer_test/lucas.dats: 906(line=68, offs=27) -- 908(line=68, offs=29)
*/
ATSINSmove_void(tmpret69, ATSPMVempty()) ;
} ATSelse() {
/*
emit_instr: loc0 = /home/ubuntu/workspace/RosettaATS/lucas_lehmer_test/lucas.dats: 923(line=71, offs=3) -- 1411(line=90, offs=6)
*/
/*
letpush(beg)
*/
/*
emit_instr: loc0 = /home/ubuntu/workspace/RosettaATS/lucas_lehmer_test/lucas.dats: 941(line=72, offs=15) -- 954(line=72, offs=28)
*/
ATSINSmove(tmp76, mypower_0(ATSPMVi0nt(2), arg0)) ;

/*
emit_instr: loc0 = /home/ubuntu/workspace/RosettaATS/lucas_lehmer_test/lucas.dats: 941(line=72, offs=15) -- 958(line=72, offs=32)
*/
ATSINSmove(tmp75, atspre_g0int_sub_int(tmp76, ATSPMVi0nt(1))) ;

/* (*nothing*) */
/*
emit_instr: loc0 = /home/ubuntu/workspace/RosettaATS/lucas_lehmer_test/lucas.dats: 1011(line=74, offs=14) -- 1031(line=74, offs=34)
*/
ATSINSmove(tmp78, ATSLIB_056_prelude__gte_g1int_int__44__1(ATSPMVcastfn(g1ofg0_int, atstkind_t0ype(atstype_int), tmp75), ATSPMVi0nt(2))) ;

/*
emit_instr: loc0 = /home/ubuntu/workspace/RosettaATS/lucas_lehmer_test/lucas.dats: 1011(line=74, offs=14) -- 1031(line=74, offs=34)
*/
ATSINSmove_void(tmp77, atspre_assert_errmsg_bool1(tmp78, ATSCSTSPmyloc("/home/ubuntu/workspace/RosettaATS/lucas_lehmer_test/lucas.dats: 1011(line=74, offs=14) -- 1031(line=74, offs=34)"))) ;

/*
emit_instr: loc0 = /home/ubuntu/workspace/RosettaATS/lucas_lehmer_test/lucas.dats: 1045(line=75, offs=14) -- 1058(line=75, offs=27)
*/
ATSINSmove(tmp83, is_prime_9(ATSPMVcastfn(g1ofg0_int, atstkind_t0ype(atstype_int), tmp75))) ;

/*
emit_instr: loc0 = /home/ubuntu/workspace/RosettaATS/lucas_lehmer_test/lucas.dats: 1089(line=76, offs=30) -- 1092(line=76, offs=33)
*/
ATSINSmove(tmp90, atspre_g0int_sub_int(arg0, ATSPMVi0nt(1))) ;

/*
emit_instr: loc0 = /home/ubuntu/workspace/RosettaATS/lucas_lehmer_test/lucas.dats: 1083(line=76, offs=24) -- 1093(line=76, offs=34)
*/
ATSINSmove(tmp89, _057_home_057_ubuntu_057_workspace_057_RosettaATS_057_lucas_lehmer_test_057_lucas_056_dats__fun_s(tmp90)) ;

/*
emit_instr: loc0 = /home/ubuntu/workspace/RosettaATS/lucas_lehmer_test/lucas.dats: 1077(line=76, offs=18) -- 1093(line=76, offs=34)
*/
ATSINSmove(tmp88, atspre_g0int_mod_int(tmp75, tmp89)) ;

/*
emit_instr: loc0 = /home/ubuntu/workspace/RosettaATS/lucas_lehmer_test/lucas.dats: 1077(line=76, offs=18) -- 1097(line=76, offs=38)
*/
ATSINSmove(tmp85, ATSLIB_056_prelude__eq_g0int_int__14__2(tmp88, ATSPMVi0nt(0))) ;

/*
emit_instr: loc0 = /home/ubuntu/workspace/RosettaATS/lucas_lehmer_test/lucas.dats: 1074(line=76, offs=15) -- 1118(line=76, offs=59)
*/
ATSif(
tmp85
) ATSthen() {
/*
emit_instr: loc0 = /home/ubuntu/workspace/RosettaATS/lucas_lehmer_test/lucas.dats: 1103(line=76, offs=44) -- 1107(line=76, offs=48)
*/
ATSINSmove(tmp84, ATSPMVbool_true()) ;
} ATSelse() {
/*
emit_instr: loc0 = /home/ubuntu/workspace/RosettaATS/lucas_lehmer_test/lucas.dats: 1113(line=76, offs=54) -- 1118(line=76, offs=59)
*/
ATSINSmove(tmp84, ATSPMVbool_false()) ;
} /* ATSendif */
/*
emit_instr: loc0 = /home/ubuntu/workspace/RosettaATS/lucas_lehmer_test/lucas.dats: 1144(line=77, offs=19) -- 1152(line=77, offs=27)
*/
ATSif(
tmp83
) ATSthen() {
/*
emit_instr: loc0 = /home/ubuntu/workspace/RosettaATS/lucas_lehmer_test/lucas.dats: 1144(line=77, offs=19) -- 1152(line=77, offs=27)
*/
ATSINSmove(tmp92, tmp84) ;
} ATSelse() {
/*
emit_instr: loc0 = /home/ubuntu/workspace/RosettaATS/lucas_lehmer_test/lucas.dats: 1144(line=77, offs=19) -- 1152(line=77, offs=27)
*/
ATSINSmove(tmp92, ATSPMVbool_false()) ;
} /* ATSendif */
/*
emit_instr: loc0 = /home/ubuntu/workspace/RosettaATS/lucas_lehmer_test/lucas.dats: 1141(line=77, offs=16) -- 1173(line=77, offs=48)
*/
ATSif(
tmp92
) ATSthen() {
/*
emit_instr: loc0 = /home/ubuntu/workspace/RosettaATS/lucas_lehmer_test/lucas.dats: 1158(line=77, offs=33) -- 1162(line=77, offs=37)
*/
ATSINSmove(tmp91, ATSPMVbool_true()) ;
} ATSelse() {
/*
emit_instr: loc0 = /home/ubuntu/workspace/RosettaATS/lucas_lehmer_test/lucas.dats: 1168(line=77, offs=43) -- 1173(line=77, offs=48)
*/
ATSINSmove(tmp91, ATSPMVbool_false()) ;
} /* ATSendif */
/*
letpush(end)
*/

/*
emit_instr: loc0 = /home/ubuntu/workspace/RosettaATS/lucas_lehmer_test/lucas.dats: 1322(line=87, offs=5) -- 1373(line=87, offs=56)
*/
ATSif(
tmp91
) ATSthen() {
/*
emit_instr: loc0 = /home/ubuntu/workspace/RosettaATS/lucas_lehmer_test/lucas.dats: 1334(line=87, offs=17) -- 1365(line=87, offs=48)
*/
ATSINSmove_void(tmp94, atspre_print_string(ATSPMVstring("Mersenne Prime: "))) ;

/*
emit_instr: loc0 = /home/ubuntu/workspace/RosettaATS/lucas_lehmer_test/lucas.dats: 1334(line=87, offs=17) -- 1365(line=87, offs=48)
*/
ATSINSmove_void(tmp95, atspre_print_int(arg0)) ;

/*
emit_instr: loc0 = /home/ubuntu/workspace/RosettaATS/lucas_lehmer_test/lucas.dats: 1334(line=87, offs=17) -- 1365(line=87, offs=48)
*/
ATSINSmove_void(tmp93, atspre_print_newline()) ;

} ATSelse() {
/*
emit_instr: loc0 = /home/ubuntu/workspace/RosettaATS/lucas_lehmer_test/lucas.dats: 1371(line=87, offs=54) -- 1373(line=87, offs=56)
*/
ATSINSmove_void(tmp93, ATSPMVempty()) ;
} /* ATSendif */
/*
emit_instr: loc0 = /home/ubuntu/workspace/RosettaATS/lucas_lehmer_test/lucas.dats: 1384(line=88, offs=10) -- 1387(line=88, offs=13)
*/
ATSINSmove(tmp96, atspre_g0int_add_int(arg0, ATSPMVi0nt(1))) ;

/*
emit_instr: loc0 = /home/ubuntu/workspace/RosettaATS/lucas_lehmer_test/lucas.dats: 1379(line=88, offs=5) -- 1400(line=88, offs=26)
*/
ATStailcal_beg()
ATSINSmove_tlcal(apy0, tmp96) ;
ATSINSmove_tlcal(apy1, arg1) ;
ATSINSargmove_tlcal(arg0, apy0) ;
ATSINSargmove_tlcal(arg1, apy1) ;
ATSINSfgoto(__patsflab_test) ;
ATStailcal_end()

/*
emit_instr: loc0 = /home/ubuntu/workspace/RosettaATS/lucas_lehmer_test/lucas.dats: 923(line=71, offs=3) -- 1411(line=90, offs=6)
*/
/*
INSletpop()
*/
} /* ATSendif */
ATSfunbody_end()
ATSreturn_void(tmpret69) ;
} /* end of [_057_home_057_ubuntu_057_workspace_057_RosettaATS_057_lucas_lehmer_test_057_lucas_056_dats__test] */

#if(0)
/*
/home/ubuntu/workspace/ATS2/prelude/DATS/integer.dats: 11750(line=596, offs=3) -- 11790(line=596, offs=43)
*/
/*
local: 
global: gte_g0int_int$41$0(level=0)
local: 
global: 
*/
ATSextern()
/*
imparg = tk(4621)
tmparg = S2Evar(tk(4621))
tmpsub = None()
*/
atstkind_t0ype(atstype_bool)
ATSLIB_056_prelude__gte_g0int_int__41(atstkind_t0ype(atstyvar_type(tk)) arg0, atstkind_t0ype(atstype_int) arg1)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret71, atstkind_t0ype(atstype_bool)) ;
ATStmpdec(tmp72, atstkind_t0ype(atstyvar_type(tk))) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /home/ubuntu/workspace/ATS2/prelude/DATS/integer.dats({$PATSPRE}/DATS/integer.dats): 11734(line=595, offs=1) -- 11790(line=596, offs=43)
*/
ATSINSflab(__patsflab_gte_g0int_int):
/*
emit_instr: loc0 = /home/ubuntu/workspace/ATS2/prelude/DATS/integer.dats({$PATSPRE}/DATS/integer.dats): 11777(line=596, offs=30) -- 11788(line=596, offs=41)
*/
ATSINSmove(tmp72, PMVtmpltcst(g0int2int<S2Eextkind(atstype_int), S2Evar(tk(4621))>)(arg1)) ;

/*
emit_instr: loc0 = /home/ubuntu/workspace/ATS2/prelude/DATS/integer.dats({$PATSPRE}/DATS/integer.dats): 11759(line=596, offs=12) -- 11790(line=596, offs=43)
*/
ATSINSmove(tmpret71, PMVtmpltcst(g0int_gte<S2Evar(tk(4621))>)(arg0, tmp72)) ;

ATSfunbody_end()
ATSreturn(tmpret71) ;
} /* end of [ATSLIB_056_prelude__gte_g0int_int__41] */
#endif // end of [TEMPLATE]

/*
/home/ubuntu/workspace/ATS2/prelude/DATS/integer.dats: 11750(line=596, offs=3) -- 11790(line=596, offs=43)
*/
/*
local: 
global: gte_g0int_int$41$1(level=1)
local: 
global: 
*/
ATSstatic()
/*
imparg = tk(4621)
tmparg = S2Evar(tk(4621))
tmpsub = Some(tk(4621) -> S2Eextkind(atstype_int))
*/
atstkind_t0ype(atstype_bool)
ATSLIB_056_prelude__gte_g0int_int__41__1(atstkind_t0ype(atstype_int) arg0, atstkind_t0ype(atstype_int) arg1)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret71__1, atstkind_t0ype(atstype_bool)) ;
ATStmpdec(tmp72__1, atstkind_t0ype(atstype_int)) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /home/ubuntu/workspace/ATS2/prelude/DATS/integer.dats({$PATSPRE}/DATS/integer.dats): 11734(line=595, offs=1) -- 11790(line=596, offs=43)
*/
ATSINSflab(__patsflab_gte_g0int_int):
/*
emit_instr: loc0 = /home/ubuntu/workspace/ATS2/prelude/DATS/integer.dats({$PATSPRE}/DATS/integer.dats): 11777(line=596, offs=30) -- 11788(line=596, offs=41)
*/
ATSINSmove(tmp72__1, atspre_g0int2int_int_int(arg1)) ;

/*
emit_instr: loc0 = /home/ubuntu/workspace/ATS2/prelude/DATS/integer.dats({$PATSPRE}/DATS/integer.dats): 11759(line=596, offs=12) -- 11790(line=596, offs=43)
*/
ATSINSmove(tmpret71__1, atspre_g0int_gte_int(arg0, tmp72__1)) ;

ATSfunbody_end()
ATSreturn(tmpret71__1) ;
} /* end of [ATSLIB_056_prelude__gte_g0int_int__41__1] */

#if(0)
/*
/home/ubuntu/workspace/ATS2/prelude/DATS/integer.dats: 12329(line=629, offs=3) -- 12369(line=629, offs=43)
*/
/*
local: 
global: gte_g1int_int$44$0(level=0)
local: 
global: 
*/
ATSextern()
/*
imparg = tk(4634)
tmparg = S2Evar(tk(4634))
tmpsub = None()
*/
atstkind_t0ype(atstype_bool)
ATSLIB_056_prelude__gte_g1int_int__44(atstkind_t0ype(atstyvar_type(tk)) arg0, atstkind_t0ype(atstype_int) arg1)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret79, atstkind_t0ype(atstype_bool)) ;
ATStmpdec(tmp80, atstkind_t0ype(atstyvar_type(tk))) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /home/ubuntu/workspace/ATS2/prelude/DATS/integer.dats({$PATSPRE}/DATS/integer.dats): 12313(line=628, offs=1) -- 12369(line=629, offs=43)
*/
ATSINSflab(__patsflab_gte_g1int_int):
/*
emit_instr: loc0 = /home/ubuntu/workspace/ATS2/prelude/DATS/integer.dats({$PATSPRE}/DATS/integer.dats): 12356(line=629, offs=30) -- 12367(line=629, offs=41)
*/
ATSINSmove(tmp80, PMVtmpltcst(g1int2int<S2Eextkind(atstype_int), S2Evar(tk(4634))>)(arg1)) ;

/*
emit_instr: loc0 = /home/ubuntu/workspace/ATS2/prelude/DATS/integer.dats({$PATSPRE}/DATS/integer.dats): 12338(line=629, offs=12) -- 12369(line=629, offs=43)
*/
ATSINSmove(tmpret79, PMVtmpltcst(g1int_gte<S2Evar(tk(4634))>)(arg0, tmp80)) ;

ATSfunbody_end()
ATSreturn(tmpret79) ;
} /* end of [ATSLIB_056_prelude__gte_g1int_int__44] */
#endif // end of [TEMPLATE]

/*
/home/ubuntu/workspace/ATS2/prelude/DATS/integer.dats: 12329(line=629, offs=3) -- 12369(line=629, offs=43)
*/
/*
local: 
global: gte_g1int_int$44$1(level=1)
local: 
global: 
*/
ATSstatic()
/*
imparg = tk(4634)
tmparg = S2Evar(tk(4634))
tmpsub = Some(tk(4634) -> S2Eextkind(atstype_int))
*/
atstkind_t0ype(atstype_bool)
ATSLIB_056_prelude__gte_g1int_int__44__1(atstkind_t0ype(atstype_int) arg0, atstkind_t0ype(atstype_int) arg1)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret79__1, atstkind_t0ype(atstype_bool)) ;
ATStmpdec(tmp80__1, atstkind_t0ype(atstype_int)) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /home/ubuntu/workspace/ATS2/prelude/DATS/integer.dats({$PATSPRE}/DATS/integer.dats): 12313(line=628, offs=1) -- 12369(line=629, offs=43)
*/
ATSINSflab(__patsflab_gte_g1int_int):
/*
emit_instr: loc0 = /home/ubuntu/workspace/ATS2/prelude/DATS/integer.dats({$PATSPRE}/DATS/integer.dats): 12356(line=629, offs=30) -- 12367(line=629, offs=41)
*/
ATSINSmove(tmp80__1, atspre_g1int2int_int_int(arg1)) ;

/*
emit_instr: loc0 = /home/ubuntu/workspace/ATS2/prelude/DATS/integer.dats({$PATSPRE}/DATS/integer.dats): 12338(line=629, offs=12) -- 12369(line=629, offs=43)
*/
ATSINSmove(tmpret79__1, atspre_g1int_gte_int(arg0, tmp80__1)) ;

ATSfunbody_end()
ATSreturn(tmpret79__1) ;
} /* end of [ATSLIB_056_prelude__gte_g1int_int__44__1] */

/*
/home/ubuntu/workspace/ATS2/prelude/DATS/integer.dats: 11831(line=601, offs=3) -- 11870(line=601, offs=42)
*/
/*
local: 
global: eq_g0int_int$14$2(level=1)
local: 
global: 
*/
ATSstatic()
/*
imparg = tk(4622)
tmparg = S2Evar(tk(4622))
tmpsub = Some(tk(4622) -> S2Eextkind(atstype_int))
*/
atstkind_t0ype(atstype_bool)
ATSLIB_056_prelude__eq_g0int_int__14__2(atstkind_t0ype(atstype_int) arg0, atstkind_t0ype(atstype_int) arg1)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret18__2, atstkind_t0ype(atstype_bool)) ;
ATStmpdec(tmp19__2, atstkind_t0ype(atstype_int)) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /home/ubuntu/workspace/ATS2/prelude/DATS/integer.dats({$PATSPRE}/DATS/integer.dats): 11816(line=600, offs=1) -- 11870(line=601, offs=42)
*/
ATSINSflab(__patsflab_eq_g0int_int):
/*
emit_instr: loc0 = /home/ubuntu/workspace/ATS2/prelude/DATS/integer.dats({$PATSPRE}/DATS/integer.dats): 11857(line=601, offs=29) -- 11868(line=601, offs=40)
*/
ATSINSmove(tmp19__2, atspre_g0int2int_int_int(arg1)) ;

/*
emit_instr: loc0 = /home/ubuntu/workspace/ATS2/prelude/DATS/integer.dats({$PATSPRE}/DATS/integer.dats): 11840(line=601, offs=12) -- 11870(line=601, offs=42)
*/
ATSINSmove(tmpret18__2, atspre_g0int_eq_int(arg0, tmp19__2)) ;

ATSfunbody_end()
ATSreturn(tmpret18__2) ;
} /* end of [ATSLIB_056_prelude__eq_g0int_int__14__2] */

/*
/home/ubuntu/workspace/RosettaATS/lucas_lehmer_test/lucas.dats: 1456(line=96, offs=17) -- 1505(line=99, offs=2)
*/
/*
local: 
global: mainats_void_0$48$0(level=0)
local: 
global: 
*/
ATSextern()
atsvoid_t0ype
mainats_void_0()
{
/* tmpvardeclst(beg) */
// ATStmpdec_void(tmpret97) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /home/ubuntu/workspace/RosettaATS/lucas_lehmer_test/lucas.dats: 1450(line=96, offs=11) -- 1505(line=99, offs=2)
*/
ATSINSflab(__patsflab_main_void_0):
/*
emit_instr: loc0 = /home/ubuntu/workspace/RosettaATS/lucas_lehmer_test/lucas.dats: 1465(line=98, offs=3) -- 1477(line=98, offs=15)
*/
ATSINSmove_void(tmpret97, _057_home_057_ubuntu_057_workspace_057_RosettaATS_057_lucas_lehmer_test_057_lucas_056_dats__test(ATSPMVi0nt(3), ATSPMVi0nt(100))) ;

ATSfunbody_end()
ATSreturn_void(tmpret97) ;
} /* end of [mainats_void_0] */

/*
** for initialization(dynloading)
*/
ATSdynloadflag_minit(_057_home_057_ubuntu_057_workspace_057_RosettaATS_057_lucas_lehmer_test_057_lucas_056_dats__dynloadflag) ;
ATSextern()
atsvoid_t0ype
_057_home_057_ubuntu_057_workspace_057_RosettaATS_057_lucas_lehmer_test_057_lucas_056_dats__dynload()
{
ATSfunbody_beg()
ATSdynload(/*void*/)
ATSdynloadflag_sta(
_057_home_057_ubuntu_057_workspace_057_RosettaATS_057_lucas_lehmer_test_057_lucas_056_dats__dynloadflag
) ;
ATSif(
ATSCKiseqz(
_057_home_057_ubuntu_057_workspace_057_RosettaATS_057_lucas_lehmer_test_057_lucas_056_dats__dynloadflag
)
) ATSthen() {
ATSdynloadset(_057_home_057_ubuntu_057_workspace_057_RosettaATS_057_lucas_lehmer_test_057_lucas_056_dats__dynloadflag) ;
/*
dynexnlst-initize(beg)
*/
/*
dynexnlst-initize(end)
*/
} /* ATSendif */
ATSfunbody_end()
ATSreturn_void(tmpret_void) ;
} /* end of [*_dynload] */

/*
** the ATS runtime
*/
#ifndef _ATS_CCOMP_RUNTIME_NONE_
#include "pats_ccomp_runtime.c"
#include "pats_ccomp_runtime_memalloc.c"
#ifndef _ATS_CCOMP_EXCEPTION_NONE_
#include "pats_ccomp_runtime2_dats.c"
#ifndef _ATS_CCOMP_RUNTIME_TRYWITH_NONE_
#include "pats_ccomp_runtime_trywith.c"
#endif /* _ATS_CCOMP_RUNTIME_TRYWITH_NONE_ */
#endif // end of [_ATS_CCOMP_EXCEPTION_NONE_]
#endif /* _ATS_CCOMP_RUNTIME_NONE_ */

/*
** the [main] implementation
*/
int
main
(
int argc, char **argv, char **envp
) {
int err = 0 ;
_057_home_057_ubuntu_057_workspace_057_RosettaATS_057_lucas_lehmer_test_057_lucas_056_dats__dynload() ;
ATSmainats_void_0(err) ;
return (err) ;
} /* end of [main] */

/* ****** ****** */

/* end-of-compilation-unit */
