/*
**
** The C code is generated by [ATS/Postiats-0-2-13]
** The starting compilation time is: 2017-1-4: 23h:16m
**
*/

/*
** include runtime header files
*/
#ifndef _ATS_CCOMP_HEADER_NONE_
#include "pats_ccomp_config.h"
#include "pats_ccomp_basics.h"
#include "pats_ccomp_typedefs.h"
#include "pats_ccomp_instrset.h"
#include "pats_ccomp_memalloc.h"
#ifndef _ATS_CCOMP_EXCEPTION_NONE_
#include "pats_ccomp_memalloca.h"
#include "pats_ccomp_exception.h"
#endif // end of [_ATS_CCOMP_EXCEPTION_NONE_]
#endif /* _ATS_CCOMP_HEADER_NONE_ */


/*
** include prelude cats files
*/
#ifndef _ATS_CCOMP_PRELUDE_NONE_
//
#include "prelude/CATS/basics.cats"
#include "prelude/CATS/integer.cats"
#include "prelude/CATS/pointer.cats"
#include "prelude/CATS/integer_long.cats"
#include "prelude/CATS/integer_size.cats"
#include "prelude/CATS/integer_short.cats"
#include "prelude/CATS/bool.cats"
#include "prelude/CATS/char.cats"
#include "prelude/CATS/float.cats"
#include "prelude/CATS/integer_ptr.cats"
#include "prelude/CATS/integer_fixed.cats"
#include "prelude/CATS/memory.cats"
#include "prelude/CATS/string.cats"
#include "prelude/CATS/strptr.cats"
//
#include "prelude/CATS/fprintf.cats"
//
#include "prelude/CATS/filebas.cats"
//
#include "prelude/CATS/list.cats"
#include "prelude/CATS/option.cats"
#include "prelude/CATS/array.cats"
#include "prelude/CATS/arrayptr.cats"
#include "prelude/CATS/arrayref.cats"
#include "prelude/CATS/matrix.cats"
#include "prelude/CATS/matrixptr.cats"
//
#endif /* _ATS_CCOMP_PRELUDE_NONE_ */
/*
** for user-supplied prelude
*/
#ifdef _ATS_CCOMP_PRELUDE_USER_
//
#include _ATS_CCOMP_PRELUDE_USER_
//
#endif /* _ATS_CCOMP_PRELUDE_USER_ */
/*
** for user2-supplied prelude
*/
#ifdef _ATS_CCOMP_PRELUDE_USER2_
//
#include _ATS_CCOMP_PRELUDE_USER2_
//
#endif /* _ATS_CCOMP_PRELUDE_USER2_ */

/*
staload-prologues(beg)
*/
/*
/home/ubuntu/workspace/ATS2/prelude/DATS/basics.dats: 1534(line=44, offs=1) -- 1573(line=45, offs=32)
*/
/*
/home/ubuntu/workspace/ATS2/prelude/DATS/integer.dats: 1596(line=49, offs=1) -- 1635(line=49, offs=40)
*/
/*
/home/ubuntu/workspace/ATS2/prelude/DATS/pointer.dats: 1533(line=44, offs=1) -- 1572(line=44, offs=40)
*/
/*
/home/ubuntu/workspace/ATS2/prelude/DATS/integer_long.dats: 1602(line=49, offs=1) -- 1641(line=49, offs=40)
*/
/*
/home/ubuntu/workspace/ATS2/prelude/DATS/integer_size.dats: 1597(line=49, offs=1) -- 1636(line=49, offs=40)
*/
/*
/home/ubuntu/workspace/ATS2/prelude/DATS/integer_short.dats: 1603(line=49, offs=1) -- 1642(line=49, offs=40)
*/
/*
/home/ubuntu/workspace/ATS2/prelude/DATS/char.dats: 1610(line=48, offs=1) -- 1649(line=48, offs=40)
*/
/*
/home/ubuntu/workspace/ATS2/prelude/DATS/float.dats: 1636(line=50, offs=1) -- 1675(line=50, offs=40)
*/
/*
/home/ubuntu/workspace/ATS2/prelude/DATS/string.dats: 1609(line=48, offs=1) -- 1648(line=48, offs=40)
*/
/*
/home/ubuntu/workspace/ATS2/prelude/DATS/strptr.dats: 1609(line=48, offs=1) -- 1648(line=48, offs=40)
*/
/*
/home/ubuntu/workspace/ATS2/prelude/DATS/strptr.dats: 1671(line=52, offs=1) -- 1718(line=52, offs=48)
*/
/*
/home/ubuntu/workspace/ATS2/prelude/DATS/integer.dats: 1596(line=49, offs=1) -- 1635(line=49, offs=40)
*/
/*
/home/ubuntu/workspace/ATS2/prelude/DATS/integer_ptr.dats: 1601(line=49, offs=1) -- 1640(line=49, offs=40)
*/
/*
/home/ubuntu/workspace/ATS2/prelude/DATS/integer_fixed.dats: 1603(line=49, offs=1) -- 1642(line=49, offs=40)
*/
/*
/home/ubuntu/workspace/ATS2/prelude/DATS/memory.dats: 1410(line=38, offs=1) -- 1449(line=39, offs=32)
*/
/*
/home/ubuntu/workspace/ATS2/prelude/DATS/filebas.dats: 1613(line=49, offs=1) -- 1652(line=50, offs=32)
*/
/*
/home/ubuntu/workspace/ATS2/prelude/DATS/filebas.dats: 1675(line=54, offs=1) -- 1721(line=55, offs=39)
*/
/*
/home/ubuntu/workspace/ATS2/prelude/DATS/integer.dats: 1596(line=49, offs=1) -- 1635(line=49, offs=40)
*/
/*
/home/ubuntu/workspace/ATS2/prelude/DATS/filebas.dats: 1744(line=59, offs=1) -- 1789(line=60, offs=38)
*/
/*
/home/ubuntu/workspace/ATS2/libats/libc/SATS/stdio.sats: 1390(line=36, offs=1) -- 1437(line=39, offs=3)
*/

#include \
"libats/libc/CATS/stdio.cats"
/*
/home/ubuntu/workspace/ATS2/libats/libc/SATS/stdio.sats: 1950(line=69, offs=1) -- 1999(line=71, offs=34)
*/
/*
/home/ubuntu/workspace/ATS2/libats/libc/SATS/sys/types.sats: 1390(line=36, offs=1) -- 1441(line=39, offs=3)
*/

#include \
"libats/libc/CATS/sys/types.cats"
/*
/home/ubuntu/workspace/ATS2/prelude/DATS/filebas.dats: 1871(line=66, offs=1) -- 1918(line=66, offs=48)
*/
/*
/home/ubuntu/workspace/ATS2/libats/libc/SATS/sys/stat.sats: 1390(line=36, offs=1) -- 1440(line=39, offs=3)
*/

#include \
"libats/libc/CATS/sys/stat.cats"
/*
/home/ubuntu/workspace/ATS2/libats/libc/SATS/sys/stat.sats: 1756(line=58, offs=1) -- 1805(line=60, offs=34)
*/
/*
/home/ubuntu/workspace/ATS2/libats/libc/SATS/sys/types.sats: 1390(line=36, offs=1) -- 1441(line=39, offs=3)
*/

#include \
"libats/libc/CATS/sys/types.cats"
/*
/home/ubuntu/workspace/ATS2/prelude/DATS/filebas.dats: 15413(line=857, offs=1) -- 15450(line=858, offs=30)
*/
/*
/home/ubuntu/workspace/ATS2/libats/libc/SATS/stdio.sats: 1390(line=36, offs=1) -- 1437(line=39, offs=3)
*/

#include \
"libats/libc/CATS/stdio.cats"
/*
/home/ubuntu/workspace/ATS2/libats/libc/SATS/stdio.sats: 1950(line=69, offs=1) -- 1999(line=71, offs=34)
*/
/*
/home/ubuntu/workspace/ATS2/libats/libc/SATS/sys/types.sats: 1390(line=36, offs=1) -- 1441(line=39, offs=3)
*/

#include \
"libats/libc/CATS/sys/types.cats"
/*
/home/ubuntu/workspace/ATS2/prelude/DATS/list.dats: 1529(line=44, offs=1) -- 1568(line=45, offs=32)
*/
/*
/home/ubuntu/workspace/ATS2/prelude/DATS/list.dats: 1569(line=46, offs=1) -- 1615(line=47, offs=39)
*/
/*
/home/ubuntu/workspace/ATS2/prelude/DATS/unsafe.dats: 1532(line=44, offs=1) -- 1566(line=44, offs=35)
*/
/*
/home/ubuntu/workspace/ATS2/prelude/DATS/list_vt.dats: 1538(line=44, offs=1) -- 1577(line=45, offs=32)
*/
/*
/home/ubuntu/workspace/ATS2/prelude/DATS/list_vt.dats: 1578(line=46, offs=1) -- 1624(line=47, offs=39)
*/
/*
/home/ubuntu/workspace/ATS2/prelude/DATS/unsafe.dats: 1532(line=44, offs=1) -- 1566(line=44, offs=35)
*/
/*
/home/ubuntu/workspace/ATS2/prelude/DATS/array.dats: 1534(line=44, offs=1) -- 1573(line=44, offs=40)
*/
/*
/home/ubuntu/workspace/ATS2/prelude/DATS/array.dats: 1574(line=45, offs=1) -- 1616(line=45, offs=43)
*/
/*
/home/ubuntu/workspace/ATS2/prelude/DATS/arrayptr.dats: 1532(line=44, offs=1) -- 1571(line=44, offs=40)
*/
/*
/home/ubuntu/workspace/ATS2/prelude/DATS/arrayref.dats: 1532(line=44, offs=1) -- 1571(line=44, offs=40)
*/
/*
/home/ubuntu/workspace/ATS2/prelude/DATS/matrix.dats: 1535(line=44, offs=1) -- 1574(line=44, offs=40)
*/
/*
/home/ubuntu/workspace/ATS2/prelude/DATS/matrixptr.dats: 1538(line=44, offs=1) -- 1577(line=44, offs=40)
*/
/*
/home/ubuntu/workspace/ATS2/prelude/DATS/matrixref.dats: 1538(line=44, offs=1) -- 1577(line=44, offs=40)
*/
/*
/home/ubuntu/workspace/ATS2/prelude/DATS/stream.dats: 1523(line=44, offs=1) -- 1562(line=44, offs=40)
*/
/*
/home/ubuntu/workspace/ATS2/prelude/DATS/stream_vt.dats: 1523(line=44, offs=1) -- 1562(line=44, offs=40)
*/
/*
/home/ubuntu/workspace/ATS2/prelude/DATS/tostring.dats: 1528(line=44, offs=1) -- 1567(line=45, offs=32)
*/
/*
/home/ubuntu/workspace/ATS2/prelude/DATS/unsafe.dats: 1532(line=44, offs=1) -- 1566(line=44, offs=35)
*/
/*
/home/ubuntu/workspace/ATS2/prelude/DATS/checkast.dats: 1531(line=44, offs=1) -- 1570(line=45, offs=32)
*/
/*
staload-prologues(end)
*/
/*
typedefs-for-tyrecs-and-tysums(beg)
*/
/*
typedefs-for-tyrecs-and-tysums(end)
*/
/*
dynconlst-declaration(beg)
*/
/*
dynconlst-declaration(end)
*/
/*
dyncstlst-declaration(beg)
*/
ATSdyncst_mac(atspre_g0int2int_int_int)
ATSdyncst_mac(atspre_g0int_eq_int)
ATSdyncst_mac(atspre_g0int_div_int)
ATSdyncst_mac(atspre_g0int_add_int)
ATSdyncst_mac(atspre_g0int_mod_int)
ATSdyncst_extfun(_057_home_057_ubuntu_057_workspace_057_RosettaATS_057_harshad_niven_057_harshad_056_dats__dsum, (atstkind_t0ype(atstype_int)), atstkind_t0ype(atstype_int)) ;
ATSdyncst_mac(atspre_g0int_gt_int)
ATSdyncst_extfun(_057_home_057_ubuntu_057_workspace_057_RosettaATS_057_harshad_niven_057_harshad_056_dats__is_harshad, (atstkind_t0ype(atstype_int)), atstkind_t0ype(atstype_bool)) ;
ATSdyncst_mac(atspre_print_string)
ATSdyncst_mac(atspre_print_int)
ATSdyncst_mac(atspre_print_newline)
/*
dyncstlst-declaration(end)
*/
/*
dynvalist-implementation(beg)
*/
/*
dynvalist-implementation(end)
*/
/*
exnconlst-declaration(beg)
*/
#ifndef _ATS_CCOMP_EXCEPTION_NONE_
ATSextern()
atsvoid_t0ype
the_atsexncon_initize
(
  atstype_exnconptr d2c, atstype_string exnmsg
) ;
#endif // end of [_ATS_CCOMP_EXCEPTION_NONE_]
/*
exnconlst-declaration(end)
*/
/*
assumelst-declaration(beg)
*/
/*
assumelst-declaration(end)
*/
/*
extypelst-declaration(beg)
*/
/*
extypelst-declaration(end)
*/
#if(0)
ATSextern()
atstkind_t0ype(atstype_int)
_057_home_057_ubuntu_057_workspace_057_RosettaATS_057_harshad_niven_057_harshad_056_dats__dsum(atstkind_t0ype(atstype_int)) ;
#endif // end of [QUALIFIED]

ATSstatic()
atstkind_t0ype(atstype_int)
loop_1(atstkind_t0ype(atstype_int), atstkind_t0ype(atstype_int)) ;

#if(0)
#if(0)
ATSextern()
atstkind_t0ype(atstype_bool)
ATSLIB_056_prelude__eq_g0int_int__2(atstkind_t0ype(atstyvar_type(tk)), atstkind_t0ype(atstype_int)) ;
#endif // end of [QUALIFIED]
#endif // end of [TEMPLATE]

ATSstatic()
atstkind_t0ype(atstype_bool)
ATSLIB_056_prelude__eq_g0int_int__2__1(atstkind_t0ype(atstype_int), atstkind_t0ype(atstype_int)) ;

#if(0)
ATSextern()
atstkind_t0ype(atstype_bool)
_057_home_057_ubuntu_057_workspace_057_RosettaATS_057_harshad_niven_057_harshad_056_dats__is_harshad(atstkind_t0ype(atstype_int)) ;
#endif // end of [QUALIFIED]

ATSstatic()
atstkind_t0ype(atstype_bool)
ATSLIB_056_prelude__eq_g0int_int__2__2(atstkind_t0ype(atstype_int), atstkind_t0ype(atstype_int)) ;

#if(0)
ATSextern()
atsvoid_t0ype
mainats_void_0() ;
#endif // end of [QUALIFIED]

ATSstatic()
atsvoid_t0ype
loop_12(atstkind_t0ype(atstype_int), atstkind_t0ype(atstype_int), atstkind_t0ype(atstype_int)) ;

#if(0)
#if(0)
ATSextern()
atstkind_t0ype(atstype_bool)
ATSLIB_056_prelude__gt_g0int_int__13(atstkind_t0ype(atstyvar_type(tk)), atstkind_t0ype(atstype_int)) ;
#endif // end of [QUALIFIED]
#endif // end of [TEMPLATE]

ATSstatic()
atstkind_t0ype(atstype_bool)
ATSLIB_056_prelude__gt_g0int_int__13__1(atstkind_t0ype(atstype_int), atstkind_t0ype(atstype_int)) ;

/*
/home/ubuntu/workspace/RosettaATS/harshad_niven/harshad.dats: 229(line=21, offs=5) -- 376(line=32, offs=4)
*/
/*
local: 
global: dsum$0$0(level=0)
local: 
global: 
*/
ATSextern()
atstkind_t0ype(atstype_int)
_057_home_057_ubuntu_057_workspace_057_RosettaATS_057_harshad_niven_057_harshad_056_dats__dsum(atstkind_t0ype(atstype_int) arg0)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret0, atstkind_t0ype(atstype_int)) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /home/ubuntu/workspace/RosettaATS/harshad_niven/harshad.dats: 225(line=21, offs=1) -- 376(line=32, offs=4)
*/
ATSINSflab(__patsflab_dsum):
/*
emit_instr: loc0 = /home/ubuntu/workspace/RosettaATS/harshad_niven/harshad.dats: 238(line=22, offs=1) -- 376(line=32, offs=4)
*/
/*
letpush(beg)
*/
/*
letpush(end)
*/

/*
emit_instr: loc0 = /home/ubuntu/workspace/RosettaATS/harshad_niven/harshad.dats: 360(line=31, offs=3) -- 372(line=31, offs=15)
*/
ATSINSmove(tmpret0, loop_1(arg0, ATSPMVi0nt(0))) ;

/*
emit_instr: loc0 = /home/ubuntu/workspace/RosettaATS/harshad_niven/harshad.dats: 238(line=22, offs=1) -- 376(line=32, offs=4)
*/
/*
INSletpop()
*/
ATSfunbody_end()
ATSreturn(tmpret0) ;
} /* end of [_057_home_057_ubuntu_057_workspace_057_RosettaATS_057_harshad_niven_057_harshad_056_dats__dsum] */

/*
/home/ubuntu/workspace/RosettaATS/harshad_niven/harshad.dats: 249(line=24, offs=7) -- 352(line=28, offs=4)
*/
/*
local: loop_1$0(level=1)
global: loop_1$0(level=1)
local: 
global: 
*/
ATSstatic()
atstkind_t0ype(atstype_int)
loop_1(atstkind_t0ype(atstype_int) arg0, atstkind_t0ype(atstype_int) arg1)
{
/* tmpvardeclst(beg) */
ATStmpdec(apy0, atstkind_t0ype(atstype_int)) ;
ATStmpdec(apy1, atstkind_t0ype(atstype_int)) ;
ATStmpdec(tmpret1, atstkind_t0ype(atstype_int)) ;
ATStmpdec(tmp2, atstkind_t0ype(atstype_bool)) ;
ATStmpdec(tmp7, atstkind_t0ype(atstype_int)) ;
ATStmpdec(tmp8, atstkind_t0ype(atstype_int)) ;
ATStmpdec(tmp9, atstkind_t0ype(atstype_int)) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /home/ubuntu/workspace/RosettaATS/harshad_niven/harshad.dats: 249(line=24, offs=7) -- 352(line=28, offs=4)
*/
ATSINSflab(__patsflab_loop_1):
/*
emit_instr: loc0 = /home/ubuntu/workspace/RosettaATS/harshad_niven/harshad.dats: 292(line=26, offs=8) -- 299(line=26, offs=15)
*/
ATSINSmove(tmp2, ATSLIB_056_prelude__eq_g0int_int__2__1(arg0, ATSPMVi0nt(0))) ;

/*
emit_instr: loc0 = /home/ubuntu/workspace/RosettaATS/harshad_niven/harshad.dats: 289(line=26, offs=5) -- 348(line=27, offs=40)
*/
ATSif(
tmp2
) ATSthen() {
/*
emit_instr: loc0 = /home/ubuntu/workspace/RosettaATS/harshad_niven/harshad.dats: 305(line=26, offs=21) -- 308(line=26, offs=24)
*/
ATSINSmove(tmpret1, arg1) ;
} ATSelse() {
/*
emit_instr: loc0 = /home/ubuntu/workspace/RosettaATS/harshad_niven/harshad.dats: 323(line=27, offs=15) -- 331(line=27, offs=23)
*/
ATSINSmove(tmp7, atspre_g0int_div_int(arg0, ATSPMVi0nt(10))) ;

/*
emit_instr: loc0 = /home/ubuntu/workspace/RosettaATS/harshad_niven/harshad.dats: 339(line=27, offs=31) -- 347(line=27, offs=39)
*/
ATSINSmove(tmp9, atspre_g0int_mod_int(arg0, ATSPMVi0nt(10))) ;

/*
emit_instr: loc0 = /home/ubuntu/workspace/RosettaATS/harshad_niven/harshad.dats: 333(line=27, offs=25) -- 347(line=27, offs=39)
*/
ATSINSmove(tmp8, atspre_g0int_add_int(arg1, tmp9)) ;

/*
emit_instr: loc0 = /home/ubuntu/workspace/RosettaATS/harshad_niven/harshad.dats: 318(line=27, offs=10) -- 348(line=27, offs=40)
*/
ATStailcal_beg()
ATSINSmove_tlcal(apy0, tmp7) ;
ATSINSmove_tlcal(apy1, tmp8) ;
ATSINSargmove_tlcal(arg0, apy0) ;
ATSINSargmove_tlcal(arg1, apy1) ;
ATSINSfgoto(__patsflab_loop_1) ;
ATStailcal_end()

} /* ATSendif */
ATSfunbody_end()
ATSreturn(tmpret1) ;
} /* end of [loop_1] */

#if(0)
/*
/home/ubuntu/workspace/ATS2/prelude/DATS/integer.dats: 11831(line=601, offs=3) -- 11870(line=601, offs=42)
*/
/*
local: 
global: eq_g0int_int$2$0(level=0)
local: 
global: 
*/
ATSextern()
/*
imparg = tk(4622)
tmparg = S2Evar(tk(4622))
tmpsub = None()
*/
atstkind_t0ype(atstype_bool)
ATSLIB_056_prelude__eq_g0int_int__2(atstkind_t0ype(atstyvar_type(tk)) arg0, atstkind_t0ype(atstype_int) arg1)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret3, atstkind_t0ype(atstype_bool)) ;
ATStmpdec(tmp4, atstkind_t0ype(atstyvar_type(tk))) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /home/ubuntu/workspace/ATS2/prelude/DATS/integer.dats({$PATSPRE}/DATS/integer.dats): 11816(line=600, offs=1) -- 11870(line=601, offs=42)
*/
ATSINSflab(__patsflab_eq_g0int_int):
/*
emit_instr: loc0 = /home/ubuntu/workspace/ATS2/prelude/DATS/integer.dats({$PATSPRE}/DATS/integer.dats): 11857(line=601, offs=29) -- 11868(line=601, offs=40)
*/
ATSINSmove(tmp4, PMVtmpltcst(g0int2int<S2Eextkind(atstype_int), S2Evar(tk(4622))>)(arg1)) ;

/*
emit_instr: loc0 = /home/ubuntu/workspace/ATS2/prelude/DATS/integer.dats({$PATSPRE}/DATS/integer.dats): 11840(line=601, offs=12) -- 11870(line=601, offs=42)
*/
ATSINSmove(tmpret3, PMVtmpltcst(g0int_eq<S2Evar(tk(4622))>)(arg0, tmp4)) ;

ATSfunbody_end()
ATSreturn(tmpret3) ;
} /* end of [ATSLIB_056_prelude__eq_g0int_int__2] */
#endif // end of [TEMPLATE]

/*
/home/ubuntu/workspace/ATS2/prelude/DATS/integer.dats: 11831(line=601, offs=3) -- 11870(line=601, offs=42)
*/
/*
local: 
global: eq_g0int_int$2$1(level=2)
local: 
global: 
*/
ATSstatic()
/*
imparg = tk(4622)
tmparg = S2Evar(tk(4622))
tmpsub = Some(tk(4622) -> S2Eextkind(atstype_int))
*/
atstkind_t0ype(atstype_bool)
ATSLIB_056_prelude__eq_g0int_int__2__1(atstkind_t0ype(atstype_int) arg0, atstkind_t0ype(atstype_int) arg1)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret3__1, atstkind_t0ype(atstype_bool)) ;
ATStmpdec(tmp4__1, atstkind_t0ype(atstype_int)) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /home/ubuntu/workspace/ATS2/prelude/DATS/integer.dats({$PATSPRE}/DATS/integer.dats): 11816(line=600, offs=1) -- 11870(line=601, offs=42)
*/
ATSINSflab(__patsflab_eq_g0int_int):
/*
emit_instr: loc0 = /home/ubuntu/workspace/ATS2/prelude/DATS/integer.dats({$PATSPRE}/DATS/integer.dats): 11857(line=601, offs=29) -- 11868(line=601, offs=40)
*/
ATSINSmove(tmp4__1, atspre_g0int2int_int_int(arg1)) ;

/*
emit_instr: loc0 = /home/ubuntu/workspace/ATS2/prelude/DATS/integer.dats({$PATSPRE}/DATS/integer.dats): 11840(line=601, offs=12) -- 11870(line=601, offs=42)
*/
ATSINSmove(tmpret3__1, atspre_g0int_eq_int(arg0, tmp4__1)) ;

ATSfunbody_end()
ATSreturn(tmpret3__1) ;
} /* end of [ATSLIB_056_prelude__eq_g0int_int__2__1] */

/*
/home/ubuntu/workspace/RosettaATS/harshad_niven/harshad.dats: 419(line=37, offs=11) -- 483(line=41, offs=2)
*/
/*
local: 
global: is_harshad$9$0(level=0)
local: 
global: 
*/
ATSextern()
atstkind_t0ype(atstype_bool)
_057_home_057_ubuntu_057_workspace_057_RosettaATS_057_harshad_niven_057_harshad_056_dats__is_harshad(atstkind_t0ype(atstype_int) arg0)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret10, atstkind_t0ype(atstype_bool)) ;
ATStmpdec(tmp11, atstkind_t0ype(atstype_bool)) ;
ATStmpdec(tmp14, atstkind_t0ype(atstype_int)) ;
ATStmpdec(tmp15, atstkind_t0ype(atstype_int)) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /home/ubuntu/workspace/RosettaATS/harshad_niven/harshad.dats: 409(line=37, offs=1) -- 483(line=41, offs=2)
*/
ATSINSflab(__patsflab_is_harshad):
/*
emit_instr: loc0 = /home/ubuntu/workspace/RosettaATS/harshad_niven/harshad.dats: 445(line=39, offs=12) -- 453(line=39, offs=20)
*/
ATSINSmove(tmp15, _057_home_057_ubuntu_057_workspace_057_RosettaATS_057_harshad_niven_057_harshad_056_dats__dsum(arg0)) ;

/*
emit_instr: loc0 = /home/ubuntu/workspace/RosettaATS/harshad_niven/harshad.dats: 439(line=39, offs=6) -- 453(line=39, offs=20)
*/
ATSINSmove(tmp14, atspre_g0int_mod_int(arg0, tmp15)) ;

/*
emit_instr: loc0 = /home/ubuntu/workspace/RosettaATS/harshad_niven/harshad.dats: 439(line=39, offs=6) -- 458(line=39, offs=25)
*/
ATSINSmove(tmp11, ATSLIB_056_prelude__eq_g0int_int__2__2(tmp14, ATSPMVi0nt(0))) ;

/*
emit_instr: loc0 = /home/ubuntu/workspace/RosettaATS/harshad_niven/harshad.dats: 436(line=39, offs=3) -- 481(line=40, offs=13)
*/
ATSif(
tmp11
) ATSthen() {
/*
emit_instr: loc0 = /home/ubuntu/workspace/RosettaATS/harshad_niven/harshad.dats: 464(line=39, offs=31) -- 468(line=39, offs=35)
*/
ATSINSmove(tmpret10, ATSPMVbool_true()) ;
} ATSelse() {
/*
emit_instr: loc0 = /home/ubuntu/workspace/RosettaATS/harshad_niven/harshad.dats: 476(line=40, offs=8) -- 481(line=40, offs=13)
*/
ATSINSmove(tmpret10, ATSPMVbool_false()) ;
} /* ATSendif */
ATSfunbody_end()
ATSreturn(tmpret10) ;
} /* end of [_057_home_057_ubuntu_057_workspace_057_RosettaATS_057_harshad_niven_057_harshad_056_dats__is_harshad] */

/*
/home/ubuntu/workspace/ATS2/prelude/DATS/integer.dats: 11831(line=601, offs=3) -- 11870(line=601, offs=42)
*/
/*
local: 
global: eq_g0int_int$2$2(level=1)
local: 
global: 
*/
ATSstatic()
/*
imparg = tk(4622)
tmparg = S2Evar(tk(4622))
tmpsub = Some(tk(4622) -> S2Eextkind(atstype_int))
*/
atstkind_t0ype(atstype_bool)
ATSLIB_056_prelude__eq_g0int_int__2__2(atstkind_t0ype(atstype_int) arg0, atstkind_t0ype(atstype_int) arg1)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret3__2, atstkind_t0ype(atstype_bool)) ;
ATStmpdec(tmp4__2, atstkind_t0ype(atstype_int)) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /home/ubuntu/workspace/ATS2/prelude/DATS/integer.dats({$PATSPRE}/DATS/integer.dats): 11816(line=600, offs=1) -- 11870(line=601, offs=42)
*/
ATSINSflab(__patsflab_eq_g0int_int):
/*
emit_instr: loc0 = /home/ubuntu/workspace/ATS2/prelude/DATS/integer.dats({$PATSPRE}/DATS/integer.dats): 11857(line=601, offs=29) -- 11868(line=601, offs=40)
*/
ATSINSmove(tmp4__2, atspre_g0int2int_int_int(arg1)) ;

/*
emit_instr: loc0 = /home/ubuntu/workspace/ATS2/prelude/DATS/integer.dats({$PATSPRE}/DATS/integer.dats): 11840(line=601, offs=12) -- 11870(line=601, offs=42)
*/
ATSINSmove(tmpret3__2, atspre_g0int_eq_int(arg0, tmp4__2)) ;

ATSfunbody_end()
ATSreturn(tmpret3__2) ;
} /* end of [ATSLIB_056_prelude__eq_g0int_int__2__2] */

/*
/home/ubuntu/workspace/RosettaATS/harshad_niven/harshad.dats: 522(line=45, offs=17) -- 972(line=69, offs=2)
*/
/*
local: 
global: mainats_void_0$11$0(level=0)
local: 
global: 
*/
ATSextern()
atsvoid_t0ype
mainats_void_0()
{
/* tmpvardeclst(beg) */
// ATStmpdec_void(tmpret16) ;
// ATStmpdec_void(tmp32) ;
// ATStmpdec_void(tmp33) ;
// ATStmpdec_void(tmp34) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /home/ubuntu/workspace/RosettaATS/harshad_niven/harshad.dats: 516(line=45, offs=11) -- 972(line=69, offs=2)
*/
ATSINSflab(__patsflab_main_void_0):
/*
emit_instr: loc0 = /home/ubuntu/workspace/RosettaATS/harshad_niven/harshad.dats: 531(line=47, offs=3) -- 970(line=68, offs=6)
*/
/*
letpush(beg)
*/
/*
letpush(end)
*/

/*
emit_instr: loc0 = /home/ubuntu/workspace/RosettaATS/harshad_niven/harshad.dats: 883(line=65, offs=5) -- 897(line=65, offs=19)
*/
ATSINSmove_void(tmp32, loop_12(ATSPMVi0nt(20), ATSPMVi0nt(1), ATSPMVi0nt(1))) ;

/*
emit_instr: loc0 = /home/ubuntu/workspace/RosettaATS/harshad_niven/harshad.dats: 903(line=66, offs=5) -- 941(line=66, offs=43)
*/
ATSINSmove_void(tmp33, atspre_print_string(ATSPMVstring("--------------------------"))) ;

/*
emit_instr: loc0 = /home/ubuntu/workspace/RosettaATS/harshad_niven/harshad.dats: 903(line=66, offs=5) -- 941(line=66, offs=43)
*/
ATSINSmove_void(tmp34, atspre_print_newline()) ;

/*
emit_instr: loc0 = /home/ubuntu/workspace/RosettaATS/harshad_niven/harshad.dats: 947(line=67, offs=5) -- 963(line=67, offs=21)
*/
ATSINSmove_void(tmpret16, loop_12(ATSPMVi0nt(1), ATSPMVi0nt(1), ATSPMVi0nt(1001))) ;

/*
emit_instr: loc0 = /home/ubuntu/workspace/RosettaATS/harshad_niven/harshad.dats: 531(line=47, offs=3) -- 970(line=68, offs=6)
*/
/*
INSletpop()
*/
ATSfunbody_end()
ATSreturn_void(tmpret16) ;
} /* end of [mainats_void_0] */

/*
/home/ubuntu/workspace/RosettaATS/harshad_niven/harshad.dats: 544(line=48, offs=9) -- 873(line=63, offs=6)
*/
/*
local: loop_12$0(level=1)
global: loop_12$0(level=1)
local: 
global: 
*/
ATSstatic()
atsvoid_t0ype
loop_12(atstkind_t0ype(atstype_int) arg0, atstkind_t0ype(atstype_int) arg1, atstkind_t0ype(atstype_int) arg2)
{
/* tmpvardeclst(beg) */
ATStmpdec(apy0, atstkind_t0ype(atstype_int)) ;
ATStmpdec(apy1, atstkind_t0ype(atstype_int)) ;
ATStmpdec(apy2, atstkind_t0ype(atstype_int)) ;
// ATStmpdec_void(tmpret17) ;
ATStmpdec(tmp18, atstkind_t0ype(atstype_bool)) ;
ATStmpdec(tmp23, atstkind_t0ype(atstype_bool)) ;
// ATStmpdec_void(tmp24) ;
// ATStmpdec_void(tmp25) ;
// ATStmpdec_void(tmp26) ;
// ATStmpdec_void(tmp27) ;
// ATStmpdec_void(tmp28) ;
ATStmpdec(tmp29, atstkind_t0ype(atstype_int)) ;
ATStmpdec(tmp30, atstkind_t0ype(atstype_int)) ;
ATStmpdec(tmp31, atstkind_t0ype(atstype_int)) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /home/ubuntu/workspace/RosettaATS/harshad_niven/harshad.dats: 544(line=48, offs=9) -- 873(line=63, offs=6)
*/
ATSINSflab(__patsflab_loop_12):
/*
emit_instr: loc0 = /home/ubuntu/workspace/RosettaATS/harshad_niven/harshad.dats: 602(line=50, offs=10) -- 614(line=50, offs=22)
*/
ATSINSmove(tmp18, ATSLIB_056_prelude__gt_g0int_int__13__1(arg1, arg0)) ;

/*
emit_instr: loc0 = /home/ubuntu/workspace/RosettaATS/harshad_niven/harshad.dats: 599(line=50, offs=7) -- 867(line=62, offs=8)
*/
ATSif(
tmp18
) ATSthen() {
/*
emit_instr: loc0 = /home/ubuntu/workspace/RosettaATS/harshad_niven/harshad.dats: 620(line=50, offs=28) -- 622(line=50, offs=30)
*/
ATSINSmove_void(tmpret17, ATSPMVempty()) ;
} ATSelse() {
/*
emit_instr: loc0 = /home/ubuntu/workspace/RosettaATS/harshad_niven/harshad.dats: 653(line=53, offs=12) -- 667(line=53, offs=26)
*/
ATSINSmove(tmp23, _057_home_057_ubuntu_057_workspace_057_RosettaATS_057_harshad_niven_057_harshad_056_dats__is_harshad(arg2)) ;

/*
emit_instr: loc0 = /home/ubuntu/workspace/RosettaATS/harshad_niven/harshad.dats: 650(line=53, offs=9) -- 859(line=61, offs=10)
*/
ATSif(
tmp23
) ATSthen() {
/*
emit_instr: loc0 = /home/ubuntu/workspace/RosettaATS/harshad_niven/harshad.dats: 694(line=55, offs=11) -- 741(line=55, offs=58)
*/
ATSINSmove_void(tmp24, atspre_print_string(ATSPMVstring("Harshad number No."))) ;

/*
emit_instr: loc0 = /home/ubuntu/workspace/RosettaATS/harshad_niven/harshad.dats: 694(line=55, offs=11) -- 741(line=55, offs=58)
*/
ATSINSmove_void(tmp25, atspre_print_int(arg1)) ;

/*
emit_instr: loc0 = /home/ubuntu/workspace/RosettaATS/harshad_niven/harshad.dats: 694(line=55, offs=11) -- 741(line=55, offs=58)
*/
ATSINSmove_void(tmp26, atspre_print_string(ATSPMVstring(": "))) ;

/*
emit_instr: loc0 = /home/ubuntu/workspace/RosettaATS/harshad_niven/harshad.dats: 694(line=55, offs=11) -- 741(line=55, offs=58)
*/
ATSINSmove_void(tmp27, atspre_print_int(arg2)) ;

/*
emit_instr: loc0 = /home/ubuntu/workspace/RosettaATS/harshad_niven/harshad.dats: 694(line=55, offs=11) -- 741(line=55, offs=58)
*/
ATSINSmove_void(tmp28, atspre_print_newline()) ;

/*
emit_instr: loc0 = /home/ubuntu/workspace/RosettaATS/harshad_niven/harshad.dats: 765(line=56, offs=23) -- 771(line=56, offs=29)
*/
ATSINSmove(tmp29, atspre_g0int_add_int(arg1, ATSPMVi0nt(1))) ;

/*
emit_instr: loc0 = /home/ubuntu/workspace/RosettaATS/harshad_niven/harshad.dats: 773(line=56, offs=31) -- 778(line=56, offs=36)
*/
ATSINSmove(tmp30, atspre_g0int_add_int(arg2, ATSPMVi0nt(1))) ;

/*
emit_instr: loc0 = /home/ubuntu/workspace/RosettaATS/harshad_niven/harshad.dats: 753(line=56, offs=11) -- 779(line=56, offs=37)
*/
ATStailcal_beg()
ATSINSmove_tlcal(apy0, arg0) ;
ATSINSmove_tlcal(apy1, tmp29) ;
ATSINSmove_tlcal(apy2, tmp30) ;
ATSINSargmove_tlcal(arg0, apy0) ;
ATSINSargmove_tlcal(arg1, apy1) ;
ATSINSargmove_tlcal(arg2, apy2) ;
ATSINSfgoto(__patsflab_loop_12) ;
ATStailcal_end()

} ATSelse() {
/*
emit_instr: loc0 = /home/ubuntu/workspace/RosettaATS/harshad_niven/harshad.dats: 843(line=60, offs=29) -- 848(line=60, offs=34)
*/
ATSINSmove(tmp31, atspre_g0int_add_int(arg2, ATSPMVi0nt(1))) ;

/*
emit_instr: loc0 = /home/ubuntu/workspace/RosettaATS/harshad_niven/harshad.dats: 825(line=60, offs=11) -- 849(line=60, offs=35)
*/
ATStailcal_beg()
ATSINSmove_tlcal(apy0, arg0) ;
ATSINSmove_tlcal(apy1, arg1) ;
ATSINSmove_tlcal(apy2, tmp31) ;
ATSINSargmove_tlcal(arg0, apy0) ;
ATSINSargmove_tlcal(arg1, apy1) ;
ATSINSargmove_tlcal(arg2, apy2) ;
ATSINSfgoto(__patsflab_loop_12) ;
ATStailcal_end()

} /* ATSendif */
} /* ATSendif */
ATSfunbody_end()
ATSreturn_void(tmpret17) ;
} /* end of [loop_12] */

#if(0)
/*
/home/ubuntu/workspace/ATS2/prelude/DATS/integer.dats: 11672(line=592, offs=3) -- 11711(line=592, offs=42)
*/
/*
local: 
global: gt_g0int_int$13$0(level=0)
local: 
global: 
*/
ATSextern()
/*
imparg = tk(4620)
tmparg = S2Evar(tk(4620))
tmpsub = None()
*/
atstkind_t0ype(atstype_bool)
ATSLIB_056_prelude__gt_g0int_int__13(atstkind_t0ype(atstyvar_type(tk)) arg0, atstkind_t0ype(atstype_int) arg1)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret19, atstkind_t0ype(atstype_bool)) ;
ATStmpdec(tmp20, atstkind_t0ype(atstyvar_type(tk))) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /home/ubuntu/workspace/ATS2/prelude/DATS/integer.dats({$PATSPRE}/DATS/integer.dats): 11657(line=591, offs=1) -- 11711(line=592, offs=42)
*/
ATSINSflab(__patsflab_gt_g0int_int):
/*
emit_instr: loc0 = /home/ubuntu/workspace/ATS2/prelude/DATS/integer.dats({$PATSPRE}/DATS/integer.dats): 11698(line=592, offs=29) -- 11709(line=592, offs=40)
*/
ATSINSmove(tmp20, PMVtmpltcst(g0int2int<S2Eextkind(atstype_int), S2Evar(tk(4620))>)(arg1)) ;

/*
emit_instr: loc0 = /home/ubuntu/workspace/ATS2/prelude/DATS/integer.dats({$PATSPRE}/DATS/integer.dats): 11681(line=592, offs=12) -- 11711(line=592, offs=42)
*/
ATSINSmove(tmpret19, PMVtmpltcst(g0int_gt<S2Evar(tk(4620))>)(arg0, tmp20)) ;

ATSfunbody_end()
ATSreturn(tmpret19) ;
} /* end of [ATSLIB_056_prelude__gt_g0int_int__13] */
#endif // end of [TEMPLATE]

/*
/home/ubuntu/workspace/ATS2/prelude/DATS/integer.dats: 11672(line=592, offs=3) -- 11711(line=592, offs=42)
*/
/*
local: 
global: gt_g0int_int$13$1(level=2)
local: 
global: 
*/
ATSstatic()
/*
imparg = tk(4620)
tmparg = S2Evar(tk(4620))
tmpsub = Some(tk(4620) -> S2Eextkind(atstype_int))
*/
atstkind_t0ype(atstype_bool)
ATSLIB_056_prelude__gt_g0int_int__13__1(atstkind_t0ype(atstype_int) arg0, atstkind_t0ype(atstype_int) arg1)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret19__1, atstkind_t0ype(atstype_bool)) ;
ATStmpdec(tmp20__1, atstkind_t0ype(atstype_int)) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /home/ubuntu/workspace/ATS2/prelude/DATS/integer.dats({$PATSPRE}/DATS/integer.dats): 11657(line=591, offs=1) -- 11711(line=592, offs=42)
*/
ATSINSflab(__patsflab_gt_g0int_int):
/*
emit_instr: loc0 = /home/ubuntu/workspace/ATS2/prelude/DATS/integer.dats({$PATSPRE}/DATS/integer.dats): 11698(line=592, offs=29) -- 11709(line=592, offs=40)
*/
ATSINSmove(tmp20__1, atspre_g0int2int_int_int(arg1)) ;

/*
emit_instr: loc0 = /home/ubuntu/workspace/ATS2/prelude/DATS/integer.dats({$PATSPRE}/DATS/integer.dats): 11681(line=592, offs=12) -- 11711(line=592, offs=42)
*/
ATSINSmove(tmpret19__1, atspre_g0int_gt_int(arg0, tmp20__1)) ;

ATSfunbody_end()
ATSreturn(tmpret19__1) ;
} /* end of [ATSLIB_056_prelude__gt_g0int_int__13__1] */

/*
** for initialization(dynloading)
*/
ATSdynloadflag_minit(_057_home_057_ubuntu_057_workspace_057_RosettaATS_057_harshad_niven_057_harshad_056_dats__dynloadflag) ;
ATSextern()
atsvoid_t0ype
_057_home_057_ubuntu_057_workspace_057_RosettaATS_057_harshad_niven_057_harshad_056_dats__dynload()
{
ATSfunbody_beg()
ATSdynload(/*void*/)
ATSdynloadflag_sta(
_057_home_057_ubuntu_057_workspace_057_RosettaATS_057_harshad_niven_057_harshad_056_dats__dynloadflag
) ;
ATSif(
ATSCKiseqz(
_057_home_057_ubuntu_057_workspace_057_RosettaATS_057_harshad_niven_057_harshad_056_dats__dynloadflag
)
) ATSthen() {
ATSdynloadset(_057_home_057_ubuntu_057_workspace_057_RosettaATS_057_harshad_niven_057_harshad_056_dats__dynloadflag) ;
/*
dynexnlst-initize(beg)
*/
/*
dynexnlst-initize(end)
*/
} /* ATSendif */
ATSfunbody_end()
ATSreturn_void(tmpret_void) ;
} /* end of [*_dynload] */

/*
** the ATS runtime
*/
#ifndef _ATS_CCOMP_RUNTIME_NONE_
#include "pats_ccomp_runtime.c"
#include "pats_ccomp_runtime_memalloc.c"
#ifndef _ATS_CCOMP_EXCEPTION_NONE_
#include "pats_ccomp_runtime2_dats.c"
#ifndef _ATS_CCOMP_RUNTIME_TRYWITH_NONE_
#include "pats_ccomp_runtime_trywith.c"
#endif /* _ATS_CCOMP_RUNTIME_TRYWITH_NONE_ */
#endif // end of [_ATS_CCOMP_EXCEPTION_NONE_]
#endif /* _ATS_CCOMP_RUNTIME_NONE_ */

/*
** the [main] implementation
*/
int
main
(
int argc, char **argv, char **envp
) {
int err = 0 ;
_057_home_057_ubuntu_057_workspace_057_RosettaATS_057_harshad_niven_057_harshad_056_dats__dynload() ;
ATSmainats_void_0(err) ;
return (err) ;
} /* end of [main] */

/* ****** ****** */

/* end-of-compilation-unit */
