/*
**
** The C code is generated by [ATS/Postiats-0-2-13]
** The starting compilation time is: 2017-1-7: 23h:43m
**
*/

/*
** include runtime header files
*/
#ifndef _ATS_CCOMP_HEADER_NONE_
#include "pats_ccomp_config.h"
#include "pats_ccomp_basics.h"
#include "pats_ccomp_typedefs.h"
#include "pats_ccomp_instrset.h"
#include "pats_ccomp_memalloc.h"
#ifndef _ATS_CCOMP_EXCEPTION_NONE_
#include "pats_ccomp_memalloca.h"
#include "pats_ccomp_exception.h"
#endif // end of [_ATS_CCOMP_EXCEPTION_NONE_]
#endif /* _ATS_CCOMP_HEADER_NONE_ */


/*
** include prelude cats files
*/
#ifndef _ATS_CCOMP_PRELUDE_NONE_
//
#include "prelude/CATS/basics.cats"
#include "prelude/CATS/integer.cats"
#include "prelude/CATS/pointer.cats"
#include "prelude/CATS/integer_long.cats"
#include "prelude/CATS/integer_size.cats"
#include "prelude/CATS/integer_short.cats"
#include "prelude/CATS/bool.cats"
#include "prelude/CATS/char.cats"
#include "prelude/CATS/float.cats"
#include "prelude/CATS/integer_ptr.cats"
#include "prelude/CATS/integer_fixed.cats"
#include "prelude/CATS/memory.cats"
#include "prelude/CATS/string.cats"
#include "prelude/CATS/strptr.cats"
//
#include "prelude/CATS/fprintf.cats"
//
#include "prelude/CATS/filebas.cats"
//
#include "prelude/CATS/list.cats"
#include "prelude/CATS/option.cats"
#include "prelude/CATS/array.cats"
#include "prelude/CATS/arrayptr.cats"
#include "prelude/CATS/arrayref.cats"
#include "prelude/CATS/matrix.cats"
#include "prelude/CATS/matrixptr.cats"
//
#endif /* _ATS_CCOMP_PRELUDE_NONE_ */
/*
** for user-supplied prelude
*/
#ifdef _ATS_CCOMP_PRELUDE_USER_
//
#include _ATS_CCOMP_PRELUDE_USER_
//
#endif /* _ATS_CCOMP_PRELUDE_USER_ */
/*
** for user2-supplied prelude
*/
#ifdef _ATS_CCOMP_PRELUDE_USER2_
//
#include _ATS_CCOMP_PRELUDE_USER2_
//
#endif /* _ATS_CCOMP_PRELUDE_USER2_ */

/*
staload-prologues(beg)
*/
/*
/home/ubuntu/workspace/ATS2/prelude/DATS/basics.dats: 1534(line=44, offs=1) -- 1573(line=45, offs=32)
*/
/*
/home/ubuntu/workspace/ATS2/prelude/DATS/integer.dats: 1596(line=49, offs=1) -- 1635(line=49, offs=40)
*/
/*
/home/ubuntu/workspace/ATS2/prelude/DATS/pointer.dats: 1533(line=44, offs=1) -- 1572(line=44, offs=40)
*/
/*
/home/ubuntu/workspace/ATS2/prelude/DATS/integer_long.dats: 1602(line=49, offs=1) -- 1641(line=49, offs=40)
*/
/*
/home/ubuntu/workspace/ATS2/prelude/DATS/integer_size.dats: 1597(line=49, offs=1) -- 1636(line=49, offs=40)
*/
/*
/home/ubuntu/workspace/ATS2/prelude/DATS/integer_short.dats: 1603(line=49, offs=1) -- 1642(line=49, offs=40)
*/
/*
/home/ubuntu/workspace/ATS2/prelude/DATS/char.dats: 1610(line=48, offs=1) -- 1649(line=48, offs=40)
*/
/*
/home/ubuntu/workspace/ATS2/prelude/DATS/float.dats: 1636(line=50, offs=1) -- 1675(line=50, offs=40)
*/
/*
/home/ubuntu/workspace/ATS2/prelude/DATS/string.dats: 1609(line=48, offs=1) -- 1648(line=48, offs=40)
*/
/*
/home/ubuntu/workspace/ATS2/prelude/DATS/strptr.dats: 1609(line=48, offs=1) -- 1648(line=48, offs=40)
*/
/*
/home/ubuntu/workspace/ATS2/prelude/DATS/strptr.dats: 1671(line=52, offs=1) -- 1718(line=52, offs=48)
*/
/*
/home/ubuntu/workspace/ATS2/prelude/DATS/integer.dats: 1596(line=49, offs=1) -- 1635(line=49, offs=40)
*/
/*
/home/ubuntu/workspace/ATS2/prelude/DATS/integer_ptr.dats: 1601(line=49, offs=1) -- 1640(line=49, offs=40)
*/
/*
/home/ubuntu/workspace/ATS2/prelude/DATS/integer_fixed.dats: 1603(line=49, offs=1) -- 1642(line=49, offs=40)
*/
/*
/home/ubuntu/workspace/ATS2/prelude/DATS/memory.dats: 1410(line=38, offs=1) -- 1449(line=39, offs=32)
*/
/*
/home/ubuntu/workspace/ATS2/prelude/DATS/filebas.dats: 1613(line=49, offs=1) -- 1652(line=50, offs=32)
*/
/*
/home/ubuntu/workspace/ATS2/prelude/DATS/filebas.dats: 1675(line=54, offs=1) -- 1721(line=55, offs=39)
*/
/*
/home/ubuntu/workspace/ATS2/prelude/DATS/integer.dats: 1596(line=49, offs=1) -- 1635(line=49, offs=40)
*/
/*
/home/ubuntu/workspace/ATS2/prelude/DATS/filebas.dats: 1744(line=59, offs=1) -- 1789(line=60, offs=38)
*/
/*
/home/ubuntu/workspace/ATS2/libats/libc/SATS/stdio.sats: 1390(line=36, offs=1) -- 1437(line=39, offs=3)
*/

#include \
"libats/libc/CATS/stdio.cats"
/*
/home/ubuntu/workspace/ATS2/libats/libc/SATS/stdio.sats: 1950(line=69, offs=1) -- 1999(line=71, offs=34)
*/
/*
/home/ubuntu/workspace/ATS2/libats/libc/SATS/sys/types.sats: 1390(line=36, offs=1) -- 1441(line=39, offs=3)
*/

#include \
"libats/libc/CATS/sys/types.cats"
/*
/home/ubuntu/workspace/ATS2/prelude/DATS/filebas.dats: 1871(line=66, offs=1) -- 1918(line=66, offs=48)
*/
/*
/home/ubuntu/workspace/ATS2/libats/libc/SATS/sys/stat.sats: 1390(line=36, offs=1) -- 1440(line=39, offs=3)
*/

#include \
"libats/libc/CATS/sys/stat.cats"
/*
/home/ubuntu/workspace/ATS2/libats/libc/SATS/sys/stat.sats: 1756(line=58, offs=1) -- 1805(line=60, offs=34)
*/
/*
/home/ubuntu/workspace/ATS2/libats/libc/SATS/sys/types.sats: 1390(line=36, offs=1) -- 1441(line=39, offs=3)
*/

#include \
"libats/libc/CATS/sys/types.cats"
/*
/home/ubuntu/workspace/ATS2/prelude/DATS/filebas.dats: 15413(line=857, offs=1) -- 15450(line=858, offs=30)
*/
/*
/home/ubuntu/workspace/ATS2/libats/libc/SATS/stdio.sats: 1390(line=36, offs=1) -- 1437(line=39, offs=3)
*/

#include \
"libats/libc/CATS/stdio.cats"
/*
/home/ubuntu/workspace/ATS2/libats/libc/SATS/stdio.sats: 1950(line=69, offs=1) -- 1999(line=71, offs=34)
*/
/*
/home/ubuntu/workspace/ATS2/libats/libc/SATS/sys/types.sats: 1390(line=36, offs=1) -- 1441(line=39, offs=3)
*/

#include \
"libats/libc/CATS/sys/types.cats"
/*
/home/ubuntu/workspace/ATS2/prelude/DATS/list.dats: 1529(line=44, offs=1) -- 1568(line=45, offs=32)
*/
/*
/home/ubuntu/workspace/ATS2/prelude/DATS/list.dats: 1569(line=46, offs=1) -- 1615(line=47, offs=39)
*/
/*
/home/ubuntu/workspace/ATS2/prelude/DATS/unsafe.dats: 1532(line=44, offs=1) -- 1566(line=44, offs=35)
*/
/*
/home/ubuntu/workspace/ATS2/prelude/DATS/list_vt.dats: 1538(line=44, offs=1) -- 1577(line=45, offs=32)
*/
/*
/home/ubuntu/workspace/ATS2/prelude/DATS/list_vt.dats: 1578(line=46, offs=1) -- 1624(line=47, offs=39)
*/
/*
/home/ubuntu/workspace/ATS2/prelude/DATS/unsafe.dats: 1532(line=44, offs=1) -- 1566(line=44, offs=35)
*/
/*
/home/ubuntu/workspace/ATS2/prelude/DATS/array.dats: 1534(line=44, offs=1) -- 1573(line=44, offs=40)
*/
/*
/home/ubuntu/workspace/ATS2/prelude/DATS/array.dats: 1574(line=45, offs=1) -- 1616(line=45, offs=43)
*/
/*
/home/ubuntu/workspace/ATS2/prelude/DATS/arrayptr.dats: 1532(line=44, offs=1) -- 1571(line=44, offs=40)
*/
/*
/home/ubuntu/workspace/ATS2/prelude/DATS/arrayref.dats: 1532(line=44, offs=1) -- 1571(line=44, offs=40)
*/
/*
/home/ubuntu/workspace/ATS2/prelude/DATS/matrix.dats: 1535(line=44, offs=1) -- 1574(line=44, offs=40)
*/
/*
/home/ubuntu/workspace/ATS2/prelude/DATS/matrixptr.dats: 1538(line=44, offs=1) -- 1577(line=44, offs=40)
*/
/*
/home/ubuntu/workspace/ATS2/prelude/DATS/matrixref.dats: 1538(line=44, offs=1) -- 1577(line=44, offs=40)
*/
/*
/home/ubuntu/workspace/ATS2/prelude/DATS/stream.dats: 1523(line=44, offs=1) -- 1562(line=44, offs=40)
*/
/*
/home/ubuntu/workspace/ATS2/prelude/DATS/stream_vt.dats: 1523(line=44, offs=1) -- 1562(line=44, offs=40)
*/
/*
/home/ubuntu/workspace/ATS2/prelude/DATS/tostring.dats: 1528(line=44, offs=1) -- 1567(line=45, offs=32)
*/
/*
/home/ubuntu/workspace/ATS2/prelude/DATS/unsafe.dats: 1532(line=44, offs=1) -- 1566(line=44, offs=35)
*/
/*
/home/ubuntu/workspace/ATS2/prelude/DATS/checkast.dats: 1531(line=44, offs=1) -- 1570(line=45, offs=32)
*/
/*
staload-prologues(end)
*/
/*
typedefs-for-tyrecs-and-tysums(beg)
*/
/*
typedefs-for-tyrecs-and-tysums(end)
*/
/*
dynconlst-declaration(beg)
*/
/*
dynconlst-declaration(end)
*/
/*
dyncstlst-declaration(beg)
*/
ATSdyncst_mac(atspre_g0int2int_int_int)
ATSdyncst_mac(atspre_g0int_gt_int)
ATSdyncst_mac(atspre_g0int_neg_int)
ATSdyncst_mac(atspre_g0int_eq_int)
ATSdyncst_mac(atspre_g0int_div_int)
ATSdyncst_mac(atspre_g0int_add_int)
ATSdyncst_mac(atspre_g0int_gte_int)
ATSdyncst_mac(atspre_g0int_mod_int)
ATSdyncst_mac(atspre_g0int_lt_int)
ATSdyncst_mac(atspre_g0int_sub_int)
ATSdyncst_mac(atspre_print_int)
ATSdyncst_mac(atspre_print_string)
ATSdyncst_mac(atspre_print_newline)
ATSdyncst_mac(atspre_g1int_neg_int)
/*
dyncstlst-declaration(end)
*/
/*
dynvalist-implementation(beg)
*/
/*
dynvalist-implementation(end)
*/
/*
exnconlst-declaration(beg)
*/
#ifndef _ATS_CCOMP_EXCEPTION_NONE_
ATSextern()
atsvoid_t0ype
the_atsexncon_initize
(
  atstype_exnconptr d2c, atstype_string exnmsg
) ;
#endif // end of [_ATS_CCOMP_EXCEPTION_NONE_]
/*
exnconlst-declaration(end)
*/
/*
assumelst-declaration(beg)
*/
/*
assumelst-declaration(end)
*/
/*
extypelst-declaration(beg)
*/
/*
extypelst-declaration(end)
*/
ATSstatic()
atsvoid_t0ype
get3mid_0(atstkind_t0ype(atstype_int)) ;

#if(0)
#if(0)
ATSextern()
atstkind_t0ype(atstype_bool)
ATSLIB_056_prelude__gt_g0int_int__1(atstkind_t0ype(atstyvar_type(tk)), atstkind_t0ype(atstype_int)) ;
#endif // end of [QUALIFIED]
#endif // end of [TEMPLATE]

ATSstatic()
atstkind_t0ype(atstype_bool)
ATSLIB_056_prelude__gt_g0int_int__1__1(atstkind_t0ype(atstype_int), atstkind_t0ype(atstype_int)) ;

ATSstatic()
atstkind_t0ype(atstype_int)
intsize_6(atstkind_t0ype(atstype_int), atstkind_t0ype(atstype_int)) ;

#if(0)
#if(0)
ATSextern()
atstkind_t0ype(atstype_bool)
ATSLIB_056_prelude__eq_g0int_int__7(atstkind_t0ype(atstyvar_type(tk)), atstkind_t0ype(atstype_int)) ;
#endif // end of [QUALIFIED]
#endif // end of [TEMPLATE]

ATSstatic()
atstkind_t0ype(atstype_bool)
ATSLIB_056_prelude__eq_g0int_int__7__1(atstkind_t0ype(atstype_int), atstkind_t0ype(atstype_int)) ;

ATSstatic()
atstkind_t0ype(atstype_int)
get_digit_12(atstkind_t0ype(atstype_int), atstkind_t0ype(atstype_int), atstkind_t0ype(atstype_int), atstkind_t0ype(atstype_int)) ;

ATSstatic()
atstkind_t0ype(atstype_bool)
ATSLIB_056_prelude__gt_g0int_int__1__2(atstkind_t0ype(atstype_int), atstkind_t0ype(atstype_int)) ;

#if(0)
#if(0)
ATSextern()
atstkind_t0ype(atstype_bool)
ATSLIB_056_prelude__gte_g0int_int__14(atstkind_t0ype(atstyvar_type(tk)), atstkind_t0ype(atstype_int)) ;
#endif // end of [QUALIFIED]
#endif // end of [TEMPLATE]

ATSstatic()
atstkind_t0ype(atstype_bool)
ATSLIB_056_prelude__gte_g0int_int__14__1(atstkind_t0ype(atstype_int), atstkind_t0ype(atstype_int)) ;

#if(0)
#if(0)
ATSextern()
atstkind_t0ype(atstype_bool)
ATSLIB_056_prelude__lt_g0int_int__18(atstkind_t0ype(atstyvar_type(tk)), atstkind_t0ype(atstype_int)) ;
#endif // end of [QUALIFIED]
#endif // end of [TEMPLATE]

ATSstatic()
atstkind_t0ype(atstype_bool)
ATSLIB_056_prelude__lt_g0int_int__18__1(atstkind_t0ype(atstype_int), atstkind_t0ype(atstype_int)) ;

ATSstatic()
atstkind_t0ype(atstype_bool)
ATSLIB_056_prelude__lt_g0int_int__18__2(atstkind_t0ype(atstype_int), atstkind_t0ype(atstype_int)) ;

ATSstatic()
atstkind_t0ype(atstype_bool)
ATSLIB_056_prelude__eq_g0int_int__7__2(atstkind_t0ype(atstype_int), atstkind_t0ype(atstype_int)) ;

#if(0)
ATSextern()
atsvoid_t0ype
mainats_void_0() ;
#endif // end of [QUALIFIED]

/*
/home/ubuntu/workspace/RosettaATS/middle_three_digits/digits.dats: 85(line=6, offs=5) -- 972(line=42, offs=4)
*/
/*
local: 
global: get3mid_0$0(level=0)
local: 
global: 
*/
ATSstatic()
atsvoid_t0ype
get3mid_0(atstkind_t0ype(atstype_int) arg0)
{
/* tmpvardeclst(beg) */
// ATStmpdec_void(tmpret0) ;
ATStmpdec(tmp1, atstkind_t0ype(atstype_int)) ;
ATStmpdec(tmp2, atstkind_t0ype(atstype_bool)) ;
ATStmpdec(tmp28, atstkind_t0ype(atstype_int)) ;
ATStmpdec(tmp29, atstkind_t0ype(atstype_bool)) ;
ATStmpdec(tmp34, atstkind_t0ype(atstype_int)) ;
ATStmpdec(tmp35, atstkind_t0ype(atstype_int)) ;
ATStmpdec(tmp36, atstkind_t0ype(atstype_int)) ;
ATStmpdec(tmp37, atstkind_t0ype(atstype_int)) ;
ATStmpdec(tmp38, atstkind_t0ype(atstype_int)) ;
ATStmpdec(tmp39, atstkind_t0ype(atstype_int)) ;
ATStmpdec(tmp40, atstkind_t0ype(atstype_int)) ;
ATStmpdec(tmp41, atstkind_t0ype(atstype_int)) ;
ATStmpdec(tmp42, atstkind_t0ype(atstype_bool)) ;
ATStmpdec(tmp45, atstkind_t0ype(atstype_int)) ;
// ATStmpdec_void(tmp46) ;
// ATStmpdec_void(tmp47) ;
ATStmpdec(tmp48, atstkind_t0ype(atstype_bool)) ;
ATStmpdec(tmp51, atstkind_t0ype(atstype_int)) ;
ATStmpdec(tmp52, atstkind_t0ype(atstype_int)) ;
// ATStmpdec_void(tmp53) ;
// ATStmpdec_void(tmp54) ;
// ATStmpdec_void(tmp55) ;
// ATStmpdec_void(tmp56) ;
// ATStmpdec_void(tmp57) ;
// ATStmpdec_void(tmp58) ;
// ATStmpdec_void(tmp59) ;
// ATStmpdec_void(tmp60) ;
// ATStmpdec_void(tmp61) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /home/ubuntu/workspace/RosettaATS/middle_three_digits/digits.dats: 85(line=6, offs=5) -- 972(line=42, offs=4)
*/
ATSINSflab(__patsflab_get3mid_0):
/*
emit_instr: loc0 = /home/ubuntu/workspace/RosettaATS/middle_three_digits/digits.dats: 111(line=6, offs=31) -- 972(line=42, offs=4)
*/
/*
letpush(beg)
*/
/*
emit_instr: loc0 = /home/ubuntu/workspace/RosettaATS/middle_three_digits/digits.dats: 162(line=8, offs=20) -- 169(line=8, offs=27)
*/
ATSINSmove(tmp2, ATSLIB_056_prelude__gt_g0int_int__1__1(arg0, ATSPMVi0nt(0))) ;

/*
emit_instr: loc0 = /home/ubuntu/workspace/RosettaATS/middle_three_digits/digits.dats: 159(line=8, offs=17) -- 188(line=8, offs=46)
*/
ATSif(
tmp2
) ATSthen() {
/*
emit_instr: loc0 = /home/ubuntu/workspace/RosettaATS/middle_three_digits/digits.dats: 175(line=8, offs=33) -- 178(line=8, offs=36)
*/
ATSINSmove(tmp1, arg0) ;
} ATSelse() {
/*
emit_instr: loc0 = /home/ubuntu/workspace/RosettaATS/middle_three_digits/digits.dats: 184(line=8, offs=42) -- 188(line=8, offs=46)
*/
ATSINSmove(tmp1, atspre_g0int_neg_int(arg0)) ;

} /* ATSendif */
/*
emit_instr: loc0 = /home/ubuntu/workspace/RosettaATS/middle_three_digits/digits.dats: 554(line=27, offs=8) -- 572(line=27, offs=26)
*/
ATSINSmove(tmp34, intsize_6(tmp1, ATSPMVi0nt(0))) ;

/*
emit_instr: loc0 = /home/ubuntu/workspace/RosettaATS/middle_three_digits/digits.dats: 554(line=27, offs=8) -- 576(line=27, offs=30)
*/
ATSINSmove(tmp29, ATSLIB_056_prelude__lt_g0int_int__18__1(tmp34, ATSPMVi0nt(3))) ;

/*
emit_instr: loc0 = /home/ubuntu/workspace/RosettaATS/middle_three_digits/digits.dats: 551(line=27, offs=5) -- 613(line=27, offs=67)
*/
ATSif(
tmp29
) ATSthen() {
/*
emit_instr: loc0 = /home/ubuntu/workspace/RosettaATS/middle_three_digits/digits.dats: 582(line=27, offs=36) -- 583(line=27, offs=37)
*/
ATSINSmove(tmp28, ATSPMVi0nt(1)) ;
} ATSelse() {
/*
emit_instr: loc0 = /home/ubuntu/workspace/RosettaATS/middle_three_digits/digits.dats: 589(line=27, offs=43) -- 607(line=27, offs=61)
*/
ATSINSmove(tmp36, intsize_6(tmp1, ATSPMVi0nt(0))) ;

/*
emit_instr: loc0 = /home/ubuntu/workspace/RosettaATS/middle_three_digits/digits.dats: 589(line=27, offs=43) -- 609(line=27, offs=63)
*/
ATSINSmove(tmp35, atspre_g0int_div_int(tmp36, ATSPMVi0nt(2))) ;

/*
emit_instr: loc0 = /home/ubuntu/workspace/RosettaATS/middle_three_digits/digits.dats: 589(line=27, offs=43) -- 613(line=27, offs=67)
*/
ATSINSmove(tmp28, atspre_g0int_add_int(tmp35, ATSPMVi0nt(1))) ;

} /* ATSendif */
/*
emit_instr: loc0 = /home/ubuntu/workspace/RosettaATS/middle_three_digits/digits.dats: 652(line=29, offs=30) -- 665(line=29, offs=43)
*/
ATSINSmove(tmp38, atspre_g0int_add_int(tmp28, ATSPMVi0nt(1))) ;

/*
emit_instr: loc0 = /home/ubuntu/workspace/RosettaATS/middle_three_digits/digits.dats: 634(line=29, offs=12) -- 669(line=29, offs=47)
*/
ATSINSmove(tmp37, get_digit_12(tmp1, tmp1, tmp38, ATSPMVi0nt(1))) ;

/*
emit_instr: loc0 = /home/ubuntu/workspace/RosettaATS/middle_three_digits/digits.dats: 682(line=30, offs=12) -- 715(line=30, offs=45)
*/
ATSINSmove(tmp39, get_digit_12(tmp1, tmp1, tmp28, ATSPMVi0nt(1))) ;

/*
emit_instr: loc0 = /home/ubuntu/workspace/RosettaATS/middle_three_digits/digits.dats: 745(line=31, offs=30) -- 758(line=31, offs=43)
*/
ATSINSmove(tmp41, atspre_g0int_sub_int(tmp28, ATSPMVi0nt(1))) ;

/*
emit_instr: loc0 = /home/ubuntu/workspace/RosettaATS/middle_three_digits/digits.dats: 727(line=31, offs=12) -- 762(line=31, offs=47)
*/
ATSINSmove(tmp40, get_digit_12(tmp1, tmp1, tmp41, ATSPMVi0nt(1))) ;

/*
letpush(end)
*/

/*
emit_instr: loc0 = /home/ubuntu/workspace/RosettaATS/middle_three_digits/digits.dats: 774(line=35, offs=6) -- 792(line=35, offs=24)
*/
ATSINSmove(tmp45, intsize_6(tmp1, ATSPMVi0nt(0))) ;

/*
emit_instr: loc0 = /home/ubuntu/workspace/RosettaATS/middle_three_digits/digits.dats: 774(line=35, offs=6) -- 796(line=35, offs=28)
*/
ATSINSmove(tmp42, ATSLIB_056_prelude__lt_g0int_int__18__2(tmp45, ATSPMVi0nt(3))) ;

/*
emit_instr: loc0 = /home/ubuntu/workspace/RosettaATS/middle_three_digits/digits.dats: 771(line=35, offs=3) -- 966(line=40, offs=4)
*/
ATSif(
tmp42
) ATSthen() {
/*
emit_instr: loc0 = /home/ubuntu/workspace/RosettaATS/middle_three_digits/digits.dats: 802(line=35, offs=34) -- 832(line=35, offs=64)
*/
ATSINSmove_void(tmp46, atspre_print_int(arg0)) ;

/*
emit_instr: loc0 = /home/ubuntu/workspace/RosettaATS/middle_three_digits/digits.dats: 802(line=35, offs=34) -- 832(line=35, offs=64)
*/
ATSINSmove_void(tmp47, atspre_print_string(ATSPMVstring(" | Too short!"))) ;

/*
emit_instr: loc0 = /home/ubuntu/workspace/RosettaATS/middle_three_digits/digits.dats: 802(line=35, offs=34) -- 832(line=35, offs=64)
*/
ATSINSmove_void(tmpret0, atspre_print_newline()) ;

} ATSelse() {
/*
emit_instr: loc0 = /home/ubuntu/workspace/RosettaATS/middle_three_digits/digits.dats: 851(line=38, offs=8) -- 869(line=38, offs=26)
*/
ATSINSmove(tmp52, intsize_6(tmp1, ATSPMVi0nt(0))) ;

/*
emit_instr: loc0 = /home/ubuntu/workspace/RosettaATS/middle_three_digits/digits.dats: 851(line=38, offs=8) -- 873(line=38, offs=30)
*/
ATSINSmove(tmp51, atspre_g0int_mod_int(tmp52, ATSPMVi0nt(2))) ;

/*
emit_instr: loc0 = /home/ubuntu/workspace/RosettaATS/middle_three_digits/digits.dats: 851(line=38, offs=8) -- 877(line=38, offs=34)
*/
ATSINSmove(tmp48, ATSLIB_056_prelude__eq_g0int_int__7__2(tmp51, ATSPMVi0nt(0))) ;

/*
emit_instr: loc0 = /home/ubuntu/workspace/RosettaATS/middle_three_digits/digits.dats: 848(line=38, offs=5) -- 962(line=39, offs=47)
*/
ATSif(
tmp48
) ATSthen() {
/*
emit_instr: loc0 = /home/ubuntu/workspace/RosettaATS/middle_three_digits/digits.dats: 883(line=38, offs=40) -- 915(line=38, offs=72)
*/
ATSINSmove_void(tmp53, atspre_print_int(arg0)) ;

/*
emit_instr: loc0 = /home/ubuntu/workspace/RosettaATS/middle_three_digits/digits.dats: 883(line=38, offs=40) -- 915(line=38, offs=72)
*/
ATSINSmove_void(tmp54, atspre_print_string(ATSPMVstring(" | Even number!"))) ;

/*
emit_instr: loc0 = /home/ubuntu/workspace/RosettaATS/middle_three_digits/digits.dats: 883(line=38, offs=40) -- 915(line=38, offs=72)
*/
ATSINSmove_void(tmpret0, atspre_print_newline()) ;

} ATSelse() {
/*
emit_instr: loc0 = /home/ubuntu/workspace/RosettaATS/middle_three_digits/digits.dats: 925(line=39, offs=10) -- 962(line=39, offs=47)
*/
ATSINSmove_void(tmp55, atspre_print_int(arg0)) ;

/*
emit_instr: loc0 = /home/ubuntu/workspace/RosettaATS/middle_three_digits/digits.dats: 925(line=39, offs=10) -- 962(line=39, offs=47)
*/
ATSINSmove_void(tmp56, atspre_print_string(ATSPMVstring(" | "))) ;

/*
emit_instr: loc0 = /home/ubuntu/workspace/RosettaATS/middle_three_digits/digits.dats: 925(line=39, offs=10) -- 962(line=39, offs=47)
*/
ATSINSmove_void(tmp57, atspre_print_int(tmp37)) ;

/*
emit_instr: loc0 = /home/ubuntu/workspace/RosettaATS/middle_three_digits/digits.dats: 925(line=39, offs=10) -- 962(line=39, offs=47)
*/
ATSINSmove_void(tmp58, atspre_print_string(ATSPMVstring(" "))) ;

/*
emit_instr: loc0 = /home/ubuntu/workspace/RosettaATS/middle_three_digits/digits.dats: 925(line=39, offs=10) -- 962(line=39, offs=47)
*/
ATSINSmove_void(tmp59, atspre_print_int(tmp39)) ;

/*
emit_instr: loc0 = /home/ubuntu/workspace/RosettaATS/middle_three_digits/digits.dats: 925(line=39, offs=10) -- 962(line=39, offs=47)
*/
ATSINSmove_void(tmp60, atspre_print_string(ATSPMVstring(" "))) ;

/*
emit_instr: loc0 = /home/ubuntu/workspace/RosettaATS/middle_three_digits/digits.dats: 925(line=39, offs=10) -- 962(line=39, offs=47)
*/
ATSINSmove_void(tmp61, atspre_print_int(tmp40)) ;

/*
emit_instr: loc0 = /home/ubuntu/workspace/RosettaATS/middle_three_digits/digits.dats: 925(line=39, offs=10) -- 962(line=39, offs=47)
*/
ATSINSmove_void(tmpret0, atspre_print_newline()) ;

} /* ATSendif */
} /* ATSendif */
/*
emit_instr: loc0 = /home/ubuntu/workspace/RosettaATS/middle_three_digits/digits.dats: 111(line=6, offs=31) -- 972(line=42, offs=4)
*/
/*
INSletpop()
*/
ATSfunbody_end()
ATSreturn_void(tmpret0) ;
} /* end of [get3mid_0] */

#if(0)
/*
/home/ubuntu/workspace/ATS2/prelude/DATS/integer.dats: 11672(line=592, offs=3) -- 11711(line=592, offs=42)
*/
/*
local: 
global: gt_g0int_int$1$0(level=0)
local: 
global: 
*/
ATSextern()
/*
imparg = tk(4620)
tmparg = S2Evar(tk(4620))
tmpsub = None()
*/
atstkind_t0ype(atstype_bool)
ATSLIB_056_prelude__gt_g0int_int__1(atstkind_t0ype(atstyvar_type(tk)) arg0, atstkind_t0ype(atstype_int) arg1)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret3, atstkind_t0ype(atstype_bool)) ;
ATStmpdec(tmp4, atstkind_t0ype(atstyvar_type(tk))) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /home/ubuntu/workspace/ATS2/prelude/DATS/integer.dats({$PATSPRE}/DATS/integer.dats): 11657(line=591, offs=1) -- 11711(line=592, offs=42)
*/
ATSINSflab(__patsflab_gt_g0int_int):
/*
emit_instr: loc0 = /home/ubuntu/workspace/ATS2/prelude/DATS/integer.dats({$PATSPRE}/DATS/integer.dats): 11698(line=592, offs=29) -- 11709(line=592, offs=40)
*/
ATSINSmove(tmp4, PMVtmpltcst(g0int2int<S2Eextkind(atstype_int), S2Evar(tk(4620))>)(arg1)) ;

/*
emit_instr: loc0 = /home/ubuntu/workspace/ATS2/prelude/DATS/integer.dats({$PATSPRE}/DATS/integer.dats): 11681(line=592, offs=12) -- 11711(line=592, offs=42)
*/
ATSINSmove(tmpret3, PMVtmpltcst(g0int_gt<S2Evar(tk(4620))>)(arg0, tmp4)) ;

ATSfunbody_end()
ATSreturn(tmpret3) ;
} /* end of [ATSLIB_056_prelude__gt_g0int_int__1] */
#endif // end of [TEMPLATE]

/*
/home/ubuntu/workspace/ATS2/prelude/DATS/integer.dats: 11672(line=592, offs=3) -- 11711(line=592, offs=42)
*/
/*
local: 
global: gt_g0int_int$1$1(level=1)
local: 
global: 
*/
ATSstatic()
/*
imparg = tk(4620)
tmparg = S2Evar(tk(4620))
tmpsub = Some(tk(4620) -> S2Eextkind(atstype_int))
*/
atstkind_t0ype(atstype_bool)
ATSLIB_056_prelude__gt_g0int_int__1__1(atstkind_t0ype(atstype_int) arg0, atstkind_t0ype(atstype_int) arg1)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret3__1, atstkind_t0ype(atstype_bool)) ;
ATStmpdec(tmp4__1, atstkind_t0ype(atstype_int)) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /home/ubuntu/workspace/ATS2/prelude/DATS/integer.dats({$PATSPRE}/DATS/integer.dats): 11657(line=591, offs=1) -- 11711(line=592, offs=42)
*/
ATSINSflab(__patsflab_gt_g0int_int):
/*
emit_instr: loc0 = /home/ubuntu/workspace/ATS2/prelude/DATS/integer.dats({$PATSPRE}/DATS/integer.dats): 11698(line=592, offs=29) -- 11709(line=592, offs=40)
*/
ATSINSmove(tmp4__1, atspre_g0int2int_int_int(arg1)) ;

/*
emit_instr: loc0 = /home/ubuntu/workspace/ATS2/prelude/DATS/integer.dats({$PATSPRE}/DATS/integer.dats): 11681(line=592, offs=12) -- 11711(line=592, offs=42)
*/
ATSINSmove(tmpret3__1, atspre_g0int_gt_int(arg0, tmp4__1)) ;

ATSfunbody_end()
ATSreturn(tmpret3__1) ;
} /* end of [ATSLIB_056_prelude__gt_g0int_int__1__1] */

/*
/home/ubuntu/workspace/RosettaATS/middle_three_digits/digits.dats: 203(line=10, offs=7) -- 304(line=14, offs=4)
*/
/*
local: intsize_6$0(level=1)
global: intsize_6$0(level=1)
local: 
global: 
*/
ATSstatic()
atstkind_t0ype(atstype_int)
intsize_6(atstkind_t0ype(atstype_int) arg0, atstkind_t0ype(atstype_int) arg1)
{
/* tmpvardeclst(beg) */
ATStmpdec(apy0, atstkind_t0ype(atstype_int)) ;
ATStmpdec(apy1, atstkind_t0ype(atstype_int)) ;
ATStmpdec(tmpret7, atstkind_t0ype(atstype_int)) ;
ATStmpdec(tmp8, atstkind_t0ype(atstype_bool)) ;
ATStmpdec(tmp13, atstkind_t0ype(atstype_int)) ;
ATStmpdec(tmp14, atstkind_t0ype(atstype_int)) ;
ATStmpdec(tmp15, atstkind_t0ype(atstype_int)) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /home/ubuntu/workspace/RosettaATS/middle_three_digits/digits.dats: 203(line=10, offs=7) -- 304(line=14, offs=4)
*/
ATSINSflab(__patsflab_intsize_6):
/*
emit_instr: loc0 = /home/ubuntu/workspace/RosettaATS/middle_three_digits/digits.dats: 249(line=12, offs=8) -- 253(line=12, offs=12)
*/
ATSINSmove(tmp13, atspre_g0int_div_int(arg0, ATSPMVi0nt(10))) ;

/*
emit_instr: loc0 = /home/ubuntu/workspace/RosettaATS/middle_three_digits/digits.dats: 249(line=12, offs=8) -- 257(line=12, offs=16)
*/
ATSINSmove(tmp8, ATSLIB_056_prelude__eq_g0int_int__7__1(tmp13, ATSPMVi0nt(0))) ;

/*
emit_instr: loc0 = /home/ubuntu/workspace/RosettaATS/middle_three_digits/digits.dats: 246(line=12, offs=5) -- 300(line=13, offs=31)
*/
ATSif(
tmp8
) ATSthen() {
/*
emit_instr: loc0 = /home/ubuntu/workspace/RosettaATS/middle_three_digits/digits.dats: 263(line=12, offs=22) -- 269(line=12, offs=28)
*/
ATSINSmove(tmpret7, atspre_g0int_add_int(arg1, ATSPMVi0nt(1))) ;

} ATSelse() {
/*
emit_instr: loc0 = /home/ubuntu/workspace/RosettaATS/middle_three_digits/digits.dats: 287(line=13, offs=18) -- 291(line=13, offs=22)
*/
ATSINSmove(tmp14, atspre_g0int_div_int(arg0, ATSPMVi0nt(10))) ;

/*
emit_instr: loc0 = /home/ubuntu/workspace/RosettaATS/middle_three_digits/digits.dats: 293(line=13, offs=24) -- 299(line=13, offs=30)
*/
ATSINSmove(tmp15, atspre_g0int_add_int(arg1, ATSPMVi0nt(1))) ;

/*
emit_instr: loc0 = /home/ubuntu/workspace/RosettaATS/middle_three_digits/digits.dats: 279(line=13, offs=10) -- 300(line=13, offs=31)
*/
ATStailcal_beg()
ATSINSmove_tlcal(apy0, tmp14) ;
ATSINSmove_tlcal(apy1, tmp15) ;
ATSINSargmove_tlcal(arg0, apy0) ;
ATSINSargmove_tlcal(arg1, apy1) ;
ATSINSfgoto(__patsflab_intsize_6) ;
ATStailcal_end()

} /* ATSendif */
ATSfunbody_end()
ATSreturn(tmpret7) ;
} /* end of [intsize_6] */

#if(0)
/*
/home/ubuntu/workspace/ATS2/prelude/DATS/integer.dats: 11831(line=601, offs=3) -- 11870(line=601, offs=42)
*/
/*
local: 
global: eq_g0int_int$7$0(level=0)
local: 
global: 
*/
ATSextern()
/*
imparg = tk(4622)
tmparg = S2Evar(tk(4622))
tmpsub = None()
*/
atstkind_t0ype(atstype_bool)
ATSLIB_056_prelude__eq_g0int_int__7(atstkind_t0ype(atstyvar_type(tk)) arg0, atstkind_t0ype(atstype_int) arg1)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret9, atstkind_t0ype(atstype_bool)) ;
ATStmpdec(tmp10, atstkind_t0ype(atstyvar_type(tk))) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /home/ubuntu/workspace/ATS2/prelude/DATS/integer.dats({$PATSPRE}/DATS/integer.dats): 11816(line=600, offs=1) -- 11870(line=601, offs=42)
*/
ATSINSflab(__patsflab_eq_g0int_int):
/*
emit_instr: loc0 = /home/ubuntu/workspace/ATS2/prelude/DATS/integer.dats({$PATSPRE}/DATS/integer.dats): 11857(line=601, offs=29) -- 11868(line=601, offs=40)
*/
ATSINSmove(tmp10, PMVtmpltcst(g0int2int<S2Eextkind(atstype_int), S2Evar(tk(4622))>)(arg1)) ;

/*
emit_instr: loc0 = /home/ubuntu/workspace/ATS2/prelude/DATS/integer.dats({$PATSPRE}/DATS/integer.dats): 11840(line=601, offs=12) -- 11870(line=601, offs=42)
*/
ATSINSmove(tmpret9, PMVtmpltcst(g0int_eq<S2Evar(tk(4622))>)(arg0, tmp10)) ;

ATSfunbody_end()
ATSreturn(tmpret9) ;
} /* end of [ATSLIB_056_prelude__eq_g0int_int__7] */
#endif // end of [TEMPLATE]

/*
/home/ubuntu/workspace/ATS2/prelude/DATS/integer.dats: 11831(line=601, offs=3) -- 11870(line=601, offs=42)
*/
/*
local: 
global: eq_g0int_int$7$1(level=2)
local: 
global: 
*/
ATSstatic()
/*
imparg = tk(4622)
tmparg = S2Evar(tk(4622))
tmpsub = Some(tk(4622) -> S2Eextkind(atstype_int))
*/
atstkind_t0ype(atstype_bool)
ATSLIB_056_prelude__eq_g0int_int__7__1(atstkind_t0ype(atstype_int) arg0, atstkind_t0ype(atstype_int) arg1)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret9__1, atstkind_t0ype(atstype_bool)) ;
ATStmpdec(tmp10__1, atstkind_t0ype(atstype_int)) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /home/ubuntu/workspace/ATS2/prelude/DATS/integer.dats({$PATSPRE}/DATS/integer.dats): 11816(line=600, offs=1) -- 11870(line=601, offs=42)
*/
ATSINSflab(__patsflab_eq_g0int_int):
/*
emit_instr: loc0 = /home/ubuntu/workspace/ATS2/prelude/DATS/integer.dats({$PATSPRE}/DATS/integer.dats): 11857(line=601, offs=29) -- 11868(line=601, offs=40)
*/
ATSINSmove(tmp10__1, atspre_g0int2int_int_int(arg1)) ;

/*
emit_instr: loc0 = /home/ubuntu/workspace/ATS2/prelude/DATS/integer.dats({$PATSPRE}/DATS/integer.dats): 11840(line=601, offs=12) -- 11870(line=601, offs=42)
*/
ATSINSmove(tmpret9__1, atspre_g0int_eq_int(arg0, tmp10__1)) ;

ATSfunbody_end()
ATSreturn(tmpret9__1) ;
} /* end of [ATSLIB_056_prelude__eq_g0int_int__7__1] */

/*
/home/ubuntu/workspace/RosettaATS/middle_three_digits/digits.dats: 314(line=16, offs=7) -- 519(line=24, offs=4)
*/
/*
local: intsize_6$0(level=1), get_digit_12$0(level=1)
global: intsize_6$0(level=1), get_digit_12$0(level=1)
local: posnum$4465(1)(HSEapp(HSEcst(atstkind_t0ype); HSEs2exp(S2Eextkind(atstype_int))))
global: posnum$4465(1)(HSEapp(HSEcst(atstkind_t0ype); HSEs2exp(S2Eextkind(atstype_int))))
*/
ATSstatic()
atstkind_t0ype(atstype_int)
get_digit_12(atstkind_t0ype(atstype_int) env0, atstkind_t0ype(atstype_int) arg0, atstkind_t0ype(atstype_int) arg1, atstkind_t0ype(atstype_int) arg2)
{
/* tmpvardeclst(beg) */
ATStmpdec(apy0, atstkind_t0ype(atstype_int)) ;
ATStmpdec(apy1, atstkind_t0ype(atstype_int)) ;
ATStmpdec(apy2, atstkind_t0ype(atstype_int)) ;
ATStmpdec(tmpret16, atstkind_t0ype(atstype_int)) ;
ATStmpdec(tmp17, atstkind_t0ype(atstype_bool)) ;
ATStmpdec(tmp20, atstkind_t0ype(atstype_int)) ;
ATStmpdec(tmp21, atstkind_t0ype(atstype_bool)) ;
ATStmpdec(tmp26, atstkind_t0ype(atstype_int)) ;
ATStmpdec(tmp27, atstkind_t0ype(atstype_int)) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /home/ubuntu/workspace/RosettaATS/middle_three_digits/digits.dats: 314(line=16, offs=7) -- 519(line=24, offs=4)
*/
ATSINSflab(__patsflab_get_digit_12):
/*
emit_instr: loc0 = /home/ubuntu/workspace/RosettaATS/middle_three_digits/digits.dats: 384(line=18, offs=16) -- 402(line=18, offs=34)
*/
ATSINSmove(tmp20, intsize_6(env0, ATSPMVi0nt(0))) ;

/*
emit_instr: loc0 = /home/ubuntu/workspace/RosettaATS/middle_three_digits/digits.dats: 376(line=18, offs=8) -- 402(line=18, offs=34)
*/
ATSINSmove(tmp17, ATSLIB_056_prelude__gt_g0int_int__1__2(arg1, tmp20)) ;

/*
emit_instr: loc0 = /home/ubuntu/workspace/RosettaATS/middle_three_digits/digits.dats: 373(line=18, offs=5) -- 515(line=23, offs=6)
*/
ATSif(
tmp17
) ATSthen() {
/*
emit_instr: loc0 = /home/ubuntu/workspace/RosettaATS/middle_three_digits/digits.dats: 408(line=18, offs=40) -- 409(line=18, offs=41)
*/
ATSINSmove(tmpret16, ATSPMVi0nt(0)) ;
} ATSelse() {
/*
emit_instr: loc0 = /home/ubuntu/workspace/RosettaATS/middle_three_digits/digits.dats: 434(line=21, offs=10) -- 450(line=21, offs=26)
*/
ATSINSmove(tmp21, ATSLIB_056_prelude__gte_g0int_int__14__1(arg2, arg1)) ;

/*
emit_instr: loc0 = /home/ubuntu/workspace/RosettaATS/middle_three_digits/digits.dats: 431(line=21, offs=7) -- 509(line=22, offs=47)
*/
ATSif(
tmp21
) ATSthen() {
/*
emit_instr: loc0 = /home/ubuntu/workspace/RosettaATS/middle_three_digits/digits.dats: 456(line=21, offs=32) -- 462(line=21, offs=38)
*/
ATSINSmove(tmpret16, atspre_g0int_mod_int(arg0, ATSPMVi0nt(10))) ;

} ATSelse() {
/*
emit_instr: loc0 = /home/ubuntu/workspace/RosettaATS/middle_three_digits/digits.dats: 484(line=22, offs=22) -- 488(line=22, offs=26)
*/
ATSINSmove(tmp26, atspre_g0int_div_int(arg0, ATSPMVi0nt(10))) ;

/*
emit_instr: loc0 = /home/ubuntu/workspace/RosettaATS/middle_three_digits/digits.dats: 497(line=22, offs=35) -- 508(line=22, offs=46)
*/
ATSINSmove(tmp27, atspre_g0int_add_int(arg2, ATSPMVi0nt(1))) ;

/*
emit_instr: loc0 = /home/ubuntu/workspace/RosettaATS/middle_three_digits/digits.dats: 474(line=22, offs=12) -- 509(line=22, offs=47)
*/
ATStailcal_beg()
ATSINSmove_tlcal(apy0, tmp26) ;
ATSINSmove_tlcal(apy1, arg1) ;
ATSINSmove_tlcal(apy2, tmp27) ;
ATSINSargmove_tlcal(arg0, apy0) ;
ATSINSargmove_tlcal(arg1, apy1) ;
ATSINSargmove_tlcal(arg2, apy2) ;
ATSINSfgoto(__patsflab_get_digit_12) ;
ATStailcal_end()

} /* ATSendif */
} /* ATSendif */
ATSfunbody_end()
ATSreturn(tmpret16) ;
} /* end of [get_digit_12] */

/*
/home/ubuntu/workspace/ATS2/prelude/DATS/integer.dats: 11672(line=592, offs=3) -- 11711(line=592, offs=42)
*/
/*
local: 
global: gt_g0int_int$1$2(level=2)
local: 
global: 
*/
ATSstatic()
/*
imparg = tk(4620)
tmparg = S2Evar(tk(4620))
tmpsub = Some(tk(4620) -> S2Eextkind(atstype_int))
*/
atstkind_t0ype(atstype_bool)
ATSLIB_056_prelude__gt_g0int_int__1__2(atstkind_t0ype(atstype_int) arg0, atstkind_t0ype(atstype_int) arg1)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret3__2, atstkind_t0ype(atstype_bool)) ;
ATStmpdec(tmp4__2, atstkind_t0ype(atstype_int)) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /home/ubuntu/workspace/ATS2/prelude/DATS/integer.dats({$PATSPRE}/DATS/integer.dats): 11657(line=591, offs=1) -- 11711(line=592, offs=42)
*/
ATSINSflab(__patsflab_gt_g0int_int):
/*
emit_instr: loc0 = /home/ubuntu/workspace/ATS2/prelude/DATS/integer.dats({$PATSPRE}/DATS/integer.dats): 11698(line=592, offs=29) -- 11709(line=592, offs=40)
*/
ATSINSmove(tmp4__2, atspre_g0int2int_int_int(arg1)) ;

/*
emit_instr: loc0 = /home/ubuntu/workspace/ATS2/prelude/DATS/integer.dats({$PATSPRE}/DATS/integer.dats): 11681(line=592, offs=12) -- 11711(line=592, offs=42)
*/
ATSINSmove(tmpret3__2, atspre_g0int_gt_int(arg0, tmp4__2)) ;

ATSfunbody_end()
ATSreturn(tmpret3__2) ;
} /* end of [ATSLIB_056_prelude__gt_g0int_int__1__2] */

#if(0)
/*
/home/ubuntu/workspace/ATS2/prelude/DATS/integer.dats: 11750(line=596, offs=3) -- 11790(line=596, offs=43)
*/
/*
local: 
global: gte_g0int_int$14$0(level=0)
local: 
global: 
*/
ATSextern()
/*
imparg = tk(4621)
tmparg = S2Evar(tk(4621))
tmpsub = None()
*/
atstkind_t0ype(atstype_bool)
ATSLIB_056_prelude__gte_g0int_int__14(atstkind_t0ype(atstyvar_type(tk)) arg0, atstkind_t0ype(atstype_int) arg1)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret22, atstkind_t0ype(atstype_bool)) ;
ATStmpdec(tmp23, atstkind_t0ype(atstyvar_type(tk))) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /home/ubuntu/workspace/ATS2/prelude/DATS/integer.dats({$PATSPRE}/DATS/integer.dats): 11734(line=595, offs=1) -- 11790(line=596, offs=43)
*/
ATSINSflab(__patsflab_gte_g0int_int):
/*
emit_instr: loc0 = /home/ubuntu/workspace/ATS2/prelude/DATS/integer.dats({$PATSPRE}/DATS/integer.dats): 11777(line=596, offs=30) -- 11788(line=596, offs=41)
*/
ATSINSmove(tmp23, PMVtmpltcst(g0int2int<S2Eextkind(atstype_int), S2Evar(tk(4621))>)(arg1)) ;

/*
emit_instr: loc0 = /home/ubuntu/workspace/ATS2/prelude/DATS/integer.dats({$PATSPRE}/DATS/integer.dats): 11759(line=596, offs=12) -- 11790(line=596, offs=43)
*/
ATSINSmove(tmpret22, PMVtmpltcst(g0int_gte<S2Evar(tk(4621))>)(arg0, tmp23)) ;

ATSfunbody_end()
ATSreturn(tmpret22) ;
} /* end of [ATSLIB_056_prelude__gte_g0int_int__14] */
#endif // end of [TEMPLATE]

/*
/home/ubuntu/workspace/ATS2/prelude/DATS/integer.dats: 11750(line=596, offs=3) -- 11790(line=596, offs=43)
*/
/*
local: 
global: gte_g0int_int$14$1(level=2)
local: 
global: 
*/
ATSstatic()
/*
imparg = tk(4621)
tmparg = S2Evar(tk(4621))
tmpsub = Some(tk(4621) -> S2Eextkind(atstype_int))
*/
atstkind_t0ype(atstype_bool)
ATSLIB_056_prelude__gte_g0int_int__14__1(atstkind_t0ype(atstype_int) arg0, atstkind_t0ype(atstype_int) arg1)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret22__1, atstkind_t0ype(atstype_bool)) ;
ATStmpdec(tmp23__1, atstkind_t0ype(atstype_int)) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /home/ubuntu/workspace/ATS2/prelude/DATS/integer.dats({$PATSPRE}/DATS/integer.dats): 11734(line=595, offs=1) -- 11790(line=596, offs=43)
*/
ATSINSflab(__patsflab_gte_g0int_int):
/*
emit_instr: loc0 = /home/ubuntu/workspace/ATS2/prelude/DATS/integer.dats({$PATSPRE}/DATS/integer.dats): 11777(line=596, offs=30) -- 11788(line=596, offs=41)
*/
ATSINSmove(tmp23__1, atspre_g0int2int_int_int(arg1)) ;

/*
emit_instr: loc0 = /home/ubuntu/workspace/ATS2/prelude/DATS/integer.dats({$PATSPRE}/DATS/integer.dats): 11759(line=596, offs=12) -- 11790(line=596, offs=43)
*/
ATSINSmove(tmpret22__1, atspre_g0int_gte_int(arg0, tmp23__1)) ;

ATSfunbody_end()
ATSreturn(tmpret22__1) ;
} /* end of [ATSLIB_056_prelude__gte_g0int_int__14__1] */

#if(0)
/*
/home/ubuntu/workspace/ATS2/prelude/DATS/integer.dats: 11513(line=583, offs=3) -- 11552(line=583, offs=42)
*/
/*
local: 
global: lt_g0int_int$18$0(level=0)
local: 
global: 
*/
ATSextern()
/*
imparg = tk(4618)
tmparg = S2Evar(tk(4618))
tmpsub = None()
*/
atstkind_t0ype(atstype_bool)
ATSLIB_056_prelude__lt_g0int_int__18(atstkind_t0ype(atstyvar_type(tk)) arg0, atstkind_t0ype(atstype_int) arg1)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret30, atstkind_t0ype(atstype_bool)) ;
ATStmpdec(tmp31, atstkind_t0ype(atstyvar_type(tk))) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /home/ubuntu/workspace/ATS2/prelude/DATS/integer.dats({$PATSPRE}/DATS/integer.dats): 11498(line=582, offs=1) -- 11552(line=583, offs=42)
*/
ATSINSflab(__patsflab_lt_g0int_int):
/*
emit_instr: loc0 = /home/ubuntu/workspace/ATS2/prelude/DATS/integer.dats({$PATSPRE}/DATS/integer.dats): 11539(line=583, offs=29) -- 11550(line=583, offs=40)
*/
ATSINSmove(tmp31, PMVtmpltcst(g0int2int<S2Eextkind(atstype_int), S2Evar(tk(4618))>)(arg1)) ;

/*
emit_instr: loc0 = /home/ubuntu/workspace/ATS2/prelude/DATS/integer.dats({$PATSPRE}/DATS/integer.dats): 11522(line=583, offs=12) -- 11552(line=583, offs=42)
*/
ATSINSmove(tmpret30, PMVtmpltcst(g0int_lt<S2Evar(tk(4618))>)(arg0, tmp31)) ;

ATSfunbody_end()
ATSreturn(tmpret30) ;
} /* end of [ATSLIB_056_prelude__lt_g0int_int__18] */
#endif // end of [TEMPLATE]

/*
/home/ubuntu/workspace/ATS2/prelude/DATS/integer.dats: 11513(line=583, offs=3) -- 11552(line=583, offs=42)
*/
/*
local: 
global: lt_g0int_int$18$1(level=1)
local: 
global: 
*/
ATSstatic()
/*
imparg = tk(4618)
tmparg = S2Evar(tk(4618))
tmpsub = Some(tk(4618) -> S2Eextkind(atstype_int))
*/
atstkind_t0ype(atstype_bool)
ATSLIB_056_prelude__lt_g0int_int__18__1(atstkind_t0ype(atstype_int) arg0, atstkind_t0ype(atstype_int) arg1)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret30__1, atstkind_t0ype(atstype_bool)) ;
ATStmpdec(tmp31__1, atstkind_t0ype(atstype_int)) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /home/ubuntu/workspace/ATS2/prelude/DATS/integer.dats({$PATSPRE}/DATS/integer.dats): 11498(line=582, offs=1) -- 11552(line=583, offs=42)
*/
ATSINSflab(__patsflab_lt_g0int_int):
/*
emit_instr: loc0 = /home/ubuntu/workspace/ATS2/prelude/DATS/integer.dats({$PATSPRE}/DATS/integer.dats): 11539(line=583, offs=29) -- 11550(line=583, offs=40)
*/
ATSINSmove(tmp31__1, atspre_g0int2int_int_int(arg1)) ;

/*
emit_instr: loc0 = /home/ubuntu/workspace/ATS2/prelude/DATS/integer.dats({$PATSPRE}/DATS/integer.dats): 11522(line=583, offs=12) -- 11552(line=583, offs=42)
*/
ATSINSmove(tmpret30__1, atspre_g0int_lt_int(arg0, tmp31__1)) ;

ATSfunbody_end()
ATSreturn(tmpret30__1) ;
} /* end of [ATSLIB_056_prelude__lt_g0int_int__18__1] */

/*
/home/ubuntu/workspace/ATS2/prelude/DATS/integer.dats: 11513(line=583, offs=3) -- 11552(line=583, offs=42)
*/
/*
local: 
global: lt_g0int_int$18$2(level=1)
local: 
global: 
*/
ATSstatic()
/*
imparg = tk(4618)
tmparg = S2Evar(tk(4618))
tmpsub = Some(tk(4618) -> S2Eextkind(atstype_int))
*/
atstkind_t0ype(atstype_bool)
ATSLIB_056_prelude__lt_g0int_int__18__2(atstkind_t0ype(atstype_int) arg0, atstkind_t0ype(atstype_int) arg1)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret30__2, atstkind_t0ype(atstype_bool)) ;
ATStmpdec(tmp31__2, atstkind_t0ype(atstype_int)) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /home/ubuntu/workspace/ATS2/prelude/DATS/integer.dats({$PATSPRE}/DATS/integer.dats): 11498(line=582, offs=1) -- 11552(line=583, offs=42)
*/
ATSINSflab(__patsflab_lt_g0int_int):
/*
emit_instr: loc0 = /home/ubuntu/workspace/ATS2/prelude/DATS/integer.dats({$PATSPRE}/DATS/integer.dats): 11539(line=583, offs=29) -- 11550(line=583, offs=40)
*/
ATSINSmove(tmp31__2, atspre_g0int2int_int_int(arg1)) ;

/*
emit_instr: loc0 = /home/ubuntu/workspace/ATS2/prelude/DATS/integer.dats({$PATSPRE}/DATS/integer.dats): 11522(line=583, offs=12) -- 11552(line=583, offs=42)
*/
ATSINSmove(tmpret30__2, atspre_g0int_lt_int(arg0, tmp31__2)) ;

ATSfunbody_end()
ATSreturn(tmpret30__2) ;
} /* end of [ATSLIB_056_prelude__lt_g0int_int__18__2] */

/*
/home/ubuntu/workspace/ATS2/prelude/DATS/integer.dats: 11831(line=601, offs=3) -- 11870(line=601, offs=42)
*/
/*
local: 
global: eq_g0int_int$7$2(level=1)
local: 
global: 
*/
ATSstatic()
/*
imparg = tk(4622)
tmparg = S2Evar(tk(4622))
tmpsub = Some(tk(4622) -> S2Eextkind(atstype_int))
*/
atstkind_t0ype(atstype_bool)
ATSLIB_056_prelude__eq_g0int_int__7__2(atstkind_t0ype(atstype_int) arg0, atstkind_t0ype(atstype_int) arg1)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret9__2, atstkind_t0ype(atstype_bool)) ;
ATStmpdec(tmp10__2, atstkind_t0ype(atstype_int)) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /home/ubuntu/workspace/ATS2/prelude/DATS/integer.dats({$PATSPRE}/DATS/integer.dats): 11816(line=600, offs=1) -- 11870(line=601, offs=42)
*/
ATSINSflab(__patsflab_eq_g0int_int):
/*
emit_instr: loc0 = /home/ubuntu/workspace/ATS2/prelude/DATS/integer.dats({$PATSPRE}/DATS/integer.dats): 11857(line=601, offs=29) -- 11868(line=601, offs=40)
*/
ATSINSmove(tmp10__2, atspre_g0int2int_int_int(arg1)) ;

/*
emit_instr: loc0 = /home/ubuntu/workspace/ATS2/prelude/DATS/integer.dats({$PATSPRE}/DATS/integer.dats): 11840(line=601, offs=12) -- 11870(line=601, offs=42)
*/
ATSINSmove(tmpret9__2, atspre_g0int_eq_int(arg0, tmp10__2)) ;

ATSfunbody_end()
ATSreturn(tmpret9__2) ;
} /* end of [ATSLIB_056_prelude__eq_g0int_int__7__2] */

/*
/home/ubuntu/workspace/RosettaATS/middle_three_digits/digits.dats: 1011(line=46, offs=17) -- 1158(line=56, offs=2)
*/
/*
local: get3mid_0$0(level=0)
global: get3mid_0$0(level=0), mainats_void_0$24$0(level=0)
local: 
global: 
*/
ATSextern()
atsvoid_t0ype
mainats_void_0()
{
/* tmpvardeclst(beg) */
// ATStmpdec_void(tmpret62) ;
// ATStmpdec_void(tmp63) ;
// ATStmpdec_void(tmp64) ;
// ATStmpdec_void(tmp65) ;
ATStmpdec(tmp66, atstkind_t0ype(atstype_int)) ;
// ATStmpdec_void(tmp67) ;
ATStmpdec(tmp68, atstkind_t0ype(atstype_int)) ;
// ATStmpdec_void(tmp69) ;
ATStmpdec(tmp70, atstkind_t0ype(atstype_int)) ;
// ATStmpdec_void(tmp71) ;
// ATStmpdec_void(tmp72) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /home/ubuntu/workspace/RosettaATS/middle_three_digits/digits.dats: 1005(line=46, offs=11) -- 1158(line=56, offs=2)
*/
ATSINSflab(__patsflab_main_void_0):
/*
emit_instr: loc0 = /home/ubuntu/workspace/RosettaATS/middle_three_digits/digits.dats: 1021(line=48, offs=3) -- 1035(line=48, offs=17)
*/
ATSINSmove_void(tmp63, get3mid_0(ATSPMVi0nt(12345))) ;

/*
emit_instr: loc0 = /home/ubuntu/workspace/RosettaATS/middle_three_digits/digits.dats: 1039(line=49, offs=3) -- 1054(line=49, offs=18)
*/
ATSINSmove_void(tmp64, get3mid_0(ATSPMVi0nt(234123))) ;

/*
emit_instr: loc0 = /home/ubuntu/workspace/RosettaATS/middle_three_digits/digits.dats: 1066(line=50, offs=11) -- 1074(line=50, offs=19)
*/
ATSINSmove(tmp66, atspre_g1int_neg_int(ATSPMVi0nt(3421353))) ;

/*
emit_instr: loc0 = /home/ubuntu/workspace/RosettaATS/middle_three_digits/digits.dats: 1058(line=50, offs=3) -- 1075(line=50, offs=20)
*/
ATSINSmove_void(tmp65, get3mid_0(tmp66)) ;

/*
emit_instr: loc0 = /home/ubuntu/workspace/RosettaATS/middle_three_digits/digits.dats: 1087(line=51, offs=11) -- 1090(line=51, offs=14)
*/
ATSINSmove(tmp68, atspre_g1int_neg_int(ATSPMVi0nt(12))) ;

/*
emit_instr: loc0 = /home/ubuntu/workspace/RosettaATS/middle_three_digits/digits.dats: 1079(line=51, offs=3) -- 1091(line=51, offs=15)
*/
ATSINSmove_void(tmp67, get3mid_0(tmp68)) ;

/*
emit_instr: loc0 = /home/ubuntu/workspace/RosettaATS/middle_three_digits/digits.dats: 1103(line=52, offs=11) -- 1107(line=52, offs=15)
*/
ATSINSmove(tmp70, atspre_g1int_neg_int(ATSPMVi0nt(325))) ;

/*
emit_instr: loc0 = /home/ubuntu/workspace/RosettaATS/middle_three_digits/digits.dats: 1095(line=52, offs=3) -- 1108(line=52, offs=16)
*/
ATSINSmove_void(tmp69, get3mid_0(tmp70)) ;

/*
emit_instr: loc0 = /home/ubuntu/workspace/RosettaATS/middle_three_digits/digits.dats: 1112(line=53, offs=3) -- 1124(line=53, offs=15)
*/
ATSINSmove_void(tmp71, get3mid_0(ATSPMVi0nt(275))) ;

/*
emit_instr: loc0 = /home/ubuntu/workspace/RosettaATS/middle_three_digits/digits.dats: 1128(line=54, offs=3) -- 1141(line=54, offs=16)
*/
ATSINSmove_void(tmp72, get3mid_0(ATSPMVi0nt(9999))) ;

/*
emit_instr: loc0 = /home/ubuntu/workspace/RosettaATS/middle_three_digits/digits.dats: 1145(line=55, offs=3) -- 1155(line=55, offs=13)
*/
ATSINSmove_void(tmpret62, get3mid_0(ATSPMVi0nt(0))) ;

ATSfunbody_end()
ATSreturn_void(tmpret62) ;
} /* end of [mainats_void_0] */

/*
** for initialization(dynloading)
*/
ATSdynloadflag_minit(_057_home_057_ubuntu_057_workspace_057_RosettaATS_057_middle_three_digits_057_digits_056_dats__dynloadflag) ;
ATSextern()
atsvoid_t0ype
_057_home_057_ubuntu_057_workspace_057_RosettaATS_057_middle_three_digits_057_digits_056_dats__dynload()
{
ATSfunbody_beg()
ATSdynload(/*void*/)
ATSdynloadflag_sta(
_057_home_057_ubuntu_057_workspace_057_RosettaATS_057_middle_three_digits_057_digits_056_dats__dynloadflag
) ;
ATSif(
ATSCKiseqz(
_057_home_057_ubuntu_057_workspace_057_RosettaATS_057_middle_three_digits_057_digits_056_dats__dynloadflag
)
) ATSthen() {
ATSdynloadset(_057_home_057_ubuntu_057_workspace_057_RosettaATS_057_middle_three_digits_057_digits_056_dats__dynloadflag) ;
/*
dynexnlst-initize(beg)
*/
/*
dynexnlst-initize(end)
*/
} /* ATSendif */
ATSfunbody_end()
ATSreturn_void(tmpret_void) ;
} /* end of [*_dynload] */

/*
** the ATS runtime
*/
#ifndef _ATS_CCOMP_RUNTIME_NONE_
#include "pats_ccomp_runtime.c"
#include "pats_ccomp_runtime_memalloc.c"
#ifndef _ATS_CCOMP_EXCEPTION_NONE_
#include "pats_ccomp_runtime2_dats.c"
#ifndef _ATS_CCOMP_RUNTIME_TRYWITH_NONE_
#include "pats_ccomp_runtime_trywith.c"
#endif /* _ATS_CCOMP_RUNTIME_TRYWITH_NONE_ */
#endif // end of [_ATS_CCOMP_EXCEPTION_NONE_]
#endif /* _ATS_CCOMP_RUNTIME_NONE_ */

/*
** the [main] implementation
*/
int
main
(
int argc, char **argv, char **envp
) {
int err = 0 ;
_057_home_057_ubuntu_057_workspace_057_RosettaATS_057_middle_three_digits_057_digits_056_dats__dynload() ;
ATSmainats_void_0(err) ;
return (err) ;
} /* end of [main] */

/* ****** ****** */

/* end-of-compilation-unit */
