/*
**
** The C code is generated by [ATS/Postiats-0-2-13]
** The starting compilation time is: 2017-1-4:  0h: 6m
**
*/

/*
** include runtime header files
*/
#ifndef _ATS_CCOMP_HEADER_NONE_
#include "pats_ccomp_config.h"
#include "pats_ccomp_basics.h"
#include "pats_ccomp_typedefs.h"
#include "pats_ccomp_instrset.h"
#include "pats_ccomp_memalloc.h"
#ifndef _ATS_CCOMP_EXCEPTION_NONE_
#include "pats_ccomp_memalloca.h"
#include "pats_ccomp_exception.h"
#endif // end of [_ATS_CCOMP_EXCEPTION_NONE_]
#endif /* _ATS_CCOMP_HEADER_NONE_ */


/*
** include prelude cats files
*/
#ifndef _ATS_CCOMP_PRELUDE_NONE_
//
#include "prelude/CATS/basics.cats"
#include "prelude/CATS/integer.cats"
#include "prelude/CATS/pointer.cats"
#include "prelude/CATS/integer_long.cats"
#include "prelude/CATS/integer_size.cats"
#include "prelude/CATS/integer_short.cats"
#include "prelude/CATS/bool.cats"
#include "prelude/CATS/char.cats"
#include "prelude/CATS/float.cats"
#include "prelude/CATS/integer_ptr.cats"
#include "prelude/CATS/integer_fixed.cats"
#include "prelude/CATS/memory.cats"
#include "prelude/CATS/string.cats"
#include "prelude/CATS/strptr.cats"
//
#include "prelude/CATS/fprintf.cats"
//
#include "prelude/CATS/filebas.cats"
//
#include "prelude/CATS/list.cats"
#include "prelude/CATS/option.cats"
#include "prelude/CATS/array.cats"
#include "prelude/CATS/arrayptr.cats"
#include "prelude/CATS/arrayref.cats"
#include "prelude/CATS/matrix.cats"
#include "prelude/CATS/matrixptr.cats"
//
#endif /* _ATS_CCOMP_PRELUDE_NONE_ */
/*
** for user-supplied prelude
*/
#ifdef _ATS_CCOMP_PRELUDE_USER_
//
#include _ATS_CCOMP_PRELUDE_USER_
//
#endif /* _ATS_CCOMP_PRELUDE_USER_ */
/*
** for user2-supplied prelude
*/
#ifdef _ATS_CCOMP_PRELUDE_USER2_
//
#include _ATS_CCOMP_PRELUDE_USER2_
//
#endif /* _ATS_CCOMP_PRELUDE_USER2_ */

/*
staload-prologues(beg)
*/
/*
/home/ubuntu/workspace/ATS2/prelude/DATS/basics.dats: 1534(line=44, offs=1) -- 1573(line=45, offs=32)
*/
/*
/home/ubuntu/workspace/ATS2/prelude/DATS/integer.dats: 1596(line=49, offs=1) -- 1635(line=49, offs=40)
*/
/*
/home/ubuntu/workspace/ATS2/prelude/DATS/pointer.dats: 1533(line=44, offs=1) -- 1572(line=44, offs=40)
*/
/*
/home/ubuntu/workspace/ATS2/prelude/DATS/integer_long.dats: 1602(line=49, offs=1) -- 1641(line=49, offs=40)
*/
/*
/home/ubuntu/workspace/ATS2/prelude/DATS/integer_size.dats: 1597(line=49, offs=1) -- 1636(line=49, offs=40)
*/
/*
/home/ubuntu/workspace/ATS2/prelude/DATS/integer_short.dats: 1603(line=49, offs=1) -- 1642(line=49, offs=40)
*/
/*
/home/ubuntu/workspace/ATS2/prelude/DATS/char.dats: 1610(line=48, offs=1) -- 1649(line=48, offs=40)
*/
/*
/home/ubuntu/workspace/ATS2/prelude/DATS/float.dats: 1636(line=50, offs=1) -- 1675(line=50, offs=40)
*/
/*
/home/ubuntu/workspace/ATS2/prelude/DATS/string.dats: 1609(line=48, offs=1) -- 1648(line=48, offs=40)
*/
/*
/home/ubuntu/workspace/ATS2/prelude/DATS/strptr.dats: 1609(line=48, offs=1) -- 1648(line=48, offs=40)
*/
/*
/home/ubuntu/workspace/ATS2/prelude/DATS/strptr.dats: 1671(line=52, offs=1) -- 1718(line=52, offs=48)
*/
/*
/home/ubuntu/workspace/ATS2/prelude/DATS/integer.dats: 1596(line=49, offs=1) -- 1635(line=49, offs=40)
*/
/*
/home/ubuntu/workspace/ATS2/prelude/DATS/integer_ptr.dats: 1601(line=49, offs=1) -- 1640(line=49, offs=40)
*/
/*
/home/ubuntu/workspace/ATS2/prelude/DATS/integer_fixed.dats: 1603(line=49, offs=1) -- 1642(line=49, offs=40)
*/
/*
/home/ubuntu/workspace/ATS2/prelude/DATS/memory.dats: 1410(line=38, offs=1) -- 1449(line=39, offs=32)
*/
/*
/home/ubuntu/workspace/ATS2/prelude/DATS/filebas.dats: 1613(line=49, offs=1) -- 1652(line=50, offs=32)
*/
/*
/home/ubuntu/workspace/ATS2/prelude/DATS/filebas.dats: 1675(line=54, offs=1) -- 1721(line=55, offs=39)
*/
/*
/home/ubuntu/workspace/ATS2/prelude/DATS/integer.dats: 1596(line=49, offs=1) -- 1635(line=49, offs=40)
*/
/*
/home/ubuntu/workspace/ATS2/prelude/DATS/filebas.dats: 1744(line=59, offs=1) -- 1789(line=60, offs=38)
*/
/*
/home/ubuntu/workspace/ATS2/libats/libc/SATS/stdio.sats: 1390(line=36, offs=1) -- 1437(line=39, offs=3)
*/

#include \
"libats/libc/CATS/stdio.cats"
/*
/home/ubuntu/workspace/ATS2/libats/libc/SATS/stdio.sats: 1950(line=69, offs=1) -- 1999(line=71, offs=34)
*/
/*
/home/ubuntu/workspace/ATS2/libats/libc/SATS/sys/types.sats: 1390(line=36, offs=1) -- 1441(line=39, offs=3)
*/

#include \
"libats/libc/CATS/sys/types.cats"
/*
/home/ubuntu/workspace/ATS2/prelude/DATS/filebas.dats: 1871(line=66, offs=1) -- 1918(line=66, offs=48)
*/
/*
/home/ubuntu/workspace/ATS2/libats/libc/SATS/sys/stat.sats: 1390(line=36, offs=1) -- 1440(line=39, offs=3)
*/

#include \
"libats/libc/CATS/sys/stat.cats"
/*
/home/ubuntu/workspace/ATS2/libats/libc/SATS/sys/stat.sats: 1756(line=58, offs=1) -- 1805(line=60, offs=34)
*/
/*
/home/ubuntu/workspace/ATS2/libats/libc/SATS/sys/types.sats: 1390(line=36, offs=1) -- 1441(line=39, offs=3)
*/

#include \
"libats/libc/CATS/sys/types.cats"
/*
/home/ubuntu/workspace/ATS2/prelude/DATS/filebas.dats: 15413(line=857, offs=1) -- 15450(line=858, offs=30)
*/
/*
/home/ubuntu/workspace/ATS2/libats/libc/SATS/stdio.sats: 1390(line=36, offs=1) -- 1437(line=39, offs=3)
*/

#include \
"libats/libc/CATS/stdio.cats"
/*
/home/ubuntu/workspace/ATS2/libats/libc/SATS/stdio.sats: 1950(line=69, offs=1) -- 1999(line=71, offs=34)
*/
/*
/home/ubuntu/workspace/ATS2/libats/libc/SATS/sys/types.sats: 1390(line=36, offs=1) -- 1441(line=39, offs=3)
*/

#include \
"libats/libc/CATS/sys/types.cats"
/*
/home/ubuntu/workspace/ATS2/prelude/DATS/list.dats: 1529(line=44, offs=1) -- 1568(line=45, offs=32)
*/
/*
/home/ubuntu/workspace/ATS2/prelude/DATS/list.dats: 1569(line=46, offs=1) -- 1615(line=47, offs=39)
*/
/*
/home/ubuntu/workspace/ATS2/prelude/DATS/unsafe.dats: 1532(line=44, offs=1) -- 1566(line=44, offs=35)
*/
/*
/home/ubuntu/workspace/ATS2/prelude/DATS/list_vt.dats: 1538(line=44, offs=1) -- 1577(line=45, offs=32)
*/
/*
/home/ubuntu/workspace/ATS2/prelude/DATS/list_vt.dats: 1578(line=46, offs=1) -- 1624(line=47, offs=39)
*/
/*
/home/ubuntu/workspace/ATS2/prelude/DATS/unsafe.dats: 1532(line=44, offs=1) -- 1566(line=44, offs=35)
*/
/*
/home/ubuntu/workspace/ATS2/prelude/DATS/array.dats: 1534(line=44, offs=1) -- 1573(line=44, offs=40)
*/
/*
/home/ubuntu/workspace/ATS2/prelude/DATS/array.dats: 1574(line=45, offs=1) -- 1616(line=45, offs=43)
*/
/*
/home/ubuntu/workspace/ATS2/prelude/DATS/arrayptr.dats: 1532(line=44, offs=1) -- 1571(line=44, offs=40)
*/
/*
/home/ubuntu/workspace/ATS2/prelude/DATS/arrayref.dats: 1532(line=44, offs=1) -- 1571(line=44, offs=40)
*/
/*
/home/ubuntu/workspace/ATS2/prelude/DATS/matrix.dats: 1535(line=44, offs=1) -- 1574(line=44, offs=40)
*/
/*
/home/ubuntu/workspace/ATS2/prelude/DATS/matrixptr.dats: 1538(line=44, offs=1) -- 1577(line=44, offs=40)
*/
/*
/home/ubuntu/workspace/ATS2/prelude/DATS/matrixref.dats: 1538(line=44, offs=1) -- 1577(line=44, offs=40)
*/
/*
/home/ubuntu/workspace/ATS2/prelude/DATS/stream.dats: 1523(line=44, offs=1) -- 1562(line=44, offs=40)
*/
/*
/home/ubuntu/workspace/ATS2/prelude/DATS/stream_vt.dats: 1523(line=44, offs=1) -- 1562(line=44, offs=40)
*/
/*
/home/ubuntu/workspace/ATS2/prelude/DATS/tostring.dats: 1528(line=44, offs=1) -- 1567(line=45, offs=32)
*/
/*
/home/ubuntu/workspace/ATS2/prelude/DATS/unsafe.dats: 1532(line=44, offs=1) -- 1566(line=44, offs=35)
*/
/*
/home/ubuntu/workspace/ATS2/prelude/DATS/checkast.dats: 1531(line=44, offs=1) -- 1570(line=45, offs=32)
*/
/*
staload-prologues(end)
*/
/*
typedefs-for-tyrecs-and-tysums(beg)
*/
/*
typedefs-for-tyrecs-and-tysums(end)
*/
/*
dynconlst-declaration(beg)
*/
/*
dynconlst-declaration(end)
*/
/*
dyncstlst-declaration(beg)
*/
ATSdyncst_mac(atspre_g0float_add_double)
ATSdyncst_mac(atspre_g0float_sub_double)
ATSdyncst_mac(atspre_mul_double_int)
ATSdyncst_mac(atspre_div_double_int)
ATSdyncst_extfun(_057_home_057_ubuntu_057_workspace_057_RosettaATS_057_temperature_conversion_057_temperature_056_dats__k2r, (atstkind_t0ype(atstype_double)), atstkind_t0ype(atstype_double)) ;
ATSdyncst_extfun(_057_home_057_ubuntu_057_workspace_057_RosettaATS_057_temperature_conversion_057_temperature_056_dats__c2k, (atstkind_t0ype(atstype_double)), atstkind_t0ype(atstype_double)) ;
ATSdyncst_extfun(_057_home_057_ubuntu_057_workspace_057_RosettaATS_057_temperature_conversion_057_temperature_056_dats__k2c, (atstkind_t0ype(atstype_double)), atstkind_t0ype(atstype_double)) ;
ATSdyncst_extfun(_057_home_057_ubuntu_057_workspace_057_RosettaATS_057_temperature_conversion_057_temperature_056_dats__r2k, (atstkind_t0ype(atstype_double)), atstkind_t0ype(atstype_double)) ;
ATSdyncst_extfun(_057_home_057_ubuntu_057_workspace_057_RosettaATS_057_temperature_conversion_057_temperature_056_dats__r2f, (atstkind_t0ype(atstype_double)), atstkind_t0ype(atstype_double)) ;
ATSdyncst_extfun(_057_home_057_ubuntu_057_workspace_057_RosettaATS_057_temperature_conversion_057_temperature_056_dats__f2r, (atstkind_t0ype(atstype_double)), atstkind_t0ype(atstype_double)) ;
ATSdyncst_mac(atspre_print_string)
ATSdyncst_mac(atspre_print_double)
ATSdyncst_mac(atspre_print_newline)
ATSdyncst_extfun(_057_home_057_ubuntu_057_workspace_057_RosettaATS_057_temperature_conversion_057_temperature_056_dats__k2f, (atstkind_t0ype(atstype_double)), atstkind_t0ype(atstype_double)) ;
/*
dyncstlst-declaration(end)
*/
/*
dynvalist-implementation(beg)
*/
/*
dynvalist-implementation(end)
*/
/*
exnconlst-declaration(beg)
*/
#ifndef _ATS_CCOMP_EXCEPTION_NONE_
ATSextern()
atsvoid_t0ype
the_atsexncon_initize
(
  atstype_exnconptr d2c, atstype_string exnmsg
) ;
#endif // end of [_ATS_CCOMP_EXCEPTION_NONE_]
/*
exnconlst-declaration(end)
*/
/*
assumelst-declaration(beg)
*/
/*
assumelst-declaration(end)
*/
/*
extypelst-declaration(beg)
*/
/*
extypelst-declaration(end)
*/
#if(0)
ATSextern()
atstkind_t0ype(atstype_double)
_057_home_057_ubuntu_057_workspace_057_RosettaATS_057_temperature_conversion_057_temperature_056_dats__c2k(atstkind_t0ype(atstype_double)) ;
#endif // end of [QUALIFIED]

#if(0)
ATSextern()
atstkind_t0ype(atstype_double)
_057_home_057_ubuntu_057_workspace_057_RosettaATS_057_temperature_conversion_057_temperature_056_dats__k2c(atstkind_t0ype(atstype_double)) ;
#endif // end of [QUALIFIED]

#if(0)
ATSextern()
atstkind_t0ype(atstype_double)
_057_home_057_ubuntu_057_workspace_057_RosettaATS_057_temperature_conversion_057_temperature_056_dats__k2r(atstkind_t0ype(atstype_double)) ;
#endif // end of [QUALIFIED]

#if(0)
ATSextern()
atstkind_t0ype(atstype_double)
_057_home_057_ubuntu_057_workspace_057_RosettaATS_057_temperature_conversion_057_temperature_056_dats__r2k(atstkind_t0ype(atstype_double)) ;
#endif // end of [QUALIFIED]

#if(0)
ATSextern()
atstkind_t0ype(atstype_double)
_057_home_057_ubuntu_057_workspace_057_RosettaATS_057_temperature_conversion_057_temperature_056_dats__r2f(atstkind_t0ype(atstype_double)) ;
#endif // end of [QUALIFIED]

#if(0)
ATSextern()
atstkind_t0ype(atstype_double)
_057_home_057_ubuntu_057_workspace_057_RosettaATS_057_temperature_conversion_057_temperature_056_dats__f2r(atstkind_t0ype(atstype_double)) ;
#endif // end of [QUALIFIED]

#if(0)
ATSextern()
atstkind_t0ype(atstype_double)
_057_home_057_ubuntu_057_workspace_057_RosettaATS_057_temperature_conversion_057_temperature_056_dats__c2r(atstkind_t0ype(atstype_double)) ;
#endif // end of [QUALIFIED]

#if(0)
ATSextern()
atstkind_t0ype(atstype_double)
_057_home_057_ubuntu_057_workspace_057_RosettaATS_057_temperature_conversion_057_temperature_056_dats__r2c(atstkind_t0ype(atstype_double)) ;
#endif // end of [QUALIFIED]

#if(0)
ATSextern()
atstkind_t0ype(atstype_double)
_057_home_057_ubuntu_057_workspace_057_RosettaATS_057_temperature_conversion_057_temperature_056_dats__k2f(atstkind_t0ype(atstype_double)) ;
#endif // end of [QUALIFIED]

#if(0)
ATSextern()
atstkind_t0ype(atstype_double)
_057_home_057_ubuntu_057_workspace_057_RosettaATS_057_temperature_conversion_057_temperature_056_dats__f2k(atstkind_t0ype(atstype_double)) ;
#endif // end of [QUALIFIED]

#if(0)
ATSextern()
atstkind_t0ype(atstype_double)
_057_home_057_ubuntu_057_workspace_057_RosettaATS_057_temperature_conversion_057_temperature_056_dats__c2f(atstkind_t0ype(atstype_double)) ;
#endif // end of [QUALIFIED]

#if(0)
ATSextern()
atstkind_t0ype(atstype_double)
_057_home_057_ubuntu_057_workspace_057_RosettaATS_057_temperature_conversion_057_temperature_056_dats__f2c(atstkind_t0ype(atstype_double)) ;
#endif // end of [QUALIFIED]

#if(0)
ATSextern()
atsvoid_t0ype
mainats_void_0() ;
#endif // end of [QUALIFIED]

/*
/home/ubuntu/workspace/RosettaATS/temperature_conversion/temperature.dats: 566(line=59, offs=4) -- 582(line=59, offs=20)
*/
/*
local: 
global: c2k$0$0(level=0)
local: 
global: 
*/
ATSextern()
atstkind_t0ype(atstype_double)
_057_home_057_ubuntu_057_workspace_057_RosettaATS_057_temperature_conversion_057_temperature_056_dats__c2k(atstkind_t0ype(atstype_double) arg0)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret0, atstkind_t0ype(atstype_double)) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /home/ubuntu/workspace/RosettaATS/temperature_conversion/temperature.dats: 563(line=59, offs=1) -- 582(line=59, offs=20)
*/
ATSINSflab(__patsflab_c2k):
/*
emit_instr: loc0 = /home/ubuntu/workspace/RosettaATS/temperature_conversion/temperature.dats: 572(line=59, offs=10) -- 582(line=59, offs=20)
*/
ATSINSmove(tmpret0, atspre_g0float_add_double(arg0, ATSPMVf0loat(273.15))) ;

ATSfunbody_end()
ATSreturn(tmpret0) ;
} /* end of [_057_home_057_ubuntu_057_workspace_057_RosettaATS_057_temperature_conversion_057_temperature_056_dats__c2k] */

/*
/home/ubuntu/workspace/RosettaATS/temperature_conversion/temperature.dats: 597(line=62, offs=4) -- 613(line=62, offs=20)
*/
/*
local: 
global: k2c$2$0(level=0)
local: 
global: 
*/
ATSextern()
atstkind_t0ype(atstype_double)
_057_home_057_ubuntu_057_workspace_057_RosettaATS_057_temperature_conversion_057_temperature_056_dats__k2c(atstkind_t0ype(atstype_double) arg0)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret1, atstkind_t0ype(atstype_double)) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /home/ubuntu/workspace/RosettaATS/temperature_conversion/temperature.dats: 594(line=62, offs=1) -- 613(line=62, offs=20)
*/
ATSINSflab(__patsflab_k2c):
/*
emit_instr: loc0 = /home/ubuntu/workspace/RosettaATS/temperature_conversion/temperature.dats: 603(line=62, offs=10) -- 613(line=62, offs=20)
*/
ATSINSmove(tmpret1, atspre_g0float_sub_double(arg0, ATSPMVf0loat(273.15))) ;

ATSfunbody_end()
ATSreturn(tmpret1) ;
} /* end of [_057_home_057_ubuntu_057_workspace_057_RosettaATS_057_temperature_conversion_057_temperature_056_dats__k2c] */

/*
/home/ubuntu/workspace/RosettaATS/temperature_conversion/temperature.dats: 628(line=65, offs=4) -- 645(line=65, offs=21)
*/
/*
local: 
global: k2r$4$0(level=0)
local: 
global: 
*/
ATSextern()
atstkind_t0ype(atstype_double)
_057_home_057_ubuntu_057_workspace_057_RosettaATS_057_temperature_conversion_057_temperature_056_dats__k2r(atstkind_t0ype(atstype_double) arg0)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret2, atstkind_t0ype(atstype_double)) ;
ATStmpdec(tmp3, atstkind_t0ype(atstype_double)) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /home/ubuntu/workspace/RosettaATS/temperature_conversion/temperature.dats: 625(line=65, offs=1) -- 645(line=65, offs=21)
*/
ATSINSflab(__patsflab_k2r):
/*
emit_instr: loc0 = /home/ubuntu/workspace/RosettaATS/temperature_conversion/temperature.dats: 635(line=65, offs=11) -- 640(line=65, offs=16)
*/
ATSINSmove(tmp3, atspre_div_double_int(arg0, ATSPMVi0nt(5))) ;

/*
emit_instr: loc0 = /home/ubuntu/workspace/RosettaATS/temperature_conversion/temperature.dats: 634(line=65, offs=10) -- 645(line=65, offs=21)
*/
ATSINSmove(tmpret2, atspre_mul_double_int(tmp3, ATSPMVi0nt(9))) ;

ATSfunbody_end()
ATSreturn(tmpret2) ;
} /* end of [_057_home_057_ubuntu_057_workspace_057_RosettaATS_057_temperature_conversion_057_temperature_056_dats__k2r] */

/*
/home/ubuntu/workspace/RosettaATS/temperature_conversion/temperature.dats: 660(line=68, offs=4) -- 677(line=68, offs=21)
*/
/*
local: 
global: r2k$5$0(level=0)
local: 
global: 
*/
ATSextern()
atstkind_t0ype(atstype_double)
_057_home_057_ubuntu_057_workspace_057_RosettaATS_057_temperature_conversion_057_temperature_056_dats__r2k(atstkind_t0ype(atstype_double) arg0)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret4, atstkind_t0ype(atstype_double)) ;
ATStmpdec(tmp5, atstkind_t0ype(atstype_double)) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /home/ubuntu/workspace/RosettaATS/temperature_conversion/temperature.dats: 657(line=68, offs=1) -- 677(line=68, offs=21)
*/
ATSINSflab(__patsflab_r2k):
/*
emit_instr: loc0 = /home/ubuntu/workspace/RosettaATS/temperature_conversion/temperature.dats: 667(line=68, offs=11) -- 672(line=68, offs=16)
*/
ATSINSmove(tmp5, atspre_div_double_int(arg0, ATSPMVi0nt(9))) ;

/*
emit_instr: loc0 = /home/ubuntu/workspace/RosettaATS/temperature_conversion/temperature.dats: 666(line=68, offs=10) -- 677(line=68, offs=21)
*/
ATSINSmove(tmpret4, atspre_mul_double_int(tmp5, ATSPMVi0nt(5))) ;

ATSfunbody_end()
ATSreturn(tmpret4) ;
} /* end of [_057_home_057_ubuntu_057_workspace_057_RosettaATS_057_temperature_conversion_057_temperature_056_dats__r2k] */

/*
/home/ubuntu/workspace/RosettaATS/temperature_conversion/temperature.dats: 692(line=71, offs=4) -- 708(line=71, offs=20)
*/
/*
local: 
global: r2f$6$0(level=0)
local: 
global: 
*/
ATSextern()
atstkind_t0ype(atstype_double)
_057_home_057_ubuntu_057_workspace_057_RosettaATS_057_temperature_conversion_057_temperature_056_dats__r2f(atstkind_t0ype(atstype_double) arg0)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret6, atstkind_t0ype(atstype_double)) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /home/ubuntu/workspace/RosettaATS/temperature_conversion/temperature.dats: 689(line=71, offs=1) -- 708(line=71, offs=20)
*/
ATSINSflab(__patsflab_r2f):
/*
emit_instr: loc0 = /home/ubuntu/workspace/RosettaATS/temperature_conversion/temperature.dats: 698(line=71, offs=10) -- 708(line=71, offs=20)
*/
ATSINSmove(tmpret6, atspre_g0float_sub_double(arg0, ATSPMVf0loat(459.67))) ;

ATSfunbody_end()
ATSreturn(tmpret6) ;
} /* end of [_057_home_057_ubuntu_057_workspace_057_RosettaATS_057_temperature_conversion_057_temperature_056_dats__r2f] */

/*
/home/ubuntu/workspace/RosettaATS/temperature_conversion/temperature.dats: 723(line=74, offs=4) -- 739(line=74, offs=20)
*/
/*
local: 
global: f2r$7$0(level=0)
local: 
global: 
*/
ATSextern()
atstkind_t0ype(atstype_double)
_057_home_057_ubuntu_057_workspace_057_RosettaATS_057_temperature_conversion_057_temperature_056_dats__f2r(atstkind_t0ype(atstype_double) arg0)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret7, atstkind_t0ype(atstype_double)) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /home/ubuntu/workspace/RosettaATS/temperature_conversion/temperature.dats: 720(line=74, offs=1) -- 739(line=74, offs=20)
*/
ATSINSflab(__patsflab_f2r):
/*
emit_instr: loc0 = /home/ubuntu/workspace/RosettaATS/temperature_conversion/temperature.dats: 729(line=74, offs=10) -- 739(line=74, offs=20)
*/
ATSINSmove(tmpret7, atspre_g0float_add_double(arg0, ATSPMVf0loat(459.67))) ;

ATSfunbody_end()
ATSreturn(tmpret7) ;
} /* end of [_057_home_057_ubuntu_057_workspace_057_RosettaATS_057_temperature_conversion_057_temperature_056_dats__f2r] */

/*
/home/ubuntu/workspace/RosettaATS/temperature_conversion/temperature.dats: 754(line=77, offs=4) -- 771(line=77, offs=21)
*/
/*
local: 
global: c2r$8$0(level=0)
local: 
global: 
*/
ATSextern()
atstkind_t0ype(atstype_double)
_057_home_057_ubuntu_057_workspace_057_RosettaATS_057_temperature_conversion_057_temperature_056_dats__c2r(atstkind_t0ype(atstype_double) arg0)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret8, atstkind_t0ype(atstype_double)) ;
ATStmpdec(tmp9, atstkind_t0ype(atstype_double)) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /home/ubuntu/workspace/RosettaATS/temperature_conversion/temperature.dats: 751(line=77, offs=1) -- 771(line=77, offs=21)
*/
ATSINSflab(__patsflab_c2r):
/*
emit_instr: loc0 = /home/ubuntu/workspace/RosettaATS/temperature_conversion/temperature.dats: 764(line=77, offs=14) -- 769(line=77, offs=19)
*/
ATSINSmove(tmp9, _057_home_057_ubuntu_057_workspace_057_RosettaATS_057_temperature_conversion_057_temperature_056_dats__c2k(arg0)) ;

/*
emit_instr: loc0 = /home/ubuntu/workspace/RosettaATS/temperature_conversion/temperature.dats: 760(line=77, offs=10) -- 771(line=77, offs=21)
*/
ATSINSmove(tmpret8, _057_home_057_ubuntu_057_workspace_057_RosettaATS_057_temperature_conversion_057_temperature_056_dats__k2r(tmp9)) ;

ATSfunbody_end()
ATSreturn(tmpret8) ;
} /* end of [_057_home_057_ubuntu_057_workspace_057_RosettaATS_057_temperature_conversion_057_temperature_056_dats__c2r] */

/*
/home/ubuntu/workspace/RosettaATS/temperature_conversion/temperature.dats: 786(line=80, offs=4) -- 803(line=80, offs=21)
*/
/*
local: 
global: r2c$9$0(level=0)
local: 
global: 
*/
ATSextern()
atstkind_t0ype(atstype_double)
_057_home_057_ubuntu_057_workspace_057_RosettaATS_057_temperature_conversion_057_temperature_056_dats__r2c(atstkind_t0ype(atstype_double) arg0)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret10, atstkind_t0ype(atstype_double)) ;
ATStmpdec(tmp11, atstkind_t0ype(atstype_double)) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /home/ubuntu/workspace/RosettaATS/temperature_conversion/temperature.dats: 783(line=80, offs=1) -- 803(line=80, offs=21)
*/
ATSINSflab(__patsflab_r2c):
/*
emit_instr: loc0 = /home/ubuntu/workspace/RosettaATS/temperature_conversion/temperature.dats: 796(line=80, offs=14) -- 801(line=80, offs=19)
*/
ATSINSmove(tmp11, _057_home_057_ubuntu_057_workspace_057_RosettaATS_057_temperature_conversion_057_temperature_056_dats__r2k(arg0)) ;

/*
emit_instr: loc0 = /home/ubuntu/workspace/RosettaATS/temperature_conversion/temperature.dats: 792(line=80, offs=10) -- 803(line=80, offs=21)
*/
ATSINSmove(tmpret10, _057_home_057_ubuntu_057_workspace_057_RosettaATS_057_temperature_conversion_057_temperature_056_dats__k2c(tmp11)) ;

ATSfunbody_end()
ATSreturn(tmpret10) ;
} /* end of [_057_home_057_ubuntu_057_workspace_057_RosettaATS_057_temperature_conversion_057_temperature_056_dats__r2c] */

/*
/home/ubuntu/workspace/RosettaATS/temperature_conversion/temperature.dats: 818(line=83, offs=4) -- 835(line=83, offs=21)
*/
/*
local: 
global: k2f$10$0(level=0)
local: 
global: 
*/
ATSextern()
atstkind_t0ype(atstype_double)
_057_home_057_ubuntu_057_workspace_057_RosettaATS_057_temperature_conversion_057_temperature_056_dats__k2f(atstkind_t0ype(atstype_double) arg0)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret12, atstkind_t0ype(atstype_double)) ;
ATStmpdec(tmp13, atstkind_t0ype(atstype_double)) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /home/ubuntu/workspace/RosettaATS/temperature_conversion/temperature.dats: 815(line=83, offs=1) -- 835(line=83, offs=21)
*/
ATSINSflab(__patsflab_k2f):
/*
emit_instr: loc0 = /home/ubuntu/workspace/RosettaATS/temperature_conversion/temperature.dats: 828(line=83, offs=14) -- 833(line=83, offs=19)
*/
ATSINSmove(tmp13, _057_home_057_ubuntu_057_workspace_057_RosettaATS_057_temperature_conversion_057_temperature_056_dats__k2r(arg0)) ;

/*
emit_instr: loc0 = /home/ubuntu/workspace/RosettaATS/temperature_conversion/temperature.dats: 824(line=83, offs=10) -- 835(line=83, offs=21)
*/
ATSINSmove(tmpret12, _057_home_057_ubuntu_057_workspace_057_RosettaATS_057_temperature_conversion_057_temperature_056_dats__r2f(tmp13)) ;

ATSfunbody_end()
ATSreturn(tmpret12) ;
} /* end of [_057_home_057_ubuntu_057_workspace_057_RosettaATS_057_temperature_conversion_057_temperature_056_dats__k2f] */

/*
/home/ubuntu/workspace/RosettaATS/temperature_conversion/temperature.dats: 850(line=86, offs=4) -- 867(line=86, offs=21)
*/
/*
local: 
global: f2k$11$0(level=0)
local: 
global: 
*/
ATSextern()
atstkind_t0ype(atstype_double)
_057_home_057_ubuntu_057_workspace_057_RosettaATS_057_temperature_conversion_057_temperature_056_dats__f2k(atstkind_t0ype(atstype_double) arg0)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret14, atstkind_t0ype(atstype_double)) ;
ATStmpdec(tmp15, atstkind_t0ype(atstype_double)) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /home/ubuntu/workspace/RosettaATS/temperature_conversion/temperature.dats: 847(line=86, offs=1) -- 867(line=86, offs=21)
*/
ATSINSflab(__patsflab_f2k):
/*
emit_instr: loc0 = /home/ubuntu/workspace/RosettaATS/temperature_conversion/temperature.dats: 860(line=86, offs=14) -- 865(line=86, offs=19)
*/
ATSINSmove(tmp15, _057_home_057_ubuntu_057_workspace_057_RosettaATS_057_temperature_conversion_057_temperature_056_dats__f2r(arg0)) ;

/*
emit_instr: loc0 = /home/ubuntu/workspace/RosettaATS/temperature_conversion/temperature.dats: 856(line=86, offs=10) -- 867(line=86, offs=21)
*/
ATSINSmove(tmpret14, _057_home_057_ubuntu_057_workspace_057_RosettaATS_057_temperature_conversion_057_temperature_056_dats__r2k(tmp15)) ;

ATSfunbody_end()
ATSreturn(tmpret14) ;
} /* end of [_057_home_057_ubuntu_057_workspace_057_RosettaATS_057_temperature_conversion_057_temperature_056_dats__f2k] */

/*
/home/ubuntu/workspace/RosettaATS/temperature_conversion/temperature.dats: 882(line=89, offs=4) -- 904(line=89, offs=26)
*/
/*
local: 
global: c2f$12$0(level=0)
local: 
global: 
*/
ATSextern()
atstkind_t0ype(atstype_double)
_057_home_057_ubuntu_057_workspace_057_RosettaATS_057_temperature_conversion_057_temperature_056_dats__c2f(atstkind_t0ype(atstype_double) arg0)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret16, atstkind_t0ype(atstype_double)) ;
ATStmpdec(tmp17, atstkind_t0ype(atstype_double)) ;
ATStmpdec(tmp18, atstkind_t0ype(atstype_double)) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /home/ubuntu/workspace/RosettaATS/temperature_conversion/temperature.dats: 879(line=89, offs=1) -- 904(line=89, offs=26)
*/
ATSINSflab(__patsflab_c2f):
/*
emit_instr: loc0 = /home/ubuntu/workspace/RosettaATS/temperature_conversion/temperature.dats: 896(line=89, offs=18) -- 901(line=89, offs=23)
*/
ATSINSmove(tmp18, _057_home_057_ubuntu_057_workspace_057_RosettaATS_057_temperature_conversion_057_temperature_056_dats__c2k(arg0)) ;

/*
emit_instr: loc0 = /home/ubuntu/workspace/RosettaATS/temperature_conversion/temperature.dats: 892(line=89, offs=14) -- 903(line=89, offs=25)
*/
ATSINSmove(tmp17, _057_home_057_ubuntu_057_workspace_057_RosettaATS_057_temperature_conversion_057_temperature_056_dats__k2r(tmp18)) ;

/*
emit_instr: loc0 = /home/ubuntu/workspace/RosettaATS/temperature_conversion/temperature.dats: 888(line=89, offs=10) -- 904(line=89, offs=26)
*/
ATSINSmove(tmpret16, _057_home_057_ubuntu_057_workspace_057_RosettaATS_057_temperature_conversion_057_temperature_056_dats__r2f(tmp17)) ;

ATSfunbody_end()
ATSreturn(tmpret16) ;
} /* end of [_057_home_057_ubuntu_057_workspace_057_RosettaATS_057_temperature_conversion_057_temperature_056_dats__c2f] */

/*
/home/ubuntu/workspace/RosettaATS/temperature_conversion/temperature.dats: 919(line=92, offs=4) -- 941(line=92, offs=26)
*/
/*
local: 
global: f2c$13$0(level=0)
local: 
global: 
*/
ATSextern()
atstkind_t0ype(atstype_double)
_057_home_057_ubuntu_057_workspace_057_RosettaATS_057_temperature_conversion_057_temperature_056_dats__f2c(atstkind_t0ype(atstype_double) arg0)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret19, atstkind_t0ype(atstype_double)) ;
ATStmpdec(tmp20, atstkind_t0ype(atstype_double)) ;
ATStmpdec(tmp21, atstkind_t0ype(atstype_double)) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /home/ubuntu/workspace/RosettaATS/temperature_conversion/temperature.dats: 916(line=92, offs=1) -- 941(line=92, offs=26)
*/
ATSINSflab(__patsflab_f2c):
/*
emit_instr: loc0 = /home/ubuntu/workspace/RosettaATS/temperature_conversion/temperature.dats: 933(line=92, offs=18) -- 938(line=92, offs=23)
*/
ATSINSmove(tmp21, _057_home_057_ubuntu_057_workspace_057_RosettaATS_057_temperature_conversion_057_temperature_056_dats__f2r(arg0)) ;

/*
emit_instr: loc0 = /home/ubuntu/workspace/RosettaATS/temperature_conversion/temperature.dats: 929(line=92, offs=14) -- 940(line=92, offs=25)
*/
ATSINSmove(tmp20, _057_home_057_ubuntu_057_workspace_057_RosettaATS_057_temperature_conversion_057_temperature_056_dats__r2k(tmp21)) ;

/*
emit_instr: loc0 = /home/ubuntu/workspace/RosettaATS/temperature_conversion/temperature.dats: 925(line=92, offs=10) -- 941(line=92, offs=26)
*/
ATSINSmove(tmpret19, _057_home_057_ubuntu_057_workspace_057_RosettaATS_057_temperature_conversion_057_temperature_056_dats__k2c(tmp20)) ;

ATSfunbody_end()
ATSreturn(tmpret19) ;
} /* end of [_057_home_057_ubuntu_057_workspace_057_RosettaATS_057_temperature_conversion_057_temperature_056_dats__f2c] */

/*
/home/ubuntu/workspace/RosettaATS/temperature_conversion/temperature.dats: 981(line=97, offs=17) -- 1104(line=103, offs=2)
*/
/*
local: 
global: mainats_void_0$14$0(level=0)
local: 
global: 
*/
ATSextern()
atsvoid_t0ype
mainats_void_0()
{
/* tmpvardeclst(beg) */
// ATStmpdec_void(tmpret22) ;
// ATStmpdec_void(tmp23) ;
// ATStmpdec_void(tmp24) ;
// ATStmpdec_void(tmp25) ;
// ATStmpdec_void(tmp26) ;
// ATStmpdec_void(tmp27) ;
ATStmpdec(tmp28, atstkind_t0ype(atstype_double)) ;
// ATStmpdec_void(tmp29) ;
// ATStmpdec_void(tmp30) ;
// ATStmpdec_void(tmp31) ;
ATStmpdec(tmp32, atstkind_t0ype(atstype_double)) ;
// ATStmpdec_void(tmp33) ;
// ATStmpdec_void(tmp34) ;
// ATStmpdec_void(tmp35) ;
ATStmpdec(tmp36, atstkind_t0ype(atstype_double)) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /home/ubuntu/workspace/RosettaATS/temperature_conversion/temperature.dats: 975(line=97, offs=11) -- 1104(line=103, offs=2)
*/
ATSINSflab(__patsflab_main_void_0):
/*
emit_instr: loc0 = /home/ubuntu/workspace/RosettaATS/temperature_conversion/temperature.dats: 990(line=99, offs=3) -- 1011(line=99, offs=24)
*/
ATSINSmove_void(tmp23, atspre_print_string(ATSPMVstring("K "))) ;

/*
emit_instr: loc0 = /home/ubuntu/workspace/RosettaATS/temperature_conversion/temperature.dats: 990(line=99, offs=3) -- 1011(line=99, offs=24)
*/
ATSINSmove_void(tmp24, atspre_print_double(ATSPMVf0loat(21.00))) ;

/*
emit_instr: loc0 = /home/ubuntu/workspace/RosettaATS/temperature_conversion/temperature.dats: 990(line=99, offs=3) -- 1011(line=99, offs=24)
*/
ATSINSmove_void(tmp25, atspre_print_newline()) ;

/*
emit_instr: loc0 = /home/ubuntu/workspace/RosettaATS/temperature_conversion/temperature.dats: 1015(line=100, offs=3) -- 1041(line=100, offs=29)
*/
ATSINSmove_void(tmp26, atspre_print_string(ATSPMVstring("C "))) ;

/*
emit_instr: loc0 = /home/ubuntu/workspace/RosettaATS/temperature_conversion/temperature.dats: 1030(line=100, offs=18) -- 1040(line=100, offs=28)
*/
ATSINSmove(tmp28, _057_home_057_ubuntu_057_workspace_057_RosettaATS_057_temperature_conversion_057_temperature_056_dats__k2c(ATSPMVf0loat(21.00))) ;

/*
emit_instr: loc0 = /home/ubuntu/workspace/RosettaATS/temperature_conversion/temperature.dats: 1015(line=100, offs=3) -- 1041(line=100, offs=29)
*/
ATSINSmove_void(tmp27, atspre_print_double(tmp28)) ;

/*
emit_instr: loc0 = /home/ubuntu/workspace/RosettaATS/temperature_conversion/temperature.dats: 1015(line=100, offs=3) -- 1041(line=100, offs=29)
*/
ATSINSmove_void(tmp29, atspre_print_newline()) ;

/*
emit_instr: loc0 = /home/ubuntu/workspace/RosettaATS/temperature_conversion/temperature.dats: 1045(line=101, offs=3) -- 1071(line=101, offs=29)
*/
ATSINSmove_void(tmp30, atspre_print_string(ATSPMVstring("F "))) ;

/*
emit_instr: loc0 = /home/ubuntu/workspace/RosettaATS/temperature_conversion/temperature.dats: 1060(line=101, offs=18) -- 1070(line=101, offs=28)
*/
ATSINSmove(tmp32, _057_home_057_ubuntu_057_workspace_057_RosettaATS_057_temperature_conversion_057_temperature_056_dats__k2f(ATSPMVf0loat(21.00))) ;

/*
emit_instr: loc0 = /home/ubuntu/workspace/RosettaATS/temperature_conversion/temperature.dats: 1045(line=101, offs=3) -- 1071(line=101, offs=29)
*/
ATSINSmove_void(tmp31, atspre_print_double(tmp32)) ;

/*
emit_instr: loc0 = /home/ubuntu/workspace/RosettaATS/temperature_conversion/temperature.dats: 1045(line=101, offs=3) -- 1071(line=101, offs=29)
*/
ATSINSmove_void(tmp33, atspre_print_newline()) ;

/*
emit_instr: loc0 = /home/ubuntu/workspace/RosettaATS/temperature_conversion/temperature.dats: 1075(line=102, offs=3) -- 1101(line=102, offs=29)
*/
ATSINSmove_void(tmp34, atspre_print_string(ATSPMVstring("R "))) ;

/*
emit_instr: loc0 = /home/ubuntu/workspace/RosettaATS/temperature_conversion/temperature.dats: 1090(line=102, offs=18) -- 1100(line=102, offs=28)
*/
ATSINSmove(tmp36, _057_home_057_ubuntu_057_workspace_057_RosettaATS_057_temperature_conversion_057_temperature_056_dats__k2r(ATSPMVf0loat(21.00))) ;

/*
emit_instr: loc0 = /home/ubuntu/workspace/RosettaATS/temperature_conversion/temperature.dats: 1075(line=102, offs=3) -- 1101(line=102, offs=29)
*/
ATSINSmove_void(tmp35, atspre_print_double(tmp36)) ;

/*
emit_instr: loc0 = /home/ubuntu/workspace/RosettaATS/temperature_conversion/temperature.dats: 1075(line=102, offs=3) -- 1101(line=102, offs=29)
*/
ATSINSmove_void(tmpret22, atspre_print_newline()) ;

ATSfunbody_end()
ATSreturn_void(tmpret22) ;
} /* end of [mainats_void_0] */

/*
** for initialization(dynloading)
*/
ATSdynloadflag_minit(_057_home_057_ubuntu_057_workspace_057_RosettaATS_057_temperature_conversion_057_temperature_056_dats__dynloadflag) ;
ATSextern()
atsvoid_t0ype
_057_home_057_ubuntu_057_workspace_057_RosettaATS_057_temperature_conversion_057_temperature_056_dats__dynload()
{
ATSfunbody_beg()
ATSdynload(/*void*/)
ATSdynloadflag_sta(
_057_home_057_ubuntu_057_workspace_057_RosettaATS_057_temperature_conversion_057_temperature_056_dats__dynloadflag
) ;
ATSif(
ATSCKiseqz(
_057_home_057_ubuntu_057_workspace_057_RosettaATS_057_temperature_conversion_057_temperature_056_dats__dynloadflag
)
) ATSthen() {
ATSdynloadset(_057_home_057_ubuntu_057_workspace_057_RosettaATS_057_temperature_conversion_057_temperature_056_dats__dynloadflag) ;
/*
dynexnlst-initize(beg)
*/
/*
dynexnlst-initize(end)
*/
} /* ATSendif */
ATSfunbody_end()
ATSreturn_void(tmpret_void) ;
} /* end of [*_dynload] */

/*
** the ATS runtime
*/
#ifndef _ATS_CCOMP_RUNTIME_NONE_
#include "pats_ccomp_runtime.c"
#include "pats_ccomp_runtime_memalloc.c"
#ifndef _ATS_CCOMP_EXCEPTION_NONE_
#include "pats_ccomp_runtime2_dats.c"
#ifndef _ATS_CCOMP_RUNTIME_TRYWITH_NONE_
#include "pats_ccomp_runtime_trywith.c"
#endif /* _ATS_CCOMP_RUNTIME_TRYWITH_NONE_ */
#endif // end of [_ATS_CCOMP_EXCEPTION_NONE_]
#endif /* _ATS_CCOMP_RUNTIME_NONE_ */

/*
** the [main] implementation
*/
int
main
(
int argc, char **argv, char **envp
) {
int err = 0 ;
_057_home_057_ubuntu_057_workspace_057_RosettaATS_057_temperature_conversion_057_temperature_056_dats__dynload() ;
ATSmainats_void_0(err) ;
return (err) ;
} /* end of [main] */

/* ****** ****** */

/* end-of-compilation-unit */
